### ISSUE TITLE
Zakladne vyhladavanie

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#1]
* zobrazovat suggestions pocas toho ako pouzivatel pise 
* odlisit vysledky podla typu (farebne/roznym markerom)

bolo by pekne, keby bolo mozne na konkretny marker kliknut a ziskat jeho explicitny URL odkaz (keby som napr. chcel s niekym zdielat informaciu "tu presne je autobusova zastavka v Brusne") -- ale toto by som nerobil v ramci tejto issue.

**Comment by petervojtek** [comment]
Martin @zdila , ak nemas nic proti, skusim vylepsit vyhladavanie, aby:
* poskytovalo suggestion-while-typing
* zobrazalo iba vysledky zo SR
* spravit privetivejsiu pracu s markermi ktore zobrazuju vysledky

**Comment by zdila** [comment]
> ak nemas nic proti

nemam :-)

**Comment by petervojtek** [comment]
ok, je to [mergnute](https://github.com/FreemapSlovakia/freemap-v3-react/pull/16).
