### ISSUE TITLE
ako zdielat nahratu GPX trasu?

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#101]
v #69 vieme nahrat trasu, ale aktualne zostava iba na frontende. keby sme chceli zaviest tlacidlo "zdielat trasu", vygenerujeme nejaku linku, napr.

```
next.freemap.sk/?tool=track-viewer&track-id=123
```

lenze na to by sme potrebovali tie gpx logy niekam uploadovat. Martin @zdila , mam vytvorit issue pre https://github.com/FreemapSlovakia/FreemapBackend aby sme mali API endpoint pre POST/GET zaznamu? alebo mozno chceme z nejakych pricin pouzivat iny endpoint (napr. firebase, openstreetmap.org tracks)?

**Comment by tjamecny** [comment]
Starý freemap uploaduje trasu len na phenixa s možnosťou ju uploadnúť aj na OSM. Upload iba na OSM by som nedoporučoval, nakoľko nevieme pôvod GPX záznamu (môže byť obkreslený z iných máp) a ani kvalitu dát v zázname. Preto by som navrhoval ostať pri uploade na phenixa, t.j. vytvoriť novú issue na FreemapBackend. 

Štatistika používania GPX na freemape:
2017 - 171 trás, z toho 44 verejných a 127 súkromných (do 9.4.2017 vrátane)
2016 - 961 trás, z toho 300 verejných a 661 súkromných
2015 - 768 trás, z toho 273 verejných a 495 sukromných

**Comment by Mirecnet** [comment]
Na strom Freemape sa nedal vymazat nahraty GPX. Ked si potom chcel vymazat GPX (napr. po chybe dvojiteho nahratia) neslo to. Upozornoval som na to. Nic sa neopravilo. Mozno preto tam ludia prestali nahravat veci....

**Comment by petervojtek** [comment]
vyrobime nodejs endpoint ktory to bude podporpovat

**Comment by petervojtek** [comment]
Martin @zdila , rozmyslam ako pristupit k tomu aby URL reflektovali stav aplikacie.
na vetve feature_101_share_tracklog je zatial jeden commit [2a475570](https://github.com/FreemapSlovakia/freemap-v3-react/commit/2a4755703b76efd77fae692479c4480b1afbf03f) v ktorom je nejaka prva iteracia --aby sme mali o com diskutovat :)

funguje je to tak, ze si musis rozbehnut `freemap-v3-nodejs-backend`, a potom:
1. v nastroji Prehliadac tras nahras trasu (v tej chvili je este len na frontende)
2. kliknes sa Zdielat -- v tejto chvili sa uploaduje a v popupe sa zobrazi url
3. ked ides na zdielaciu url, napr. `http://localhost:8080/?map=11/48.20168/17.04434&layers=T&tool=track-viewer&trackUID=1IG3inPbCy9jU3QOhVJSLa`, tak sa prislusne gpx stiahne a zobrazi.

ten kod este nie je prilis ucesany a urlka sa pri prvom pohybe mapy prepise, skor sa chcem venovat tomu ako robit routovania.
* chceme to robit cez explicitne params (`&tool=track-viewer&trackUID=123`), alebo krajsie urlk-ky (/track-viewer/uid)? mne sa zda ze prvy pristup nam dnes staci, a krajsie urlky uz neskor hocikedy vyrobime nad tym (mozno na urovni konfiguracie webservera)
* aku konvenciu pre nazvy parametrov v url chceme pouzivat? pomlcka ako separator je ok? (`tool=track-viewer`). `trackUID` sa mi nepaci, asi radsej downcase, `track-uid`?
* vobec som nepouzil explicitnu deklaraciu `<Route>` -- chceme/nechceme ist touto cestou? (ak by sme sli cez `<Route>`predpokladam ze to by znamenalo ze nebudeme volat setTool implicitne ako teraz, ale zavolame `zmen url` -> a az observer nad url zavola setTool.

**Comment by zdila** [comment]
Moja odpoved je vseobecna a nema nic priamo s touto issue :-)

Ako som uz spominal, chcem skusit pouzit http://peterbeshai.com/react-url-query/, alebo nieco podobne. Syncovat URL s reduxom sa mi nepaci. Ako som uz spominal, su to rozne sources of truth a namiesto ich syncovania ich treba nezavisle pouzivat. Stav, ktory chceme aby sa reflektoval v URL, pojde iba do URL a ostatny stav iba do reduxu.

> chceme to robit cez explicitne params

Asi to uplne staci a podla mna aj do buducna, ale mozno... vid. nizsie.

> aku konvenciu pre nazvy parametrov v URL chceme pouzivat? pomlcka ako separator je ok?

Pouzil by som asi priamo hodnotu aku mame v kode a ta je cez pomlcku. A osobne sa mi polmckovy zapis v url aj viac paci. CamelCase mi pride pekne len pre kod (premenne, funkcie, ...), nazvy properties v json-e a pod.

> vobec som nepouzil explicitnu deklaraciu `<Route>` ...

Cez react-router riesime iba mapovanie URL ciest (path) takze na toto tam netreba nic nove. Naviac momentalne je cely react router uplne nevyuzity (a teda aj zbytocny) kedze mame v nom iba jednu biednu route. Kto vie ci casom budeme pouzivat aj ine routes ktore by sme vedeli dat do react-routera a vyuzit jeho potencial. Akoze viem si predstavit ze by tam mohol ist tool (napr. `https://next.freemap.sk/route-planner/?start=...&finish=...`).

**Comment by petervojtek** [comment]
vdaka za postrehy. vycistil som to podla [pripomienok](https://github.com/FreemapSlovakia/freemap-v3-react/commit/2a4755703b76efd77fae692479c4480b1afbf03f#commitcomment-22124261), pridal som toasty pre chybove stavy (aj ked to este neskor lepsie otestujem), a commitol som to cele do master vetvy v jednom commmite 0879c28.

aktualne to ma nedostatok ze stav url stale nereflektuje stav UI, t.j. ked idem na `http://localhost:8080/?tool=track-viewer&track-uid=4Dx5nnONW49CAX5tBm3pvj`, tak trasa sa zobrazi, ale url sa hned prepise na `http://localhost:8080/?map=11/48.20168/17.13978&layers=T`, ale to nechcem riesit v tejto issue, lebo je to vseobecnejsie.
