### ISSUE TITLE
UX na mobile/tablete: ro/zbalovanie hlavneho menu aj kliknutim hocikde na hornu listu

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#102]
teraz sa hlavne menu roz/zbaluje len kliknutim na burger icon. bolo by pohodnejsie, keby sa roz/zbalovalo kliknutim hocikde na hornu listu, ktora najma na tablete predstavuje dost velku plochu:

<img width="755" alt="screen shot 2017-04-07 at 7 53 32 pm" src="https://cloud.githubusercontent.com/assets/225506/24812868/1abb9898-1bcc-11e7-9f20-b0b8c338e944.png">

**Comment by Mirecnet** [comment]
Ked kliknem na nastroje - miesta - typ a mam zvolit polozku napr. HRAD tak rolujem celu obrazovku. Nedalo by sa rolovat len vo vyberovom okne ?

**Comment by zdila** [comment]
@Mirecnet to je offtopic. Sprav na to novu issue.

**Comment by Mirecnet** [comment]
ok

**Comment by petervojtek** [comment]
co sa horneho menu na mobile tyka, inspirovat sa osm.cz portalom (napr. neposuvaju mapu nadol pri rozbaleni menu).

**Comment by zdila** [comment]
Bezpredmetne po zmenach UI
