### ISSUE TITLE
vlastná mapa

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#103]
Pri plánovaní nejakých výletov využívavam službu Moje Mapy od googlu na plánovanie zaujímavých miest kde by sa človek mohol zastaviť, prípadne načrtnúť si trasu. Jedinou nevýhodou (ak opomenieme obmedzenie free použitia) je že tam nie je osm/freemap mapa :D 
Dávam to len ako námet ak také niečo náhodou nie je na možné rozšírenie freemap portálu.

**Comment by MichalPP** [comment]
umap?

**Comment by seg-on** [comment]
Dík nepoznal som. Škoda len že tam nie sú freemap vrstvy

**Comment by zdila** [comment]
Ale su. http://umap.openstreetmap.fr/en/map/nezmapovana-turistika-freemap-slovakia_58872

**Comment by seg-on** [comment]
vďaka. chvíľku mi to trvalo, ale keď som videl že sa to dá tak som na to došiel :D

**Comment by petervojtek** [comment]
moj namet -- tlacidlo "otvorit pohlad na umap prazdnej template s tiles z freemap.sk"

**Comment by zdila** [comment]
Implementovane (zatial experimentalna feature).
