### ISSUE TITLE
Tlačitko/odkaz na otvorenie aktuálneho výrezu mapy v openstreetmap.org

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#104]
Išlo by spraviť že by sa dalo otvoriť z freemap mapa na openstreetmap.org s "rovnakým" výrezom mapy?

Poviem ešte prečo. Často chcem vedieť info aké tagy má daná cesta či bod a robím to cez openstreetmap.
Možno však existuje lepšie riešenie len som ho ešte neobjavil :)

**Comment by zdila** [comment]
viditelne v expertnom rezime

**Comment by seg-on** [comment]
Parádička.
Akurát tom Editor JOSM nechápem to by malo otvoriť lokálnu aplikáciu v compe?

**Comment by zdila** [comment]
> Akurát tom Editor JOSM nechápem to by malo otvoriť lokálnu aplikáciu v compe?

http://josm.openstreetmap.de/wiki/Help/Preferences/RemoteControl

**Comment by seg-on** [comment]
díki
