### ISSUE TITLE
Diakritika v itineráry

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#108]
Vyzerá že popisky Itinerára v plánovači majú problém s diakritikou. Namiesto písmen s diakritikou sú dva ??

**Comment by tjamecny** [comment]
Už je to nahlásené ako https://github.com/FreemapSlovakia/FreemapBackend/issues/10. Nakoniec sa to asi ani riešiť nebude, nakoľko je v pláne použiť iný softvér (GraphHopper, prípadne OSRM).
