### ISSUE TITLE
globalny gui loader

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#11]
ktory budeme zobrazovat napr ked sa nieco dotahuje cez ajax.

zda sa mi ze toposcope tam mal nieco s nazvom hourglass, neviem ci to bol loader..

**Comment by zdila** [comment]
Ano, hourglass je komponent, ktory zobrazi nad svojimi children semitransparentne divko ak `active={true}`. Podla typu nacitavania by sa to zobrazovalo skrz celu stranku, alebo iba nad nejakou konkretnou komponentou...

**Comment by zdila** [comment]
@petervojtek mas nejaku predstavu? Lebo "blurrovat" celu obrazovku pri kazdom async vloani je asi moc. Mozno by to malo byt pri roznych async volaniach indikovane inac.

**Comment by petervojtek** [comment]
cielom"blurovania" celej obrazovky je vlastne zamedzit pouzivatelovi interagovat - je to implementacne najjednoduchsi sposob, ale bolo by to pouzivatelsky neprijemne. 

navrhujem medzi navigacnu listu a mapu vlozit horizontalny pasik siroky mozno 2 px, ktory by zobrazoval nejaky progress indikator tecuci horizontalne (a ak by loader nebol aktivny tak pasik by bol rovnako sedy ako je teraz border-bottom navigacnej listy).

co sa tyka dosledkov toho ze sa prebieha loadovanie, to by si kazdy nastroj musel osetrit sam (napr. ked planovac prave prepocitava trasu, t.j. je zobrazeny loader, tak nedovoli posuvat/pridavat body.

otazkou potom ostava ako zobrazovat progres indikator v modalnych popupoch -- ale to by som riesil az taky problem nastane.

**Comment by zdila** [comment]
> ... pasik ...

to by mohlo vyzerat celkom efektne

> napr. ked planovac prave prepocitava trasu, t.j. je zobrazeny loader, tak nedovoli posuvat/pridavat body.

redux-logic ma funkciu debounce a cancelovania akcii, takze v tomto pripade by som neobmedzoval pridavanie dalsieho bodu alebo modifikovanie. ale ako pises, asi per tool.

> otazkou potom ostava ako zobrazovat progres indikator v modalnych popupoch

asi cez neho hodit biely polopriesvitny overlay :-)

**Comment by petervojtek** [comment]
>  a ak by loader nebol aktivny tak pasik by bol rovnako sedy ako je teraz border-bottom navigacnej listy

alebo by mohol mat roznu farbu podla toho, aky typ mapy je zobrazeny (turisti zelena, cyklo zlta, lyze biela, auto neviem.)

**Comment by zdila** [comment]
> alebo by mohol mat roznu farbu

to uz by som neprehanal :)

**Comment by petervojtek** [comment]
napriklad toto je cisty css horizontalny loading indikator:
http://codepen.io/anon/pen/KWyPym
