### ISSUE TITLE
Výškovy profil

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-v3-react#110]
Výškovy profil - vygenerovať z vyhľadanej cesty routingom alebo z manualne vyklikanej.

**Comment by petervojtek** [comment]
pred nedavnom som pre ucely generovania vyskoveho profilu pre nahratu gpx trasu skumal v akom stave je [leaflet.elevation](http://stackoverflow.com/questions/43514451/anyone-managed-to-get-leaflet-elevation-working-with-react-leaflet), ale aktualny npm build je zle spraveny, nesedia tam cisla verzii suborov a nedokaze si to samo donistalovat svoje zavislosti (d3).
samotny d3.min.js ma 216kb, co nie je uplne malo..

**Comment by zdila** [comment]
> samotny d3.min.js ma 216kb, co nie je uplne malo

webpack kompiluje z neminimalizovanych suborov a odstranuje nepotrebny kod

**Comment by petervojtek** [comment]
ideme si naprogramovat sami

**Comment by petervojtek** [comment]
pozeral som react-d3 wrapper (http://www.reactd3.org/), projekt je ako tak aktivny, ale [zda sa ze vobec nema dokumentaciu](https://github.com/react-d3/react-d3.github.io/issues/16).. takze to nevyzera uzitocne.

**Comment by MichalPP** [comment]
tu som urobil elevation profil http://epsilon.sk/elevation.php?tabulka=trasy&osm_id=-1493097&name=Ro%C5%BE%C5%88ava%20-%20Stolica

najpríjemnešie sú pohyby po mape keď hýbeš myšou nad profilom a opačne. 

ešte by bodlo mať možnosť dať do profilu extra veci (napr názvy vrchov, názvy TIM, ...)

**Comment by zdila** [comment]
Tke nieco si predstavujem aj na next.freemap.sk. Technicky to nie je problem spravit, ked su data :-)

**Comment by MichalPP** [comment]
už som urobil postgis funkciu, čo do linestringu v rámci postgisu doplní Z súradnicu a vypluje geojson s x,y,z (ako ten hore). ešte zistiť ako vstup bezpečne dočasne narvať do DB.

zatiaľ na testovanie môžeš používať ten hore, teda http://www.oma.sk/gpx/gpx-ref.php?ref=-1493097&typ=trasy&format=json3d

btw, leaflet-elevation blbne na multilinestring.

**Comment by petervojtek** [comment]
pridal som prvu velmi jednoduchu verzii vyskoveho profilu do prehliadaca tras. nadmorske vysky to berie z gpx (ak v gpx nie su nadmorske vysky, tak sa ani nezobrazi tracidlo "vyskovy profil".

todos:
* zatial nie je interaktivita medzi trasou na mape a grafom pri mouseover
* kilometre na osi x su skarede cisla, mali by to byt nasobky 1, 5, 10km.
* ak by sme mali rychle api ktore nam pre koordinaty (povedzme 100 bodov trasy) vrati ich nadm. vysku, mohli by sme radsej ukazovat tieto nadm vysky, aby sme sa nemuseli zaoberat vyhladzovat nameranej ele (teraz tam ziadne vyhladzovanie nie je).
* nad popisom x-ovej osi je privelky biely priestor, zistit ako ho zmensit.

<img width="890" alt="screen shot 2017-05-20 at 12 58 08 pm" src="https://cloud.githubusercontent.com/assets/225506/26275228/44eaaa9e-3d5c-11e7-879a-905645d8b7f9.png">

**Comment by petervojtek** [comment]
pridana interaktivita elevation chart -> mapa, t.j. onmouse over nad grafom sa zobrazi prislusny bod na mape.

**Comment by petervojtek** [comment]
docasne by som na ziskavanie nadm. vysky (pre generovanie vyskoveho profilu pre planovac trasy) mohol pouzit toto:
https://developer.mapquest.com/documentation/open/elevation-api/elevation-profile/get/

vo free plane je 15000 transakcii za mesiac. ak som pochopil spravne, ziskanie elevation profilu pre jednu trasu = 1 transakcia.

**Comment by petervojtek** [comment]
pridal som vyskovy profil do planovaca tras.
kedze vsak ziskavanie profilu z mapquest api trva 5-10 sekund, tak ked pouzivatel zmeni naplanovanu trasu, vyskovy profil sa automaticky zavrie a pouzivatel ho musi znova otvorit ( a az vtedy sa znovu robi request na mapquest a ziskavaju nove elevations)

<img width="907" alt="screenshot 2017-05-25 15 24 35" src="https://cloud.githubusercontent.com/assets/225506/26452063/d2aba8b4-415e-11e7-935f-233994201122.png">

**Comment by zdila** [comment]
> tak ked pouzivatel zmeni naplanovanu trasu

v logic na ziskavanie elevation profile mi (nie len) k tomu chyba `cancelType`

**Comment by petervojtek** [comment]
vdaka za postreh, pridam to

**Comment by petervojtek** [comment]
vyskovy profil sa uz nachadza v nasledovnych nastrojoch:
* meranie vzdialenosti
* planovac trasy (router)
* prehliadac tras

aktualne sa vysky ziskavaju cez mapquest.ak budeme mat vlastny rychly backend ktory nam pre zadane pole latlons vrati elevations, tak to vieme rychlo prehodit na iny endpoint

TODO - zrejme by sme mali pridat kvoli tomu mapquest do attribution, pravnik OZ freemap by mal preskumat licencne podmienky :)
