### ISSUE TITLE
horne menu - rolovacia lista pre miesta

### ISSUE THREAD

**Issue by Mirecnet** [FreemapSlovakia/freemap-v3-react#111]
Ked kliknem na nastroje - miesta - typ a mam zvolit polozku napr. HRAD tak rolujem celu obrazovku. Nedalo by sa rolovat len vo vyberovom okne ?

**Comment by Mirecnet** [comment]
Tie miesta su vseobecne volake rozhodene. Napriklad hladal som kadernictvo a nieje v sluzbach, ale v ochode. Tam som ho necakal. Najhorsie, ze po zadani kadernictva (shop=hairdresser) nic nenajde.

Nedali by sa pridat aj vyhladavanie prepadlisk ? (natural=sinkhole)

**Comment by zdila** [comment]
Skrolovanie opravene v 51010cdc54c10da48dffd3986a6fb63f54388d95.

Poznamka https://github.com/FreemapSlovakia/freemap-v3-react/issues/111#issuecomment-299618751 je tu offtopic, prosim vytvorit novu issue.

**Comment by Mirecnet** [comment]
Uplne super.
