### ISSUE TITLE
orezat bbox ako je z12 SR (neumoznit pohyb mimo toho co renderujeme)

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#114]

**Comment by petervojtek** [comment]
a zaroven minzoom zmenit z 7 na 8

**Comment by petervojtek** [comment]
zial, sucasne spravanie nie je to pouzivatelsky prijemne, napr. pre pouzivatelov z Bratislavy.

ja sa rad na mape pohybujem z jedneho miesta na druhe (napr z centra BA do malaciek)  tak, ze odzoomujem (napr na z9) a potom sa zase pri-zoomujem (napr. z15 do malaciek). problem je, ze pri odzoomovani (z9) sa teraz mapa "taha do stredu SR" a az niekde pri z12 mi "dovoli" mat malacky v strede mapy.

**Comment by zdila** [comment]
Suhlasim, aj mne to vadi. Takze treba navrhnut riesenie :-)

**Comment by tjamecny** [comment]
Malokedy odzoomujem na z10 a takmer vobec na z8/z9, preto v tom nevidim zasadny problem. 
Skuste zmenit BBOX tak, aby bol zarovnany na z8:
![sr_osm_bbox_z8](https://cloud.githubusercontent.com/assets/16599347/26013632/99f97672-3759-11e7-8286-ae07a3cfbafb.png)

Ale potrva dost dlho, kym sa upravi rendering na takyto BBOX, lebo vypocet pozicie POI/labels v aktualnej implementacii je nepouzitelny na takto velku plochu.

**Comment by zdila** [comment]
Ja som nastavil bbox tak, ze na navyssom nativnom zoome (16) sa nevies dostat mimo freemap styl (ked pustis mysku). @tjamecny posli presne hodnoty a mozeme vyskusat tie.

**Comment by tjamecny** [comment]
@zdila skus tento BBOX: http://tools.geofabrik.de/calc/#type=geofabrik_standard&bbox=15.4688,47.040256,23.906238,49.837969
Stazovat sa potom budu len ti, co byvaju na Orave ;)

**Comment by petervojtek** [comment]
na toto sa asi zabudlo, zmenil som dnes bbox na ten Tiborov.
