### ISSUE TITLE
Naucne chodniky a naucne tabule

### ISSUE THREAD

**Issue by Mirecnet** [FreemapSlovakia/freemap-v3-react#116]
Zdravim,
v poslednom case sa zacal boom naucnych chodnikov, ktore postupne mapujeme. Kazda dedina na Liptove musi mat svoj naucny chodnik na ktorom v paneloch prezentuje zaujimavosti okolia.
Kazdy naucny chodnik musi mat prirodzene svoje tabule. Akosi sa nam ta hlavna vec, ako tabule na mape nezobrazuju.
Nedali by sa zviditelnit naucne tabule na tychto naucnych chodnikoch ?

Napriklad:
board_type=wildlife
description=Prales, pasiensky a hospodársky les
information=board
name=Tabuľa č.8
source=GPS, survey
tourism=information

Napriklad tag information=board zobrazoval na mape vo forme malej bielej bodky. 

Pouvazujte nad zlepsovacim navrom :)
![tabule](https://cloud.githubusercontent.com/assets/24828961/25785657/b0766332-3386-11e7-96c4-3e0e2aed05a6.jpg)

**Comment by petervojtek** [comment]
toto je vec na tile renderer, treba to reportovat v tomto repozitari
https://github.com/FreemapSlovakia/FreemapDiSK/issues

**Comment by Mirecnet** [comment]
Jaskne, ok. Dik za upozornenie
