### ISSUE TITLE
Prehliadač trás - ušetriť klik

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#118]
Automaticky po vybratí voľby **Prehliadač trás** otvoriť okno ktoré sa objaví po kliknutí na Nahrať trasu.
Taktiež možno po kliknutí vrátiť pôvodné voľby, tj. menu kde je Hľadanie, Nástroje, Otvor na.

**Comment by petervojtek** [comment]
spravene

**Comment by seg-on** [comment]
je to aj nasadené lebo sa to správa stále rovnako.

vypadlo mi tam slovíčko zrušiť :) tj. klikneš na Nástroje -> Prehliadač trás a vyskočí popup na nahratie trasy. Keď ale v ten moment stlačíš zrušiť nezostaneš v menu Prehliadač trás ale opäť na úvodnom menu s vyhľadávačom.
Keď nechcem nahrať trasu tak zväčša asi nebudem ostávať v menu Prehliadač trás.

No celkovo by bolo možno dobre keby po nahratí trasy by sa dali naďalej využívať ostatné nástroje. Trasa by by mohla ostať zobrazená a v ľavom dolnom rohu by sa objavila bublina s názvom a stručným súhrnom k trase a možnosťou zrušiť zobrazenie trasy.

**Comment by petervojtek** [comment]
nie je to nasadene na next.freemap.sk.

Zrusit -- radej by som to nechal ako to je, lebo ked sa bude tlacidlo Zrusit v popupe spravat rozne, bude to posobit na pouzivatela nejasne. ked uz by sa upload popup dal uplne zrusit, a upload dropzone presunut do menu (avsak na to aby bola dropzone dost velka by sme museli robit nieco take, ze akonahle pouzivatel zacne tahat subor nad plochu tabky prehliadaca, dropzone sa zvacsi na celu plochu okna (tak to ma napr. 9gag)

**Comment by petervojtek** [comment]
> keby po nahratí trasy by sa dali naďalej využívať ostatné nástroje

to by malo svoje caro, ale dnes by nam to zrejme dost skomplikovalo vyvoj, kedze cela aplikacia je zatial postavena na principe ze aktivny moze byt len jeden nastroj..

**Comment by zdila** [comment]
@seg-on nasadenia vies sledovat na https://github.com/FreemapSlovakia/freemap-v3-react-dist/commits/master

> No celkovo by bolo možno dobre keby po nahratí trasy by sa dali naďalej využívať ostatné nástroje.

toto je tu offtopic, prosim zalozit novu issue.
