### ISSUE TITLE
Prehliadac tras - onmouseover nad trasou -- Uncaught Error: Coordinates must be an array of two or more positions

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#119]
sposobil to [tento commit](b946abb483) ktory updatol verziu `turf/line-slice` z 3.14.2 na 4.1.0

```
index.js:123 Uncaught Error: Coordinates must be an array of two or more positions
    at lineString (index.js:123)
    at lineSlice (index.js:74)
    at TrackViewerResult._this.computeInfoDistanceKm (TrackViewerResult.js:64)
    at TrackViewerResult._this.showInfoPoint (TrackViewerResult.js:51)
```
mam pocit ze je to bug v tej novsej verzii `turf/line-slice`, lebo rovnaku chybu to hadze aj s ich [vzorovymi datami](http://turfjs.org/docs/#lineslice)

**Comment by petervojtek** [comment]
problematicky je ale len v turf ktory je zbuildovany cez npm. ked pouzijem turf.js explicitne cez `<script src="https://npmcdn.com/@turf/turf/turf.min.js"></script>`, tak to funguje.

**Comment by petervojtek** [comment]
skusil som aj najnovsi turf 4.3.0 (cez npm), ale tiez hadze tu chybu

**Comment by zdila** [comment]
Hm. Ja tento problem nemam a to som skusil aj s 4.1.0 aj s 4.3.0. Skus si zmazat `node_modules` pripadne aj ~/.npm a dat `npm i`.

**Comment by petervojtek** [comment]
potvrdzujem ze `rm -r node_modules/ && npm i` riesi kazdy problem :)
