### ISSUE TITLE
ako a kam robit deploy?

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#12]
Martin @zdila ,

predvcerom som z git-u odstranil `build/app.js`, aby to nerobilo problemy pri mergovani vetiev, ale dosledkom je ze uz nevieme repozitar deploynut iba cez git pull/staticky upload.

ak sa ti Martin zda ze bude pohodlnejsie mat `build/app.js` v repozitari z dovodu deploymentu, mozem ho tam vratit.

co sa tyka serveru kam to deployovat, dolezite je, aby odtial fungovali dopyty na freemap api bez vypinania CORS.

ja inak mam ten server litava.eu, kam viem dat cokolvek (je to [Scaleway Baremetal ARM](https://www.scaleway.com/pricing/)), ale asi by bolo prehladnejsie to mat na serveri freemap-u (tam ale nemam pristup).

neviem aky mas na to cele nazor..

**Comment by zdila** [comment]
upravil by som webpack config aby do `/dist` dal okrem skopilovaneho JS aj vsetky resources potrebne k behu (html, css, ...) a tento `/dist` by bol potom ina vetva repozitara alebo rovno iny github project.

**Comment by zdila** [comment]
Spravil som ze vsetko co treba k behu ide do `dist` (mozes si zmazat adresar `build`). Takze uz sa iba dohodnut ci to `dist` bude branch v ramci projektu `freemap-v3-react`, alebo vytvorime novy github projekt, napr. `freemap-v3-react-dist`. (alebo to budeme deployovat niekam inde).

**Comment by petervojtek** [comment]
ok, vyskusam si nakonfigurovat webpack (lebo nikdy som v nom poriadne nic nenastavoval) a mozeme to na uvod deployovat cez separatny projekt cez gh-pages.

**Comment by zdila** [comment]
uz nic nemusis konfigurovat, vsetko je pripravene. len si spust `npm i`.

**Comment by petervojtek** [comment]
skoda :)

**Comment by zdila** [comment]
https://freemapslovakia.github.io/freemap-v3-react-dist/

Projekt je na https://github.com/FreemapSlovakia/freemap-v3-react-dist

**Comment by petervojtek** [comment]
je to super, ale nie je mi zrejme som ako sa obsah dist dostane v podobe commitu do freemap-v3-react-dist repozitara? nezda sa ze by k tomu bol nejaky cmdline prikaz.  ci len mas /dist napojeny na  freemap-v3-react-dist  a rucne odtial robis commit (a asi nejaky force push) ? [to je uplne dostacujuce, len si nie som isty]

**Comment by zdila** [comment]
> ci len mas /dist napojeny na freemap-v3-react-dist a rucne odtial robis commit

ano

> (a asi nejaky force push)

netreba force push. ak si force pullnes, skompilujes a normalne commin/pushnes :-)
