### ISSUE TITLE
link 'otvor na oma.sk'

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#120]
nový link "otvor na oma.sk"

ktorý smeruje na:
`http://redirect.oma.sk/?&lat=48.28616283985548&lon=18.923263549804688&zoom=11&mapa=T`
(alebo iné parametre, prehodím)

**Comment by zdila** [comment]
parameter `mapa` to berie z https://github.com/FreemapSlovakia/freemap-v3-react/blob/master/src/mapDefinitions.js#L1 plus este `S` pre satelitnu.
