### ISSUE TITLE
zachovat stav UI v URL

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#122]
aktualne mame iba `http://localhost:8080/?tool=track-viewer&track-uid=4Dx5nnONW49CAX5tBm3pvj`. hned po navstiveni sa parameter `tool` a `track-uid` z URL strati.

**Comment by zdila** [comment]
Hotovo. Este by podla mna bolo lepsie keby track nacitany z URL necentroval mapu ak uz v URL je lat/lon/zoom.
