### ISSUE TITLE
Vyhľadávanie - zobraziť vyhľadanú pozíciu

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#123]
Keď použijem vyhľadávanie, ale výsledok si nevyberám pomocou myšky, ale klávesnice, tak sa nepresuniem na zvolenú pozíciu iba sa aktivuje panel pre navigovanie.

**Comment by petervojtek** [comment]
uvidime ci nam nieco odpise autori toho pluginu:
https://github.com/ericgio/react-bootstrap-typeahead/issues/146#issuecomment-303296742
