### ISSUE TITLE
Stratila sa vrstva NLC

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#125]
Bola odstránená vrstva lesných ciest či to nejakým nedopatrením?

**Comment by seg-on** [comment]
nič sa nezmenilo :/

**Comment by zdila** [comment]
si si to lokalne nainstaloval a neide? lebo to nie je nasadene. deploymenty sleduj na https://github.com/FreemapSlovakia/freemap-v3-react-dist/commits/master

**Comment by seg-on** [comment]
ahá prepáč sledoval som to tuna v commitoch. už to chápem.
