### ISSUE TITLE
Neakceptuje poziciu z URL

### ISSUE THREAD

**Issue by miro-janosik** [FreemapSlovakia/freemap-v3-react#126]
Ak si otvorim adresu http://next.freemap.sk/?map=13/48.92701/20.42230&layers=T tak nevidim poziciu urcenu v URL, ale poziciu kde som naposledy bol na mape.

Nechapem ako to robi, v browseri Firefox 53.0.2 (windows) nepomoze ani vycistenie cookies (po vycisteni a navsteve uz ani nevidim nove cookies), ani restart browsera.

**Comment by zdila** [comment]
vdaka za report, ale to uz je opravene, ako som spomenul v tom zle umiestnenom reporte.
