### ISSUE TITLE
prehliadac tras - informacie o trase

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#129]
mat moznost zobrazit/schovat nejaky infobox s nasledovnymi informaciami:
* nazov trasy
* dlzka trasy 
* cas startu, cas finisu
* cas trvania
* nastupane a naklesane vyskove metre
* max rychlost
* priemerna rychlost

**Comment by petervojtek** [comment]
zakladne udaje tam su. 
pokrocilejsie udaje odvodene z nadmorskej vyssie (napr. nastupane metre) tam nie su, lebo na to aby tie udaje boli uzitocne, je vhodne nepouzit priamo surove udaje o nadmorskych vyskach z gpx, ale nejako ich vycistit. su dve moznosti:
* prevziat vysky z mapquest api (tak ako to robi aj ele profile)
* alebo pouzit tie z gpx, ale treba ich vycistit, lebo tam mozu byt uletene hodnoty.

**Comment by zdila** [comment]
poznamka: medzi hodnotou a jednotku sa vzdy dava medzera, t.j. 102,6 km. tiez cisla by sme mali formatovat jednotne - slovensky, t.j. `,` ako oddelovac desatinnych miest a medzera na oddelenie tisicov. vid merac vzdialenosti ktory na to pouziva `NumberFormat`.

**Comment by petervojtek** [comment]
vdaka za postreh, fixol som to v 0869be a 4c9ad57

**Comment by petervojtek** [comment]
vo vseobecnosti je to je spravene, dalsie sub-features riesime separatne, napr. v #144
