### ISSUE TITLE
meranie nadmorskej vysky

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#13]
pre zvoleny bod vypise nadmorsku vysku

**Comment by zdila** [comment]
samozrejme este to bude treba potom precistit, ale az pri globalnom precisteni kedy sa prida async loader, nasadi (najskor) redux atd... aj vyber toolov z horneho menu moze ist napr priamo do mapy, ako to je napr. na toposcope.freemap.sk.

**Comment by petervojtek** [comment]
podla mna to nema zmysel robit takto a davat to do main a potom stravime 2x tolko casu refactorovanim ako trval samotny vyvoj feature.

**Comment by zdila** [comment]
Ked nahodim redux aj tak sa to cele prekope - ajax volania budu upne inde, setState sa bude pouzivat minimalne.
