### ISSUE TITLE
Návrh / diskusia: nahradiť Leaflet Pigeon mapami

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-v3-react#130]
https://github.com/mariusandra/pigeon-maps

Nema to sice kopu hotovych featur ako Leaflet, ale je to nativne reactovske, ziadne wrappery a tym padom to vieme lahko rozsirovat. Projekt vyzera byt teraz menej aktivny, preto by som ho asi forkol ak by obycajne rozsirovanie nestacilo.

@petervojtek co ty na to?

**Comment by petervojtek** [comment]
mne leaflet v react nerobi ziadne konceptualne problemy, cize nevidim vyhodu prejst na inu mapovu kniznicu. ked uz tak by pre mna osobne bolo zaujimave zbavit sa reactu a prejst na vue.js, aby som si ho vyskusal vo vacsej mierke :)

a inak prave skusenost ako integrovat non-react kniznice do reactu sa mi na tom celom react.js zazitku zda asi najzaujimavejsia

**Comment by zdila** [comment]
Mne robi problem samotny Leaflet, ze ma rozne mensie/vacsie nedostatky. Ako napr.:

* nemoznost oznacit text v tooltipe (riesenie: pouzit mohutny popup, alebo implementovat Leaflet plugin (non-react))
* nemoznost nastavit popup aby sa nedal zavriet (napr. kliknutim na marker)
* nemoznost zmenit ikonu ked ju zacnes tahat (reportovane, nikto neriesi)
* "hacky" vytvorenie Leaflet pluginu, ktory by pouzival react

> a inak prave skusenost ako integrovat non-react kniznice do reactu sa mi na tom celom react.js zazitku zda asi najzaujimavejsia

Kedze to si uz zazil, mozem to brat tak ze uz najzaujimavejsie bolo? :-). Integroval si napr ten toastr, a ja som ti ho "odintegroval" ;-). A teraz chcem odintegrovat Leaflet.

> pre mna osobne bolo zaujimave zbavit sa reactu a prejst na vue.js, aby som si ho vyskusal vo vacsej mierke :)

Tomu ti samozrejme nebranim ani nie som proti, len prispievat tam najskor nebudem.

**Comment by petervojtek** [comment]
mne sa to zda nevhodne investovany (tvoj) cas. myslim ze by bolo pre spolocnost uzitocnejsie keby sme namiesto toho mali spravenu galeriu fotiek, alebo lepsie vyhladavanie.

to preco doslo k odstraneniu povodnej toast kniznice mi nie je jasne.

> mozem to brat tak ze uz najzaujimavejsie bolo?

urcite najzaujimavejsie pre mna bolo ked som sa ucil nove koncepty (cize react ako taky). sucasna faza je uz nuda (v pozitivnom zmysle).

tvoj pristup mi pripomina situaciu, ze mas v ruke kladivo a trapi ta, ze nie vsetko sa podoba na klinec :)

**Comment by zdila** [comment]
> mne sa to zda nevhodne investovany (tvoj) cas. myslim ze by bolo pre spolocnost uzitocnejsie keby sme namiesto toho mali spravenu galeriu fotiek, alebo lepsie vyhladavanie.

no ved to by som spravil az hned potom :-)

> to preco doslo k odstraneniu povodnej toast kniznice mi nie je jasne.

lebo:

* to bol ne-reactovsky pristup
* komponenta nema sama o sebe co zobrazovat toasty, ma len zavolat callback nech si to poriesi nieco vyssie akymkolvek sposobom (tj. napr. tym toastom)
* ak sa komponenta ktora zobrazovala toast unmountla predtym ako sa toast zavrel (zavrel si tool pri otazke ci vymazad bod), tak jeho ovladacie prvky (ano/nie) vyvolali chyby, lebo volali callback uz zruseneho komponentu
* nove "nativne" riesenie je jednoduche, ucinne a poskytuje feature, ktore neviem ci toastr ma (napr collapse key) alebo urcite nema (auto-zatvorenie toastu po dispatchovanie nejakej akcie). a lahucko si ho rozsirim podla potreby. Napr. pozri si branch `area-measurement-result-in-toast` kde namiesto popupu zobrazujem vysledok merania plochy v toaste, pricom tezt sa klasicky live-updatuje. Mozno by sa to dalo aj toastrom, ale neviem ci by tom nebolo dalsie hackovanie.

> tvoj pristup mi pripomina situaciu, ze mas v ruke kladivo a trapi ta, ze nie vsetko sa podoba na klinec :)

Zvolili sme si (zvolil som si :-)) napisat appku v React-e. Integrovanie nereactovskych veci UI bude vzdy take "hackovanie". Je to podobne ako keby som pisal v Jave nejaku desktopovu appku, nasiel by som nejaky super UI komponent napisany v JS, tak by som ho zintegroval cez Nashorn (JS engine pre Javu). Dakujem, ale ja si radsej pohladam menej super nativny komponent a rozsirim ho.

**Comment by petervojtek** [comment]
vdaka za detaily.

inak rozmyslal som nad tym co vlastne moze priniest [vyssi merit](http://www.merit.world/), a keby si (_sme_) tie pigeon maps znovuozivili a udrziavali, to by v konecnom dosledku asi bolo to naozaj prinosne (viac nez nejaky novy freemap portal :)

**Comment by zdila** [comment]
BTW pokus o to uz bol (https://github.com/FreemapSlovakia/freemap-v3-react/tree/pigeon-maps) avsak Pigeon maps este maju nejake ergonomicke chyby (ktore som im reportoval).

**Comment by MichalPP** [comment]
a nie radšej niečo čo zvláda vektorové tiles/MVT?

**Comment by zdila** [comment]
@MichalPP kludne. Navrhni. Nech to zvlada raster aj vektor a je to napisane v Reacte.

**Comment by MichalPP** [comment]
https://github.com/uber/react-map-gl alebo https://docs.mapbox.com/help/tutorials/use-mapbox-gl-js-with-react/ ale neskúšal som reactovú nadstavbu

samotné MVT som [skúšal](https://www.palenik.sk/mapa-podla-smeru#9/48.84/21.24)

**Comment by zdila** [comment]
Znova su to len wrappery a nie "nativne React". Ale skus spravit nejake demo - prepinatelne raster a vektor s  nejakym GeoJSON overlayom.

**Comment by MichalPP** [comment]
stačí to urobiť o 48 dní? teraz mám trochu perno..

**Comment by zdila** [comment]
keby nieco, tak v buducnosti mozno maplibre
