### ISSUE TITLE
Chyba zdieľania GPX s obsahom obsahujúcim diakritiku

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-v3-react#131]
V Chrome to vypluvne `Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.`.

Testcase: [miesta.zip](https://github.com/FreemapSlovakia/freemap-v3-react/files/1046077/miesta.zip)

**Comment by zdila** [comment]
PS nahodil som server na www.freemap.sk:3000 takze sa to da otestovat aj na next.freemap.sk.

**Comment by petervojtek** [comment]
zablokovane kvoli https://github.com/FreemapSlovakia/freemap-v3-nodejs-backend/issues/3
