### ISSUE TITLE
Plánovač trás - odlíšiť segmenty farebnými odtieňmi

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#134]
Idea, ak je to možné tak v prípade že si človek nakliká v plánovači nejakú koplikovanejšiu cestu z viacerými medzibodmi, tak striedať bledší a tmavší odtieň čiary jednotlivých úsekov.

**Comment by petervojtek** [comment]
ok, vyzera to takto:

<img width="672" alt="screen shot 2017-06-16 at 1 26 38 pm" src="https://user-images.githubusercontent.com/225506/27224834-8d34c956-5297-11e7-846c-03256688ebe5.png">
