### ISSUE TITLE
fotogaleria - razcestniky

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#137]
pripad pouzitia: pouzivatel chce pozerat iba fotky razcestnikov (a nechce vidiet ziadne ine fotky).

tu su moje postrehy:

pri nahravani fotky/fotiek razcestnikov to navrhujem riesit cez vlastny dialog (nejaky dropzone s nazvom "nahrat fotky razcestnikov"), pricom tam bude dropdown s moznostou zvolit typ "turisticky/cyklo/konsky/.."
a potom si uz backend nastavi flag `isGuidepost=true` a `guidepostType`.

v prvej iteracii ocakavame len fotky ktore su o-geotagovane, neskor mozeme pridat aj moznost urcit fotke polohu na mape.

co sa zobrazenia tyka, v prepinaci mapovych vrstiev by zrejme boli aspon dalsie dve polozky: 
* fotky turistickych razcestnikov
* fotky cyklorazcestnikov

v dalsej iteracii by sme mohli spravit, aby bolo mozne priradit existujuci guidepost (v osm) k fotke/fotkam razcestniku -- vdaka tomu sa budu dat jednoducho pridavat fotky bez geotagov.

**Comment by zdila** [comment]
zovseobecnil by som tento issue na "filtorvanie fotiek". filtre:

* kategoria (razcestniky / priroda / ...)
* pouzivatel
* hodnotenie fotiek
* cas (idealne fotenia, z exifu...)

**Comment by zdila** [comment]
implementovane formou volnych tagov (zatial)
