### ISSUE TITLE
fotogaleria - nie je zrejme ze na fotky sa da kliknut

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#138]
chcelo by to zmenit kurzor mysi onmouseover.
avsak vzhladom na to ako je to implementovane to asi nebude mozne.
ak tomu spravne rozumiem, fotky su bitmapova vrstva nad mapou, cize nevieme pouzit css `:hover`.

Leaflet overlays podporuju `mouseover` event -- ale predpokladam ze to berie celu vrstvu ako spojitu plochu (a nie "deravu").

**Comment by zdila** [comment]
Pri momentalnom rieseni to nie je mozme. Rozmyslal som ale ze by to neboo riesene formou bitmapovej vrstvy, ale by sa dynamicky dotahovali POI na miestach kde su fotky.

Dalsia vec ze by to bolo ako tool, nie ako vrstva, lebo prezeranie obrazkov v kombinacii napr. s meranim alebo planovanim cesty moze byt nesikovne.

**Comment by petervojtek** [comment]
sucasne riesenie ze fotky su bitmap overlay je pekne v tom ake je to rychle.
ale predpokladam, ze ak budeme chciet pridat #137, tak zrejme pojdeme cestou dynamickeho tahania fotiek (lebo inak by sme asi museli na backende rendrovat dalsiu vrstvu. v takom pripade predpokladam, ze ak by pouzivatel nahral fotku, hned by ju nevidel, lebo fotky-tiles sa prerenduju az po nejakom case).

**Comment by zdila** [comment]
inac riesenie zmenit kursor mysku len ked prides nad fotku nie je celkom spravne, pretoze ono to aj tak vyhlada vsetky fotky v radiuse okolo mysky. uvazujem nad zobrazovanim silno priesvitneho kruhu okolo mysky aby clovek videl ten radius.

**Comment by petervojtek** [comment]
> silno priesvitneho kruhu okolo mysky aby clovek videl ten radius.

to znie dobre.

**Comment by zdila** [comment]
fixed in 1d85921
