### ISSUE TITLE
prichod na planovac cez url -- prepinac mapovych vrstiev sa rozbrazi 3x

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#139]
napr. idem na http://next.freemap.sk/?map=12/48.79884/19.42657&layers=K&tool=route-planner&transport=car&points=48.79850/19.37611,48.79103/19.38263,48.81500/19.44202

a zobrazi sa toto:

<img width="170" alt="screen shot 2017-06-16 at 1 13 36 pm" src="https://user-images.githubusercontent.com/225506/27224478-a31afb66-5295-11e7-8968-8fadfd4dadaf.png">

**Comment by petervojtek** [comment]
aj indikator vzdialenosti v pravom dolnom rohu je 3x

**Comment by zdila** [comment]
Lepsie 3x ako vobec ;-)

**Comment by zdila** [comment]
Najskor si to privodil v 06f188636713ad2d190d72b9b1450df0df0a10fa. Dal som tam taky narychlo surovy fix, prosim precisti ak treba.

**Comment by petervojtek** [comment]
tento bug sa deje aj na starsich commitoch ktore predchadzaju 06f1886 (napr. 46370ad), tak ktovie..
