### ISSUE TITLE
nastavenie: png/jpg dlazdice

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#14]
napr. pri slabsej konektivite si to zmenim na jpg.

az raz bude podporovane toto, tak to mozeme menit automaticky:
https://developer.mozilla.org/en-US/docs/Web/API/Network_Information_API

**Comment by zdila** [comment]
@petervojtek spravil som Layes znova bezstavovym funkcionalnym komponentom. Zbytocne si tam zaviedol stav a preniesol definicie zakladnych vrstiev z `mapDefinitions.js`.

**Comment by petervojtek** [comment]
Martin @zdila , podla mna tvoje zmeny sposobuju horsiu citatelnost kodu:
*  [toto](https://github.com/FreemapSlovakia/freemap-v3-react/blob/master/src/components/Layers.js#L13) je bez kontextu tazko zrozumitelne a v buducnosti nachylne na rozne chyby.
* namiesto [tohto](https://github.com/FreemapSlovakia/freemap-v3-react/blob/master/src/components/Main.js#L245) je podla mna prehladnejsie explicitne vymenovat string-y (ako casto sa za poslednych 5 rokov menili na freemap zakladne vrstvy?)
* mapDefinitions -- kym to pouziva iba jeden komponent, nevidim pointu mat tie definicie vo vlastnom subore -- len to zhorsuje citatelnost.

**Comment by zdila** [comment]
absolutne si dovolim nesuhlasit s prvym bodom. zpomen nejake chyby na ktore je to nachylne.

nachylne na chyby su stavove komponenty. sablona mapy definuje uz teraz {s}, {x}, {y}, {z} takze pridat jdnu naviac nevidim ako ziaden problem. naviac aj jej nazov vravi o com je.

k druhemu bodu - mozeme to dat do extra supboru s nasimi proptypes, ale opakovat stale tie site stringy mi nepride ako velmi dobra programatorska praktika

k poslednemu, tiez nechapem co tym mienis. nie preto sa delia moduly a funkcie do mensich, lebo sa pouzivaju na viacerych miestach, ale preto, lebo to zvysuje citatelnost. ale hlavne ze si v mapDefinitions nechal overlays - to ti tam uz nevadilo?

pozri si rozne ine projekty, tam je takato praktika bezna. nie pisat dlhe subory, ale delit ich do mensich celkov kde kazdy celok definuje presne domenu.

**Comment by petervojtek** [comment]
> absolutne si dovolim nesuhlasit s prvym bodom. spomen nejake chyby na ktore je to nachylne.

prepac, mas pravdu, na prvy pohlad som si myslel ze to hladas/replacujes na zaklade stringu 'jpg'/'png'.

> ale hlavne ze si v mapDefinitions nechal overlays - to ti tam uz nevadilo?

mal som v plane to tiez odtial presunut do Layers :)

**Comment by zdila** [comment]
V e42f9b9b00861e8eb0dcc7c9a6a7e776f3f61eb5 som vyextrahoval "nase" proptypes do estra reusable suboru
