### ISSUE TITLE
Planovac - prichod cez url - nespravne nastavovanie start/stop markeru

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#140]
nizsie uvedene sa deje iba ked pridem na planovac cez url, napr. http://localhost:8080/?map=10/48.85975/19.56940&layers=K&tool=route-planner&transport=car&points=48.80867/19.16565,48.79420/19.37714,48.81003/19.64630

* ked nie je aktivne ani tlacidlo (dropdown) start, ani stop, tak teraz kliknutie do mapy presunie poziciu startu. kliknutie do mapy v takejto situacii by nemalo zmenit polohy ziadnej markeru
* ked kliknem na tlacidlo Stop a kliknem do mapy, zmeni sa poloha markeru Start

**Comment by zdila** [comment]
Mne to po fixnuti #139 nerobi. A predtym som to neskusal.

**Comment by petervojtek** [comment]
potvrdzujem ze uz to nerobi
