### ISSUE TITLE
spatna kompatibilita s url parametrami stareho freemap-u

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#141]
vselikde po webe lezia odkazy na stary freemap, napr. http://www.freemap.sk/#p=49.04854|18.42833|9|T

v novej verzii by sme mali byt tieto url parametre konvertovat na nove.

**Comment by petervojtek** [comment]
Martin @zdila , netusis preco co v starom freemap-e znamena to posledne `T` ?
```
http://www.freemap.sk/#m=T,p=48.22069|17.42333|16|T
```

pri prepinani mapovych vrstiev sa meni parameter `#m=`, zatial co to posledne `T` sa zda sa vobec nemeni.

**Comment by zdila** [comment]
Tipujem ze to je to iste `T` ake je za `m=` len sa to nejako zle synchronizuje. Ale ak chces presnu odpoved, skus napisat @nickn17 alebo dodimu.

**Comment by petervojtek** [comment]
ok, pridal som podporu pre toto:
```
#p=48.21967|17.37481|14|C   // rozozna to ako cyklomapu
#p=48.20846|17.4021|14|C,m=A  // rozozna to ako automapu
?m=A&p=48.1855|17.4029|14   // ako automapu
```

@nickn17 , vies poradit ake ine url parametre zvyknu/zvykli ludia pouzivat v starom freemape? /nie je  asi cielom podporovat vsetky specialne pripady, skor tie napouzivanejsie). 

ak dobre pozeram, embednuty stary freemap vyzera takto:
```
http://embedded.freemap.sk/?lon=19.35&lat=48.55&zoom=8&marker=1&layers=A
// plus nejake dalsie optional parametre
```
tam by sme ale najprv. museli dat podporu na urovni webserveru, aby nam domenu tretieto stupna `embedded.freemap.sk` prepisal na nieco ako `freemap.sk?embed=true`.

**Comment by zdila** [comment]
nie som si isty ci nickn17 na githube je Lubos...

**Comment by petervojtek** [comment]
hehe, vyzera ze nie :)

**Comment by petervojtek** [comment]
todo: pridat spatnu kompatibilitu pre http://embedded.freemap.sk/ odkazujuci na infobod

**Comment by petervojtek** [comment]
ok, novy freemap rozoznava tento stary format:
```
embed.freemap.sk/?lon=19.35&lat=48.55&zoom=10&marker=1&layers=T
```
a vtedy zobrazi portal v embed mode a vlajocku v strede mapy

este [vsak existuje aj druhy format](http://wiki.freemap.sk/EmbeddedFreemap) pre embednutie stareho freemapu:

```
http://embed2.freemap.sk/index.html?lat=48.79&lon=19.55&zoom=12&layers=T&markerLat=48.8&markerLon=19.6&markerHtml=Hello&markerShowPopup=1
```

pre ten podporuje ste len pridame.

**Comment by petervojtek** [comment]
ok, pridana podpora aj pre druhy format embedded url `index.html?lat=48.79&lon=19.55&zoom=12&layers=T&markerLat=48.8&markerLon=19.6&markerHtml=Hello&markerShowPopup=1`
