### ISSUE TITLE
embedded mode - vlajka/tooltip s textom ako url parameter

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#143]
stary freemap podporuje dva sposoby ako upriamit pozornost na konkretny bod:
* vlajocka
* tooltip s textom

**Comment by zdila** [comment]
Toto by sa mozno mohlo dat nejako skombinovat s toolom zistenia pozicie/vysky. Tooly merania by som tiez chcel premietat do URL a tym padom by boli lahko zdielatelne.

**Comment by petervojtek** [comment]
hmm. 
mozeme spravit komponent s nazvom `InfoPoint` (url/kompomentove parametre `infoPointLat`, infoPointLon` a `htmlContent`).
v embed mode ho vyrendrujeme ak su url parametre `?embed=true&infoPointLat=..`.
ak je `htmlContent` null, vyrendrujeme vlajocku.

nastroj na meranie vysky tiez pouzije komponent `InfoPoint` (namiesto sucasneho `MarkerWithAutoOpeningPopup`).

synchronizaciu stavu url si bude riesit  samotny `InfoPoint`.
neskor bude mat InfoPoint aj mod na editovanie (posuvanie polohy) -- kvoli embed wizardu.

**Comment by petervojtek** [comment]
alebo este lepsi nazov je `UrlSyncedPoint`, kedze neskor mozno budeme mat aj `UrlSyncedLineString`, a podobne.

**Comment by zdila** [comment]
Komponenta nema co tusit ze existuje nejake URL. Na to je Logic a spol.

**Comment by petervojtek** [comment]
no, pridal som zakladny InfoPoint (bez synchronizacie s URL):

funguje to tak, ze ked pojdes na url:

http://localhost:8080/?map=12/48.12302/17.15721&layers=C&tool=info-point&info-point-lat=48.12302&info-point-lon=17.15721&info-point-label=tu%20sa%20stretneme&embed=true

zobrazi sa marker s tooltipom s textom `info-point-label`.
ked nie je zadany parameter `info-point-label`, zobrazi sa len samotny marker.

v nie-embedded mode sa ten nastroj bude volat napr. "Zdielat odkaz na lokalitu" (nie je to najlepsi nazov).

  planujem spravit to, ze v hornej liste budu tlacidla "posunut bod", zmenit "popis", "zdielat", a "vlozit na inu stranku". 
kliknutie na "zdielat" poskytne URLku, napr. ked chces niekomu poslat emailom miesto kde sa stretneme.

kliknutie na "vlozit na inu stranku" by mohlo otvorit popup, v ktorom bude kod s iframom a pripadne ten iframe hned aj bude vidiet v popupe. nebude to uplne interaktivny wizard, ale myslim ze by to mohlo stacit.
