### ISSUE TITLE
Pridat celkova nastupana vyska do info o trase

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#144]
Ak si naklikam alebo importujem trasu do mapy, viem si zobrazit jej vyskovy profil. Pri importovanych mapach tam vidim aj info box s nejakymi udajmi o trase, napriklad minimalna nadmorska vyska a maximalna. Avsak nevidim tam celkove nastupane prevysenie (elevation gain) co si myslim ze je dolezity udaj ktory by mohol zaujimat aj inych okrem mna.

P.S. je ten info box zobrazitelny aj pri naklikanych trasach? Nevidim na to tlacitko.

**Comment by petervojtek** [comment]
@alexanderzatko, pridal som to prehliadaca tras aj info o celkovej nastupanej a naklesanej vyske. zatial je to spravene len velmi jednoducho a neosetruje to uletene nadmorske vysky.

ja mam ako referecny aplikaciu iba Locus, ale ta meria nastupanu vysku podla mna (aj teba) uplne prehnane (napocita viac nez by sme cakali). nasadil som novu verziu na next.freemap.sk, ked tak vyskusaj to so svojimi gpx logmi a daj vediet ci by to malo ukazovat viac alebo menej) [idealne potom priloz do tejto issue aj nejake gpx a uved ake cisla od toho cakas :)

ten infobox je dostupny len v prehliadaci tras. dal by sa dat aj inde, keby o to bol velky zaujem.

**Comment by alexanderzatko** [comment]
[Track 001-1.gpx.zip](https://github.com/FreemapSlovakia/freemap-v3-react/files/1092689/Track.001-1.gpx.zip)
 Pre pripojeny subor mi Ascent aplikacia vypocitala prevysenie 1681 m, ked mam v preferenciach nastavene "altitude smoothing" 95 zo 100. Netusim aky algo pouziva :-(
...ale myslim ze je to ako-tak spravne cislo. 

Na http://utrack.crempa.net/ mi to pocita cez 4 km, co je nezmysel.

**Comment by petervojtek** [comment]
pridal som do nastaveni parameter (viditelny iba v expertnom mode), ktory umoznuje nastavovat sirku plavajuceho okna ktorym sa vyhladzuje ele profil pri vypocte celkovej nastupanej/naklesanej vysky.

<img width="662" alt="screenshot 2017-06-22 13 36 11" src="https://user-images.githubusercontent.com/225506/27432285-d74f3bea-574f-11e7-876c-67c97d4924e7.png">

od hodnoty 5 a vyssie to robi navyse aj taku vec, ze z daneho plavajuceho okna vyhodi pred priemerovanim najvyssiu a najnizsiu hodnotu.
