### ISSUE TITLE
ak embedded mode odkazuje na infopoint a pouzivatel klikne na logo freemap, mal by sa mu tiez zobrazit infopoint

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#145]
teraz sa mu zobrazi len zakladny pohlad na portal

**Comment by petervojtek** [comment]
tento bug bude zadarmo vyrieseny ked url bude zodpovedat stavu aplikacie

**Comment by zdila** [comment]
Klik na logo už nemaže obsah mapy.
