### ISSUE TITLE
socialna vrstva nad mapou -- polohy poslednych changesetov

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#146]
predstavujem si to tak, ze nad mapou sa zobrazia markery/plochy kde boli robene posledne zmeny (pouzivatel si moze zvolit za kolko poslednych dni/tyzdnov).

jeden pripad pouzitia je, ze si pozriem cele slovensko za posledne dva tyzdne, a uvidim, ze:
* 2 dni dozadu bol pouzivatel Martin na vylete v Slanskych vrchov
* vcera Jose pridal kaviaren v Novom meste
* ...

cize prehlad "aku aktivitu vyvija openstreetmap komunita na slovensku".

v prvej verzii sa po kliknuti na dany chaneset (resp. jemu zodpovedajuci  marker+popup) zobrazi odkaz na changeset na osm.org, alebo na achawi.

https://wiki.openstreetmap.org/wiki/API_v0.6#Query:_GET_.2Fapi.2F0.6.2Fchangesets

ak by sme to mali pouzivat intenzivnejsie, je potrebne spravit nejaky buffer na nasom backende, lebo:
> The editing API is provided in order to edit the map data, not for read-only purposes or projects. Clients may be blocked without notice if they are affecting the service level for others or causing data corruption.

**Comment by petervojtek** [comment]
pridana prva verzia. mozne vylepsenia do buducnosti:
* v menu dropdown vyber ako stare changesety sa maju zobrazit (pri vacsom pocte dni to uz ale bude treba obmedzit na mensi bbox -- teraz je to cele sr)
* starsie changesety budu mat viac priehladnu ikonku
* zobrazit avatary pouzivatelov

**Comment by zdila** [comment]
Super to je.

Poznamky:

* nie achawi ale Achavi
* namiesto tlacitok by som dal linky, tak ako je spraveny autor ("semanticky" spravnejsie)
* na popisky vo formate "nazov: hodnota" by sa viac hodilo http://getbootstrap.com/css/#horizontal-description (to aj do info o trase a vsade kde sa takyto zoznam vyskytuje)

**Comment by zdila** [comment]
A tlacitko "Stiahnut zmeny" je podla mna zatial zbytocne kym sa da nastavit iba jeden parameter. Alebo aspon pouzit to iba na prvotne stiahnutie a potom uz automaticky.

**Comment by petervojtek** [comment]
vdaka za postrehy, tie odrazkove poznamky implementujem.

> A tlacitko "Stiahnut zmeny" je podla mna zatial zbytocne kym sa da nastavit iba jeden parameter. Alebo aspon pouzit to iba na prvotne stiahnutie a potom uz automaticky.

podla mna nebude dobre ked to bude tahat data automaticky pri kazdom mapRefocus-e, lebo co aspon ja casto robim je ze stiahnem vacsiu oblast a potom si zoomujem a odzoomujem sa nad jednotlive changesety (najma ked ich je viac na sebe sa z vysky neda dobre precitat autor/message) - a vtedy nechcem aby sa robili dalsie requesty.

**Comment by zdila** [comment]
aha, to som si neuvedomil, ze on mapchange by to bolo treba znovunacitat :-)

**Comment by petervojtek** [comment]
ten bootstrapovsky `<dl> <dt> <dd>` som skusil pouzit, ale pouziva to prilis velky padding/margin, takze som to radsej nepouzil. keby nahodou, [tu som to odlozit do gist-u](https://gist.github.com/petervojtek/1b1c10c2ccfdb96e71d6c241bd920147).

<img width="605" alt="screenshot 2017-06-26 15 22 00" src="https://user-images.githubusercontent.com/225506/27541271-9e97b6b0-5a83-11e7-9591-a8d8112762c9.png">

**Comment by petervojtek** [comment]
ukazuje sa, ze osm api nezarucuje, ze sa zobrazia vsetky ocakvane changesety aj ked je vybrany velmi maly bbox. [napr. tento changeset](https://www.openstreetmap.org/changeset/49212050) to zda sa nikdy neukaze, lebo ho predbehne 100 inych changesetov (100 je zda sa limit na osm backende) -- predbehnu  sa novsie changesety, ktore pokryvaju sialene velke uzemia, vid min/max lat/lon::

```
  <changeset id="49630318" user="mikecc" uid="14034" created_at="2017-06-18T09:03:04Z" closed_at="2017-06-18T09:03:07Z" open="false" min_lat="2.0909295" min_lon="-118.150338" max_lat="49.6949134" max_lon="111.4866568" comments_count="0">
    <tag k="source" v="Bing; Geotagged Images; dort gewesen"/>
    <tag k="created_by" v="JOSM/1.5 (12275 en)"/>
    <tag k="comment" v="Dies und das"/>
  </changeset>
```

**Comment by petervojtek** [comment]
ok, vsetko podstatne som uz myslim implementoval
