### ISSUE TITLE
warning.js: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#147]
my vsade mame spravne `import PropTypes from 'prop-types';`. (rovnako s `React.createClass is deprecated`)

> These warnings could be coming from anything in your entire dependency graph. You'll have to ensure everything in node_modules has updated, as well.
https://github.com/airbnb/enzyme/issues/901

**Comment by zdila** [comment]
problemove su tieto 2 packages:
- react-leaflet-bing
- react-stars

projektom som poslal pull requesty.
