### ISSUE TITLE
fotogaleria - komentovanie a hodnotenie

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-v3-react#148]
Skusil by som to riesit pomocou sluzby ako napr. Disqus. Po kliku by na mapy by potom nezobrazilo vsetky foto v radiuse pod sebou, ale koli komentarom vzdy iba jenu a s tlacitkami "dalsia" a "predosla". Tym padom by vlastne aj radius mohol byt vacsi. Poradie fotiek je podla vzdialenosti od stradu (uz aj teraz).

**Comment by petervojtek** [comment]
rozmyslam ako sa autor fotky/ini dozvedia, ze pribudol komentar.
co sa autora tyka, [az bude identita autor prepojena na disqus](https://github.com/FreemapSlovakia/freemap-v3-react/issues/149#issue-238473176), tak bude autor dostavat emailom od disqusu notificie -- ale to je trochu vzdialenejsia buducnost.

pre blizsiu buducnost by v nastroji Galeria obrazkov mohlo byt toggle Zobrazit posledne komentare, a vyroloval by sa nejaky feed.

**Comment by zdila** [comment]
Ked kliknes na text "Freemap Slovakia" tak sa ti take nieco aj zobrazi.

![image](https://user-images.githubusercontent.com/636095/27577117-cf5147de-5b1f-11e7-93e3-0ee4a8ee77fe.png)

Ale do buducna mozno aj zrusime DISQUS a dame vlastne riesenie, ked narocnost implementovania nasich specialit prevysi.

**Comment by zdila** [comment]
viacmenej hotovo, nasledovat budu uz len vylepsenia.

**Comment by petervojtek** [comment]
ta slovenska lokalizacia Disqus je carovna :)

<img width="475" alt="screenshot 2017-06-27 11 12 39" src="https://user-images.githubusercontent.com/225506/27579971-961f6d42-5b29-11e7-9b6b-83c6d9a45fcf.png">

**Comment by zdila** [comment]
:smiley:

**Comment by zdila** [comment]
Neskutocne. Nacitanie prazdnej diskusie mi spravi 65 HTTP requestov. Ked strankujem fotky tak ich spravi pri kazdej fotke.

**Comment by petervojtek** [comment]
myslim ze skoncime s vlastnou implementaciu komentarov, ale z ineho dovodu: aktualne hned nevidiet, kolko komentarov ma fotka - so socialneho hladiska je to presne ta informacia, ktora je zaujimava. clovek ktory sa nudi a chce nieco "zazit", ide na nastroj Galeria obrazkov a co ho zaujima su fotky, "kde sa nieco deje" (teda kde su nove komentare). to s disqus podla mna nie je mozne jednoducho spravit (velmi zbezne som pozeral [disqus api](https://disqus.com/api/docs/) a nenasiel som endpoint ktory by nam umoznil implementovat nieco ako indikator poctov komentarov pre fotku).

**Comment by zdila** [comment]
ok, postupne prejdeme :)
