### ISSUE TITLE
fotogaleria - sprava fotiek

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-v3-react#149]
* upload
* mazanie
* editovanie (popisky, posun)

Na to vsak treba najprv implementovat konta (pomocou osm.org oauth? a prepojit s disqus... ale to uz je tu offtopic)

**Comment by Mirecnet** [comment]
Keby sa dal robit user friendly upload fotiek, tak to by bolo inak super....

**Comment by zdila** [comment]
upload je spraveny. pre editaciu bude zvlast issue.
