### ISSUE TITLE
ako robit scoped css ?

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#15]
@zdila , zatial vsetko css davam do `styles/page.css`, ale rad by som pouzival per-component s/css - Martin, ak mas skusenost s nejakym pristupom v react, daj vediet.

**Comment by zdila** [comment]
Najjednoduchsie riesenie je vytvorit `*.scss` subor per komponent a v komponente dat na zaciatok `include '../styles/someComponent.scss';`.

Ale je viacero rieseni, skus vygooglit `react modular css`.

**Comment by petervojtek** [comment]
ok, vdaka, pouzil som to prve.
