### ISSUE TITLE
fullscreen rezim

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-v3-react#152]

**Comment by petervojtek** [comment]
mas na mysli len schovanie hornej listy, alebo uplny fullscreen (ako maju video prehravace?):
https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API

**Comment by zdila** [comment]
uplny, ako maju na openstreetmap.cz. polyfill najdes na https://github.com/neovov/Fullscreen-API-Polyfill :-)

**Comment by petervojtek** [comment]
skusil som ten Fullscreen-API-Polyfill, ale nemam pocit ze funguje. 
tato metoda mi funguje (standartne browser api):
```
document.documentElement.webkitRequestFullscreen()
```

polyfill ma pridat metodu 
```
document.documentElement.requestFullscreen()
```

ale u mna element taku metodu nema (ani ziaden iny dom element).

**Comment by zdila** [comment]
Asi ti ho z nejakeho dovodu neaplikuje. My ten polyfill pouzivame (na www.gruveo.com) a funguje.
