### ISSUE TITLE
prehliadac tras - moznost farebne odlisit klesania a stupania

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#157]
cca nieco taketo:

<img width="717" alt="screen shot 2017-07-07 at 9 55 38 am" src="https://user-images.githubusercontent.com/225506/27948546-76ca5028-62fa-11e7-99e7-dad101a6847b.png">

**Comment by zdila** [comment]
Fuha,  sama dopravna zapcha ;-).

Inac neda sa plynuly prechod podla sklonu?

**Comment by petervojtek** [comment]
myslis nieco taketo? https://iosphere.github.io/Leaflet.hotline/demo/

v podstate sa cez farebny gradient daju zobrazovat dve rozne informacie:
* nadmorska vyska
* sklon

ja osobne nemam velku pridanu hodnotu zo zobrazenia farebnej ciary s plynulym prechodom kde farby zodpovedaju nadm. vyskam (ako to robi napr. locus) -- najma preto, ze niektore farby ludske oko vnima ovela vyraznejsie ako ine (cervena vs zltozelena).

ale preto som vytvoril tuto issue, aby sme diskutovali co sa komu paci..

**Comment by zdila** [comment]
nadm. vysku som nemyslel, len sklon.

**Comment by petervojtek** [comment]
cize mali by sme len dve farby (napr. cervena a modra) a to ako budu na konkretnom bode polyline namixovane zavisi od sklonu (derivacie) funkcie prevysenia?

**Comment by zdila** [comment]
Take nieco. Ak to nie je zlozite.

**Comment by petervojtek** [comment]
znie to dobre, vyskusam to..

**Comment by petervojtek** [comment]
duhova trasa ofarbena podla nadm. vysky napokon vyzera podla mna citatelnejsie nez v locuse, takze som ju na uvod pridal. viditelna je iba ked pouzivatel stlaci tlacidlo Vyskovy profil:

<img width="1268" alt="screenshot 2017-07-09 10 59 25" src="https://user-images.githubusercontent.com/225506/27992486-ede0f512-6495-11e7-9d58-7852f2ae1dd1.png">

**Comment by petervojtek** [comment]
este ten kod budem refactorovat, lebo [toto je neefektivne](https://github.com/FreemapSlovakia/freemap-v3-react/commit/64771fcdaf81dde883fcb48b4b5dd3c4a20bcbe9#diff-c4f21d532b5eba12ab6726f6fb4f8570R111) a farebna ciara sa odstrani a znovu vykresli pri kazdom onmouse over (pri zobrazeni zobrazeni infobodu nad ciarou)

**Comment by zdila** [comment]
N a este pridat vyfarbovanie podla intenzity stupania/klesania :).

**Comment by petervojtek** [comment]
hej, chcem tam pridat prepinac (podla akej funkciu sa ma trasa ofarbovat) a tym uzavriem tuto feature

**Comment by zdila** [comment]
...mozno este podla rychlosti a svetovej orientacie :).

Pripadne este aj volbu "intenzita vyhladzovania" - tj. ked si dam vyfarbovanie podla stupania a na kilometri som isiel 10x hore a 10x dole, tak chcem aby mi nezobrazilo 10 farebnych prechodov, ale spriemerovalo. Ale to moze byt kludne spravene aj neskor...

**Comment by petervojtek** [comment]
no, je to tam, ale ofarbenie podla skonu som pre jednoduchost spravil len na pevno tak, ze extremy (plna cervena/plna zelena) su pri 100% stupani (na vzdialenost 1m nastupam 1 vyskovy meter) -- co je celkom v pohode pre turisticke vylety, ale pre cyklovylety niekedy malo vyrazne.

ak by sme to chceli robit lepsie, chcelo by to [lepsiu funkciu vyhladzovanie nadm. vysiek](https://github.com/FreemapSlovakia/freemap-v3-react/blob/master/src/geoutils.js#L117). skoda ze tato [js kniznica pre Kalmanov filter](https://github.com/wouterbulten/kalmanjs) ma velmi nejasne parametre, inak by som ju uz vyskusal..
