### ISSUE TITLE
Plánovať - suma stúpanie/klesanie

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#158]
Bolo by možné pridať niekde v plánovači trás informáciu o nastúpanej prípadne aj naklesanej výške?
mohlo by to byť vkľude aj v grafe  výškového profilu.

**Comment by petervojtek** [comment]
to by slo, ze informacie o najvyssom a najnizsom bode a nastupana a naklesana vyska budu priamo pod grafom prevysenia.

**Comment by zdila** [comment]
Medzicasom to bolo zimplementovane.

![image](https://user-images.githubusercontent.com/636095/53665407-a641ad00-3c6b-11e9-9d4b-4286c9571d05.png)
