### ISSUE TITLE
nastroj "Detaily v mape"

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#159]
#jeden pripad pouzitia: 
ked kliknem na cestu (alebo v jej tesnej blizkosti), zobrazil by sa toast s informaciou aky je to tracktype a povrch (pripadne dalsie key-values) a vysvieti sa dana cesta.
uzitocne ked si planujem vylet na cestnom bicykli.

povodne sme asi predpokladali ze taka funkcia bude sucastou #93 alebo #54, ale zda sa mi ani jedna z tychto issues sa nehybe dopredu a nie je nam zrejme ako to robit "zhora nadol".

preto by som uz ani nesnazil robit nastroj podobny nastroju "?" na openstreetmap.org, pretoze to je vseobecny dopytovaci nastroj ("co je v okoli?") --  a je vhodny pre expertov, ale nie pre beznu populaciu (a experti uz dnes mozu pouzit osm.org).

radsej by som na to siel cez konkretne pripady pouzitia. preto navrhujem pridat nastroj s nazvom "Detaily v mape" (pripadne s lepsim nazvom), a ten bude mat zatial jedine tlacidlo -- "Stav cesty", ktore ked je aktivne a kliknem do mapy, tak sa zobrazi vyssie spominany toast.

dalsie tlacidla by mohli byt:
* Detaily turistickej trasy (v toaste sa zobrazi sa info o relacii, dlzka, farba, ci je complete, ref, a na mape sa vysvieti cela trasa) 
* Detaily cyklistickej trasy

**Comment by zdila** [comment]
Nevyhody tohoto nastroja voci funkcii "?" (#54):

* na zistenie napr. stavu cesty musis spravit o jeden krok viac - zvolit "Stav cesty". Do buducna tam moze byt kludne aj 30 volieb a tym to bude dost neprehladne
* co ak mas vybrate "Stav cesty" a kliknes povedzme na jazero?
* co ak mas vybrate "Stav cesty" a kliknes medzi 2 rozne cesty?
* Funkcia "?" mi vrati vsetko o objektoch pri ktorych som klikol. Tych informacii nebude az tak vela ze by som sa v tom stratil a naraz zistim vsetko (napr. kapacitu parkoviska, ci je kryte, povrch parkoviska, poplatok, ci je supervised, ...)

**Comment by petervojtek** [comment]
> na zistenie napr. stavu cesty musis spravit o jeden krok viac - zvolit "Stav cesty". Do buducna tam moze byt kludne aj 30 volieb a tym to bude dost neprehladne

cast volieb bude vidiet len pre urcity typ mapy (napr. info o turistickej trase nebude dostupne pre inu mapu ako T) a nemyslim si ze by sme sa mali snazit podporovat vselijake specialne pripady pouzitia, ale iba tych zopar najbeznejsich.

> co ak mas vybrate "Stav cesty" a kliknes povedzme na jazero?

ak bude nejaka cesta velmi blizko, tak sa zobrazi dana cesta, inak sprava "v blizkosti kliknutia nebola najdena ziadna cesta".

 >co ak mas vybrate "Stav cesty" a kliknes medzi 2 rozne cesty?

zobrazi sa ta, co je blizsie

> Funkcia "?" mi vrati vsetko o objektoch pri ktorych som klikol. Tych informacii nebude az tak vela ze by som sa v tom stratil a naraz zistim vsetko 

lenze poda mna sa nam "?" nepodari poludstit a bude z toho nieco ako  phpmyadmin (alebo oma.sk :). vhodne pre expertov, ale beznym ludom su tie informacie nevelmi uzitocne.
napr., chce sa ti prekladat do slovenciny vsetky kluce a hodnoty z osm ontologie a to tak, aby im ludia rozumeli bez skumania detailov na osm wiki (ak navyse nevedia po anglicky)? 

priklad:
pre bezneho pouzivatela samotna infomacia "tracktype=track2" nema ziadnu hodnotu.
teraz ma napadlo, ze dokonca by som podnastroj ani nenazyval "stav cesty", ale ak je zapnuta cyklovrstva, nazval by som to tlacidlo "pre aky typ bicykla je cesta vhodna?" a dal tam mapovanie:
*  g1/g2 = zjazdne na cestnom bicykli
* g3 = zjazdne na trekkingovom bicykli
* g4 = zjazdne na horskom bicykli
* g5 = nevhodne pre bicykel

a iba ked je zapnuty expertny mod by som dodatocne zobrazil aj explicitne osm keys a values

**Comment by zdila** [comment]
Vlastne tento nastroj je "?" s filtrom - ze co ma dat do overpass query a co spracovat z vysledku.

**Comment by MichalPP** [comment]
to api co som vela mesiacov dozadu urobil ste si aspon pozreli?

**Comment by petervojtek** [comment]
@MichalPP , ak mas na mysli toto: http://www.oma.sk/api?lat=48.14627&lon=17.11128&vzdialenost=25&mapa=T

ak som spravne pochopil, to je dobre api pre re-implenentaciu nastroja "?"  z osm.org -- ale to je prave to, comu sa tu snazim vyhnut.
pricom netvrdim, ze napokon nebudeme mat nieco ako nastroj "?" v freemap portali, ale ako som vyssie pisal, je to nastroj pre ludi ktory rozumeju osm ontologii, kym tu sa snazim navrhnut riesenie pre plebs.

**Comment by Mirecnet** [comment]
hehe novy pojem: riesenie pre plebs :) A potom, ze preco ITakom nik nerozumie :D

**Comment by MichalPP** [comment]
@petervojtek nie, nie je reimplementacia. ak by si klikol na ten link, vidis ze to je dost daleko od ontologie osm.

je to na zakladne info par px v okoli kliku. co sa zobrazuje nastavujem podla layeru mapy.

**Comment by zdila** [comment]
@MichalPP a vies spravit aby to nevracali Javascript ale JSON a neobsahovalo HTML markup (viazany na oma.sk)?

**Comment by petervojtek** [comment]
ak tomu spravne rozumiem, http://www.oma.sk/api?lat=48.14627&lon=17.11128&vzdialenost=25&mapa=T vracia pouzivatelsky krajsie vysledky nez "?" nastroj na osm.org, ale moja pointa v prvom komentari v tejto issue bola, ze pouzival vie co hlada ("pre aky typ bicykla je vhodna dana cesta?"), a pre ziskanie odpovede na tuto otazku je jednoduchsie je pouzit overpass ql, nie? to oma api bude zrejme fajn na implementaciu lepsieho najstroja "?" - ked pouzival celkom nevie co hlada (resp. nevie co vsetko je v db).

**Comment by MichalPP** [comment]
@zdila urobíš nejaký vzor ako to vracať? (napr uprav ten link hore do iného textu, ja presne nechápem aký je rozdiel medzi js a json)

@petervojtek podľa toho akú má zapnutú vrstvu viem čo asi hľadá (?), a teda je len vec dohody čo zobrazíme pri danej vrstve (a danom zoome). teraz je len prvý nástrel čo spája čiary a body do jedného.

**Comment by zdila** [comment]
@MichalPP  Rad by som vyuzival najviac rozsirene APIcka a implementoval a pouzival vlastne len ak nenajdeme nic v hodne. Tym padom sa nemusime starat o aktualizacie, beh servrov, riesenie roznych chyb. Na tuto featuru bude overpass API uplne stacit.

@petervojtek tu bude treba urcit vsetky mozne kategorie. Bud ich rozbijeme na male detaily, alebo len na nejake velke skupiny ako napr:

* info o najblizsich POI (vrati typ, nazov a rozne detaily podla typu); pozor, niektore ways su tiez ako POI - napr budovy, jazera
* info o (najblizsej) ceste (vrati povrch, access, smoothness, ...)
* info o lokalite (podla admin hranic - stvrt, obec, kraj, stat)
* co s ways typu dolina, rieka, ...?

**Comment by petervojtek** [comment]
> tu bude treba urcit vsetky mozne kategorie

podme na to radsej opacne a zacnime len s dopytmi ktore nad mapou naozaj robime. 
mna naozaj zaujima len toto:
* info o (najblizsej) ceste

a toto by bolo fajn, ale v principe to az tak casto nepotrebujem.
* routes (cyklotrasy)

**Comment by MichalPP** [comment]
všetky tieto veci sú v oma api implementované, netreba nič vymýšlať a duplikovať

**Comment by zdila** [comment]
@MichalPP dokumentacia? vyhoda voci overpass?

**Comment by MichalPP** [comment]
dokumentácia: parametre sú lat, lon, vzdialenosť a layer: znamenajú latitude, longitude, vzdialenosť do akej vrátiť, layer je z T,C,A...

výhody: oddeluje od elementov v OSMdb, od OSM dialektov, spríjemňuje prácu

**Comment by petervojtek** [comment]
navrhujem spravit to takto: budeme mat nastroj "Detaily v mape" (pripadne s trefnejsim nazvom), ktory bude mat dve tlacidla:
* jedno bude dropdown tlacidlo, v ktorom budu konkretne pripady pouzitia (napr. "info o ceste") -- az ich budeme mat viac, zoskupime ich do kategorii
* tlacidlo "?" (alebo lepsie nazvane), ktore bude robit nieco podobne ako "?" na osm.org. to aky backend sa pre toto tlacidlo pouzije nech si zvoli ten, kto to bude implementovat :)  [pripadne sa v expertnych nastaveniach bude dat vybrat, ci oma.sk backend, alebo ten backend co pouziva osm.org]

**Comment by Mirecnet** [comment]
Zdravim Vas pani,

je dobre ze sa snazite zaviest nove funkcie pre beznych ludi. Vsimol som si, ze nemate moc radi ked Vam do toho niekto czudzi moc keca :) Tak sa uz dako moc nezapajam :) Ale aby to napokon neskoncilo takto: System Ditecu je nefunkcny paskvil. https://dennikn.sk/blog/prezil-som-elektronicke-colne-konanie-system-za-15-mil-e-je-nefunkcny-paskvil/

Skuste sa v nejakom online dotazniku opytat obycajnych ludi (plebsu:), co by v tretej verzii Freemapu ocakavali a co by bolo najlepsie zakomponovat.
Nie je nic horsie, ako pracovat v Ditecu a odlepit sa od reality potrieb beznych ludi :)

**Comment by petervojtek** [comment]
vdaka za povzbudenie @Mirecnet , suhlasim s tym ze by sme mohli na osm google group dat nejaky dotaznik, kde by ludia napisali ake dopyty nad mapou casto robia (a dnes na to asi pouzivaju nastroj "?" v osm.org a potom si z tagov odvodia vysledok).

**Comment by tjamecny** [comment]
Ako sa spomína v [https://groups.google.com/d/msg/osm_sk/HkT5NmqTG5c/rCz73pvkCQAJ](url), bod 6:

> 
>6.       Rozlíšenie ubytovacích zariadení určených pre VEREJNOSŤ:
>
>a.       Kategória, štandard http://www.epi.sk/zz/2008-277 ak je zariadeniu vôbec pridelená podľa toho aj povinnosti vlastníka, prevádzkovateľa. Žiaľ pracoviská v cestovnom ruchu a ani KST netuší o čom je reč a aké sú dôsledky (pozri ďalej) o tvorcoch vyhlášky, čo v horách asi ani príliš neboli a nezamýšľali sa nad problematikou v širšom pohľade ani nehovorím.  
>
>b.      Sezónnosť, chýba legislatívny predpis o povinnosti na prevádzkovanie a otvorenie takýchto zariadení a o ich povinnom vybavení, lebo prípadov, že došli ku chate podľa mapy a tam zamrzli, pretože bola zavretá, už sme v histórií mali. Skrátka otváracie hodiny, dni, sezónnosť na horských zariadeniach, prístup k zavolania prvej pomoci, prvá pomoc, základné vybavenie – prístrešok, zdroj vody, prostriedky na prežitie (a definovať čo je to horské zariadenie, čo by mala byť legislatívna snaha, o čom a súvislostiach legislatívci nemajú potuchy) nemôžu byť také smiešne ako dole (inventúra, z technických príčin zatvorené, preberám tovar, prídem hneď...) http://horami-sk.blogspot.sk/2012/12/vdaka-vam-chaty-bivaky.html  A sezónnosť by na mape mala byť zvýraznená kvôli osudovosti takejto informácie. Mali by to mať pod palcom majitelia zariadení, (KST, James...) čo majú dominantné postavenie vo svete tunajších hôr, hájacich si teoreticky záujmy turistov a horolezcov.
>

Navrhujem rozšíriť nástroj "Detaily v mape" o možnosť zobrazovania detailov ubytovacích zariadení. Pre začiatok aspoň: názov, kategória (penzión/motel/hotel/...), website, otváracie hodiny.

**Comment by MichalPP** [comment]
ako som hore písal, api na data.oma.sk/api toto všetko ponúka.

**Comment by zdila** [comment]
na tom api mi vadi ze vracia HTML a linky na omu.

**Comment by MichalPP** [comment]
vracia geojson, v nom kopu poloziek. co by mal vracat?

**Comment by zdila** [comment]
vracia, ale v nom je html markup a linky na oma.sk. nepoviem ti teraz co presne by mohol vraciat lebo zatial su prioritnejsie tasky :-)

**Comment by zdila** [comment]
vyriesene v ramci branchu `map-details-ng` - este je to alfaverzia, ale uz je to pouzitelne
