### ISSUE TITLE
problem vo Firefoxe 

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#160]
Je mozne ze problem je sposobeny konfliktom s nejakymi pluginmi v mojej instalacii, ale pri pouzivani mapy vo Firefoxe sa postupne predlzuju reakcne casy pri akciach ako posun mapy, volba poloziek v menu a pod. V Safari ani Chrome tieto problemy nevidim.

**Comment by petervojtek** [comment]
@alexanderzatko , skusal som to na macos na vo FF 52.0.1 , ale nepodarilo sa mi tvoj problem zreprodukovat.
po akom case pouzivania sa to zacne spomalovat?
aby sme zistili, ci za to nemozu tvoje pluginy, mozes skusit otvorit stranku v anonymnom okne? vtedy by pluginy nemali byt aktivne (aspon v chrome to tak funguje).

pozeral som v FF webovu konzolu, ale nezda sa zeby sa tam nejako zacyklovat reactjs stavovy stroj.

**Comment by alexanderzatko** [comment]
vyskusal som co si odporucil, ale problem je rovnaky - asi po 20 posunoch (pan) sa zacne prekreslovanie spomalovat. Tu je vypis z konzoly:

The resource at “https://www.google-analytics.com/analytics.js” was blocked because tracking protection is enabled.[Learn More]  next.freemap.sk
Image corrupt or truncated.  2831.png
Image corrupt or truncated.  2830.png
Image corrupt or truncated.  2828.png
Image corrupt or truncated.  2831.png
Image corrupt or truncated.  2830.png
Image corrupt or truncated.  2831.png
Image corrupt or truncated.  2829.png
Image corrupt or truncated.  2830.png
Image corrupt or truncated.  2828.png
Image corrupt or truncated.  2829.png
Image corrupt or truncated.  2829.png
Image corrupt or truncated.  2831.png
Image corrupt or truncated.  2829.png
Image corrupt or truncated.  2830.png
Image corrupt or truncated.  2828.png
Image corrupt or truncated.  2828.png
Image corrupt or truncated.  2830.png
Image corrupt or truncated.  2828.png
Image corrupt or truncated.  2829.png
Will-change memory consumption is too high. Budget limit is the document surface area multiplied by 3 (1110240 px). Occurrences of will-change over the budget will be ignored.  next.freemap.sk
WrongDocumentError: Node cannot be used in a document other than the one in which it was created  index.js:28
	o http://next.freemap.sk/index.js:28:1265019
	r/< http://next.freemap.sk/index.js:28:1264540
	c http://next.freemap.sk/index.js:28:1268467
	a.rawxhr/i.onreadystatechange http://next.freemap.sk/index.js:28:1269810
	onStopRequest resource://gre/modules/WebRequest.jsm:345:7

**Comment by petervojtek** [comment]
"Will-change memory consumption is too high." aj "Image corrupt or truncated." sa mi podarilo  uz tiez uvidiet v FF konzole, ale portal ani po dlhsom pouzivani nespomaluje.

ta prva hlaska pochadza of leafletu, ale [tvaria](https://github.com/Leaflet/Leaflet/issues/4686) sa ze je to ok.
hlaska s poskodenymi obrazkami sa tiez da najst na stackoverflow v spojeni FF + tahanie obrazkov cez ajax.

je to zatial zahada. ked tak mozes skusit v nastaveniach zmenit format dlazdic z PNG na JPG, ci to to nepomoze, kedze tie druhe su mensie.

**Comment by alexanderzatko** [comment]
urobil som video (~150 mega):
https://drive.google.com/file/d/0B82EooAqcIE4emVzUExudkhveVk

**Comment by zdila** [comment]
Ani mne sa to nepodarilo zreprodukovat: FF 54 - ani na Linuxe, ani na MacOS.

**Comment by zdila** [comment]
@alexanderzatko skus startnut FF s cistym profilom (`firefox -P` a vytvor si profil)

**Comment by alexanderzatko** [comment]
vylucovacou metodou som zistil ze extension ghostery sposobuje tento problem. Odinstaloval som ju a je to ok.
