### ISSUE TITLE
Vyhladavanie - suggestions ok ale vyhladavanie nie ok

### ISSUE THREAD

**Issue by miro-janosik** [FreemapSlovakia/freemap-v3-react#161]
Do vyhladavania na http://next.freemap.sk zadam "Hlinkova" - vylistuje mi ze tato ulica existuje v "Kosice", "Kosice I" a aj inde. pisem "Hlinkova, Kosi" a vidim ze sedy suggestion mi odporuca doplnit "ce I" a tak to doplnim na "Hlinkova, Kosice I". Hlada 5 sekund a vyhlasi "Nenasli sa ziadne vysledky". To iste napise aj ked skusim hladat "Hlinkova, Kosice". 

Zaujimave je, ze ked tento editbox strati fokus, tak doplni diakritiku na "Košice".

**Comment by petervojtek** [comment]
[tu sme nedavno diskutovali](https://github.com/FreemapSlovakia/freemap-v3-react/issues/98#issuecomment-311503225) ze sa vyskusame vratit k nominimativ backendu, tak uvidime ked to prepneme, ako sa to bude spravat.
