### ISSUE TITLE
Hľadať podľa súradníc

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#162]
Pridať voľbu hľadania (zobrazenia) miesta podľa rôzneho formátu súradníc WGS84

**Comment by zdila** [comment]
@petervojtek napr toto by si mohol skusit. Niekedy sa to zide aj mne. Prikladam nejake zdrojaky ktore som davnejsie napisal. PHP je nasadena na starom freemape a java verzia v JOSM (http://josm.openstreetmap.de/ticket/5604) (mozno ju odvtedy este vylapsili, ktovie)


[coord-parsers.zip](https://github.com/FreemapSlovakia/freemap-v3-react/files/1278499/coord-parsers.zip)

Este tuto upravu som navrhol pre PHP kod:
> Inac namiesto replacovania ciarky za bodky, ako si spominal, radsje uprav regex na
> /([+|-]?\d+[.,]\d+)|([+|-]?\d+)|(°|o|deg)|(\'|′|min)|("|″|sec)|(,|;)|([NSEW])|\s+|(.+)/i
>
> a potom namiesto
> $params[] = $match[1];
> dat toto
> $params[] = str_replace(',', '.', $match[1]);
