### ISSUE TITLE
Plánovač - medzibod

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#163]
Pri používaní plánovača by by som skôr privítal keby sa po kliknutí štartu, následne volil bod prechodu namiesto cieľa.  Prípadne mať tlačidlo Štart|Cez|Cieľ a keď sa zvolí Cez bude sa zadávať bod prechodu.

**Comment by petervojtek** [comment]
@seg-on , a keby si stlacit "Cez" a klikol na mapu (a uz tam mas start, tri  medzibody a ciel), kam medzi by sa podla teba mal pridat stvrty medzibod ?

**Comment by seg-on** [comment]
Dal by sa za posledný medzibod.

**Comment by zdila** [comment]
Takze co s tym? Mne osobne vyhovuje sucasne riesenie.

**Comment by petervojtek** [comment]
mne tiez vyhovuje sucasne riesenie. kedysi na zaciatku to bolo spravene tak ako by tuzil segi (za posledny medzibod), ale to sme povazovali za "prvu, nedokonalu verziu" :)

**Comment by seg-on** [comment]
ok. môe ostať ako je. bol to návrh. 
možno využívam ten nástroj iným spôsobom ako ostatný a preto som uvažoval nad zmenou riešenia.
