### ISSUE TITLE
zo serveru zmizli gpx zaznamy?

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#167]
vcera som nahraval na server gps zaznam 
http://next.freemap.sk/?map=12/48.93727/19.59274&layers=C&track-uid=3CY2uHJ3mL7gcsMDcNqM1J

a dnes server pise 404, nenajdeny.
nevies o tom nieco Martin @zdila  ?

ja som totiz uz zacal to zdielanie trasy pouzivat a vkladat na webstranky, tak mi to trochu skomplikovalo zivot..

**Comment by petervojtek** [comment]
aj tento mi zmizol, nahral som ho 13.7. :(
http://next.freemap.sk/?map=8/48.40915/18.98987&layers=C&track-uid=2PXVpMo2xRNUgneDSlmtVs

**Comment by zdila** [comment]
Sorry, checkoutol som server do noveho adresara a data som neprehodil.

**Comment by petervojtek** [comment]
vdaka za rychle vyriesenie problemu.
