### ISSUE TITLE
Planovac - itinerar

### ISSUE THREAD

**Issue by Mashin6** [FreemapSlovakia/freemap-v3-react#169]
Co som si vsimol tak je tam niekolko problemov.

1. Zda sa, ze nepodporuje slovenske znaky a dava namiesto nich "?". (Chrome 59)

2. Vsetko je po anglicky. Mozno by sa dalo nejako lokalizovat, tych fraz tam nie je az tak vela.

3. Ked dam hladat pesiu trasu napr cez Malu Fatru do Martina, tak by som ocakaval navigaciu v style: Odbocte do lava a pokracujte po zelenej znacke. Pri rozcestniku xyz pokracjte po cervenej znacke... 
Alebo nieco ako pokracujeto po polnej ceste/lesnom chodniku.

Momentalne su instrukcie: continue on Grade1, Turn rigth into asphalt, Continue on http://gpsve.szm.sk, Sharp right into r1358466,...

**Comment by petervojtek** [comment]
hej, s itinerarom je problem uz od zaciatku, je to zalezitost backendu, ale uz niekolko mesiacov niet nikoho kto by sa tym zacal zaoberat. ku poznamke c. 1 je aj [issue](https://github.com/FreemapSlovakia/FreemapBackend/issues/10)

[tu](https://github.com/FreemapSlovakia/freemap-v3-react/issues/90#issuecomment-289588641) sme inak viedli svojho casu diskusiu o itinerari, ale nikam sme velmi nedospeli..
