### ISSUE TITLE
[fotogaleria] filtrovanie fotiek

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-v3-react#170]
Filtrovat podla:

- [x] tag
- [x] pouzivatel
- [x] datum (co s fotkami ktore nemaju datum fotenia?)
- [x] hodnotenie
- [ ] (rocne obdobie - problem je ze nie vsetky foto maju datum fotenia)
- [ ] len mnou nehodnotene foto (ak chcem hodnotit fotky)
- [ ] moje foto bez popisu (ak chcem popridavat popisy)

UI - dialog kde sa to vsetko bude nastavovat

**Comment by petervojtek** [comment]
pozeral som kod okolo filtrovania fotiek podla tagu.

backend uz ma podporu na filtrovanie podla jedneho tagu (`GET /gallery/pictures?by=bbox&tag=<tag`), a v principe aj frontend, staci nieco taketo `<GalleryLayer key={uploadSeq} tag="cyklorozcestnik" />`

ale nie je mi zrejme ako si to Martin @zdila myslel, kedze ak som pochopil spravne, teraz to podporuje filtrovanie iba podla jedneho tagu (kym my zrejme chceme mat aj viac zvolenych tagov naraz).

**Comment by zdila** [comment]
Spravim podla viacerych tagov. Fotogaleriu mozes nechat kludne na mna. Samozrejme vitam pripomienky.

**Comment by petervojtek** [comment]
ok

**Comment by zdila** [comment]
@petervojtek  Inac filtrovanie podla viacerych tagov - mas nejaky konkretny usecase? Teda ci pouzit potom AND alebo OR?

**Comment by petervojtek** [comment]
mne osobne by stacilo iba AND (a input field by vyzeral rovnako ako ked sa pridavaju tagy fotografii)

**Comment by zdila** [comment]
ok. a nejaky usecase? napr. hladas fotky s tagom "cyklorazcestnik" a "???"

**Comment by petervojtek** [comment]
mapy ktore su len cyklomapy som zacal tagovat ako `mapa`  a `cyklo`, podobne mapam ktore su len pre bezkarov som dal tagy `mapa` a `bezky`.   ale je to marginalna vec, jeden tag vo filtrovani nateraz podla mnna pokryva 99% pripadov pouzitia.
