### ISSUE TITLE
[fotogaleria] hodnotenie a komentovanie fotiek

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-v3-react#171]
Treba poriesit aj notifikacie o novych komentaroch (vytvorit novu issue).

**Comment by zdila** [comment]
@petervojtek inac ohladom hodnotenia si sa mal moznost vyjadrit tu ;-)

**Comment by petervojtek** [comment]
aha. zial ten [commit v ktorom som zacal diskusiu](https://github.com/FreemapSlovakia/freemap-v3-react/commit/b786568155460013a8757d08110bb4fbc957b9e9#commitcomment-23753964) nereferencoval cislo tejto issue, tak som si to nespojil.

> primarny ciel je hodnotit umelecky dojem. hviezdickovat razcestniky zmysel velmi nema.

aky ma zmysel na portali freemap hodnotit umelecky dojem fotografii? podla mna je nosnou myslienkou portalu informacna (a nie umelecka) hodnota a cielom fotografii je doplnit informacie, ktore nie su zistitelne priamo z mapy.

napr. aj dost nekvalitna fotografia rozcestniku ma z tohto pohladu ovela vyssiu hodnotu nez kompozicne skvela fotka zapadu slnka.

z tohto informacneho hladiska su uzitocne napr. 
* fotografie ciest, z ktorych si cestny cyklista vie zistit v akom stave je asfalt, ci aky hruby je strk
* fotka pristresku, ci posedu, z ktorej turista zisti, ci sa tam da prespat

mierim k tomu, ze podla mna su tie hviezdicky zbytocne. lepsie a jednoduchsie je podla mna dat pri uploade fotiek info spravu, ze nas zaujimaju iba fotky s informacnou hodnotou (a nie selfies a zapady slnka).

**Comment by zdila** [comment]
kludne tu featuru ignoruj ak ju nepouzijes. u mna to ma a malo pridanu hodnotu. su aj ludia ktori si povedzme na mape budu chciet pozriet pekne fotky krajiny. daju filter 4 a viac hviezdiciek a mozu sa kochat. ak chces vidiet razceztniky, do filtra si das tag "razcestnik".

pripadne daj hlasovanie na osm_sk a ak vacsina bude proti tejto feature (minimalne nech sa vyjadri 10 ludi), odstranim.

**Comment by zdila** [comment]
> fotografie ciest, z ktorych si cestny cyklista vie zistit v akom stave je asfalt, ci aky hruby je strk

pozri si momentalnu galeriu - takych foto je tam silne minimum. je jasny trend co pouzivatelia uploaduju. ak ty budes uploadovat fotky ciest, das im vhodny tag a vsetko je ok.

**Comment by petervojtek** [comment]
a tak ked sa ti hviezdicky pacia, nech tam su.

uz som [jeden pokus zistovat nazor verejnosti spravil](https://groups.google.com/forum/#!topic/osm_sk/a01vUyupElk) a nulovu odozvu v danom pripade si vysvetlujem tak, ze verejnost velmi netuzi byt sucastou rozhodovacieho procesu :)

**Comment by zdila** [comment]
> ...nulovu odozvu...

nj. to je smutné.
