### ISSUE TITLE
[fotogaleria] zoznam vsetkych fotiek

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-v3-react#172]
* v dialogu ako je klasicke prezeranie foto po kliknuti do mapy, plus strankovanie
* zohladnit filter
* poradie podla datumu uploadu alebo hodnotenia

**Comment by Mirecnet** [comment]
Ja by som uvital zoznam vsetkych fotiek. Podobne ako to bolo napriklad na Panoramiu. Alebo aspon vypis fotiek. Lebo mam kopec fotiek a neviem, ktora je posledna a co tam vlastne je a co nieje. Nech nedochadza k duplicite fotiek.
Bolo by super, keby som pri niektorych mojich fotkach mohol upravit polohu. Poloha je este z roku 2007-2009, ked sa poloha urcovala manualne na totalne rozmazanych Google mapach.

**Comment by zdila** [comment]
No veď na to je tu tá issue.

**Comment by zdila** [comment]
Poloha sa dá upravovať už aj teraz. A svoje foto uvidíš keď si vyberieš svoje meno vo filtri fotografií.

**Comment by Mirecnet** [comment]
Viem, skusal som to asi pred tyzdnom a volako ten presun fotiek blbol. Nemal som cas pisat report. Ale teraz kukam, ze to uz ide bez problemu. Dik
