### ISSUE TITLE
[fotogaleria] sprava fotiek

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-v3-react#173]
Sprava vlastnych fotiek, resp. sprava vsetkych ak som admin.

* v prehliadaci foto tlacitka:
  * [x] _Zmazať_
  * [ ] _Upraviť_

**Comment by Mirecnet** [comment]
Ak som  prihlaseny na vlastnom konte - mozem vymazavat a upravovat vlastne fotky ?

Ja to tam nikde nevidim. Bolo by fajn mat takuto funkciu.

**Comment by zdila** [comment]
Vlastnu foto mozes zmazat:
![image](https://user-images.githubusercontent.com/636095/29705453-5b6fe91e-897e-11e7-8ddb-0fcfd25784b6.png)

Upravovat samozrejme este nie, kedze tento issue je "open" a v popise tu vidno
![image](https://user-images.githubusercontent.com/636095/29705479-74a211a0-897e-11e7-9be2-bbf1d0238d92.png)

**Comment by Mirecnet** [comment]
Hoj, dik za info.
Ja som hladal upravit a nie zmazat. Mazat som nepotreboval skusat :)
