### ISSUE TITLE
Nedá sa prihlásiť

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#174]
Skúšal som sa prihlásiť ale vracia to chybovú hlášku:
"Nepodarilo sa prihlásiť: Server vrátil neočakávaný status: 500"

**Comment by zdila** [comment]
Asi si nemal nastavenu domovsku poziciu v OSM. Opravil som to (dufam).

**Comment by zdila** [comment]
PS: toto malo ist do https://github.com/FreemapSlovakia/freemap-v3-nodejs-backend/issues :-)

**Comment by seg-on** [comment]
yop funguje to už. díki
idem skúsiť dačo uploadovať
