### ISSUE TITLE
odhlasit pouzivatela az po potvrdeni

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#176]
teraz je lahke nahodou nechtiac kliknut v menu na `Odhlas <meno>` a ono to hned odhlasi.. mohol by sa zobrazit popup s potvdenim.

**Comment by zdila** [comment]
ale zase odhlasenim nic nestratis, ak nie si utocnik, ktory sa nevie znova prihlasit :-)

**Comment by petervojtek** [comment]
ok, tak ponechame sucasny stav... a ak nahodou zacne viac pouzivatelov reportovat ze nechciac casto klikaju na logout, mozeme sa k tejto issue vratit
