### ISSUE TITLE
ako zaviest redux/jeho alternativu..

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#18]
Martin @zdila , zo zvedavosti som vyskusal spravit to, ze poloha startovacieho bodu vyhladavania trasy sa bude propagovat cez redux (s jedinou akciou "SET_START")-- chcel som si vyskusat, ake zlozite je zaviest do projektu redux. tym netvrdim ze mame pouzit redux, tie jeho alternativy vyzeraju mozno aj lepsie, ale chcel som si to skusit.

ak si to nahodou chces pozriet, tu som trochu okresal kod okolo planovaca, planovac dokaze len to, ze vies zvolit startovaci bod:
https://github.com/FreemapSlovakia/freemap-v3-react/tree/try-redux

zvolil som taky pristup, ze kazdy nas "stary" komponent ktory sa nejako dotykal startovacieho bodu planovaca trasy (Main, RoutePlannerResults) som este zabalil do redux-enhanced containera. netusim ci je to dobry pristup, ale mam pocit ze keby sme nahodou chceli ist touto cestou, tak to umoznuje postupnu migraciu stavoveho stroja na redux pricom zvysok kodu funguje po starom.

co mi pride trochu zradne je Immutable Map, ktoru som pouzil na pracu so stavom.

aby som sa dostal k startovaciemu bodu, volal som `state.routePlanner.start` a stale to bolo null, az kym som zistil ze sa to ma volat takto:

```
state.routePlanner.get('start')
```

toto vie byt buducim zdrojom tazko odhalitelnych bugov :)

**Comment by zdila** [comment]
> co mi pride trochu zradne je Immutable Map

ja by som pouzil klasicke JS objekty a funkciu `update`. presne ako to pouzivame na `this.setState(...)`. niekde som cital ze s immutable map su nejake ine problemy

> `state.routePlanner.start` a stale to bolo `null`

no lebo immutable map

> toto vie byt buducim zdrojom tazko odhalitelnych bugov

mozeme zaviest flowtype...

k zvysku:

som za redux. konkuruje mu napr. mobx ale mne pridu vyhody reduxu (no-magic, funkcionalne programovanie) osobne lepsie --- https://medium.com/@adamrackis/a-redux-enthusiast-tries-mobx-af675f468c11

a este bude potrebne zvolit ako napichneme business logiku na redux. moznosti je kopa, od najprimitivnesich ako redux-thunk az po napr. redux-logic. vid. https://medium.com/@jeffbski/where-do-i-put-my-business-logic-in-a-react-redux-application-9253ef91ce1. Ja mam skusenost iba s redux-thunk. je to pouzitelne, ale asi by som vyskusal nieco ine (redux-logic?).

**Comment by zdila** [comment]
a ako pises, prechod zo setState na redux moze byt postupny, ale vela toho nemame, takze by to malo ist rychlo.

**Comment by petervojtek** [comment]
> ja by som pouzil klasicke JS objekty a funkciu update. presne ako to pouzivame na this.setState(...)

ok

> mozeme zaviest flowtype

radsej nie, ked uz chceme typy tak pouzime typescript (ktory inak pouzivam na inych projektoch).. ale najradsej by som to nechal tak ako to je - beztypove.

> redux-logic

pozrel som si to, a vyzera to v pohode. ale neviem to cele posudit. takze necham rozhodnutie radsej na teba (nebudem ti za to neskor nadavat :)
