### ISSUE TITLE
[fotogaleria] otvorenie galerie na zoom leveli 9 zabije prehliadac 

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#180]
lebo leaflet rendruje privela markerov.

**Comment by zdila** [comment]
Na Pc mi to ide v pohode, ale súhlasím že to treba optimalizovať pre veľa bodov.

**Comment by zdila** [comment]
Malo by to byt lepsie. Na PC to ide takmer realtime (max. nejaky 200 ms lag). Na mobile to vsak trva par sekund.

Da sa este s tym algoritmom pohrat. Plus mozno na mobiloch zakazat galerku od zoom 9 a menej.
