### ISSUE TITLE
vyhladavanie - chyba obrazok markeru

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#182]
nevidiet to velmi dobre, ale je to chybajuci obrazok markeru:

<img width="1067" alt="screen shot 2017-08-17 at 8 59 01 pm" src="https://user-images.githubusercontent.com/225506/29428887-1156f92a-838f-11e7-867f-7a32366ed999.png">

**Comment by zdila** [comment]
Vsomil som Vsimol som si to tiez. Nezobrazuje default leaflet markery lebo zle sklada URL. Najskor to je chybou v webpack/url-loader/leaflet/react-leaflet. Treba postupnym vracanim sa k starsim commitom zistit kyory upgrade to sposobil (`git checkout _hash_ && npm i`).

**Comment by zdila** [comment]
nieco z toho: https://github.com/FreemapSlovakia/freemap-v3-react/commits/master/package.json

**Comment by zdila** [comment]
Vyriesil som to tak ze sa pouziva custom marker. Len neviem preco leaflet ma problem s draggable markerom s divicon - napr ked nastavujes poziciu uploadnutej foto tak dragging nefunguje :-( ale napr pri elevation measurement ide
