### ISSUE TITLE
prihlasenie v dev env cez osm.org by malo fungovat?

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#186]
mam rozbehnuty backend a frontend, obe v development env.
ked kliknem v menu na prihlasit sa, zobrazi sa osm popup (Authorize access to your account), kliknem na authorize, a potom sa okno popupu redirectne na urlku `http://local.freemap.sk:8080/authCallback.html?oauth_token=<token>&oauth_verifier=<x>`, ale ta ma nejaky problem, lebo 

```
This site can’t be reached

local.freemap.sk refused to connect.
```

Martin @zdila , request na url `local.freemap.sk:8080` sa ma robit aj ked je aplikacia v development env?

v prehliadaci mam zapnuty no-cors plugin, lebo bez neho sa nedostanem ani k tomu uvodnemu "Authorize access to your account" popupu.

**Comment by zdila** [comment]
Musis si pridat v `/etc/hosts` k `127.0.0.1` este `local.freemap.sk`. Potom ani ziadne no-cors netreba.

TODO dat to do README :-)
