### ISSUE TITLE
[fotogaleria] zmenit dizajn sipiek tak, aby boli vzdy viditelne, ale bolo hned zrejme kedy su disabled

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#189]

**Comment by zdila** [comment]
Inac mne osobne pridu teraz v beznom prehliadaci vpohode rozlisitelne, naviac este ak sa aj meni kurzor mysky a na on mouse over sa sipka (ne)zvyrazni.

Ale pre touch zariadeniach to asi fakt treba zvyraznit.

**Comment by zdila** [comment]
Tiez navrhujem zrusit ten tmavy gradient a zatmavit iba okolie sipky (aby bola viditelna na bielej fotke).

**Comment by petervojtek** [comment]
no, venoval som tomu asi 20 minut, ale je to len zle a horsie a este by to bolo treba odladovat na smartfonovych displejoch. tak som len [revertol](54f944d8) stav sipok do povodneho stavu ako ho nechal Martin a nejdem sa tomu dalej venovat lebo je to vela usilia s malym prinosom.
