### ISSUE TITLE
vylepsit prepinac mapovych vrstiev - nie je jasne aka vrstva je zvolena

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#19]
a na mobile zostane po zmene vrstvy otvoreny prepinac vrstiev.

**Comment by petervojtek** [comment]
Martin @zdila , mame nejaky sposob ako pouzivat nase lokalne obrazky v scss `url` ?
napr. keby som chcel spravit nieco v style:

```
.leaflet-control-layers-toggle {
  background-image: url('ikonka-bicykla.png') !important;
}
```

toto je skor hypoteticka otazka -- ak to nevieme robit, tak to nemusime podporovat, len som bol zvedavy..

**Comment by zdila** [comment]
malo by to fungovat. do `url(...)` daj relativnu cestu k obrazku, ale malo by ist aj `fm3/images/...`. proste ako pri `import`e (`require`).

**Comment by petervojtek** [comment]
Martin @zdila , vdaka za pomoc, tu je zopar postrehov:

ked skusim v css toto:

```
url(fm3/images/icon-walk.png)
```

tak webpack pada s 

```
Module not found: Error: Can't resolve './fm3/images/icon-walk.png' in '/Users/peter/repos/freemap-3-react/src/styles'
 @ ../~/css-loader!../~/sass-loader/lib/loader.js!./styles/main.scss 6:386-423
```

ale toto funguje:

```
url(../images/icon-walk.png)
```

dalsia vec ktora sa mi nepaci je, ze sa sa mi nepodarilo dat viac classNames nad komponent Map. ked skusim toto:

```
<Map className={`tool-${tool || 'none'} active-map-type-${this.props.mapType}`}
```

tak to pada s 
```
class name contains HTML space characters, which are not valid in tokens
```

skusal som aj rozne alternativy ktore som nasiel na stackoveflow, ale nic nefungovalo (ale neskusal som riesenia s pouzitim npm pluginov urcenych na ten ucel, lebo mi prislo absurdne aby som musel pouzit npm plugin na tak trivialnu vec).

napokon som to spravi tak, ze tu moju class name nastavujem o uroven vyssie, [na Row](https://github.com/FreemapSlovakia/freemap-v3-react/commit/b1da0921e44d62923ef82123e382967fdb26775b)

**Comment by zdila** [comment]
> dalsia vec ktora sa mi nepaci je, ze sa sa mi nepodarilo dat viac classNames nad komponent Map. ked skusim toto

tak neviem, ale mne to funguje a bezne to tak robim. a tu error hlasku som v zivote neidel a ani google vela vysledkov nevrati.

Inac ta ikona prepinania mapy ma vyzerat takto?

![image](https://cloud.githubusercontent.com/assets/636095/23718322/4f4485ea-0437-11e7-8474-a39adc8077c1.png)

A `!important` v css zavana zlym dizajnom ;-)

**Comment by petervojtek** [comment]
v akom prehliadaci to mas take velke?
u mna (chrome) ta ikonka je pekne naskalovana v tom obdlzniku.

ten !important som dal prec, ide to aj bez neho 633e47

**Comment by zdila** [comment]
chrome aj FF

**Comment by zdila** [comment]
a vzdy vidim tu istu ikonu ked prepinam typ mapy

**Comment by petervojtek** [comment]
no to je riadna zahada. tento problem:
> a vzdy vidim tu istu ikonu ked prepinam typ mapy

mozes skusit restartnut webpack?

ten problem som chvilami zaznamenal aj ja ked som skusal dat className nad Map (a vtedy sa ani nepropagoval typ mapy do URL). bolo to pre mna velka zahada.

tu velkost ikony by ti malo fixnut toto v main.scss:

```
    background-size: 29px 29px;
```

ale ak mas problem aj s tym ze ikona sa neprepina a restart webpacku to nevyriesi, tak to asi radsej cele revertnem, nestoji mi za to skumat prilis do detailu tento nepredvidatelny framework.

**Comment by zdila** [comment]
> no to je riadna zahada. tento problem

sorry, to bol moj lokalny problem ked som premiestnil tu className na `<Map` - hned som komment zmazal.

ked mam kod 1:1 s origin, takje len ten problem s velkostou ikony. neskor sa na to pozriem.
