### ISSUE TITLE
[fotogaleria] ak nahravanie fotky zlyha, nie je zrejme ze ostatne fotky boli nahrane upesne

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#190]
u mna asi najbeznejs pripad ze nahravam viac fotiek a len jedna nema v exife lat lon poziciu. ostatne to nahra uspesne, ale z UI to nie je zrejme a moze to viest k nahravaniu duplicit. 

mohli by sme v takom pripade zobrazit toast, ze "uspesne bolo nahratych 10 fotiek, ostatne 3 sa nepodarilo nahrat, pozri chybovu spravu pod kazdou fotkou), a v modalnom okne uz zobrazit iba fotky ktore maju `item.error`.

**Comment by zdila** [comment]
afaik uspesne nahrate zmiznu a ostanu iba chybove

**Comment by petervojtek** [comment]
aha, moja chyba.. aby som v #184 mohol zobrazovat upload progress, upravil som kod tak, ze uspesne nahrate `items` sa nemazu, ale nastavuje sa im flag `item.uploaded`. takze upravim upload modal aby nezobrazoval items s `item.uploaded === true` (a potom zostanu viditelne len tie s `item.error`).

**Comment by zdila** [comment]
Tak to uz mozes rovno revertnut ten commit a trackovat ten pocet len extra stavovou premennou. Ale ako som uz cca pisal, galerku by som rad dorobil ja a prijimam navrhy a pripomienky.

**Comment by petervojtek** [comment]
mne sa zda (aj z pohladu do buducnosti) elegantnejsie ked pole `items` zostava a nezmensuje sa. napriklad si viem predstavit ze pre zlepsenie spatnej vazby po uspesnom uploade by sa mohli prave uploadnute fotky nejako viac zvyraznit (docasne odlisit od ostatnych bodiek).

ale necham teda kod galerie na teba a ak to chces robit cez skracovanie pola, tak kludne ten commit revertni.

**Comment by zdila** [comment]
Suhlasim. Cca uploadnute nejako "zosivit" a dat overlay "zelena fajka" alebo take nieco.
