### ISSUE TITLE
nepravidelne a sezonne potoky na Freemape

### ISSUE THREAD

**Issue by Mirecnet** [FreemapSlovakia/freemap-v3-react#195]
Zdravim,
az potoky na mape hornatych oblasti vzdy dodaju mape ten pravy charaker a 3D vzhlad.
Ked sa teraz vsetko prestavuje a modernizuje: neuvazuje sa v novom Freemape, ze by sa renderovali potoky (waterway=stream) podla ich toku ?
Teda:
intermittent=yes - nepravidelne
seasonal=yes - sezonne

Ze by sa zobrazovali obcastne potoky cierkovano, ako na OSM. 
Priklad:
Freemap: http://next.freemap.sk/?map=17/48.98558/19.35068&layers=T
OSM: https://www.openstreetmap.org/#map=18/48.98439/19.34916

Zkuste zvazit. Mapa by ziskala zase trocha viac grafickeho smrncu.
Miro

**Comment by zdila** [comment]
Renderovanim mapy sa zaoberá projekt https://github.com/FreemapSlovakia/FreemapDiSK, kde si už dokonca aj niečo zareportoval. Tento projekt sa týka funkcionality portálu a nerieši chyby zobrazenia mapy, chýb v mape ani chyby zlh routovania a pod. Prosím prehod issue tam.

**Comment by Mirecnet** [comment]
OK, dik za upozornenie. Nebolo to naschval. Nevsimol som si v akej skupine som, ked som zacal pisat. Prehadujem tam...
