### ISSUE TITLE
Tlacidlo "Zdielat odkaz na mapu"

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#2]
pouzije aktualnu URL

**Comment by Mirecnet** [comment]
Mohli by ste do mapy zapracovat tento tool na zielanie odkazu mapy?

http://embedded.freemap.sk/wizard.php

V starej verzii bol ten tool dost zasity a sam som si nevedel spomenut, kde je. Zdielanie map by mala byt dnes priorita. Len vsade nazdielane mapy je najlepsia reklama....

**Comment by petervojtek** [comment]
embednutie mapy riesime v #50

**Comment by zdila** [comment]
tak tak. zatvaram ako duplicitu.

**Comment by Mirecnet** [comment]
Nevsimol som si...dako to az tak podrobne nesledujem. Dik za info.
