### ISSUE TITLE
Miesta: prekrytie názvu ikonou

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#201]
Pri funkcií Miesta je ikonka umiestňovaná nad miesto čím spôsobuje prekrytie názvu miesta.
Bolo by fajn keby mohol názov ostávať čitateľný.

**Comment by zdila** [comment]
Prosim poslat screenshot a obrazok s navrhom riesenia. Nazov je inac v tooltipe ked kliknes na marker.

**Comment by seg-on** [comment]
No s riešením je to ťažko :/
Uvažoval som a nič elegantné ma nenapadlo preto som ani nepísal.
![image](https://user-images.githubusercontent.com/19683952/29750193-bdcd3f80-8b3b-11e7-9034-aa900d4b0168.png)

Hľadám totiž v okolí cesty zaujímavé miesta na ktorých by sa oplatilo zastaviť.
Bol to iba námet ak by niekoho napadlo nejaké vhodné riešenie.

**Comment by zdila** [comment]
ok.
PS: "mi napadlo" a "niekomu napadlo" ;-)

**Comment by petervojtek** [comment]
keby ikonka uz vyzerala ako tooltip obrateny dole hlavou (cize jeho sipka by smerovala nahor), tak by nebolo ani potrebne klikat na ikonku aby sa zobrazil tooltip, a zemepisne nazvy na mapovych tiles by bolo citatelne (lebo tooltip by bol zdola).

**Comment by zdila** [comment]
@petervojtek mozes skusit :-)

**Comment by zdila** [comment]
Nazvy sa na X vrstve uz mozu renderovat aj pod POI; na inych vrstvach to moze byt rozne. Naviac prejdenim kurzora mysky nad pin sa nazov zobrazi.
