### ISSUE TITLE
[Fotogaleria] problem s vypinanim nastroja

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#202]
Kliknutie na tlacidlo “Zavriet” nevypina nastroj Fotografie pretoze jeho zapnutim sa automagicky aktivuje aj vrstva Fotografie. Iba po deaktivacii tej vrstvy miznu markery fotiek a modry kruh okolo kurzora. Asi by bolo dobre nezapinat tu vrstvu pri zapnuti nastroja.

**Comment by zdila** [comment]
Tlacitko "Zavriet" ta vrati naspat na hlave menu. Vrstva fotografii je nezavisla od prepinania nastrojov. A ked zvolis v menu Fotografie tak je podla mna matuce ak sa vrstva fotografii nezapne.

**Comment by zdila** [comment]
Alternativa by mohla byt ze po zvoleni "Fotografie" v menu by sa zobrazila otazka, ci user chce zapnut vrstvu s fotografiami. Alebo opacne, ak da "Zavriet" tak sa ho spytat, ci chce tu vrstvu vypnut (vsetko klasicky v toasteri, neinvazivne).

**Comment by zdila** [comment]
Alebo k tlacitku `Zavriet` pridat tlacitko `Zavriet a vypnut fotky`

**Comment by alexanderzatko** [comment]
Moje ocakavanie bolo, ze po kliknuti tlacidla "Zavriet" zmizne vsetko co sa tyka mojej prace s fotografiami (vcitane vrstvy). Mozno by bolo dobre zistit ci maju aj ini pouzivatelia take ocakavanie a ak ano, tak to jednoducho tak naimplementovat. Ak som sam, tak to treba nechat ako je - uz viem ako tu vrstvu vypnut.

**Comment by zdila** [comment]
Mne osobne predtym dost chybala moznost pozriet si fotky ked som mal zapnute ine nastroje - konkretne "Miesta", pri hladani miesta na opekacku v prirode. Uzitocne to moze byt aj pri naplanovanej trase, kde si viem pozriet ake krasy ma cakaju po ceste.

**Comment by alexanderzatko** [comment]
Tento multi-tool mod povazujem za uzitocny, ale implementovat ho intuitivne bude asi vyzva. Mozno by stacilo pridat jeden prepinac na vstup/vystup do/z modu pretoze predpokladam ze ho budu pouzivat len power users. Defaultne by menu fungovalo ako single tool mod.

**Comment by zdila** [comment]
> implementovat ho intuitivne bude asi vyzva

to ano. casom sa to nejako vykrystalizuje :-). mozno aj ten prepinac na zaciatok moze byt, uvidime.

**Comment by zdila** [comment]
Pridavam citaciu od @jose1711 :

> uzitocne. len to cistenie mapy by imho mohlo zrusit aj vrstvu fotiek. j

**Comment by zdila** [comment]
Zatial to bude fungovat tak, ze zvolenim toolu "Fotografie" sa zobrazi fotovrstva a ta sa bude brat ako vysledok toolu - t. j. vycisti sa az zvolenim "Vycistit mapu". To iste plati pre filter fotiek.

Takto to je identicke ako s ostatnymi toolmi.

Do buducna to mozeme globalne vylepsit (pre vsetky tooly). Navrhy su vitane.
