### ISSUE TITLE
pridat link na garmin files download

### ISSUE THREAD

**Issue by jurajbelobrad** [FreemapSlovakia/freemap-v3-react#205]
Freemap ma vyborne spravene mapy pre zariadenia garmin. Bolo by vhodne spropagovat tuto sluzbu aj na novom portali napr. cez button, alebo niekde v menu.
http://www.freemap.sk/index.php?c=core.download&filename=/garmin

**Comment by zdila** [comment]
To co hladas najdes v menu: Viac / Export mapy. Len freemap wiki ma teraz problem.
