### ISSUE TITLE
[fotogaleria] Pridat hromadne pridanie tagu do vsetkych foto upload dialogu

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-v3-react#206]

**Comment by synalik** [comment]
super, súradnice rozpoznáva, 3 fotky (spolu 4 MB) uploadlo za 35 sekúnd cez Vivaldi. dík

**Comment by zdila** [comment]
Po vlastnorucnim uploade a tagovani cez tisic foto sudim, ze tato feature nie je potrebna :-)

**Comment by synalik** [comment]
Keďže budú všetky rozcestníky, tak by to možno bolo fajn...ale v pohode je aj to, keď funguje pridávanie tagov zadaním začiatočných písmen.
Je mám väčšinu rozcestníkov pomenovaných, neplánuješ spraviť žeby freemap prevzal názov fotky z importovanej?

**Comment by zdila** [comment]
Ja som vcera a dnes uploadol cez 1500 fotiek z razcestnikmi a pridavat ten tag ma nezdrzovalo. Aj tak som musel rozlisit ci je to cylko / peso / bezky.

Nazov fotky sa berie uz aj teraz. Ak ti to nefunguje, priosim pripoj fotku na ktorej by to malo ist a pozriem sa na to.

**Comment by synalik** [comment]
pripájam dve fotky (ani jednej neberie názov). Jedna je z Canon G12 a druhá z mobilu Sony Xpreia 10 mini pro. Zaujímavé je aj to, že z toho Sony sa obrázok importne naležato . aj keď ho v PC vidím postojačky...nevieš poradiť ako to mám spraviť, aby bola importnutá nastojato?
![driekyna_2011](https://user-images.githubusercontent.com/26544966/30562725-cfe5c512-9cbf-11e7-9e78-dfbac31402dd.JPG)
![gabcikovo vodne dielo_2011](https://user-images.githubusercontent.com/26544966/30562727-cfe7e2f2-9cbf-11e7-82f6-dbb969e79380.jpg)

**Comment by zdila** [comment]
Ani iny software mi v tych foto neukazal ziaden popis. Skus napr. na http://metapicz.com/.

A to otacanie druhej foto je sposobene tym, ze v EXIFe je povedane ze fotku netreba otacat, ale v XMP ze treba. To je fotka rovno z fotaku, alebo si ju uz v niecom procesoval?

**Comment by synalik** [comment]
uff, netuším, či som ju otáčal - určite som v Geosetteri priraďoval podľa GPSka súradnice...nevadí, už som ju otočil v Zoneri a je to OK...

noooo, aký popis sa Ti mal ukázať? Ja som ku fotke nepridával žiadny popis, len som ju manuálne premenoval v prieskumníku vo Windowse...ja som myslel, že či freemap necucne názov z názvu súboru (fotky)

**Comment by zdila** [comment]
Popis fotiek je mozne ulozit do metadat fotiek (do XMP, pripadne do EXIF-u). Mnoho softverov to dokaze. Davat nazov fotky do nazvu suboru podla mna nie je najstastnejsie a vidis to aj tu, ze ked stiahnes tie prilozene fotky, tak nazov suboru uz mas uplne iny.

**Comment by synalik** [comment]
Skúsil som názov (popis) doplniť v Zoneri. Keď fotku skúsim uploadnuť do next.freemap.sk nerozozná správne diakritiku. Na http://metapicz.com/ je názov správny.
![amonova luka_2011](https://user-images.githubusercontent.com/26544966/30610062-66d59c6e-9d7d-11e7-8a7b-99a26d36a8ff.JPG)

**Comment by zdila** [comment]
Vdaka, zareportoval som to do kniznice ktoru pouzivame. https://github.com/mattiasw/ExifReader/issues

**Comment by zdila** [comment]
opravene
