### ISSUE TITLE
Link na zdielanie vyhladania

### ISSUE THREAD

**Issue by jurajbelobrad** [FreemapSlovakia/freemap-v3-react#207]
Pridat moznost odoslat link na mapu so zvyraznenou trasou, napr. ako v prilohe.
![obrazok](https://user-images.githubusercontent.com/31770020/30389593-8ff14612-98b3-11e7-8c15-a55805ce83a7.png)

**Comment by zdila** [comment]
Prehliadač trás / Nahrať trasu, Zdieľať nestačí?
http://next.freemap.sk/?track-uid=43I3uK1VbYFoi2t1j7rrPY

**Comment by jurajbelobrad** [comment]
Chcel som niekomu ukazat trasu, a takto ju hned vyznacilo.
Ale, pokial nemam gpx, tak to neukaze.
Je tu este moznost planovac, cize ak toto nie je lahko realizovatelne, tak to pojde aj pomocou neho.

**Comment by zdila** [comment]
A ako si tam dostal tu trasu?

**Comment by jurajbelobrad** [comment]
Na hlavnej stranke som dal vyhladat a klikol na vysledok.

![obrazok](https://user-images.githubusercontent.com/31770020/30390696-4341f25e-98b7-11e7-8712-a244d837dcc6.png)

**Comment by zdila** [comment]
Aha. Takže vlastne chcete zdieľať výsledok hľadania.

**Comment by zdila** [comment]
Také je v pláne, zatiaľ si to môžeš obkreslit a zdieľať ako http://next.freemap.sk/?map=13/48.71396/21.22953&layers=T&distance-measurement-points=48.71713/21.22541,48.71668/21.21786,48.71271/21.21151,48.70614/21.21202,48.70002/21.21082,48.68915/21.20979,48.68915/21.22267,48.69957/21.23417,48.69334/21.24670,48.68677/21.23812

**Comment by jurajbelobrad** [comment]
V tomto konkretnom pripade je to zaujimava moznost - pokial ma trasa nejaky nazov.
Pokial sa jedna o bod, tak to az take nutne nie je.

**Comment by zdila** [comment]
Po vyhladani sa do URL vklada odkaz na vyhladany OSM prvok.
