### ISSUE TITLE
vymyslieť ako sa bude uchovávať stav toolov pri ich prepínani

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-v3-react#21]
Momentálne už máme takmer všetko v reduxe. Tým, že sa stav toolov zachováva a explicitne ho nemažem  pri ich prepínani, tak si môžeme zvoliť, či a ako zobrazovať výsledky z rôzných toolov a ako ich resetovať.

**Comment by petervojtek** [comment]
pre jednoduchost navrhujem zobrazovat vzdy len obsah jedneho (aktivneho nastroja), viacmenej tak ako je to teraz-- ci napada ta pripad pouzitia v ktorom bude velmi uzitocne vidiet naraz obsah dvoch nastrojov?

* planovac --- navrhujem pri prechode na iny tool odstranit jeho start/stop/mid points (pride mi to ako najjednoduchsi sposob ako ho resetnut, lebo inak by sme do UI museli zavadzat tlacidla typu "remove midpoint", co je zbytocne zlozite)
* vyhladavanie -- aktualne nie je explicitne nastavovane ako nastroj, navrhujem aby ked nie je aktivny ziaden iny nastroj tak bude `tool = 'search'` (cize aj by default situacii v reduxe bude tool=search). pri zmene na iny tool -- navrhujem nic z neho neresetovat.
* meranie -- resetnut vsetko pri zmene na iny nastroj (lebo inak by sme podobne ako pri planovaci museli zavazat UI prvky navyse na odstranenie markerov)
* pois -- zatial nedolezite, budeme riesit az ked tam budeme mat bohatsie kategorie.
* vyskomer -- nic neresetovat.

**Comment by zdila** [comment]
> navrhujem aby ked nie je aktivny ziaden iny nastroj tak bude tool = 'search'

momentalne ak nie je aktivny ziaden nastroj, tak `tool === null`
