### ISSUE TITLE
planovac cyklo (MTB)

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#214]
Z diskusie na osm-sk fore:
https://groups.google.com/d/msgid/osm_sk/08e5cfd7-a804-4ec2-bab8-5b77c7eb29f7%40googlegroups.com?utm_medium=email&utm_source=footer
--------------------------------------------------------------
2017-09-21 8:14 GMT+02:00 Palo TT <palinow@atlas.cz>:
Na fore mtbiker sa objavil prispevok o nepouzitelosti planovaca pre MTB.
https://www.mtbiker.sk/forum/post1279997.html#p1279997 
Tiez som toho nazoru a spominal som to tu: https://groups.google.com/forum/#!topic/osm_sk/7SFu7NJ92G4

Ak by niekto planoval nejake upravy s planovacom, dovolim si ako inspiraciu pridat moju predstavu o jeho fungovani:
Po zapnuti MTB planovaca:
1. klik  - prvy bod trasy  - ak je v blizkosti OSM cesta tak planovac prichyti zaciatok na takyto bod (preferovane je prichytenie na bod krizovatky ak je blizko), inak  to bude volny bod mimo OSM  - bez autoroutovania pri dalsom kliknuti).
2. klik  - ak je v blizkosti OSM cesta, planovac spravy autorouting od bodu 1. po najblizsi OSM bod (preferovane krizovatku OSM ciest ak je v blizkosti), inak to bude volny bod mimo OSM (bez autoroutingu)
3. a kazdy dalsi klik - podobne ako v bode 2,  ak klik bude prichyteny na OSM bod tak autoroutovanie by sa nerobilo od zaciatku trasy, ale len od predchadzajuceho vykliknuteho OSM bodu (pri volnych bodoch sa samozrejme autoroutovanie nerobi vobec).

Obdobne by mohlo fungovat aj planovanie pre turistiku, s tym rozdielom, ze preferovane (resp. povolene) by boli len OSM cesty s turistickymi relaciami.

**Comment by zdila** [comment]
Po zmene planovaca je routovanie podla mna dost lepsie. Momentalne UX je podla mna lepsie ako v tomto popise.
