### ISSUE TITLE
spristupnit zoznam tagov pri nacitavani do galerie

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#215]
Pri importe fotiek by bolo uzitocne mat k dispozicii zoznam uz vytvorenych tagov aby sa zabranilo vytvaraniu novych ktore su podobne tym ktore uz mame. Toto by sa dalo urobit tak, ze do import formulara by sa vlozil link "existujuce tagy" (alebo podobne oznaceny) ktory by po kliknuti otvoril pop-up okno, alebo odhalil skrolovatelny zoznam priamo pod polom "Tag".

**Comment by zdila** [comment]
Zatial si zoznam vsetkych tagov mozes pozriet vo filtri. A ak nahodou pridas podobny k nejakemu co uz existuje (napr pridas cyklosmerovnik k cyklorazcestniku) tak ja to obcas budem upratovat :-)

**Comment by alexanderzatko** [comment]
Ok. Mam pri zadavani navrhov na nove features pridavat aj poznamku ze ja viem ako opisany problem riesit pomocou existujucej funkcionality? Aby bolo jasne ze nejde o support request. Mozno len neviem ako pouzivat github (urcite :-) ) ale v inych source control systemoch ktore poznam by som zvolil tag ako "bug" alebo "feature request" a pod.

**Comment by zdila** [comment]
> Mam pri zadavani navrhov na nove features pridavat aj poznamku ze ja viem ako opisany problem riesit pomocou existujucej funkcionality?

Ano, "workaround"y standardne patria do popisu ak o nejakych vies. Druhy clovek nema ako inac vediet ci vies alebo nie :-). Neplati to len na Githube, ale vseobecne.

> v inych source control systemoch ktore poznam by som zvolil tag ako "bug" alebo "feature request" a pod

Tu mas na to Labels: 
![image](https://user-images.githubusercontent.com/636095/30776259-98be7722-a0a3-11e7-9b05-55b73876a0f5.png)

**Comment by zdila** [comment]
A samozrejme to nie je striktne. Nic sa nestane, ked niekto napise nieco viac, pripadne menej, ak to nerobi naschval :-)

**Comment by alexanderzatko** [comment]
a tie labels ako by som mohol pouzit v tomto pripade? Nezda sa ze by som mal moznost ten widget editovat.

**Comment by zdila** [comment]
Vo filtri vidis zoznam vsetkych labels ktore su uz vytvorene. Ak chces vytvorit novy label, tak ho rucne napis ku fotke a sltac enter alebo tab.

**Comment by alexanderzatko** [comment]
myslim, ze si nerozumieme. Ked pisem o "labels" tak reagujem na tvoju [instrukciu](https://github.com/FreemapSlovakia/freemap-v3-react/issues/215#issuecomment-331663708) o tom, ako pouzivat github. Konkretne na sekciu, ktora sa zacina:
> Tu mas na to Labels:

**Comment by zdila** [comment]
Aha. Tak potom na to nemas prava.

**Comment by zdila** [comment]
v dropdowne sa zobrazuje zoznam tagov
