### ISSUE TITLE
tagovanie nefunguje?

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#216]
Pri (hromadnom) nacitavani som vytvoril pre fotky zopar novych tagov tak, ze som vpisal nove vyrazy do pola Tag. Tieto sa vsak nezobrazuju pri prezerani fotiek po nacitani. Ani snaha o tagovanie uz nacitanych fotiek sa mi nedari vytvorit nove - su jednoducho ignorovane.

**Comment by zdila** [comment]
Po napísaní tagu treba stlačiť TAB alebo ENTER.
