### ISSUE TITLE
[fotogaleria] Upravu polohy fotografie nie je mozne potvrdit

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#217]
Po nedavnych zmenach UI sa stratil nastroj na potvrdenie upravy polohy (v minulosti nacitanej) fotografie.

**Comment by zdila** [comment]
Ja to tam vidim (hoci je to skarede)
![image](https://user-images.githubusercontent.com/636095/31058395-1e7e9810-a6f3-11e7-9448-3239dac2f686.png)

**Comment by alexanderzatko** [comment]
ano, dnes to tam vidim. hmmm...
