### ISSUE TITLE
Prekrývajúce vrstvy nevidno pri prepnutí podkladovej mapy

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#218]
Vrstvy na prekrývanie sa pri prepnutí podkladovej mapy dostanú pravdepodobne pod ňu a tým pádom ich nie je vidno. Je potrebné vynúť a zapnúť vrstvu/vrstvy

**Comment by zdila** [comment]
Vdaka za report.

**Comment by seg-on** [comment]
nie zač
inak páči sa mi ako portál vyvíja ;)

**Comment by zdila** [comment]
vdaka :)
