### ISSUE TITLE
Plánovač - Výškový profil -32768m.n.m

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#221]
Nejaká chyba s údajmi reliéfu?
http://next.freemap.sk/?map=14/49.21244/20.07786&layers=CtN&transport=walk&points=49.26332/20.11537,49.20992/20.02267,49.21889/20.02001,49.21922/20.03254,49.22690/20.03348,49.22292/20.04816,49.26366/20.11571

**Comment by zdila** [comment]
Na vypocet sa pouziva esterna sluzba mimo freemapu a ocividne tam ma zle data :-/
