### ISSUE TITLE
pridat moznost dalsieho bodu do mapy

### ISSUE THREAD

**Issue by Mirecnet** [FreemapSlovakia/freemap-v3-react#226]
Kamarat robi rigoroznu pracu a potreboval by do mapy next.freemap naklikat viacero bodov, ktore budu mat popis. Next Freemap umoznuje osadit len jeden bod do mapy.

http://next.freemap.sk/?map=16/49.00766/19.59063&layers=C&info-point=49.00836/19.58568&info-point-label=jasky%C5%88a%20Okno

Bolo by mozne pridat moznost dalsich bodov do mapy ? 

Alebo sa to uz da a neviem, ako na to ? :)
Dakujem za info.

**Comment by zdila** [comment]
Zatial sa to naklikat neda. Ale da sa importnut GPX s viacerimi bodmi ktore potom zobrazi.

**Comment by Mirecnet** [comment]
Dakujem za radu. Velmi si mi pomohol.

**Comment by Mirecnet** [comment]
Vytvoril som GPX, ale nemozem nast moznost ako ich importovat do next.freemap.sk
Ako sa importuje GPX do Freemapu ? Nikde to nevidim....

Inak prihlasenie na portal cez konto na OSM nefunguje. Neviem, ci je problem v OSM. Uz dva dni sa tam poriadne nerenderuju zadane veci...

**Comment by zdila** [comment]
Cez menu - prehliadac tras - nahrat trasu.

Prihlasenie neide lebo tibor to uz tyzden nadadzuje na www. Ked stihnem, tak to vecer rozbeham na nex-te, lebo to www asi tak skoro nebude.

**Comment by zdila** [comment]
a to, ze sa nerenderuje bolo upozornovane v mailing liste.

**Comment by Mirecnet** [comment]
Myslel som rendering OSM. Ale uz vsetko pomaly nabieha. Problem este vidno napr. na Ohnisti: https://www.openstreetmap.org/#map=15/48.9742/19.7061

Vidis...V trasach ma to nenapadlo hladat. GPX som vytvoril naklikanim bodov v JOSM. Ten vsak do GPX suboru vyexportoval vsetko. V com by bolo najlepsie naklikat body, aby sa korektne zobrazili vo Freemape ?
Dakujem za odpoved a pomoc.

**Comment by zdila** [comment]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/osm_sk/IBRhQdKL61k/W0UKbfMMBwAJ

ale pisat o tom tu je silny offtopic

**Comment by zdila** [comment]
> Ten vsak do GPX suboru vyexportoval vsetko.

Ked si naklikal iba body a exportlo vsetko (tie body) tak co je zle?

**Comment by Mirecnet** [comment]
No...offtopic - to len tak mimochodom. Zabudnime na to.

Tie body oznacim a dam subor-export do GPX. Skopiruje celu datovu vrstvu. Asi robim daco zle :)
Potrebujem v JOSM exportovat do GPX len oznacene body.

**Comment by zdila** [comment]
body skopiruj do novej vrstvy a tu exportni

**Comment by Mirecnet** [comment]
jj...fakci to. Ale body sa nedaju popisovat. Volal som s nim (ten co pise tu pracu) a on potrebuje hotove riesenie, ktore si naklika bez zlozitej babracky. Tak som mu poradil http://umap.openstreetmap.fr/cs-cz/
To je specialny nastroj na to urceny. Skoda, ze tam nieje vrstva Freemapu.

**Comment by zdila** [comment]
> Skoda, ze tam nieje vrstva Freemapu.

Je tam to, co si tam das: http://umap.openstreetmap.fr/en/map/nezmapovana-turistika-freemap-slovakia_58872#8/48.798/19.361

**Comment by Mirecnet** [comment]
jj...a v tom pripade, aku adresu treba vlozit do nastavenia pozadia ?
Pisu, ze:
Podporované schéma: http://{s}.domain.com/{z}/{x}/{y}.png

**Comment by zdila** [comment]
http://wiki.freemap.sk/LayerAllInOne
alebo si naklonuj umap mapu a pomaz vsetky vrstvy

**Comment by Mirecnet** [comment]
Nebola by lepsia a priama adresa viditelna v nastaveniach umap-freemap?

**Comment by zdila** [comment]
Preco sa pytas mna? Ja som autor umap-u? A taketo offtopic veci kludne pis radsej na osm_sk alebo na slack.

**Comment by Mirecnet** [comment]
jj..Slack som nemal v mobile. Dik za pomoc
