### ISSUE TITLE
Nefunguje vyhľadávanie

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#229]
Vyhľadávač vracia žiadne nájdené miesta.

**Comment by tjamecny** [comment]
Tabuľka v DB, ktorá obsahuje predspracované dáta pre vyhľadávanie, je prázdna. Pravdepodobne to súvisí v výpočtom pozícií pre POI a labels. Spustil som aktulizáciu danej tabuľky, dám vedieť výsledok, až to dobehne.

**Comment by tjamecny** [comment]
Aktualizácia tabuľky v DB už dobehla, vyhľadávanie som otestoval, funguje.
