### ISSUE TITLE
Kombinacia mapa + overlay mi nezafungovala

### ISSUE THREAD

**Issue by didoa** [FreemapSlovakia/freemap-v3-react#231]
Zapol som si expert mode, zobrazil turisticku mapy, cez nu cyklotrasy 
https://www.freemap.sk/?map=17/49.04847/19.25116&layers=Tc

a cyklo sa nestalo ... je to bug ? alebo robim nieco zle

**Comment by zdila** [comment]
Vdaka za report.

Je to chtba certifikatu. @tjamecny prosim pozries sa na to?

Priklad: https://tiles.freemap.sk/cycle/15/18139/11245.png

**Comment by tjamecny** [comment]
Už generujem certifikát, tiež som sa na to teraz díval.

**Comment by didoa** [comment]
Uz ide ;) super

**Comment by tjamecny** [comment]
Certifikát je rozšírený, akurát sme nemali nakonfigurovanú subdoménu cez HTTPS.
Mne to už funguje v poriadku, zatváram :)
