### ISSUE TITLE
Využiť viac údajov z výstupu OSRM routovača

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-v3-react#233]
+ pridať podporu alternatív

**Comment by MichalPP** [comment]
podpora alternatív, bude treba: 
- inak zobrazovať sumár jednotlivých trás (momentálne je nad koncovým bodom, ktoré budú rovnaké)
- trochu ich odlíšiť (asi hlavná širšie, alternatívy užšie, aby sa nebilo s #260 )
-

**Comment by zdila** [comment]
* spravil som zakladnu implementaciu
* zakomentoval som itinerar kedze v danej podobe nemal vyznam, prerobim do dialogu
