### ISSUE TITLE
navigácia exclude

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#237]
OSRM vie vyhodiť niektoré cesty, napr v car profile daj na koniec &exclude=motorway (vráti trasu, ktorá nevyužíva motorway). týchto exclude tried môže byť 16. 

vo foot profile plánujem "nevhodné pre kočík", "nevhodné v noci", "nemám rád blato", bike profile asi niečo podobné.

dať to možnosť užívateľovi vidieť?

**Comment by zdila** [comment]
Som za. Treba zadefinovat co vsetko chceme povedzme:

* auto (+ volby "mimo spoplatnene" a "minimalna vzdialenost vs minimalny cas")
* bike - horsky (+ volba "prioritizovat znacene cyklotrasy")
* bike - cestny (+ volba "prioritizovat znacene cyklotrasy")
* peso (+ volby "minimalne prevysenie", "prioritizovat znacene trasy")
* bezky (+ volbe "minimalne prevysenie", "prioritizovat znacene trasy")

Ale neviem ci to riesi aj prevysenie.

> "nemám rád blato"
to by muselo aj sledovat pocasie :-)

> "nevhodné pre kočík" a "nevhodné v noci"
to uz je dost specialita, ale moze to byt niekde v advanced volbach

**Comment by MichalPP** [comment]
exclude len vyhodí niektoré cesty z grafu (napr highway=steps pre kočík; lit=no a opening_hours pre noc, ...). to je vec jednoduchá.

meniť prioritizáciu znamená udržiavať dva rôzne profily so všetkými komplikáciami. mimochodom už teraz preferuje značené trasy (s parametrom 1.5-2) a vyhýba sa stúpaniam (podľa vzorca KST).

**Comment by zdila** [comment]
Da sa iba vyhadzovat, nie penalizovat?

Tak potom sa da len toto?

* auto (+ volba "mimo spoplatnene")
* bike - horsky
* bike - cestny (asi iny profil ako horsky?)
* peso
* bezky

Volby pre peso:

* vozicek
* kocik

Osvetlenie by som neriesil ak sa to neda riesit penalizaciou, lebo ak niekde bude neosvetlenych 10 metrov tak je to dost silne na vyhodenie.

Ani opening hours by som neriesil - takych pripadov je asi extremne malo.

**Comment by zdila** [comment]
> obrázok mesiačika

To mam niekde hladat, alebo len navrhujes ako by to malo na www.freemap.sk vyzerat?

A profil `test` je pre pesich? Kym sa to vola `test` tak to asi do produkcie nedame, ze?

**Comment by zdila** [comment]
Vies prosim pridat parameter na routovanie mimo platenych ciest? Parameter `&exclude=motorway` to asi nepokryva, alebo ano?

**Comment by MichalPP** [comment]
`test` beriem ako testovací profil, niekedy to bude foot, niekedy bike, predtým ako pôjde do produkcie

`&exclude=toll` - je to default profil osrm, takže neviem či je úple vhodný pre SR. možno by som motorway rozšíril aj na trunk. https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/lib/way_handlers.lua#L307

obrázky - že zo štandardnej sady ikôn vybrať ďalšiu.

**Comment by zdila** [comment]
Čo je zle na `exclude=toll` pre Slovensko? Požiadavka by mala byť _okrem spoplatnených ciest_ a tento filter by to mal zabezpečiť.

**Comment by MichalPP** [comment]
ok, tak toll : https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/lib/way_handlers.lua#L282

aspoň upravíme osm dáta, tam kde sú zlé

**Comment by MichalPP** [comment]
toll vyzerá že funguje, ostatné exclude keď budú hotové.
