### ISSUE TITLE
navigácia z URL

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#238]
ak užívateľ zadá do url niečo typu `https://www.freemap.sk/?transport=foot&points=,49.14623/17.88162` (napr link z stránky hotela typu "naviguj k nám")

malo by to nazoomovať na miesto, otvoriť menu navigácie, dať jeden marker do mapy, vysvietiť prázdne políčko v menu navigácie (a možno dať tooltip že "klikni skade navigovať")

**Comment by zdila** [comment]
Myslim ze je to postacujuce: https://www.freemap.sk/?map=14/48.842859/19.119558&layers=T&tool=route-planner&points=,48.838622/19.115009&transport=foot
