### ISSUE TITLE
kliknutie na logo (teraz text freemap vlavo hore) nech resetne mapu

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#24]
* navrhujem resetnut iba lat/lon/zoom na default hodnoty -- to je uzitocne ked sa clovek nahodou ocitne niekde uplne mimo SR a vidi len sede dlazdice.
* typ mapy nechat
* nastroj nastavit na search

**Comment by petervojtek** [comment]
Martin @zdila , chcem sa poradit ako/aky spustas dev server ked vyvijas aplikaciu?
ja som doteraz mal spusteny len nejaky staticky web server v `./dist` a mam taky problem, ze ked som [pridal logo](https://github.com/FreemapSlovakia/freemap-v3-react/commit/cba58ff647753022d9fd4b5953f93e4f2e223552#diff-ea337f34aa79e31b41de2123664a0de4R131) cez `require('fm3/images/freemap-logo.png')`, tak mi webpack vygeneruje v  root adresari projektu subor `de25b273f6fb4ae377b1d575ad09ebc2.png` (uz to mi pride zvlastne) a potom mi web server (ktory ma root v `dist`) hlasi:

```
GET http://localhost:8000/de25b273f6fb4ae377b1d575ad09ebc2.png 404 (Not Found)
```

zvlastne je ze starsie obrazky (farebne markery) to nerobia.

**Comment by zdila** [comment]
pouzivam file:/// :-)

ak mas v `dist` subor `de25b273f6fb4ae377b1d575ad09ebc2.png` a ten server ho nenajde, tak asi je vadny :-). a to require funguje spravne.

**Comment by petervojtek** [comment]
praveze ten subor `de25b273f6fb4ae377b1d575ad09ebc2.png` nevyrobi webpack to `/peter/freemap3/dist` ale do `peter/freemap3/`

**Comment by zdila** [comment]
fixol som to
