### ISSUE TITLE
pridanie komentaru spadne na http status-e 500

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#241]
Nastala chyba pri pridávani komentára: Request failed with status code 500

https://www.freemap.sk/?map=8/48.53843/19.78088&layers=C&image=72965

Request URL:https://backend.freemap.sk/gallery/pictures/72965/comments
Request Method:POST
Status Code:500 Internal Server Error

payload: {"comment":"vdaka za postreh, opravene."}

**Comment by zdila** [comment]
Vdaka za report (hoci pasoval by skor do server projektu :-)).
