### ISSUE TITLE
share link na routing debug

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#242]
v menu share dať nový link s textom "navigácia debug" a linkom 
`https://routing.epsilon.sk/debug.php?profil=ski&lon=48.94276&lat=19.59249`
podľa vrstvy: ski, bike, car, foot

**Comment by zdila** [comment]
no ja sa obavam, ci to nebude funkcia pouzivana iba tebou ;-)

**Comment by MichalPP** [comment]
tak aspoň do expert modu, pls :)

**Comment by zdila** [comment]
hotovo. len to patri skor do "supperexpert".
