### ISSUE TITLE
Prekrytie Render. klienti nefunguje

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#243]
Vrstva Render. klienti nič nezobrazuje.
Taktiež by bolo fajn pridať funkciu na vynútenie prerenderovania dlaždice.

**Comment by tjamecny** [comment]
@zdila Martin, možeš prosím zmeniť linku pre `renderedby` z `www.freemap` na `old.freemap`?

**Comment by zdila** [comment]
hotovo, ale kludne take mozes opravovat aj ty ak chces :-)
nenasadil som. ak chces, mozes pre www skompilovat pomocou `npm i && DEPLOYMENT=www ./node_modules/.bin/webpack` (vid `README.md`)

**Comment by zdila** [comment]
nie je

**Comment by seg-on** [comment]
ok :)
