### ISSUE TITLE
Vyhľadávanie

### ISSUE THREAD

**Issue by synalik** [FreemapSlovakia/freemap-v3-react#245]
Pri vyhľadávaní zadám miesto, ktoré chcem vyhľadať. Keď kliknem myšou na vyhľadaný výsledok v tabuľke hľadania sa za menom zobrazí "×". Keď naň kliknem, že zadať nové hľadanie zmizne celé vyhľadávacie dialógové okno nielen text (názov predtým vyhľadaného objektu). Správa sa to rovnako ako keď stlačím tlačidlo "Zavrieť" zobrazeného napravo na paneli. Keďže box na Hľadanie nie je umiestnený priamo na mape, tak sa hľadanie viacerých objektov po sebe mení na veľkú klikačku.

**Comment by zdila** [comment]
ako som uz pisal v zatvorenej issue, niektore veci uz boli fixnute. tato do toho spada.
