### ISSUE TITLE
pridať meta tagy pre zdieľanie stránky

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-v3-react#247]
* http://ogp.me/
* https://msdn.microsoft.com/en-us/library/dn255024(v=vs.85).aspx
* https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

**Comment by MichalPP** [comment]
ideálne podľa lat-lon kde bola mapa načítaná.

**Comment by zdila** [comment]
> ideálne podľa lat-lon kde bola mapa načítaná.

priklad?

**Comment by MichalPP** [comment]
[príklad](http://poi.oma.sk/n309598409) ako `<meta property='place:location:longitude' content='21.27590' />` alebo og:image ktorý bude meniť mapový podklad.

**Comment by zdila** [comment]
dynamicke meta tagy pridane neboli, kedze index.html sa negeneruje dynamicky (zatial)
