### ISSUE TITLE
Otvaranie v externej aplikacii (JOSM)

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#249]
...nefunguje. Asi je to sposobene tym, ze stranka je SSL.

workaround: 

1. z ponuky na freemap stranke nastartuj "externu aplikaciu" openstreetmap
2. prepis URL openstreetmap stranky z https na http
3. refresh
4 v Edit zvol Edit with remote control (JOSM, merkator)

za opravu ponukam 10 CH

**Comment by zdila** [comment]
> za opravu ponukam 10 CH

10 uhlovodikov?

**Comment by alexanderzatko** [comment]
:-) Chronov.

**Comment by zdila** [comment]
Taku chorobu nepoznam.

Vyskusaj teraz, ale musis mat povolene pocuvanie na https v JOSM. Neviem ci to je default. Ale mne to nepocuva ani ked mam povolene :-)

**Comment by zdila** [comment]
Otvor https://localhost:8112/ v prehliadaci a povol bezpecnostnu vynimku. Potom by to uz malo ist (asi az kym nezavries browser).

A este pri spustani JSOM skontroluj ci pise do konzoly:
```
2017-11-10 19:28:28.106 INFO: RemoteControl::Accepting secure remote connections on /127.0.0.1:8112
```

**Comment by zdila** [comment]
Otvaram aby sa implementoval warning kvoli certifikatu s postupom ako to rozchodit.

**Comment by alexanderzatko** [comment]
Musel som v JOSM zapnut https ([screenshot](https://drive.google.com/file/d/18NmKEb3gDW6T3ZBk72fH9ZmVxFcd1kYW/view?usp=sharing)). Uz to funguje.

dakujem.

**Comment by zdila** [comment]
@MichalPP prosim nezatvaraj. Vid https://github.com/FreemapSlovakia/freemap-v3-react/issues/249#issuecomment-343551400.
