### ISSUE TITLE
vlastny klon

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#251]
chcel by som vyrobiť vlastný klon (lyžiarska mapa celosvetovo). znamenalo by to:
- vymeniť TMS vrstvy
- vymeniť routing
- vyhodiť niektoré veci z menu, niektoré pridať (iné about)
- zmeniť jazyk, texty

išlo by to urobiť nejakým konfigurákom do súčasného systému?

**Comment by zdila** [comment]
zamer?

ak to ma byt iny projekt (uz nie freemap.sk) tak potom asi len forknut.

**Comment by MichalPP** [comment]
dve usecase mi napadá
- mať vlastný web na testovanie nového routingu
- urobiť niečo nové celosvetové, alebo využiť doménu freemap.eu

**Comment by zdila** [comment]
> mať vlastný web na testovanie nového routingu

na to ti netreba menit texty :-)

> urobiť niečo nové celosvetové, alebo využiť doménu freemap.eu

@petervojtek na zaciatku "zamietol" robit freemap "celosvetovo". uz presne neviem dovody, ale asi najskor ze na to nemame zdroje (HW).

**Comment by petervojtek** [comment]
moj argument preco by freemap. sk mal byt lokalny portal bol ideologicky. 
OZ Freemap nema ambicie robit aktivity za hranicami SR, a preto by sa ani portal freemap.sk nemal snazit ist za tieto hranice. 
ak by mal niekto ambiciu robit nieco celosvetovo, je podla mna lepsie, keby tym prispel do portalu openstreetmap.org (ci uz pull requestom, alebo forkom).

**Comment by zdila** [comment]
> keby tym prispel do portalu openstreetmap.org

trochu offtopic: z "pocutia" viem, ze pretlacit tam aj trivialne a uzitocne zmeny je dost narocne. su tam fest konzervy.

**Comment by MichalPP** [comment]
ak neriešime tiles a iba málo api, tak imho celosvetový portál je rovnako náročný ako SK. (?)

**Comment by zdila** [comment]
by vyzadoval:

* ovela vacsie kapacity napr. na fotky
* mat vo vyhladavacej a routovacej DB cely svet
* schopnost servovat celosvetove requesty
* pride plno poziadaviek aby sme upravili veci podla narodnych zvyklosti
* zvysenie security a robustnosti kedze uz by sme neboli "bezvyznamny"
* ine...

**Comment by zdila** [comment]
myslim ze "otazka je zodpovedana", zatvaram.

**Comment by MichalPP** [comment]
ďalší usecase je doplnenie mapky ako súčasť inej stránky, napr. na vyhľadávanie trás so špeciálnym routerom. napr pre bikeshare (http://whitebikes.info/)

(a ako discussion asi nemá zmysel rýchlo zatvárať)

**Comment by didoa** [comment]
asi aj tu by developer povedal, ze iny usecase ... ina story :)

**Comment by MichalPP** [comment]
a ďalší usecase je mapa pre vozíčkarov (existuje viacero typov invalidných vozíčkov, teda viacero routingov) a iný tms podklad.

**Comment by zdila** [comment]
zatvaram v ramci upratovania. pre "klonovanie" si moze hocikto projekt forknut.
