### ISSUE TITLE
cookie policy

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#253]
asi uchovávame nejaké dáta v cookies (?). chcelo by to nejak informovať userov resp. pýtať od nich povolenie. nieoč typu "aby sme vám vylepšili používateľskú skúsenosť, ukladáme miesto kde ste naposledy mali otvorenú mapu [ok]"

**Comment by zdila** [comment]
Ziadne cookies nepouzivame. Na lokalne veci sa pouziva localStorage.
