### ISSUE TITLE
routing: iné farby podľa mode

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#260]
v výstupe routing je pri každom steps aj položka mode. rozdiel je zatiaľ iba v profile bike (cycling a pushing bike) a v ski profile (lyže a lanovka). 

dá sa meniť farba výstupu podľa mode? 

ideálne iba jeden konfigurák čo určí  profil, mode -> farba (a keď nie je splnená ani jedna podmienka, zostane v default farbe)

**Comment by MichalPP** [comment]
podobne by sa dala meniť farba podľa rýchlosti (profil auto), napr do 30, do 50, do 90, viac.

**Comment by zdila** [comment]
Potrebujem vediet vsetky hodnoty mode.

**Comment by MichalPP** [comment]
- cycling
- pushing_bike
- ferry (asi iba hypoteticky), to by som zhrnul do 'ine'
