### ISSUE TITLE
navigácia lyže

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#267]
navigáciu pre lyže som prehlásil za stable. je na klasických adresách profil ski (zjazdové, lanovky) a nordic (bežky). pokrytie je celý svet :)

**Comment by zdila** [comment]
casto to vracia HTTP 400

**Comment by MichalPP** [comment]
vieme tam použiť utf8 chars? ako napr ⛷ alebo &#9975; ? (alebo len fa?)

400 vracia keď nevie nájsť cestu. pri lyžiach vcelku bežné, že nie sú poprepájané segmenty. štart pripojí na vlek, cieľ na zjazdovku a vlek a zjazdovka nie sú spojené. (inak: chyba dát).

**Comment by zdila** [comment]
> vieme tam použiť utf8 chars?

vsetko sa da, len to nie je narychlo. ale planujem.

> 400 vracia keď nevie nájsť cestu

ani pri bezkach by to nemuselo vraciat. mohlo by to byt ako pri biku - mod vyzuj bezky :-). ale aj bezne lesne cesty su bezkovatelne ked je sneh.
