### ISSUE TITLE
Dialógové okno pre možnosti podpory

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#269]
Pridať dialógové okno ktoré by obsahovalo všetky druhy podpory či už číslo účtu pre prevod, odkaz na paypal, možnosti nastavenia trvalého príkazu, informácie o 2% plus odkazy na tlačivo, informácie ohľadom darovacej zmluvy, odkaz na stanovy, výročné správy, kontakt,..

**Comment by seg-on** [comment]
Podporte projekt Freemap
Mapový portál Freemap tvoria ľudia vo voľnom čase. Na fungovanie a prevádzku je však potrebný hardware a služby komerčných spoločnosťí.
Za kažý príspevok budeme veľmi vďačný.

Bankové spojenie: VÚB 2746389453/0200
IBAN: SK33 0200 0000 0027 4638 9453

PAYPAL

Občianske združenie

Freemap Slovakia
Matičná 8/A5
900 28 Ivanka pri Dunaji

Registrované na MV/VVS/1-900/90-34343 dňa 2.10.2009

IČO: 42173639
DIČ: 2022912870


E-mail: freemap(zavinac)freemap.sk

**Comment by zdila** [comment]
dakujem sa text (cislo uctu som nekontroloval, ale verim, ze to nie je tvoje ;-))

**Comment by seg-on** [comment]
nz. skopčil som ho z https://oz.freemap.sk/
