### ISSUE TITLE
Pridať Legendu mapy

### ISSUE THREAD

**Issue by jurajbelobrad** [FreemapSlovakia/freemap-v3-react#272]
Bolo by dobre mat legendu mapy - mozno ako plavajucu ikonku nad mapou niekde v rohu, po kliknuti ktorej by sa vysunula lista s legendou.

Navrh ikonky
https://thenounproject.com/term/question-mark/14383/

![legenda](https://user-images.githubusercontent.com/31770020/33185285-d4418010-d081-11e7-8caa-9e036ae0b87d.jpg)
![legenda2](https://user-images.githubusercontent.com/31770020/33185284-d41e0694-d081-11e7-9820-b9dca6b87f75.jpg)

---
Podnet pochadza z tohto mailu
https://groups.google.com/forum/#!topic/osm_sk/HkT5NmqTG5c

5. S úžasom som zistil ako dezorientovaní sú niektorí tiežturisti, keď som si v sedle pod Kôprovým vypočul nejakú mladú kočku, čo sa tvárila za nejakú sprievodkyňu podriadenej tiež mladej skupiny a rozkazovala, že teraz pôjdu zelenou na Štrbské pleso zelenou. To som už spozornel. Lebo tá zelená na mape, bola značením hranice rezervácie. Ak by som ich neupozornil, možno by hľadali neexistujúcu zelenú značku, možno by išli daným smerom, čo je lezecká hrebeňovka a skončil i by možno v čiernej kronike. Oni ale aj tak chceli, už aj v časovej tiesni, ísť dookola, cez Kôprovku, čo som ich pri pohľade na ich umorené postavičky, ich oblečenie, obutie, nulovú bivakovú výstroj a na hodinky, silne odrádzal. Neviem, ako sa vrátili Mengušovskou na Popradské a či došli aj na Štrbské..., lebo s ich kondíciou to nevyzeralo príliš optimisticky. Takže definovať v legende aj hocijaké iné značky a čiary.

**Comment by tjamecny** [comment]
Duplicita s #5 , ponechávam zatiaľ otvorené (t.j. @zdila rozhodne, čo ďalej), keďže sa mi tvoj návrh celkom páči.

**Comment by zdila** [comment]
* ikonu som vybral z _font awesome_ kedze podpora inych zatial nie je implementovana (casom mozno budeme mat vlastny icon font)
* pristup k legende som dal do menu _Viac_. Nedal som to priamo do mapy lebo 95% ludi to nikdy nepouzije zo zvysnych 5% to 90% pouzije raz :-)

**Comment by zdila** [comment]
Pozrite tiez #274
