### ISSUE TITLE
tipy do menu

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#275]
do menu doplniť zoznam tipov (čo sa zobrazujú po načítaní stránky), aby si ich vedel človek pozrieť všetky.

**Comment by zdila** [comment]
Rozumiem tomu spravne ze chces pridat do menu polozku na otvorenie dialogu s tipmi?

**Comment by MichalPP** [comment]
aby v menu (asi to pravé) bola jedna z možností že ukáže zoznam tipov, a aby som si vedel jeden vybrať (nie náhodný tip ako je pri otvorení, ale zoznam). zoznam robiť podľa názvu tipu (prvý riadok). poradie netuším.

a asi aj url, aby som vedel tip poslať mailom/dať na FB.

**Comment by zdila** [comment]
vid. next.

odkazovatelnost cez URL som zatial neimplementoval. mozno v buducnosti.

**Comment by zdila** [comment]
pridal som odkazovatelnost (nie len) tipov do URL
