### ISSUE TITLE
zmena ikonky kočík na wheelchair

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#276]
zmeniť ikonku routovanie pre kočíky/vozíčky z ženy na wheelchair fa-wheelchair

(viem zmeniť, len či je súhlas)

**Comment by zdila** [comment]
Ak je to aj pre voziky, tak suhlasim. Ale potom treba zmenit aj tooltip. A mozno to moze ist aj mimo expertny rezim.

**Comment by MichalPP** [comment]
je to pre ten najľahší typ vozíka (celkovo sú tri hlavné typy vozíkov) alebo pre kočík

**Comment by zdila** [comment]
taky z karbonovych vlakien? ;)
