### ISSUE TITLE
zmeniť tile osm.org na https

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#279]
zmeniť súčasný systém ťahania tile-ov z osm.org z http na https.

(rovnako lesné cesty,...)

inak hlási ssl bugy (ikonka vľavo hore je s výkričníkom)

**Comment by zdila** [comment]
je to fixnute len nie je to nasadene na produkciu

**Comment by pdragun** [comment]
Zdar,
nešlo by to už nasadiť do produkcie? Stále to mám ako warning. (Chromium, Ubuntu)

`Mixed Content: The page at 'https://www.freemap.sk/?map=15/49.147367/20.036119&layers=X' was loaded over HTTPS, but requested an insecure image 'http://tiles-ng.freemap.sk/15/18207/11232@1.100000023841858x'. This content should also be served over HTTPS.`

Ďakujem veľmi pekne.

**Comment by zdila** [comment]
@pdragun tento issue sa tyka Openstreetmap mapy, nie nasej experimentalnej. Ta je stale v experimentalnom mode. Ale skusim to poriesit.

**Comment by pdragun** [comment]
Zdar, aha to som nevedel. Vďaka za upozornenie. Možno by potom stálo za zváženie zmeniť link "Report application problem" pri experimentálnej verzii na niečo iné ako na "https://github.com/FreemapSlovakia/freemap-v3-react/issues/new".

Vďaka.

**Comment by zdila** [comment]
Experimentalna je len ta jedna vrstva, nie cely portal.
