### ISSUE TITLE
map.bounds nie su na zaciatku nastavene

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#28]
kym nepohnem mapou tak sa map.bounds nenastavia. 
do sposobi ze ak pouzijem search suggestions (a este som nepohol rucne mapou), tak sa mapa [nebude refocusovat](https://github.com/FreemapSlovakia/freemap-v3-react/blob/master/src/logic/searchLogic.js#L36) na highlighed search result.

**Comment by zdila** [comment]
Som to cele kus vylepsil - 67a738ad5a6f8f0c00ec574773be614d691ee2ba
