### ISSUE TITLE
klaves ctrl+shift+r zapne vrstvu render klienti

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#281]
po stlaceni ctrl+r (aka F5) to zapne vrstvu Renderovaci klienti. nemuselo by.

**Comment by zdila** [comment]
Divne, mne to robi na Shift+R a tak je to aj nakodene? Neprehodil ti noektory zo synov klavesy na PC? ;-)

**Comment by MichalPP** [comment]
pravdu máš, keď stlacím ctrl+shift+r tak to urobí, (iba ctrl+r nie)
