### ISSUE TITLE
spadnuta mapa

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#282]
[tento request](http://next.freemap.sk/?map=15/48.189165/17.144787&layers=T&transport=foot-stroller&points=48.158800/17.106593,48.185946/17.132406), mne urobí že sa na chvíľu zobrazí mapa a potom zmizne (teda celá stránka zmizne).

asi preto že router vráti 

```
message | "No route found between points"
code | "NoRoute"
````

**Comment by zdila** [comment]
uz fixnute v 292b932d5ebf479f51350e6dcc456316f7dd4c00, coskoro nasadim
