### ISSUE TITLE
Plánovanie trasy - bicykel pešie chodníky

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#283]
Keďže plánovač funguje tak že hľadá cestu pre bicykel aj po peších zónach, bolo by super keby trasa v takýchto častiach bola označená napr inou farbou prípadne piktogramom/značkou pešej zóny.

**Comment by MichalPP** [comment]
teda podľa mode (cycling/pushing bike). #260  alebo aj podľa rýchlosti (dole kopec, hore kopec)

**Comment by zdila** [comment]
Zatvaram kedze je to duplicita s #260 ak som spravne pochopil :-)
