### ISSUE TITLE
Dopravná mapa - zvýraznenie konkrétnej linky

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#285]
Bolo by fajn keby mohla mať dopravná mapa funkcionalitu na zvýraznenie konkrétnej linky.
Napríklad kliknutím na zastávku sa zobrazí okno s linkami ktoré prechádzajú danou zastávkou. vybratím linky sa zvýrazní v mape.

**Comment by zdila** [comment]
toto bolo medzicasom viacmenej pokryte funkciou "detaily v mape"
