### ISSUE TITLE
Zbytocna pesia odbocka k zastavke

### ISSUE THREAD

**Issue by jose1711** [FreemapSlovakia/freemap-v3-react#286]
Navigacia MHD navrhuje zbytocnu pesiu odbocku (tam a nazad) k zastavke Autobusova stanica. Nakolko cesta pokracuje peso az do ciela, je takato odbocka uplne zbytocna.

https://www.freemap.sk/?map=17/48.146865/17.125475&layers=T&transport=imhd&points=48.145787/17.131162,48.146847/17.124724

**Comment by zdila** [comment]
Vdaka za report, ale na routing je projekt https://github.com/FreemapSlovakia/freemap-routing avsak toto je bug na strane imhd.sk.

**Comment by jose1711** [comment]
preco ma ist o data imhd? ten posledny usek je vedeny len po chodnikoch v OSM.

**Comment by zdila** [comment]
imhd vracia zoznam odkial kam sa ma ist a akym prostriedkom. pre viac info pis @MichalPP

**Comment by MichalPP** [comment]
pls screenshot. tá trasa dosť závisí od času kedy si ju robil (a tým pádom sa vlastne nedá replikovať)

**Comment by jose1711** [comment]
![obrazok](https://user-images.githubusercontent.com/1406222/34130277-8220ec88-e447-11e7-9595-10a459574290.png)
zbytocna zachadzka ku autobusovej zastavke, ktoru nasledne nevyuzijem je v cervenom ovale

**Comment by MichalPP** [comment]
známy bug, riešenie je v príprave, ale trvá (a hlavne časť riešenia treba na strane imhd)
