### ISSUE TITLE
informovat pouzivatela cez Toast preco je vyhladavanie POIs neaktivne

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#29]

**Comment by petervojtek** [comment]
Martin @zdila , zaviedol som do projektu UI toasts, ktore by sme mohli pouzivat vo vseobecnosti na zobrazovanie docasnych infromacii pouzivatelovi. ak vsak mas inu predstavu ako zobrazovat takyto typ informacii, mozeme pouzit nieco ine a revertnut tento commit.

**Comment by zdila** [comment]
toast je fajn, len ta animacia ako z nejakeho spiderman komixu. ani farba velmi nesedi do nasej klasickej temy.

**Comment by petervojtek** [comment]
hej, to boli default nastavenia. zmenil som to na trochu konzervativnejsie c013c10
