### ISSUE TITLE
Miesta - chyba pri hladani POI kadernictva

### ISSUE THREAD

**Issue by Mirecnet** [FreemapSlovakia/freemap-v3-react#293]
Bol som na skok v Kosiciach a chcel som najst vsetky kadernictva v meste.

Bohuzial cez Freemap ziadne POI "KADERNICTVA" nenaslo. Bude tam daka chyba.

Prosim pozrite sa na to.

https://www.freemap.sk/?map=14/48.723698/21.260819&layers=C

**Comment by tjamecny** [comment]
Je to spôsobené nadbytočnou medzerou v tagu:
    `node["shop "="hairdresser"]`
Pravdepodobne sa to týka tagu "shop" všeobecne, lebo ani "optician" mi to nenašlo.
