### ISSUE TITLE
fotogaleria - umoznit zoom fotky vo full screen mode

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#294]
ked dam zobrazit fotku na fullscreen, neviem si ju uz nasledne zoomovat* (prva verzia zobrazenia fotiek, kedy sa fotka samotna otvorila v novej tabke to umoznovala).

(*) chrome, mac os.

**Comment by zdila** [comment]
ked fotku otvoris v novom okne (uz je na to tlacitko) tak si ju vues zoomovat pretoce stiahne plnu velkost

vo fullscreen mode stahuje velkost situ na velkost obrazovky aby sa setrily prensene data

staci taketo vysvetlenie, alebo vies ponuknut navrh ineho riesenia?

**Comment by petervojtek** [comment]
vdaka Martin, otvorenie v novom okne je to co som potreboval.
