### ISSUE TITLE
nastroj meranie vzdialenosti - nefunguje zdielanie URL 

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#295]
tuto url som vyrobil v nastroji meranie
https://www.freemap.sk/?map=13/48.196761/17.200813&layers=K&distance-measurement-points=48.217810/17.129145,48.171237/17.230339

 ale ked ju otvorim v novej tabke, spravi to redirekt na:
https://www.freemap.sk/?map=11/48.174557/17.259865&layers=K

**Comment by zdila** [comment]
vdaka za report
