### ISSUE TITLE
implementovat prezerac relacii

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-v3-react#301]
- turisticke
- cyklo
- linky MHD
- ine (mozno aj nie-relacie)

**Comment by MichalPP** [comment]
aka odkaz na oma.sk?

**Comment by zdila** [comment]
Napr. v dropdowne zoznam vsetkych tur. relacii (zgrupenych napr. podla farby) a po zvoleni https://www.freemap.sk/?map=16/48.726154/21.198882&layers=T&osm-relation=937130

**Comment by petervojtek** [comment]
pripadne aj export relacie do gpx :)

**Comment by zdila** [comment]
toto je viacmenej substituovane funkciou detaily v mape
