### ISSUE TITLE
Prehliadač trás (GPX) - nevidno trasu

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#307]
Po vybratí súboru GPX preblikne trasa ale okamžite zmizne a nie je ju vidno v mape.

**Comment by seg-on** [comment]
tak to vyzerá že som trafil nejaké okno, aktualizácie, lebo už to ide :D. Ale skúsil som to asi 4x predtým

**Comment by zdila** [comment]
No mne to neslo vobec :-)
Smutne, ze iba ty si to reportoval, asi si jediny pouzivatel tejto funkcie ;-)

**Comment by seg-on** [comment]
nie zač
keď neviem inak pomôcť tak aspoň reportovaním ;)
