### ISSUE TITLE
planovac: zobrazovat kilometre na medzizastavkach

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#31]
podobne ako to ma nastroj meranie vzdialenosti.
teraz sa zobrazuje iba na cieli.

**Comment by petervojtek** [comment]
asi bolo by lepsie keby tu informaciu poskytoval backend

**Comment by alexanderzatko** [comment]
Merac vzdialenosti je dost problematicke pouzivat, kedze "kvapky" casto krat zakryvaju miesta kam chce clovek kliknut. Zistil som, ze stitky s udajom o vzdialenosti dovoluju kliknut na miesto ktore zakryvaju, ale ani to nie je velka vyhra z hladiska pouzivatela.

Asi by som viac privital, ak by sa vzdialenost ukazovala pri umiestneni kurzora nad uzol naklikanej trasy v okienku, niekde na okraji mapy alebo inom vhodnom mieste.

<img width="490" alt="screen shot 2017-03-20 at 07 47 15" src="https://cloud.githubusercontent.com/assets/3430677/24090810/c805efc2-0d43-11e7-87fa-6d3040981f6b.png">

**Comment by petervojtek** [comment]
Sano, spravil som z toho novu issue, lebo to co reportujes sa tyka nastroja merania vzdialenosti (a nie planovaca): #79

**Comment by MichalPP** [comment]
LRM toto rieši, načo duplikovať?

**Comment by petervojtek** [comment]
aktualne to vyzera takto (tooltipy pri midpoints su viditelne len ked je itinerar vypnuty:

<img width="504" alt="screenshot 2017-04-03 18 53 21" src="https://cloud.githubusercontent.com/assets/225506/24620696/dfb887d6-189e-11e7-9319-d44869e461c3.png">
