### ISSUE TITLE
navigácia - cesty nad sebou v inom poradí

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#310]
keď navigácia vráti možné cesty, zobrazia sa na mape. ak užívateľ klikne na jednu z neaktívnych, vysvieti sa. problém je, že klikateľná je vrstva, ktorá bola vykreslená ako posledná, tedá tá, ktorú navigácia vrátila ako poslednú (teda najhoršiu). v prípade mhd navigácie to po kliku dá cestu, čo ide o hodinu (a nie o 10 min). 

to že viac vyhľadaných ciest ide po tých istých cestách je feature, nie bug. zobrazí to busy čo idú o 5min aj o 15min. asi sa týka najmä MHD navigácie.

riešenie:
- vykreslovať ich v inom poradí (odspodu)
- niekam dať klikateľný zoznam všetkých vyhľadaných ciest (napr namiesto text že sa dá čiara posúvať).

**Comment by zdila** [comment]
Pozri na next.

Naviac som odstranil nahradzanie textov z OSRM, takze namiesto minut (_5 min._) zobrazuje metre (_5m_) a na miesto _električka_ zobrazuje české slangové slovo _šalina_.
