### ISSUE TITLE
slovencina

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#312]
ked si nastavim SK ako jazyk v firefoxe, tak niektore veci nie su v slovencine: 
- horny text je v SK, popupy nad dolnymi ikonami su v SK
- cele horne menu je v AJ

**Comment by zdila** [comment]
Ak vidis nieco po anglicky, tak mas nastavenu anglictinu a tam este nie je vsetko prelozene. Jazyk z prehliadaca sa berie iba pri prvom navstiveni stranky, potom si to nastavujes v menu.

**Comment by zdila** [comment]
A tiez je to duplikat k #309
