### ISSUE TITLE
upraviť popisky iMHD navigácie

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#315]
upraviť aby popisky iMHD navigácie boli krajšie (a multijazyčné).

aké premenné dávať?

- duration, distance
- price (cena lístka)
- arrival (kedy dorazíš)
- duration_walking, duration_waiting, duration_home, duration_bus - koľko bude chôdza, čakanie, čakanie doma (vyraz o 10 min), a dĺžka v buse/električke
- buses (čísla autobusov) - array alebo text oddelený čiarkou?

na step:
- kedy začína step - o koľkej ide bus, 
- type (bus, trolleybus, tram, train, walk, bicycle, ferry) - na ikonku,
- number (číslo busu)
- destination (kam smeruje bus, resp kde vystúpiť)

na niečo som zabudol? či môžem dorobiť backend?

**Comment by zdila** [comment]
V JSONe preferujem camelCase. Ak si na nieco zabudol, dam vediet ked mi to bude chybat :-). A array, nie oddelene ciarkou. Spravis na to dev endpoint?

**Comment by MichalPP** [comment]
durationBus má byť v sekundách alebo minútach? (bude to vždy s presnosťou na minúty).

**Comment by zdila** [comment]
ak budu inde sekundy tak daj aj tu nech je to jednotne

**Comment by MichalPP** [comment]
backend je (asi) hotový.

**Comment by zdila** [comment]
Vdaka. Este namiesto `"durationBus": ...` by bolo krajsie duration: `{ "bus": ..., "walk": ...` :-)

**Comment by MichalPP** [comment]
lenze je standardna premenna `duration=cislo`. extraDuration={}?

**Comment by zdila** [comment]
potom hod vsetko do extra: `"extra": { "duration": { "bus": ..., ... }, "price": ..., ... }`

**Comment by MichalPP** [comment]
ok, hotovo;

**Comment by zdila** [comment]
Este nejake negativne cisla dava: 
![image](https://user-images.githubusercontent.com/636095/34640791-db2fc72a-f2f9-11e7-90ad-73a22ceb353c.png)

**Comment by zdila** [comment]
a namiesto `all` daj `total` :)
`home` znamena kolko cakat doma?

**Comment by zdila** [comment]
> `home` znamena kolko cakat doma?

aha, uz vidim ze ano

a ake este kluce mozu byt v `duration`? bude aj `tram` a `trolleybus`?

**Comment by MichalPP** [comment]
iba tieto, pod bus rozumiem ze akakolvek MHD. home je doma (aka vyraz o 5 min), wait by malo byt cakanie pri prestupoch.

este to mozem zmenit z `duration` na `durations`, a nebude sa to byt a nemusim do davat do `extra`.

**Comment by zdila** [comment]
podla mna je fajn mat vsetko OSRM nestandardne v `extra`

**Comment by MichalPP** [comment]
ok, v `extra`.

**Comment by zdila** [comment]
* `departure` v step by mohol byt absolutny cas (unix timestamp alebo ISO formatovany)`
* `number` som videl ciselne, ale napr. v KE maju spoje casto aj pismenka
* `buses` prosim premenuj na `numbers` ked v stepe je tiez `number`
* v `duration` je aj `foot` aj `walk`. `walk` prosim zrus
* ake su vsetky typy presunov? zatial prekladam: `foot`, `bus`, `tram`, `trolleybus`

**Comment by MichalPP** [comment]
unix timestamp je problém, ono celkovo blbnú popisky ak to ide cez polnoc. je to na dlhšie.

typy sú iba tieto, možno pribudne train, možno bicycle (bikesharing)

ostatné by malo byť vyriešené.

**Comment by zdila** [comment]
A vies umoelo vypocitat unix timestamp? Nech to hackuje server a nie klient. Lebo bez toho nebudem pocitat relativny cas (ide o X minut) ale rovno tam dam absolutny cas (16:32). A planoval som aj postupom plynutia casu ze by sa tie popicky dynamicky aktualizovali a expirovane trasy by vyhadzovalo (vsetko bez kontaktovania servera).

**Comment by MichalPP** [comment]
ok, asi si ma ukecal. ale je to na dlhsie.

**Comment by zdila** [comment]
A co by sa malo nastavovat?

**Comment by MichalPP** [comment]
texty co zobrazuje pri popiske legu alebo routu. asi to iste cim budes nastavovat texty globalne

ze v nastaveniach dam cosi typu `bus %number vyrazi o %departure`

**Comment by MichalPP** [comment]
asi do `extra` doplnim aj `distance` (s rovnakymi pravidlami ak o`duration`). 

mozem z extra vyhodit `duration->total`? duplikuje `duration` z standardneho osrm.

**Comment by zdila** [comment]
mozes

**Comment by MichalPP** [comment]
rozdelím aby v `route->extra->duration` boli rovnaké typy ako v stepoch? napr v step je `type=tram`, `type=bus` a aby aj v `route->extra->duration->tram` bolo to isté číslo. príde mi to prehľadnejšie (a jednoduhšie). 

asi dopním mhd, čo bude súčet tram+bus+trolleybus.

môžem z `step->extra` vyhodiť duration? je v normalnom výstupe.

**Comment by zdila** [comment]
suhlasim, mozes :)

**Comment by zdila** [comment]
V pripade cisto pesej alternativy vracias v `routes[].extra.duration` namiesto `foot` property `walk`. Prosim daj tam `foot`.

**Comment by zdila** [comment]
A v `routes[].legs[].steps[].extra` mi v pripadne cisto pesej alternativy chyba `duration`. Viem ze si ho mozem prebrat zo sumaru, ale pre konzistanciu a jednoduchsi kod by to tam mohlo byt.

**Comment by MichalPP** [comment]
skôr by som z `extra` zrušil duration a nechal iba na `steps` (a zjednotil, teraz ako pozerám sú tam rôzne čísla)

**Comment by zdila** [comment]
ok, skús

**Comment by zdila** [comment]
na next-e si mozes pozriet vysledok (este pred tymi zmenami)
