### ISSUE TITLE
spravit nieco s logom - je necitatelne

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#32]
to logo freemap je navrhnute dost zle - text freemap.sk je zle citatelny a motto pod nim je uplne zbytocne lebo nie je citatelne vobec. tiez mi nie je jasne co ma predstavovat ta farebna machula na pravej strane loga.
mozno je spravny cas vymysliet nove logo freemap :)

**Comment by zdila** [comment]
> mozno je spravny cas vymysliet nove logo freemap

to treba reportovat inde :-)

**Comment by petervojtek** [comment]
ok, napisem o tom prispevok do google groups, ale az potom ako budeme mat to logo nasadene na dist github page, aby si mohli ludia pozriet sucasny stav.. https://github.com/FreemapSlovakia/FreemapBackend/issues/4#issuecomment-284693747

**Comment by petervojtek** [comment]
kdesi som nasiel psd loga freemap a odstranil som z neho necitatelny podnadpis a v 4de742f2 som to pridal takto:

<img width="921" alt="screenshot 2017-03-19 16 31 47" src="https://cloud.githubusercontent.com/assets/225506/24082198/c762d7ce-0cc1-11e7-9348-f948f6cd2ac3.png">
<img width="328" alt="screenshot 2017-03-19 16 31 52" src="https://cloud.githubusercontent.com/assets/225506/24082199/ca1c954a-0cc1-11e7-982a-90db8756f8da.png">

tu je vektorove logo, keby sme to chceli v buducnosti editovat:
https://www.dropbox.com/s/4utygppdn25q27l/2017-03-19-freemap-3-logo.xcf?dl=0
