### ISSUE TITLE
bikesharing navigacia

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#321]
pridať možnosť bikesharing navigácie - najprv choď pešo, tu si požičaj bajk, dobajkuj sem a vráť ho tu a potom choď pešo do cieľa.

backend je rovnaký, len `s/imhd/bikesharing/`

ikonka bicykel s bankovkou?

funguje v BA, Kežmarku (a v Nitre, len tam skryli všetky bajky, asi na jar budú). samozrejme berie do úvahy či tam bajky naozaj sú

**Comment by zdila** [comment]
nazvy po starom az kym nedokoncim #315
