### ISSUE TITLE
Vyhľadávač trás – neznáme znaky/symboly

### ISSUE THREAD

**Issue by karol-bujacek** [FreemapSlovakia/freemap-v3-react#324]
V popise (?) trasy sú neznáme symboly, viď priložený obrázok.

![selection_014](https://user-images.githubusercontent.com/4030734/34832375-128a355e-f6ea-11e7-8039-415ab1e020fc.png)

**Comment by zdila** [comment]
Vdaka za report, #315 to vyriesi.
