### ISSUE TITLE
navigacia: dvojklik zmeni ciel

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#329]
na nexte, novy klik zmeni ciel (co je super).

dvojklik by ale ciel menit nemal.

**Comment by zdila** [comment]
dvojklik implikuje klik
alebo inac, dvojklik nespravis bez toho aby si aspon raz neklikol :-)

**Comment by MichalPP** [comment]
ale ked vies odfiltrovat ze klik+posun nie je klik, tak ti verim ze zvladnes aj dvoklik ze nie je klik :)

**Comment by zdila** [comment]
klik+posun sa robi nad markerom a ten neposiela dalej klik ako polygon. takze neviem.

**Comment by MichalPP** [comment]
myslel som posun mapy ako takej (teda klik+posun hocikde v mape)

neda sa ze handler co riesi doubleclick vrati false a tym dalsie uz klik nevidia?

**Comment by zdila** [comment]
mne klik + posun mapy (t.j. drag mapy) nemeni ciel

**Comment by MichalPP** [comment]
ano, drag mapy nemeni ciel, ale dvojklik (zoom) meni (urobi zoom aj zmeni ciel)

**Comment by zdila** [comment]
tak to je dan za funkcionalitu ktora bola pozadovana. na zoom v tom pripade treba pouzit koliesko mysi, pinch gesture alebo tlacitka +/- v spodnej liste alebo klavesy + a - :-)
