### ISSUE TITLE
Výškový profil je príliš veľký

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#330]
Graf cýškového profilu prekrýva skoro celú mapu.
![image](https://user-images.githubusercontent.com/19683952/34916510-b4406250-f939-11e7-82d8-82044a502922.png)
Vyzerá že to spraví pri prvom zobrazení po vypnutí a znovu zobrazení výškového profilu už je to OK.

**Comment by zdila** [comment]
Vdaka za report, viem o tom :-)
