### ISSUE TITLE
obcasne padajuci www

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#331]
ak idem na https://www.freemap.sk/?map=17/48.139820/17.108057&layers=O , vsetko funguje OK.

ak idem na https://www.freemap.sk//?map=17/48.139835/17.108057&layers=O (dve lomitka za .sk), vsetko pada (napr hociaky zoom)

**Comment by zdila** [comment]
vdaka za report

**Comment by zdila** [comment]
Zareportoval som na https://github.com/ReactTraining/history/issues/560
