### ISSUE TITLE
Tlacitko "reset search field" je zle umiestnene

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#332]
<img width="464" alt="screenshot 2018-01-21 17 32 44" src="https://user-images.githubusercontent.com/225506/35196357-41a67dcc-fed1-11e7-96b5-6360968e6ab5.png">

podobne, aj kym prebieha hladanie je kruhovy search indikator posunuty mimo.

chrome  63.0.3239.132, mac os.

**Comment by zdila** [comment]
vdaka za report
