### ISSUE TITLE
Info oznam na Freemape

### ISSUE THREAD

**Issue by Mirecnet** [FreemapSlovakia/freemap-v3-react#333]
Zmazal som historiu v prehliadaci a narazil som na zaujimavu vec.
Ked sa lognem 1x na stranku Freemap, tak mi ponukne okno o funkciach mapy.
Nebolo by lepsie, keby prve okno obsahovalo informacie o Fremape, preco pouzivat a ako prisievat do Freemapu ?  Az potom prejst na funkcie? Darmo bude nahodny prekliknuty navstevnik citat o funkciach, ked 1x ani mozno nevie o co ide....

**Comment by zdila** [comment]
vdaka za report
