### ISSUE TITLE
Application error! (Chromium, Ubuntu)

### ISSUE THREAD

**Issue by pdragun** [FreemapSlovakia/freemap-v3-react#334]
Zdar, po prvom otvorení stránky freemap.sk (aj next.freemap.sk) dostanem chybovú hlášku:
Application error!
The error has been automatically reported under Ticket ID 72131b37-07ef-4e1b-ba59-4fc916c43e97. You can report the problem at GitHub, or eventually email us the details at freemap@freemap.sk.

Thank you.

Príklad stránky: https://www.freemap.sk/?map=12/49.258283/21.225929&layers=T
Chromium: Version 63.0.3239.84 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)
Ubuntu 16.04.3 LTS
Rozšírenia som vypol (HTTPS everywhere, PrivacyBadger). Chyba sa zobrazuje aj keď som, aj keď nie som prihlásený. Stránka na Firefox Quantum 57.0.4 (64-bit) funguje bez problémov.

Stránka inak funguje ďalej bez problémov a chyba sa už nezobrazuje.

Vďaka

**Comment by zdila** [comment]
Ahoj. Vdaka za report! Bohuzial v logovani chyby bola chyba :-o a je tam malo detailov. Tu som dufam prave opravil, tak prosim skus este raz a napis sem Ticked ID. Dakujem.

**Comment by zdila** [comment]
Resp. uz netreba, vidim to aj u seba - Chromium na Debiane.

**Comment by zdila** [comment]
Je to vyvolane z Google API:

```
details: "Cookies are not enabled in current environment."
error: "idpiframe_initialization_failed"
```

Sposobene je to tym ze Chromium blokuje externym skriptom nastavovat cookies. Porozmyslam co s tym.

**Comment by zdila** [comment]
Tu je jedno skarede riesenie: https://developers.google.com/identity/sign-in/web/troubleshooting#third-party_cookies_and_data_blocked

**Comment by zdila** [comment]
https://github.com/google/google-api-javascript-client/issues/260

**Comment by zdila** [comment]
Je s tym stale problem?

**Comment by pdragun** [comment]
Nie. Ďakujem.
