### ISSUE TITLE
Klávesová skratka pre Lyžiarsku mapu

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#336]
Prečo je klávesová skratka pre Lyžiarsku mapu **k**?
Nebolo by lepšie mať **l** že by to bolo rovnako ako ostatné základné mapy kedy je skratkou prvé písmeno?

**Comment by tjamecny** [comment]
Asi z historických dôvodov, keďže vrstva používa identifikátor "K", tak aj klávesová skratka je rovnaká. Predpokladám, že "L" je použité asi pre "labels". Podotýkam, že tieto skratky sa používajú aj interne v skriptoch na serveri, napr. pri skladaní čiastkových tiles na výsledný tile.

Ak sa zmení skratka na "L", potom môžme očakávať ďalšiu otázku, prečo je v URL reprezentovaná ako "K" :)

**Comment by seg-on** [comment]
Je to možné že by sa niekto ozval na to že prečo v URL je K ale domnievam sa že väčšina užívateľov URL ani nepozerá ľahšie sa pamätá že všetky základné klávesové skratky zodpovedajú prvému písmenu.

Tento argument ma moc nepresvedčil prečo je dobré mať pre lyžiarsku mapu skratku K :D

**Comment by zdila** [comment]
Tak potom sa ozve user co ma Freemap v anglictine, ze by chcel na lyziarsku mapu klavesu `s` ako _ski_ ;-).

(nevravim, ze by sa klavesove skratky nedali lokalizovat, len ci by to obl dobry napad)

**Comment by seg-on** [comment]
ok
