### ISSUE TITLE
Export/Import merania vzdialenosti

### ISSUE THREAD

**Issue by petermisovic** [FreemapSlovakia/freemap-v3-react#338]
Zdravim.
v meraci vzdialenosti som nameral planovanu vzdialenost, ktoru som exportoval do GPX. Pri naslednom importe daneho GPX mi system vygeneroval chybu s ID 6837a591-8d2c-490b-a77c-51f4cd6d2bc2. Trasa zobrazena na freemape je. Dane GPX maju problem spracovat viacere aplikacie, napr. Garmin Connect, mapy.cz, Garmin BaseCamp, uTrack.
![clipboard-1](https://user-images.githubusercontent.com/11147552/36339061-4cfd27b0-13bd-11e8-9595-f6f1a0c56f8b.jpg)

**Comment by zdila** [comment]
Ahoj. Skus sem prosim prilozit to GPX lebo ja to neviem zreprodukovat. Dakujem.

**Comment by petermisovic** [comment]
Ahojte,

tuje to je ...

Peter




s pozdravom
Peter Misovic
http://misovic.net
http://about.me/misovicpeter/

**Comment by zdila** [comment]
Takto to nefunguje. Musis subor prilozit na https://github.com/FreemapSlovakia/freemap-v3-react/issues/338, nie do mailu.

**Comment by petermisovic** [comment]
[export.zip](https://github.com/FreemapSlovakia/freemap-v3-react/files/1755297/export.zip)

**Comment by zdila** [comment]
Momentalne mi to ziadnu chybu nevyhadzuje a GPX zobrazi. Inac po novom sa vyklikane veci exportuju ako "track" a nie ako "route" takze dalsie exporty by mali lepsie fungovat so zariadeniami.
