### ISSUE TITLE
pridať možnosť otvoriť v Moja mapa

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#340]
Bolo by možné pridať do Otvoriť v externej aplikácií portál https://mojamapa.sk/ ?

**Comment by zdila** [comment]
Napis v akom formate otvarat URL s konkretnou poziciou (pripadne aj typm mapy).

**Comment by zdila** [comment]
Je to mozne. Zamer najskor nebol. Kludne im napis ci a ako sa to da :-)

**Comment by seg-on** [comment]
Toto je spôsob ako otvoriť portál na konkrétnom mieste aj s informáciou o parcele v strede https://mojamapa.sk?op=C-17.818413-48.596947
