### ISSUE TITLE
Add Mapillary imagery

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-v3-react#345]

**Comment by miro-janosik** [comment]
Veru, toto by bolo fajn. Zobrazovat to hadam vo foto-vrstve, mozno ako bodky odlisnou (zelenou) farbou, pripadne aj s linkom na mapillary ak by som si chcel pozriet celu trasu.

**Comment by zdila** [comment]
zamietnute z dovodu finkcie "orvorit na mapillary"

**Comment by pkundrat** [comment]
Otvorit v Mappilary nie je celkom ekvivalentna funkcia (rovnako ako vrstva Strava heatmap nie je rovnocenna s klikom Otvorit v Strave). Rovnaka vrstva ako v Brouter pomoze napr. planovat cestu na cestnom bicykli - co preklik do Mapillary neumozni.
Existuje nejake negativum pridania dalsej online vrstvy?

**Comment by zdila** [comment]
> Existuje nejake negativum pridania dalsej online vrstvy?

Napr. udrziavanie kodu ak povedzme mapillary zmeni api, suport riesenia, viac dat (javascriptu) na stahovanie, ...

Tak ci tak, ja to implementovat neplanujem a nemyslim ze sa niekto iny podujme :-)

**Comment by zdila** [comment]
Naviac naco implementovat Mapillary, Stravu a mozno dalsie sluzby do freemapu, ked su na to dedikovane stranky so vsetkymi funkciami co treba.

**Comment by pkundrat** [comment]
To beriem. Ak nebude s tym vela roboty tak mozno aj ja :)
Ved strava heatmap vo freemap.sk uz je :) A je to uplne genialna vec (ste zatial jediny online mapovy/routovaci tool co to ma) - je to uplne neporovnatelne mocnejsie ked je to overlay na mape oproti originalu. Ja to mam aj v telefone ako overlay v Locuse.
Totiz na strave je original global heatmap dost biedny - sice umoznuje filtrovat aktivity a menit farby, ale mapa pod tym je skoro necitatelna. Heatmapa vo vytvaranie tras je kus lepsi, ale zase moznosti mapy pod tym su slabsie.
Je urcite lepsie mat vsetko v jednej mape ako mat otvorenych 10 map naraz.
