### ISSUE TITLE
Po "zatvoreni" modu "meranie" nie je mod v skutocnosti ukonceny

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#348]
Po vyklikani trasy v mode "meranie" a "zatvoreni" (alebo kliknuti na X na smartfone) lista merania zmizne. Ocakaval by som preto, ze naklikana trasa sa nebude dat editovat. Pri testovani na desktope a aj na smartfone som si vask vsimol, ze aj po zatvoreni uzlove body miznu ked na ne kliknem, mozem ich volne presuvat a vytvarat nove uzly presuvanim stredovych "virtualnych" uzlov. Takze editovaci mod nie je ukonceny. Ak by ukonceny bol, potom by napriklad aj na smartfonoch bolo mozne implementovat funkciu na ziskanie pristupu k informacii o danom node, kliknutim nan  (napr. o vzdialenost od pociatku, nadmorskej vyske a podobne).

**Comment by zdila** [comment]
Vzhladom na posledne zmeny v UX sa "mod" (tool) automaticky prepne pri interakcii s priradenym objektom. Tym padom je tato issue bezpredmentna a mozno by sa zisla issue "pridat funkciu uzamknutia mapy".
