### ISSUE TITLE
Chyba v planovani trasy

### ISSUE THREAD

**Issue by recruit-assistant** [FreemapSlovakia/freemap-v3-react#349]
Dobry den, chcel som si na vasom portaly freemap.sk naplanovat cestu z Ľubochne cez Šíp do Kráľévany, zastávka, čo je v podstate trasa po žltom chodníku, no váš vyhľadávač mi tam z nejakého dôvodu pridáva sedlo Osnice (pod Rozsutcom) co je poriadna zachadzka
s pozdravom
Durco

**Comment by tjamecny** [comment]
Ahoj,
vďaka za report. Trasa nie je vyhľadaná po žltej TZT, lebo [most](https://www.openstreetmap.org/way/158495466) pri "Kraľovany, zastávka" má zakázaný vstup. Je to ale tri roky stará informácia, možno je už opäť otvorený, treba preveriť v teréne. Nakoľko v okolí nie je žiadny iný most, plánovač uprednostní omnoho dlhšiu turistickú trasu, namiesto kratšej trasy po ceste prvej triedy.

S pozdravom
Tibor

**Comment by recruit-assistant** [comment]
OK, chystam sa tam cez vikend, poslem info

S pozdravom/Best Regards,

  
Armenia
Bulgaria
Czech Republic
Netherlands
Romania
Russia
Slovakia
Poland
Ukraine

 

 Dusan Durco
 IT Manager
  dusan.durco@lugera.com
  +421 905 387 030

 Lugera & Makler spol. s r.o.
 Jilemnickeho 3
 911 01 Trencin, Slovakia
 Tel: +421 32 6538 124
 Fax:+421 32 6582 873

**Comment by recruit-assistant** [comment]
Nasiel som tom moste toto 
https://myorava.sme.sk/c/7958299/most-do-dierovej-je-opraveny.html, takze 
ho asi mozete uvolnit do pesej turistiky

S pozdravom/Best Regards,

  
Armenia
Bulgaria
Czech Republic
Netherlands
Romania
Russia
Slovakia
Poland
Ukraine

 

 Dusan Durco
 IT Manager
  dusan.durco@lugera.com
  +421 905 387 030

 Lugera & Makler spol. s r.o.
 Jilemnickeho 3
 911 01 Trencin, Slovakia
 Tel: +421 32 6538 124
 Fax:+421 32 6582 873

**Comment by tjamecny** [comment]
Vďaka za link, zrušil som obmedzenia na moste.
Ale neviem odhadnúť, ako rýchlo sa táto zmena prejaví v nástroji "Plánovač trasy".

**Comment by MichalPP** [comment]
na https://routing.epsilon.sk/ je vidno z akého dátumu sú dáta foot profilu. 

o 2-3 dni to bude sprocesované.

**Comment by MichalPP** [comment]
malo by to byť už ukončené. je to OK?

**Comment by tjamecny** [comment]
Zatiaľ žiadna zmena routingu k lepšiemu:
![obrazok](https://user-images.githubusercontent.com/16599347/38675453-15cc5926-3e58-11e8-999c-6dc588506789.png)

**Comment by MichalPP** [comment]
ale aspon bicyklu to pomohlo :) tak za par dni...
