### ISSUE TITLE
api_key na tiles

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#356]
asi by sme do budúcna chceli/mali sprístupniť niektoré služby iba platiacim užívateľom (alebo členom OZ alebo registrovaným).

napr
- layer allinone
- png tiles
- ortofoto (ak bude veľký traffic)

jedna z možností je doplniť api_key za ?

implementácia:
- do nastavení položku api_key (náhodne generovanú)
- v backende to niekam ukladať
- synchronizovať z backendu na tile servery
- na tile serveroch používať
- v js frontende api_key používať

**Comment by zdila** [comment]
To je hudba vzdialenej buducnosti, ak vobec. Zatial zatvaram
