### ISSUE TITLE
Tip na používanie uvádza aj "Pešo (s kočíkom/vozíkom)" ale v aplikácii taká možnosť nie je

### ISSUE THREAD

**Issue by Zaijo** [FreemapSlovakia/freemap-v3-react#358]
<img width="615" alt="screen shot 2018-05-10 at 14 23 13" src="https://user-images.githubusercontent.com/1964908/39869423-c397ce80-545d-11e8-89be-675f59ab1ea6.png">
<img width="749" alt="screen shot 2018-05-10 at 14 23 28" src="https://user-images.githubusercontent.com/1964908/39869424-c3c326f2-545d-11e8-9469-5564af318d06.png">

Je to chyba "Tips" okna, alebo chyba aplikácie?

**Comment by zdila** [comment]
Pre vsetky moznosti je potrebne si zapnut expertny rezim. V tipe by sa mohlo poukazat ktore rezimy su expertne (alebo ich tam neuviest a len pridat poznamku z expertnom rezime je tam toho viac).
