### ISSUE TITLE
zjednodusit planovac -- typ mapy urcuje typ pohybu

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#36]
Miso P. mi dal namet, ze v planovaci vieme odstranit prepinac typov pohybov, a typ pohybu moze byt odvodeny od aktualneho typu mapy. akurat treba novemu pouzivatelovi nejako povedat, ze prepnutim typu mapy ovlyvni routovanie. 
co si o tom myslis Martin @zdila ?

**Comment by zdila** [comment]
Podla mna ho dajme iba predvoleny podla typu mapy.

Inac by bol problem s lyziarskou mapou a tiez ak raz budeme mat este napr. pri aute vyhybanie sa spoplatnenym cestam, alebo pri cyklo ci cestny alebo MTB :-)

**Comment by petervojtek** [comment]
> Inac by bol problem s lyziarskou mapou

nerozumiem. ked odstranime explititny prepinac routovania, aky typ routovania bude pre lyziarsku mapu (to som nejako nedomyslel) ?

**Comment by zdila** [comment]
aj tak by som to asi nechal. kludne niekto moze may turisticku mapu (lebo je krasna) a planovat si cestu autom.

**Comment by petervojtek** [comment]
> kludne niekto moze may turisticku mapu (lebo je krasna) a planovat si cestu autom.

ok (ja to tak inak robim a automapu vobec nepouzivam :)
