### ISSUE TITLE
Rewrite app to TypeScript

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-v3-react#363]
(I just have more joy to code in TypeScript ;-) )

**Comment by petervojtek** [comment]
napisal som par (angular 2+) aplikacii v typescripte, a pre react a zvlast tento projekt mi to nedava velky zmysel, vidim skor nevyhody (a stratu casu). 
mne osetrovanie typov  react cez props pride ako velmi silny nastroj, a ani ho nevyuzivame do tej miery, ako by sa dalo (napr. zoom osetrujeme ako number, pricom by sme mohli byt striktnejsi (napr. one of 7-18).

**Comment by zdila** [comment]
No hadam MS uz nejaky dovod na to mal, aby intenzivne vyvijal TypeScript a preferoval ho pred JS :-)

**Comment by zdila** [comment]
Hotovo. Este precistit obcasne `any` a dospiet k svatemu gralu `"strict": true`.
