### ISSUE TITLE
diskusia: ako zobrazovat dalsi obsah?

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#37]
moj navrh je nasledovny:

do hornej listy uz pridame len jednu vec -  tlacidlo "Viac" (mozno nas napadne lepsi nazov), ktore bude v pravom hornom rohu, a ktore po stlaceni zobrazi dropdown menu. v dropdown menu budu vsetky ostatne polozky, napr.:
* O projekte
* Legenda
* Nastavenia

obsah poloziek zobrazime rovnakou formou ako sucasny POI search, teda cez modalny popup. pristup cez popup ma nevyhodu pri Legende, pri ktorej by bolo uzitocne keby pouzivatel zaroven videl legendu aj mapu, ale mozeme to vyriesit aj tak, ze tam legendu vobec nedame :)

alternativou k zobrazovaniu obsahu cez modalny popup je panel ktory by sa vysunul zboku (na sirokom displeji povedzme do 30% sirky), ale je problem so smartfonmi, lebo tam sa uz teraz vysuva zhora collapsed menu, a keby sa este vysuvala zboku dalsia lista, bolo by to neprehladne. preto sa priklanam k zobrazovaniu obsaho cez modalny popup, lebo to bude fungovat rovnako na velkych aj malyh displejoch.

co sa tyka celkovej koncepcie - podla mna sme sa mali snazit aby sme uz nepresiahli sucasne mnozstvo ovladacich prvkov ktore teraz vidi pouzivatel ked navstivi portal, co napr. znamena ze nebudeme priamo na plochu mapy uz davat dalsie tlacidla/obsah.

aku mas ty viziu, Martin @zdila ?

**Comment by zdila** [comment]
Mozno by sme mohli funkcie "Hladat POI, Meranie vzdialenosti, Planovac trasy a vyskomer" zbalit do menu s nazvom "Funkcie". Uz aj teraz, ak je u mna sirka obrazovky nieco pod 936px, tak skaredo zalomi menu.

Dalsia alternativa je hodit jetnoduche funkcie (zatial Vyskomer a meranie vzdialenosti) priamo ako tlacitka do mapy, ako je to pri http://toposcope.freemap.sk. V hornom menu by ostali iba zlozitejsie funkcie, ktore vyzaduju vstupy alebo menia menu (ako planovac trasu, co je tiez aj zlozitejsia funkcia).

Inac momentalne prerabam sposob volenia kategorii funkcie "Hladat POI". Mal som viacero napadov a tazko (mi) je navrhnut nieco idealne :-). Problem je ze tych kategorii je vela, su kategorie a subkategorie a malo by to byt pekne aj na mobiloch. Zatial pracujem na takom rieseni, ze "Hladat POI" bude ako tool, ktory zmeni horne menu. Tam bude dropdown so vsetkymi kategoriami aj podkategoriami, plus neskor filter (textbox) na rychle vyhladanie. Na to som vsak priamo komponentu nenasiel tak to bude treba dorobit "rucne". Snad coskoro dokoncim prvy nastrel hoci mozem pracovat iba po nociach, po pracovnej sichte a rodinnej sichte, kym dokazem drzat otvorene aspon jedno oko :-)

Ak mas ine napady, kludne pis. Podla mna si v UX designe zdatjejsi ako ja ;-)

**Comment by petervojtek** [comment]
> zbalit do menu s nazvom "Funkcie".

aj to by slo, ale nevyhoda bude, ze ked ten nastroj zapnes, budes ho asi chciet vediet nejako vypnut - a kvoli tomu by si sa musel znovu vracat do menu a stlacit znovu tlacidlo nastroj (dost nepohodlne), alebo by sme museli davat pre kazdy nastroj ked je aktivny na hornu listu tlacidlo "vypni nastroj", co sa mi zda menej elegantne.

> Uz aj teraz, ak je u mna sirka obrazovky nieco pod 936px, tak skaredo zalomi menu.

mali by sme tam mat len tolko veci, aby sa zmestili na sirku 768px (pod 768px to uz bootstrap zbali).

to inak vieme docielit pomerne lahko, napr. takto:

<img width="771" alt="screenshot 2017-03-11 20 48 46" src="https://cloud.githubusercontent.com/assets/225506/23826435/47f4673a-069c-11e7-9926-365361d4ae95.png">
 
az nebude freemap backend robit cors obstrukcie tak chcem portal lepsie vyskusat v tychto konstalaciach:
* bezny displej notebooku na sirku (tak vlastne vyvijam, len ja mam na macbooku dost vysoke rozlisenie, chcem to vyskusat na biednejsich displejoch)
* bezny smartfon na vysku
* tablet na sirku a na vysku

a na zaklade toho budem mat dalsie postrehy. napr. uz teraz vidim ze polozky v rozbalenom menu na mobile maj vela volneho priestoru napravo, mozno by sa dalo tie nastroje uvadzat vo forme ne-blokovych tlacidiel, takze by sa ich zmestilo viac na jeden riadok.

<img width="340" alt="screenshot 2017-03-11 20 51 30" src="https://cloud.githubusercontent.com/assets/225506/23826446/a1d36670-069c-11e7-86df-97671d546b0b.png">


> Dalsia alternativa je hodit jetnoduche funkcie (zatial Vyskomer a meranie vzdialenosti) priamo ako tlacitka do mapy

vedel by som sa s tym zzit, ale pokusil by som sa tomu vyhnut, lebo pokial by sme nenavrhli o dost lepsie ikonky, tak tie sucasne nie samovysvetlujuce a novoprichodzi pouzivatelia nevedia co tlacidlo robi, lebo vidis len iba ikonu. na pc by dal zobrazovat onhover tooltip ktory napise co dane tlacidlo robi, lenze na dotykovych displejoch onhover nie je.

> Zatial pracujem na takom rieseni, ze "Hladat POI" bude ako tool, ktory zmeni horne menu.

mne sa takyto pristup zatial pozdava

ja som tuto temu nacal preto, aby som zatial niekam umiestnil dalsi obsah -- a (hoci len) docasne to dat pod tlacidlo "viac' sa mi zda na uvod fajn lebo je to minimum usilia a neskor to lahko zmenime na nieco ine.

**Comment by tjamecny** [comment]
@petervojtek Ak ešte stále sú nejaké problémy s CORS, kľudne znova otvor [https://github.com/FreemapSlovakia/FreemapBackend/issues/6](url) a dopíš to tam.

Čo sa týka miesta na hornom paneli, osobne by som preferoval presun merania vzdialeností a výškomer do tlačítiek na ľavý okraj mapy pod zmenu zoomu (rovnako ako to má overpass-turbo). A v budúcnosti sa tam môže presťahovať aj POI, keďže si to otvára vlastné popup okno (a teda nevyužíva horné menu tak, ako plánovač trás).

**Comment by petervojtek** [comment]
> CORS

aha, nebol som prihlaseny na zmeny v backend repo a tak som si nevsimol ze uz to bolo na backende fixnute.

> osobne by som preferoval presun merania vzdialeností a výškomer do tlačítiek na ľavý okraj mapy pod zmenu zoomu

**Comment by zdila** [comment]
Do dropdownu by som uz teraz nasekal viacero liniek na freemap wiki clanky, geoblog, facebook...

**Comment by petervojtek** [comment]
> Do dropdownu by som uz teraz nasekal viacero liniek

ked tam toho bude vela, moze sa stat ze po rozbaleni menu sa mapa uplne strati, co neviem ci je dobre -- problem je v tom, ze ked je to menu dlhe, tak sa nim musis zacat skrolovat dole, a odrazu sa ocitnes na mape a menis si polohu mapu/odzoomujes a je to cele matuce.

<img width="412" alt="screen shot 2017-03-15 at 3 16 56 pm" src="https://cloud.githubusercontent.com/assets/225506/23952711/8b1ed150-0992-11e7-9671-c4dc74a1f654.png">

dalo by sa to (na mobile) spravit tak ze ked menu otvoris, bude vyzerat nasledovne:
* Nastroje
   *  Search input 
   *  POI
   * Planovac
   * Meranie
* Viac
   * Nastavenia
   * ...
  
a rozbalena bude vzdy len jedna sekcia.

**Comment by zdila** [comment]
plus na mobile nemusime ukazovat vsetko...

**Comment by zdila** [comment]
@petervojtek este toto je zaujimava komponenta https://github.com/Turbo87/leaflet-sidebar. je na to aj nejaky react wrapper, len neviem v akej kvalite.

**Comment by petervojtek** [comment]
zaujimave, otestujem to na feature-vetve a dam vediet ako sa to sprava.
akurat ked to pouzijeme asi sa nevyhneme vetveniu kodu pre mobily a ne-mobily, napr. ak si predstavime ze Settings budu v tom sidebare a pouzivatel si vybera domovsku polohu, na velkom displeji sidebar asi chceme ponechat rozbaleny, kym na mobile ho musime schovat aby videl mapu.

**Comment by zdila** [comment]
nastavenia mi vyhovuju ako su robene teraz. len mozno pride nejaky iny obsah ktoremu viac vyhovuje sidevar. napr itinerar k planovanej route?

k vybere polohy - ved aj teraz skryvame dialog, rovnako by sme skryvali sidebar. ale ako pisem, na settings je podla mna teraz dialog ok.

**Comment by petervojtek** [comment]
ked uz by sme mali mat aj sidebar, tak by toho uz mohlo by trochu vela a posobilo by to nekonzistentne (najma na mobile -- aj sidebar, aj bootstrap roz/zbalene menu, aj popup).

ale moje prve pokusy s leaflet sidebarom neskoncili slavne :)
https://github.com/Turbo87/leaflet-sidebar/issues/47#issuecomment-289222892

**Comment by zdila** [comment]
ok, sidebar zatial netreba.

**Comment by MichalPP** [comment]
kľudne sa inšpirujte http://freemap.epsilon.sk/#page=navigacia&map=OCM/18/48.15192/17.11865

**Comment by zdila** [comment]
@MichalPP kludne pridaj ruku k dielu, nie len v ramci tohoto issue a nemusi to byt len kodovanie, ale povedzme aj UX design :-)

**Comment by petervojtek** [comment]
zatial nemame obsah ktory by nutne potreboval sidebar. ak sa taky zjavi, vratime sa k tomu
