### ISSUE TITLE
neotvárať zdroje čo nepoužívam

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#370]
ak otvorím freemap, načítava to kopu zdrojov čo netreba (napr strava, facebook, google accounts,...) aj keď to nemám zapnuté.

ide zapnúť načítavanie týchto vecí až po kliku?

**Comment by zdila** [comment]
- stravu nasica iba 1 tile aby zistil ci zobrazit `!` pri strave v zozname map
- facebook a google nacita aby zistil ci si cez to prihlaseny
