### ISSUE TITLE
Nefunkcne vyhladavanie ulic

### ISSUE THREAD

**Issue by jose1711** [FreemapSlovakia/freemap-v3-react#373]
Vstupy do vyhladavacieho pola by mali vsetky spravne najst zadanu ulicu (ako MultiPoint alebo aspon priblizny stred) a to aj bez cakania na nasepkavaca (autocomplete).
* Mojmírova, Košice
* Mojmírova Košice
* Košice, Mojmírova
* Mojmirova, Kosice
Okrem tohto je nasepkavac casto uplne nepouzitelny - napr. pokus o najdenie ulice Nova v Novom Meste nad Vahom sa nepodari.

**Comment by zdila** [comment]
Toto treba reportovat pre vyhladavaci backend, s frontendom to nema velmi nic :-)

**Comment by jose1711** [comment]
dik, nahlasil som to teda pod backendom
