### ISSUE TITLE
Výškový profil - odlišný graf pri prejazde v rôznych smeroch

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#378]
Ak dám trasu cez kopce a potom tou istou naspäť tak profil je mierne odlišný. Keďže sa jedná o tú istú trasu mal by byť zrkadlení.
![image](https://user-images.githubusercontent.com/19683952/43468812-24c4673c-94e5-11e8-8707-1db0c45706f6.png)

https://www.freemap.sk/?map=14/48.633533/17.954321&layers=C&tool=route-planner&points=48.648718/17.881730,48.634972/17.997054,48.648675/17.881665&transport=car-free

Niekedy sa to prejaví dramatickejšie niekedy menej.

**Comment by zdila** [comment]
Opravené, prejaví sa až po nasadení.

![image](https://user-images.githubusercontent.com/636095/45118736-9d0ed200-b159-11e8-9178-413b54c297bf.png)
