### ISSUE TITLE
Navigacia: "vehicle=no" brani vytvorenie cyklo-route

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#379]
Neviem ci je to tym tagom, ale na nizsie-citovanej mape sa neda nastavit cyklo-route medzi vyznacenymi bodmi.

https://www.freemap.sk/?map=16/48.264534/19.113765&layers=K&tool=route-planner&points=48.266098/19.108915,48.261898/19.115589&transport=bike

**Comment by tjamecny** [comment]
Ak je na tej ceste umiestnena zakazova znacka B1 (zakaz vjazdu vsetkych vozidiel), tak navigacia ju ignoruje spravne. Ak je tam znacka B3 (zakaz vjazdu vsetkych motorovych vozidiel), treba upravit tagovanie na motor_vehicle=no a navigacia by mohla fungovat.

V realite sa ale dost casto stretavam s tym, ze na ceste, kade vedie znacena cyklotrasa SCK, je umiestnena prave znacka B1. Potom by sme naozaj potrebovali do navigacie moznost "kaslem na zakony" :)

**Comment by alexanderzatko** [comment]
No to je problem, pretoze vacsinou vidim na cestach na miestach kde vchadzaju do lesa prave tie B1-tky, aj ked by tam mali byt B3. Vsimol som si aj, ze vlastnici pozemkov si casto ozadzaju taketo znacky sami, cize tie budu asi nezakonne. Ktovie ci ma ministerstvo vnutra nejaku mapu  s ich oficialnymi znackami. Skusim zistit.

**Comment by zdila** [comment]
https://github.com/FreemapSlovakia/freemap-routing/issues/7
