### ISSUE TITLE
Globalizácia

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-v3-react#38]
Čo tak sa nesústrediť len na Slovensko ale spraviť portál globálny?

Stačilo by pridať lokalizáciu a využívať globálne služby (ako overpass, graphopper, nominatim a pod.). Služby by mohli byť konfigurovateľné, napr formou pluginov (napr.graphopper vs freemap api na routovanie)...

@petervojtek ?

**Comment by petervojtek** [comment]
mne osobne sa viac paci robit lokalny portal, nez mat globalne ambicie -- v principe si portal freemap v3 predstavujem ako obalku ktora ludom spristupnuje produkt "dlazdice ktore rendruje tibor".  a bolo by zaujimave keby sme takto neskor dokazali pridat aj vektorovy styl mapy ktory udrziava kayle (ku ktoremu ma dnes pristup len malo ludi, lebo importnut to do locusu a podobne je skor pre hackerov).

keby sme mali globalne ambicie tak to znamena ze chceme robit alternativu ku portalu openstreetmap.org (ktory je z UX hladiska na tom podla mna dost biedne, cize zmysel by to malo :) -- ale tu by sa mi zdalo lepsiu cestou skor robit code contributions do codebase openstreetmap.org a ponukat im vylepsenia cez pull requesty, nez mat svoj portal.
