### ISSUE TITLE
Zamačknuté tlačítka

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#384]
Tlačítka sa "neodtláčajú". Niekedy pomôže stalčenie iného tlačítka, niekedy ostane tlačítko zamačknuté aj naďalej a pomôže kliknutie do mapy.

**Comment by zdila** [comment]
Screenshot by nebol?

**Comment by seg-on** [comment]
už sa mi to nepodarilo zopakovať takže to bola nejaká chybička v prehliadači :)
