### ISSUE TITLE
search: ked dost rychlo kliknem na highlighnuty search result: Warning: setState(...): Can only update a mounted or mounting component.

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#39]
```
warning.js:36 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the ReactClass component.
```

postup:
1. treba ist kurzorom na nejaky search result
2. a ihned nan kliknut

**Comment by petervojtek** [comment]
je zvlastne, ze ked zavolam [dispatch(selectResult(result));](https://github.com/FreemapSlovakia/freemap-v3-react/blob/master/src/components/Search.js#L99), tak sa komponent Search znovu mountne (intuitivne by som cakal ze sa nebude kvoli tomu re-mountovat).

toto sa nas zrejme tyka:
https://facebook.github.io/react/blog/2015/12/16/ismounted-antipattern.html

**Comment by petervojtek** [comment]
Martin @zdila , zda sa mi ze ten problem sposobila [tato zmena](https://github.com/FreemapSlovakia/freemap-v3-react/commit/831a60c778880d8eb3158cc49583ac21c538acd0) v organizacii headeru v main, ktora sposobuje ze Search komponent sa remountuje po kazdej zmene tool-u.

a [to zretazenie ternarnych operatorov](https://github.com/FreemapSlovakia/freemap-v3-react/blob/master/src/components/Main.js#L145) je podla mna dost nestastny napad.. je to zle zrozumitelne :(

**Comment by zdila** [comment]
Pravda, react nevie, ze to je iny komponent, tak ho vytvori znova (https://github.com/facebook/react/issues/3965). Opravil som to.

Inac zapis:
```
cond1 ? result1
  : cond2 ? result2
  : cond3 ? result3
  : result4;
```

je podla mna citatelny. Ale tu je jeho prepis ak ti toto pride citatelnejsie:

```
() => {
  switch (tool) {
    case 'a':
      return <A/>;
    case 'b':
      return <B/>;
    default:
      return <C/>;
  }
}()
```

**Comment by petervojtek** [comment]
vdaka za fix.

switch je podla mna rovnako zly ako zretazeny ternarny operator (switch radsej vobec nepouzivam) -- podla mna je najlepsi obycajny if (bez zbytocnych krutenych zatvoriek :)

inak udivuje ma, ze tento problem frameworky uz davno vyriesili, len react [znovyvymysla hranate koleso](https://en.wikipedia.org/wiki/Reinventing_the_wheel) :), napr. v angulare by to bolo uplne jednoduche a prehladne:

```
<Search *ngIf="tool == 'search'" />
```

**Comment by zdila** [comment]
Zase davas zle porovnanie.

Aj v angulari by to muselo byt: `<Search *ngIf="tool !== 'objects' && tool !== 'route-planner'" />`

V reacte je to teraz: `{tool !== 'objects' && tool !== 'route-planner' && <Search/>}`

**Comment by zdila** [comment]
> switch je podla mna rovnako zly ako zretazeny ternarny operator

dost subjektivny nazor :-)

Vyhoda switchu je ze porovnavas jenu hodnotu s ostatnymi. Naproti tomu v if/else-if/else moze byt kazda podmienka ina, takze je to zlozitejsia konstrukcia.

**Comment by petervojtek** [comment]
mas pravdu, ale ani jedno z toho nie je switch case. obe su implicitne if-y.

switch je problematicky preto, lebo mu rozumie menej programatorov, a ked pouzivas viac programacich jazykov, niekdy nevies ci tam nechyba nejaky break a aka je presne syntax. if je silny najma vtedy, ked si nehadzes polena pod nohy lint pravidlom ze aj pri jednoriadkovo obsahu if-u musia byt krutene zatvorky :)

**Comment by zdila** [comment]
> switch je problematicky preto, lebo mu rozumie menej programatorov

Toto ma nepresvedci aby som to prestal pouzivat. Ak robi programator v javascripte, musi povinne rozumiet vsetkym jeho konstruktom. A switch/case je v C, PHP, Java, C# a rozne obdoby v inych jazykoch.

**Comment by petervojtek** [comment]
no, z mojej skusenosti je najlepsie pisat co najjednoduchsi kod (najpr. pouzivat iba if a nie switch a ternarny operator),lebo potom dokaze po tebe prevziat kod iny clovek rychlejsie, a takisto tym znizis latku pre novych prispievatelov, co je pri opensource projekte podla mna vyhoda. napriklad tym ze sme zvolili react a redux sme podla mna odpisali vsetkych ktori co i len teoreticky mohli prispiet do codebase freemap v3-- lebo vacsina z potencialnych kandidatov nanajvys rozumie html a jquery, ale react sa kvoli freemap 3 ucit nebudu.

**Comment by zdila** [comment]
Tak to sme malo ostat pri plain JS (ECMA Script 5), jquery a PHP na serveri. Tomu rozumie najviac ludi. Ziaden babel ani nic :-). Co vychadza ze sme mali dalej lepit sucastny freemap portal ;-).

Ale moj nazor je, ze programatora, ktory sa nezvladne (nema ochotu) naucit technologie, ktore su sucasne trendy, nechcem na projekte ani vidiet.
