### ISSUE TITLE
forbid user scalling

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#390]
forbid scalling by users by adding 

`<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, minimum-scale=1, user-scalable=no" />` to the head.

**Comment by zdila** [comment]
Feel free to directly edit it here on github: https://github.com/FreemapSlovakia/freemap-v3-react/edit/master/src/index.html

:-)
