### ISSUE TITLE
Map authentication error with new Garmin GPSMAP 66st

### ISSUE THREAD

**Issue by DiscoverHu** [FreemapSlovakia/freemap-v3-react#391]
Dear All,
I regret to inform you that your Garmin freemapSKtopo map unfortunately does not work on Garmin GPSMAP 66st. The error message is 'The map is closed'. It worked perfectly on Garmin Oregon 650 without any error messages.
Thank you in advance for your help.
Kind regards
Istvan Erdődi
discover.gc@gmail.com
Hungary

**Comment by zdila** [comment]
Please move this bugreport to correct project: https://github.com/FreemapSlovakia/freemapSKtopo/issues?q=is%3Aopen+is%3Aissue
