### ISSUE TITLE
Application error (no cookies and no local storage)

### ISSUE THREAD

**Issue by pdragun** [FreemapSlovakia/freemap-v3-react#393]
Ahoj, pri skúšaní embed mapy s vlastným GPX súborom som narazil na Application error! pod číslom: 39e9ef48-1f14-4a55-a7f8-3eaa3f46dcd6

Problém je zrejme(?) v nastavení permissions v mojom prehliadači Chromium, Ubuntu, ktoré znemožňuje nastaviť freemap aplikácii cookies a local storage. Kým problém s local storage globalErrorHandler.js ešte zachytí, tak problémy s cookies sa v konzole zobrazia ako samostatná chyba: 
Uncaught {error: "idpiframe_initialization_failed", details: "Cookies are not enabled in current environment."}

Najväčší problém je, že ono všetko vlastne funguje, len tam zavadzia tá chybová hláška. Áno, ja viem - stačí ju zatvoriť s krížikom vpravo hore.

Ak by niekto chcel viac informácií o chybe, dajte vedieť. Ďakujem a pozdravujem všetkých.

**Comment by zdila** [comment]
> Najväčší problém je, že ono všetko vlastne funguje

Ani nie. Napr login ces FB ;-)
