### ISSUE TITLE
Zdielanie nacitaneho GPX nefunguje

### ISSUE THREAD

**Issue by petermisovic** [FreemapSlovakia/freemap-v3-react#397]
Po nacitani uzivatelskeho GPX a kliknuti na Zdielat sa zobrazi chybova hlaska: "Nepodarilo sa uložiť trasu: Request failed with status code 413"

![freemap](https://user-images.githubusercontent.com/11147552/50547374-f040ef00-0c38-11e9-8e3b-01cdffaa19e5.jpg)

**Comment by zdila** [comment]
Prosim priloz GPX. Vyzera, ze je velmi velky.

PS: experimentalna mapa je krajsia https://www.freemap.sk/?map=14/48.943306/21.468530&layers=X ;-)

**Comment by petermisovic** [comment]
Ahoj, tu je to. Vdaka, pozriem experimentalnu verziu.
[Move_2018_12_29_09_40_23_Cross-country+skiing.zip](https://github.com/FreemapSlovakia/freemap-v3-react/files/2717137/Move_2018_12_29_09_40_23_Cross-country%2Bskiing.zip)

**Comment by zdila** [comment]
Po odstraneni objemnych metadat sa to podarilo uploadnut. Ale limit trochu navysime.

https://www.freemap.sk/?map=14/48.935695/21.459088&layers=X&track-uid=6zNVb7jtv82Wl4yXQ4YvRY&track-colorize-by=steepness

**Comment by zdila** [comment]
Prikladam aj zmensene GPX (+ som odstranil ten nadpis): [x.gpx.zip](https://github.com/FreemapSlovakia/freemap-v3-react/files/2717167/x.gpx.zip)

**Comment by zdila** [comment]
Velkos suboru ktora bola v tomto pripade sposobena velkostou metadat.

**Comment by zdila** [comment]
Limit zvyseny na serveri.
