### ISSUE TITLE
Zobrazovanie fotografii podla datumu v galerii 

### ISSUE THREAD

**Issue by petermisovic** [FreemapSlovakia/freemap-v3-react#398]
Dnes (27.01.2019) som pridal fotografie, ktorych atribut "fotene" a "nahrate" je 27.01.2019 (napr. https://www.freemap.sk/?map=14/48.966019/21.425142&layers=KIt&tool=gallery&image=99249&gallery-user-id=23). Ked vsak zapnem filter (autor thailon) s polozkami datum fotenia 27.01.2019 https://www.freemap.sk/?map=14/48.966019/21.425142&layers=KIt&tool=gallery&gallery-user-id=23&gallery-taken-at-from=2019-01-27&gallery-taken-at-to=2019-01-27 stranka nezobrazi ziadnu fotografie daneho dna.

**Comment by zdila** [comment]
Tak ked das od 27.01.2019 do 27.01.2019 tak to berie od 27.01.2019 00:00:00 do 27.01.2019 00:00:00. Ale spravim to viac user friendly.

**Comment by petermisovic** [comment]
Tak myslel som, ze  27.01.2019 00:00:00 do 27.01.2019 23:59:59. Prosto
zobrazit foto konkretneho dna. Lebo napriklad neviem tym padom dat z 26.01.
Lebo ked zadam len od, zobrazi aj 27
https://www.freemap.sk/?map=14/48.961342/21.420336&layers=KIt&tool=gallery&points=48.758887/21.266865,48.796419/21.258395&transport=foot&gallery-user-id=23&gallery-taken-at-from=2019-01-26
preto som daval do, aby som vyhradil den.

Peto

**Comment by zdila** [comment]
> Ale spravim to viac user friendly.

**Comment by petermisovic** [comment]
Imho UI (rozhranie toho filtra) je user friendly ako ma byt. Ale rozumieme
sa.
