### ISSUE TITLE
príliš presné retina tiles

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#399]
freemap.sk dopytuje príliš presné retina tiles, v mojom prípade `@1.3953488372093024x`

naozaj to treba na toľko desatinných miest? lebo potom sa nedá nastaviť cachovanie na mapniku...

**Comment by zdila** [comment]
hm?

**Comment by zdila** [comment]
jj, treba to upravit, ale je to experimentalna funkcia a HDPI tiles sa momentalne uplne ze vobec necachuju

**Comment by zdila** [comment]
K tomu `@1.3953488372093024x`, to na akom zariadeni? Co vypise ked na nom das do URL `javascript:alert(devicePixelRatio.toString())`? Resp. ake _pixel ratio_ hlasi https://www.mydevice.io/ ?

**Comment by MichalPP** [comment]
môj jediný nb, firefox
`JS pixel-ratio : 1.3953`

dnes napr `https://tiles-ng.freemap.sk/10/569/351@1.3953488372093024x`

**Comment by zdila** [comment]
A co je to za notebook? A OS? A nemas nahodou zoomnutu celu web stranku?

**Comment by MichalPP** [comment]
firefox, normálny HP notebook, ubuntu, nezoomnuté. 

chrome neberie retina tiles.

ešte potestujem na iných počítačoch.
