### ISSUE TITLE
Planovanie trasy

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#4]

**Comment by petervojtek** [comment]
@zdila , osobne by som planovanie trasy spravil rad tak, aby to vyuzilo gui vyhladavania POIs (podobne to maju spravene google maps) -- lenze pre ten ucel by sme najprv mali spravit poriadne vyhladavanie, lebo tam chceme search suggestions.

aktulne inak vyhladavanie cez nominativ ktore si tam dal funguje dost zvlastne, napr. pre "Senec" to najde pois zapadne od Prahy a po kliknuti na poi sa zobrazi prazdny popup.

**Comment by zdila** [comment]
Som fixol ten "Senec", hoci body s navyssiou priritou su mimo SK.

To planovanie - zatial mozno staci nejake jednoduche gui nech je to rychlo hotovo a potom by sa to mohlo vylepsie.

**Comment by petervojtek** [comment]
ok

On 26 Feb 2017 1:40 p.m., "Martin Ždila" <notifications@github.com> wrote:

Som fixol ten "Senec", hoci body s navyssiou priritou su mimo SK.

To planovanie - zatial mozno staci nejake jednoduche gui nech je to rychlo
hotovo a potom by sa to mohlo vylepsie.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/FreemapSlovakia/freemap-v3-react/issues/4#issuecomment-282553139>,
or mute the thread

**Comment by zdila** [comment]
Krajšie by bolo namiesto "Zmeniť štart/cieľ" implementovať posúvanie bodov myškou, ako je ti pri toole merania vzdialenosti.

**Comment by zdila** [comment]
Ako ináč vypínaš v chrome CORS na testovanie toho routovania?

**Comment by petervojtek** [comment]
> osúvanie bodov myškou

hej, to spravim tiez.

> cors:

https://chrome.google.com/webstore/detail/nlfbmbojpeacfghkpbjhddihlkkiljbi

**Comment by petervojtek** [comment]
Martin @zdila , fyi -- pridal som [non-react-js sposobom font-awesome ikonky](https://github.com/FreemapSlovakia/freemap-v3-react/blob/master/src/components/routePlanner.jsx#L26), lebo v glyphicons v boostrape som nenasiel ikonu auta.

skusal som najprv pouzit tieto react icon kniznice, ale ani jedna nefungovala:
* https://github.com/gorangajic/react-icons -- uz som zabudol kvoli comu
* a v https://github.com/nkt/react-icon mi neslo toto: https://github.com/nkt/react-icon/issues/1

**Comment by zdila** [comment]
Ono to je uplne koser a je to react way, lebo aj z `i` spravi react komponentu :-).

Inac ak element nic neobsahuje je ho lepsie pisat `<nieco/>`, takze: `<i className="fa fa-car" aria-hidden="true"/>`

A ten bug co ssi reportoval, tak to je "iba" warning a je sposobeny tym, ze v novsich reactoch sa kontroluje ci nahodou iekde nedavas atribut ktory nie je komponentou podporovany. Aj je, tak vypise warning a atribut zignoruje.

**Comment by petervojtek** [comment]
ok, zakladne planovanie trasy aj s medzizastavkami a posuvanim bodov by malo fungovat (s disabled cors)

**Comment by zdila** [comment]
Parada, musim pochvalit najma UX :-)
