### ISSUE TITLE
nefunguje na mojom mobile

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#401]
freemap.sk nefunguje na mojom mobile (a ani na IE). cca 2 mesiace dozadu fungoval, teraz uz nie.

ako zistim ktory commit to urobil?
mame nejake stranky typu www.freemap.sk/2019-02-28/ aby som jednu po druhej preklikal ktore mi funguju?

**Comment by zdila** [comment]
Ak chces zistit rucne ze ktory commit tak rozbehaj to lokalne a skusaj bisect pomocou `git checkout <commit_rev>`. Nezabudaj po kazdom dat `npm i`. Najskor to bude nejakou kniznicou co uz kasle na stare browsre. Ak taku najdes, pridaj ju ako vynimku do https://github.com/FreemapSlovakia/freemap-v3-react/blob/10b07a0f1e8f836cfccfba638a6cfad6928cff62/webpack.config.js#L46

Ale lahsie to bude zistit asi podla chybovej hlasky z konzoly MSIE.

Inac samotny FM kod by mal ist na 99.75% browseroch (https://github.com/FreemapSlovakia/freemap-v3-react/blob/10b07a0f1e8f836cfccfba638a6cfad6928cff62/webpack.config.js#L66). To su tieto: https://browserl.ist/?q=%3E+0.25%25

**Comment by MichalPP** [comment]
IE hlasi (moj mobil asi nema debugger :) )
`SCRIPT1002: Syntax error main.27ecf71927a4c9e7ba2c.js (64,15578)`
co je stredny riadok z :

```
case 'index': 
            return (key, value, accumulator) => { 
                result = /\[(\d*)\]$/.exec(key);          
```

**Comment by MichalPP** [comment]
vďaka, už funguje :)
