### ISSUE TITLE
round-tripping

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#402]
...som klikol "Start" na bezkarsku trasu a cakal som ze sa zacnu objavovat navrhy okruhov pre bezkovanie. Nic sa nedialo. Po kliknuti na ikonku startu sa objavila chybova hlaska. Tento test som robil na bezkarskom okruhu pri Donovaloch. Je tam viac na seba nadvazujucich okruhov a teda aj "potravy" pre tento algoritmus - som si myslel.

https://www.freemap.sk/?map=14/48.855765/19.237919&layers=K&tool=route-planner&points=48.865505/19.225988,&transport=nordic&route-mode=roundtrip

EDIT: toto je poznamka k Ticket ID 0c8b993a-f90d-4664-8392-7e1a2c712683

**Comment by zdila** [comment]
Uznavam, UI asi nie je 100% zrozumnitelne. Prvy klik do mapy je start a dalsie kliky su body v mape ktore chces navstivit (ako na screenshote v mailing liste). Ta chybova hlaska tam byt nema, pozriem sa na to.

**Comment by alexanderzatko** [comment]
Asi minutku po odoslani toho reportu som dosiel na to ako to funguje, takze zatial by som sa s tym UI netrapil a pockal na pripadne dalsie pripomienky. Vyzera to uzitocne.
