### ISSUE TITLE
routing UI vylepsenia

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#403]
v roundtrip routingu  

feature request:
* ak su dva body: vyhodit polozku 'po poradi','roundtrip','navsteva' (implicitne iba po poradi)
* ak su tri body: nechat iba 'po poradi','roundtrip'
* ak su 4+: vsetky tri moznosti

bug:
* ak je mhd/bikesharing: implicitne iba 'po poradi' (backend nepodporuje trip)

**Comment by zdila** [comment]
ohladom "feature request" - prave ze to je vec ktoru sa patri mat nastavenu este pred tym ako klikas do mapy. lebo pridas treti bod a hned ti zacne hladat povedzme defaultne route a ty vlastne chces roundtrip avsak doteraz si si ho nemohol zvolit.

ohladom "bug" - ok, cakal som ze tam bude nieco speci :)

**Comment by MichalPP** [comment]
aha, jasne. FR beriem spat :)
