### ISSUE TITLE
reklama na 2%

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#406]
ako každý rok, nejaká pekná reklama na 2%

http://wiki.freemap.sk/DvePercenta

**Comment by MichalPP** [comment]
uz asi netreba..

**Comment by synalik** [comment]
šak 2% sa dajú darovať až do konca apríla...tak možno ešte treba :)

št 28. 3. 2019 o 19:54 MichalPP <notifications@github.com> napísal(a):

**Comment by zdila** [comment]
nestihli ste
