### ISSUE TITLE
POI?

### ISSUE THREAD

**Issue by mlendl** [FreemapSlovakia/freemap-v3-react#408]
Pouzivam sluzbu na ziskanie POI vo formate GPX. Vsetko funguje OK, ale momentalne na vasom portali neviem najst API tejto sluzby. Preto sa pytam, ci tato sluzba je nadalej podporovana a ci sa neuvazuje o nejakom rozsireni popisov jednotliuvych POI? Pokrytie POI je velmi dobre, ale problem je prave v nedostatocnych popisoch.

**Comment by zdila** [comment]
Na poi vyuzivame overpass API. Web k tomu najdete na https://overpass-turbo.eu/

**Comment by zdila** [comment]
inac na taketo otazky prosim pouzivajte [forum](https://groups.google.com/d/forum/osm_sk)

**Comment by MichalPP** [comment]
alebo na https://data.oma.sk/api.php
