### ISSUE TITLE
Tracking - Pri označovaní myšou zruší editačné okno

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#410]
Keď v niektorých editačných oknách Trackingu pri označovaní textu v textboxe pomocou myšie kliknem a pri ťahaní (označovaní) prejdem za hranicu okna zruší mi celé editačné okno.
Ak by to nebolo jasné môžem skúsiť ešte nejako inak popísať.

**Comment by zdila** [comment]
> Ak by to nebolo jasné môžem skúsiť ešte nejako inak popísať.

Netreba, viem o tom :-)

**Comment by zdila** [comment]
uz to nerobi
