### ISSUE TITLE
Tracking - Pri dvoch zariadeniach to hapruje

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#411]
Teraz som refrešoval stránku a trackeri sa mi menili bez toho aby som niečo menil alebo aby vysielali.
- farba na oboch je rovnaká aj keď mám nastavenú rozdielnu
- ak som mal obe zariadenie a dal jedno sledovať presunul sa mimo na mape nevrátilo ma na sledované zariadenie
- zobrazila sa mi história jedného zariadenia, ktorá sa mi už prestala zobrazovať

**Comment by zdila** [comment]
Neviem to zreprodukovat. Posli mi pls URL ked sa to takto sprava (mozes aj mailom). Pripadne nahraj video.
