### ISSUE TITLE
Tracking - support pre OsmAnd

### ISSUE THREAD

**Issue by miro-janosik** [FreemapSlovakia/freemap-v3-react#413]
OsmAnd podporuje odosielanie polohy cez parametre v URL:

https://backend.freemap.sk/tracking/track/SqRInpLj?lat={0}&lon={1}&time={2}&acc={3}&alt={4}&speed={5}

podporuje parametre:
lat={0}
lon={1}
timestamp={2}
hdop={3}
altitude={4}
speed={5}
bearing={6}

**Comment by zdila** [comment]
Parametre su uz podporovane, len si uprav `altitude` na `alt` a `hdop` na `acc`.

**Comment by miro-janosik** [comment]
V povodnej url su uz upravene, url by mala byt korektna.
Viem ze Aceman444 pisal ze jemu to uz funguje, ale prosim o verifikaciu mojho pripadu.

Mam zariadenie "miro-a3 | SqRInpLj", skusal som o pridanie polohy cez OsmAnd alebo aj cez browser:
https://backend.freemap.sk/tracking/track/SqRInpLj?lat=48.698212&lon=19.39636&alt=200 co by malo byt niekde v strede slovenska. Dostavam spet json "id | 8321", takze zda sa ze request je spracovany korektne.

V "Devices you watch" mam dve zariadenia:
f2HQmq5O | Martin
miro-a3 | MiroJ
(skusal som namiesto "miro-a3" aj token), a na mape vidim iba Martin, nevidim "MiroJ". Su data na serveri? Preco ich nezobrazuje?

**Comment by zdila** [comment]
Musi si vygenerovat token na sledovanie pre dany device. Klikni na ikonku kde je kllucik, pridaj si novy zaznam a ten token pre ostatnych aby ta mohli sledovat.

Urcite nie je mozne sledovat podla mena ktore si ty vymyslis, pretoze niekto iny si moze vymysliet rovnake meno.

Tiez nie je dobre pouzit ten isty token ktory davas do OsmAnd lebo ked ho das ostatnym, mozu ho zneuzit a ties zi ho dat do OsmAnd. Preto je to takto trosku zlozitejsie. Ale je to v tych modrych popisoch. Ak to vies popisat lepsie, smelo mi to posli.

**Comment by miro-janosik** [comment]
Okej, az teraz mi to doslo. Matuce bolo to, ze ved "token" tam uz je (token zariadenia), necakal som ze to je rozdielne od "tokenu" pre zobrazovanie. A "access token" je take vseobecne, preto by som upravil popis na "watch token" takto:

na stranke "Devices you watch": nazov stlpca "Token or Device" => "Watch token"

na stranke "My Tracking Devices": 
"...if you give them access token [key] you create." =>"...if you give them watch token (create watch token through [key] icon)."

na koniec navodu dopisat samples pre najpouzivanejsie programy:
"Tracking url for OsmAnd: https://backend.freemap.sk/tracking/track/track-token?lat={0}&lon={1}&time={2}&acc={3}&alt={4}&speed={5}" a zvyraznit "track-token" pretoze to treba zmenit.

nazov stlpca "Token" => "Track token"

stranka "Access Tokens" => "Watch tokens":
nazov stlpca "Token" => "Watch token"

stanka "Modify Tracked Device"
"Access Token of existing shared device" => "Watch token of existing shared device"

**Comment by miro-janosik** [comment]
Oprava, spravna url pre OsmAnd je bez time, nevie ho spracovat a ani snad netreba:
https://backend.freemap.sk/tracking/track/track-token?lat={0}&lon={1}&time={2}&acc={3}&alt={4}&speed={5}
