### ISSUE TITLE
Niektore pripomienky komunity doplnenia prvkov vo vrstve X

### ISSUE THREAD

**Issue by Mirecnet** [FreemapSlovakia/freemap-v3-react#414]
Vzhladom na prechd vrstvy X od experimentalnej na hlavnu by bolo dobre zapracovat do noveho  renderu X niektore prvky stareho Freemapu:
Niektore pripomienky komunity:

Nedal by sa zobrazovat aj tag "nasyp" ? man_made=embankment

Potom prosim rovnako aj embankment=yes a man_made=dyke . 

Odporucal by som sa este pozriet sa aj na cesty a chodniky
highway=track
tracktype=grade5
a
highway=path

sa nedaju skoro vobec rozoznat. Na starom Freemape je to piam umelecky zvladnute.
Priklad uplneho chausu lesnych ciest a chodnikov: https://www.freemap.sk/?map=17/49.119690/19.362599&layers=X

Odporucal by som chodnik zobrazit a rozlisit viac bodkato.

Nazov malych dolin sa zobrazuje daleko - casto na ich bocnych hrebenoch. Priklad: - https://www.freemap.sk/?map=17/49.105506/19.222679&layers=X
https://www.freemap.sk/?map=17/49.133127/19.298150&layers=X

Tak isto je problem vo vrstve X pri podzemnych priepustoch - zobrazuju sa, ako rieky na povrchu a krizuju budovy
tunnel=culvert
layer=-1
waterway=drain
Napriklad tu: https://www.freemap.sk/?map=19/49.076831/19.318933&layers=X
Na starom Freemape pekne pochadzaju budovu a su ciarkovane.

Doplnil by som do turistickej mapy urcite aj chaty v divocine. Pre utocisko pred zlym pocasim by v turistickej mape nemalo nieco take chybat.
name=Mlynová koliba
tourism=wilderness_hut
T: https://www.freemap.sk/?map=18/49.065186/19.226136&layers=T
X: https://www.freemap.sk/?map=18/49.065186/19.226136&layers=X

Mozno este doplnit dialnice a cesty vo vystavbe (staveniska na zelenej luke a podobne).
landuse=brownfield (na starom Freemape sa zobrazovalo)
https://www.freemap.sk/?map=17/49.101790/19.353103&layers=T

Oznacovat hlavne neznackovane chodniky viac vyrazne
Cervena:
highway=path
sac_scale=hiking
Vzor stary Freemap: https://www.freemap.sk/?map=17/49.098349/19.286267&layers=T
Modra
highway=path
sac_scale=alpine_hiking
Vzor stary Freemap: 
https://www.freemap.sk/?map=17/49.161787/20.139452&layers=T
https://www.freemap.sk/?map=17/49.192441/20.218636&layers=T

Zaujimave body a atrakcie v mape zobrazovat viac farebne - na cerveno
tourism=attraction
https://www.freemap.sk/?map=17/49.052413/19.480200&layers=T

Mapu najlepie rozdelit na turisticku a cyklisticku. Nech to nieje vsetko neprehladne nasekane v jednom.

Vrstva X je velky progres (takmer okamzity render POI) a oproti inym map portalom je to nieco kam sa oplati kazdy den chodit. Treba si na to sadnut s vedomim, ze kazdy den do mapy zadarmo ludia vkladaju stovky novych objektov a pekny render ich isto bude motivovat k dalsej produktivnej praci.
Na tieto pripomienky sa treba pozriet. Potom ta mapa uz nebude mat ziadnej chyby. Bude teda v dnesnej rychlej dobe inovacii moct plne konkurovat komercnym portalom a bude lepsia, ako vsetky ostatne...

M.

**Comment by zdila** [comment]
Tuto poziadavku je nutne rozdelit do samostatnych jednotiek, ako som pisal v mailing liste.
