### ISSUE TITLE
Kufrik sa neda otvorit

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#415]
Polozka nastrojov v menu (ikona kufrika) sa pri kliknuti neotvara. Testovane vo FF (prihlaseny pouzivatel) aj v Safari (neprihlaseny pouzivatel. Na MacOS X pocitaci.

**Comment by zdila** [comment]
Kedysi vyvoj webovych appiek komplikoval Explorer, dnes je to Mac. Vyvoj nezastavis.

**Comment by alexanderzatko** [comment]
vyvoj apiek komplikuje kadeco. Nam by najviac vyhovovalo ak by existoval jeden browser, jeden OS, jeden typ pocitaca, atd... :-)

dakujem za fix.
