### ISSUE TITLE
Vylepsit vyhladavanie POI

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-v3-react#42]
vylepsit (upratat) kod a UI

**Comment by zdila** [comment]
> dropdown - ja by som obmedzil jeho vysku a spravil ho vnutorne scrollovatelny (aby nebol vyssi nez je vyska obrazovky a nesposoboval scroll celej stranky).

Idealne keby na to bol uz hotovy komponent. Nateraz som tam dat `NavDropdown` ktory take nepodporuje. V mobilnom zobrazeni sa skroluje cela obrazovka, takze tam by sa ta featura mala potom vypnut.

> kliknutie na kategoriu by mohlo zbalit jej clenov

to ano, este to nie je dokoncene

> oznacena polozka by mohla mat indikator.
> multiselect?

to bolo kedysi ,ale som to odstranil. Chcem, aby po zvoleni polozky sa vysledok okamzite zobrazil na mape. Po zvoleni inej kategorie sa pridaju dalsie body (z tej kategorie). Je to koli tomu, aby clovek cim menej klikal. Vacsinou aj tak vyhladava iba jednu vec, anpr pramene, takze po ich zvoleni mu ich hned zobrazi.

**Comment by zdila** [comment]
A naviac tam bude search textbox kde vies zacat pisat co hladas a bude to filtrovat zoznam.

**Comment by petervojtek** [comment]
> dropdown - ja by som obmedzil jeho vysku a spravil ho vnutorne scrollovatelny
> Idealne keby na to bol uz hotovy komponent. Nateraz som tam dat NavDropdown ktory take nepodporuje.

to je lahke, staci:

```
ul.dropdown-menu {
  overflow-x: auto;
  height: calc(70vh);
}
```

ale na mobile (s css aj bez neho) to bude treba este osetrit nejako inak, lebo teraz ked sa preskrolujem uplne dole rozbalenym menu, tak sa ocitnem v mape  - ale kedze sa to udeje rychlo, tak obvykle spravim este jeden dotykovy skrolovaci pohyb, lenze to uz som v mape a tu si niekam nechtiac posuniem.

**Comment by zdila** [comment]
Stale sa da co vylepsovat. Na konkretne vylepsenia prosim vytvorit zvlast issue(s).
