### ISSUE TITLE
Application error with advanced settings

### ISSUE THREAD

**Issue by kudlav** [FreemapSlovakia/freemap-v3-react#421]
Device:
Samsung Galaxy A3 (SM-A300FU)
Android 6.0.1
Samsung Internet 9.2.10.15

How to reproduce:

1. Open Freeman
2. Open Settings → General
3. Check *Expert mode*
4. The Application error without ticket ID occurs

---
Application error!

The error has been automatically reported under Ticket ID .... You can report the problem at GitHub, or eventually email us the details at freemap@freemap.sk.

Thank you.

You can try:

reload last pageload initial pageclear local data and load initial page

**Comment by zdila** [comment]
Vdaka za report, fix bol nasadeny.
