### ISSUE TITLE
chyba vo funkcii vlozit do webstranky

### ISSUE THREAD

**Issue by vito007** [FreemapSlovakia/freemap-v3-react#426]
Ahojte. Vyklikám si výrez, ktorý mi vyhovuje, html kód sa ale neaktualizuje podľa polohy výrezu a zoomu. Keď dám skopírovať kód, tak je to default kód pred vyklikavaním.

**Comment by zdila** [comment]
Kod sa ani aktualizovat nema, v tom dialogu je len nahlad ako to budes vidiet na svojej stranke aj s interaktivitou. Ale do buducna skusim pridat aby sa to reflektovalo do URL.

**Comment by vito007** [comment]
Som si myslel ze by to mal byt wizard na embed kod, tak potom som to zle
pochopil, ok. Ale ako wizard by to bolo pouzitelnejsie. Vdaka za vsetko, co
robite pre komunitu a aj obycanych pouzivatelov.
