### ISSUE TITLE
Mapa sa nenastartuje v IE11

### ISSUE THREAD

**Issue by matuszuborupc** [FreemapSlovakia/freemap-v3-react#438]
Aplikáciu sa nepodarilo spustiť.
Application error.

**Comment by zdila** [comment]
Nie je az taky velky problem pridat podporu aj pre IE, avsak zbytocne by sa zvacsil celkovy kod. Tiez nahrada modernych konstruktov by robila aplikaciu v modernych prehliadacoch menej efektivnou. Naviac podiel MSIE je uz skoro marginalny a Microsoft ich uz davno nepodporuje.

**Comment by zdila** [comment]
Duplikuje #416.

**Comment by matuszuborupc** [comment]
Mne ani tak nejde o IE11 ako o TWebbrowser, ktory je mozne pouzit v kode programovacich jazykov ako je Delphi alebo C. Islo mi najma o router pre najdenie najlepsiej cesty, ktory fungoval az do poslednej upravy webu s exportom do gpx. Poslednym modulom, sa stalo to, ze teraz to uz vo IE11 vobec nejde nabehnut a tym padom ani v Twebbrowseri od MS....
