### ISSUE TITLE
routing pridávanie bodov

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#439]
keď si vytvorím nejakú navigáciu a posúvam mapu, občasne kliknem do mapy a celú mi ju pokazí (pridá nový bod)

dal by sa pridať (konfigurovateľný) parameter aby kliky do mapy nebral ako nový koncový bod ak som "dlho" nepridával? (napr 10 sekúnd) (aby som si vedel nastaviť aj na 0, čo by vlastne zrušilo možnosť pridávať nové koncové body a nechalo iba možnosť posúvať čiaru a tak pridať waypointy)

**Comment by zdila** [comment]
Staci si zavriet nastroj navigacie.

**Comment by MichalPP** [comment]
potom nevidím časy, typ routingu atď.

**Comment by zdila** [comment]
casy vidno v tooltipe. a typ je v URL.
