### ISSUE TITLE
car routing: prehodit backend

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#440]
v car routingu prehodit backend z routing.epsilon.sk na routing.freemap.sk

ostatne profily nechat ako su teraz (teda z domeny routing.epsilon.sk)

**Comment by zdila** [comment]
prehodim naraz ked bude pripravene vsetko

**Comment by MichalPP** [comment]
nebude všetko naraz, dosť to závisí od PHP a postgisu (čo som rád že funguje aspoň u mňa). prehoď zatiaľ iba car profil.

**Comment by zdila** [comment]
ok, len to par tyzdnov/mesiacov potrva kedze to prepisujem na typescript, bude treba vsetko riadne otestovat a nemam casu.
