### ISSUE TITLE
konfigurácia klonu

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#446]
rád by som urobil klon/fork pre niektoré špec prípady (napr špecializovaná kočíková mapa alebo zimná mapa). na to by som potreboval oddeliť do samostatného konfiguračného súboru (alebo viacerých):

- logo, title, (base url)
- zoznam mapových TMS podkladov
- zoznam routing služieb
- (tips už viem meniť bez problémov)
- horné menu (aby som vedel vyhodiť prihlasovanie, nastavenia, expert režim, sledovanie,...)

časť asi stačí návod.

**Comment by zdila** [comment]
Nerozumiem. Ved daj `git clone` a upravuj zdrojaky.

**Comment by MichalPP** [comment]
lenže tie veci sú rozhádzané kade-tade po zdrojákoch (nájsť ich je problém). plus bojím sa upravovať zdroják, lebo potom sa strašne ťažko drží s masterom.

ale možno stačí popis, kde čo môžem meniť (a nerozbije sa to po pár mesiacoch commitov)

**Comment by zdila** [comment]
Casti freemap portalu nie su vypinatelne nejakym suborom. Riesenie pre teba bude forknut si projekt a povyhadzovat co netreba.
