### ISSUE TITLE
Live tracking - zaseknutie

### ISSUE THREAD

**Issue by miro-janosik** [FreemapSlovakia/freemap-v3-react#447]
Dnes po update freemap a pri kliknuti na Live Tracking (BETA) - moje zariadenia - ikona "oka" pri zariadeni sa Firefox zasekne, CPU je vytazene na 100%. Dostavam vo Firefoxe spravu "Webpage is slowing down your browser, do you want to close the page"?

Ubuntu 19.04 + Firefox 68.0.2 ; reprodukovatelne aj na Ubuntu 18.04 + Firefox 68.0; na Windows 10 + Firefox 68.0.2 sa to rozbehlo trochu rychlejsie.

Vidim ze cez tlacidlo "Watched" su watch tokeny su uz male cisla. Ale cez tlacidlo "My devices" / "Ikona kluca" su to stale dlhe texty, a po kliknuti na ne uz nefunguju. Asi treba zmazat vsetky tieto stare watch tokeny.

Browser zasekne napriklad aj ked idem na tuto watch url: https://www.freemap.sk/?map=16/49.139320/20.299208&layers=X&track=JeCSZ40r&follow=JeCSZ40r (na 5-20 sekund).

**Comment by zdila** [comment]
Vdaka za report. Ak myslis tie male cisla ako `22` a podobne, tak tie sa pouzivaju len pre vlastne zariadenia a sledovat ich moze len prihlaseny user ktoremu zariadneie patri (t.j. sam seba). Na zdielane sharovanie pouzivas watch tokeny.
