### ISSUE TITLE
amenity=doctos/s

### ISSUE THREAD

**Issue by debyos** [FreemapSlovakia/freemap-v3-react#448]
Dear all,
I think in the [subcategories file](https://github.com/FreemapSlovakia/freemap-v3-react/blob/9fa06dc4969d5e97906b3c37de60d8062eaf0e45/src/subcategories.json) in line 232 there should be [doctor**s**](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Ddoctors) (in plural) instead of doctor.
Please modify
Thanks

**Comment by zdila** [comment]
Thanks for the report.
