### ISSUE TITLE
Hungarian translation ready

### ISSUE THREAD

**Issue by debyos** [FreemapSlovakia/freemap-v3-react#455]
Dear All,
I find Freemap Slovakia a great tool thus I have created a [Hungarian translation](https://github.com/FreemapSlovakia/freemap-v3-react/files/3573483/hu.zip) to it. If you think it is worth to be there, please put it [in the translations directory](https://github.com/FreemapSlovakia/freemap-v3-react/tree/653eeb2ab5448bd64dfe68350806a70010455383/src/translations) and then make it online.
Thanks in advance!

**Comment by zdila** [comment]
Thanks! I've integrated it. Please wait couple of days before I do the deployment.

**Comment by zdila** [comment]
Please translate also this:

```
              <h1>Problem starting application</h1>
              <p>
                Please make sure you are using recent version of some modern browser (Google Chrome, Firefox, Safari, Opera, Edge, Chromium).
                Ancient Internet Explorer is no more supported.
              </p>
```

**Comment by debyos** [comment]
Dear Zdila,

Here you are:

              <h1>Hiba történt az alkalmazás elindításánál</h1>
              <p>
                Győződjék meg arról, hogy egy modern böngésző (Google Chrome, Firefox, Safari, Opera, Edge, Chromium) friss verzióját használja. Az ősi Internet Explorer már nem támogatott.
              </p>

* * * * *

Az alkalmazás futtatásához JavaScriptet támogató böngészőre van szükség.

* * * * *

      <h1>Alkalmazáshiba</h1>
      <p>Jegyazonosító (ticket ID): ${id}.</p>
      <p>A jegyazonosítót és a hiba újbóli megjelenéséhez vezető lépések leírását a következő e-mail címre küldheti:
	  <a href="mailto:freemap@freemap.sk">freemap@freemap.sk</a>.</p>`;

**Comment by zdila** [comment]
Thanks!

**Comment by debyos** [comment]
Dear All,

I have updated the [Hungarian translations](https://github.com/FreemapSlovakia/freemap-v3-react/blob/cb52150288c8bca8cb21064d09445a01aa872d48/src/translations/hu.tsx). Here you get [the file](https://github.com/FreemapSlovakia/freemap-v3-react/files/4008479/hu_tsx.zip).

Cheers

Gábor
