### ISSUE TITLE
nezobrazuje popisky

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#456]
po otvorení nalogovaného človeka nezobrazuje popisky:

![image](https://user-images.githubusercontent.com/3583700/64315880-9bb5f680-cfb3-11e9-9de1-5b3d32f794d6.png)

refresh nepomohol, až nastavenie jazyka v menu.

asi malá blbosť, len či to nie je znak čohosi väčšieho

**Comment by zdila** [comment]
> asi malá blbosť, len či to nie je znak čohosi väčšieho

pri vyvoji sa mi to asi 3x stalo ale nevedel som zreprodukovat. ale nieco skusim...
