### ISSUE TITLE
Novy search - resetnut scrollbar

### ISSUE THREAD

**Issue by miro-janosik** [FreemapSlovakia/freemap-v3-react#457]
Ak vyhladam "Bratislavska" zobrazi mi viacero ulic, v tomto zozname poskrolujem dolu.
Potom dam vyhladat "Trnavska" a zasa mi zobrazi viacero ulic, ale nevidim tu najrelevantnejsiu - prvu, ale som uz odskrolovany dolu. Treba resetovat poziciu scrollbaru na 0.

**Comment by miro-janosik** [comment]
Otestoval som (ponuklo mi novsiu verziu stranky), dal som aj refresh, ale stale sa to sprava rovnako - chyba je pritomna.
Ubuntu 19.04, Firefox 69.0
Windows 10, Firefox 68.0.2

**Comment by zdila** [comment]
Treba cakat na deploy (tj. kym stranka neukaze modru notifikaciu o novsej verzii). Medzi fixnutim issue na githube a deployom mozu prejst kludne aj dni, mesiace, (roky) ;-)

**Comment by zdila** [comment]
Aha, pozeram ze ti ponuklo. Tak asi novsiu ale nie najnovsiu. Skus este raz.

**Comment by miro-janosik** [comment]
Hm, teraz mi to neponuklu modru notifikaciu, ale problem je fixnuty :-) Fixed.
