### ISSUE TITLE
planovac: pridat start/ciel -- mat moznost vybrat si aj z 'aktualna poloha'/'domov'

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#46]
na tlacidle Pridat start/ciel by mohol byt dropdown, ktory by ponukol dve moznosti:
* aktualna poloha
* domov -- nemam premyslene ako by mohol pouzivatel nastavit jeho domovsku polohu

**Comment by zdila** [comment]
> nemam premyslene ako by mohol pouzivatel nastavit jeho domovsku polohu

v nastaveniach? idealne vsak nejako kliknutim do mapy (napr settings dialog zmizne, v menu bude iba "zrusit" a mozes len manipulovat s mapou a kliknut do nej. nasledne sa dialog znova objavi)

**Comment by petervojtek** [comment]
> nastavit jeho domovsku polohu - v nastaveniach

ok, mozeme pridat dalsiu polozku do Settings.
ak pouzivatel nebude mat nastavenu domovsku polohu a klikne v planovaci na start > domov, tak by mu to pre jednoduchst mohlo len zobrazit toast nech si najprv nastavi domovsku polohu v nastaveniach.
