### ISSUE TITLE
Pridat facebook tlacitko

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-v3-react#47]
* like tlacitko
* link na nasu fanpage (vo "Viac"?)

**Comment by tjamecny** [comment]
Prosim o moznost vypnut vsetky asocialne hluposti, zatial staci ako premenna v kode, a v buducnosti, ked bude podporovane prihlasenie, tak sa to len nalinkuje do nastaveni, t.j. kto bude mat konto na freemape, moze si to vypnut, inak to bude defaultne zapnute.

**Comment by zdila** [comment]
Uz mame link na fb stranku
