### ISSUE TITLE
Po kliknuti na prihlasenie cez OSM sa nic neudeje - iOS nativny prehliadac Safari

### ISSUE THREAD

**Issue by jurajbelobrad** [FreemapSlovakia/freemap-v3-react#470]
Pri vytvorenie linku na portal na "desktop" v telefone (web sa otvori ako aplikacia) nefunguje prihlasenie cez OSM, len preblikne raz ikona a nic sa neudeje, ani ziadna chyba, ani popup.
Prihlasenie cez FCB, aj Google funguje - otvori sa dana stranka v novom tabe.
To iste sa deje cez apple prehliadac Safari.

V prehliadaci Chrome prihlasenie vsetkymi 3 sposobmi funguje.

iOS 13.1.1, freemap.sk portal aktualizovany.

**Comment by zdila** [comment]
Mne to na testovacom Macu ide - Safari 13.0.1.

Nemas nejaky popup blocker? Pripadne pozri do JavaScript konzoly.

**Comment by zdila** [comment]
> Pri vytvorenie linku na portal na "desktop" v telefone

ako si vytvoril linku v telefone? aky prehliadac? screnshot?

ale najskor to bude blokovanim popup a s tym nic nezmozem ak to nepovolis v nejakych nastaveniach

**Comment by jurajbelobrad** [comment]
Nespecifikoval som, ze to skusam na telefone - iPhone SE, os: iOS 13.1.1

Linkom som myslel vytvorenie ikony na ploche telefonu - home screen, aby sa portal spustal ako app.

V Safari nemam ziadne doplnky, je to pre dumb userov, nema ani nastavenia :)
