### ISSUE TITLE
Upload fotiek - nevalidny datum a cas fotenia

### ISSUE THREAD

**Issue by jurajbelobrad** [FreemapSlovakia/freemap-v3-react#471]
Pri nahravani foto vytvorenych na iPhone SE sa po stlaceni tlacidla Nahrat objavi chyba "Nevalidný dátum a čas fotenia."
V prílohe hláška aj daná foto.
Testované na iOS 13.1.1, prehliadač Safari / Chrome / appka na "desktop"

Pri nahrati rovnakej fotky skopirovanej do PC sa nahra v poriadku bez hlasky - Win 7 64bit, Firefox 69.0.1

![IMG_3166](https://user-images.githubusercontent.com/31770020/66422070-4d0fd800-ea09-11e9-9835-decbf4a10ea1.JPG)
![IMG_3187](https://user-images.githubusercontent.com/31770020/66422072-4d0fd800-ea09-11e9-9259-52009ab4c528.PNG)

**Comment by zdila** [comment]
A ked tu foto stiahnies do PC (al. Mac) tiez to robi? Ak ano, prosim zozdielaj nu niekam nemodifikovanu.

**Comment by jurajbelobrad** [comment]
Ano, ked ju skopirujem z telefonu do PC - Windows 7 64 bit, tak sa da nahrat normalne.
Z mobilu som to skusal prvy krat, na PC nahravam fotky fotene mobilom bezne.

**Comment by jurajbelobrad** [comment]
Poslal som ti do mailu link na dropbox, ak nepride, daj vediet, hodim to inde.
