### ISSUE TITLE
Moznost ulozit gpx ako track

### ISSUE THREAD

**Issue by jurajbelobrad** [FreemapSlovakia/freemap-v3-react#478]
gpx by sa mohla dat ulozit aj ako track (tento format pouziva locus, aj mapy.cz).
Teraz to musim prekonvertovat inde.

Original message:
https://www.mtbiker.sk/forum/post1531691.html#p1531691

**Comment by zdila** [comment]
Mne to uklada ako "track".

**Comment by PertR** [comment]
Si si isty? Ked chcem importovat gpx z freemap,tak mi to mapy.cz nezjedia,ze to nie je track. (chodim tam,pretoze na freemaps  nie je ukladanie si vlastnych tras do profilu,alebo aspon o tom neviem)

**Comment by zdila** [comment]
Poprosim o konkretne GPX kedze z freemapu sa da exportovat kadeco.

**Comment by PertR** [comment]
Bolo to exportovane ako "vyhladanu trasu" ine moznosti sa nedali zaciarknut
[export.zip](https://github.com/FreemapSlovakia/freemap-v3-react/files/3769237/export.zip)

**Comment by zdila** [comment]
V pohode drag and drop `export.gpx` suboru zo zipka na mapy.cz:

![image](https://user-images.githubusercontent.com/636095/67520535-55bf0a00-f6a9-11e9-8038-510ca159f67e.png)

**Comment by PertR** [comment]
toto neriesi moj problem,furt to je route,tie zastavky tam nechem mat..nevadi,budem budem to robit ako dotaraz

**Comment by zdila** [comment]
> furt to je route

Nie, je to track (`<trk>`), ziadna route (`<rte>`). Vid obsah xml konfrontovat z GPX 1.1 schemou - v GPX je jeden track `<trk>` s jednym segmentom `<trkseg>` a niekolko waypointov `<wpt>`. Ak nejaky softver vyzaduje specializovany vstup, tak si ho musi pouzitavel pripravit sam.

**Comment by PertR** [comment]
Ja len chcem,aby som si to po vytvoreni trasy nahral bez tych zastavok na mapy.cz..nejde to,musim to uploadnut na www.ridewithgpx.com a odtial to ulozit ako track. Potom to mozem uploadnut na mapy.cz. Neriesme to ked to nejde.

**Comment by zdila** [comment]
@LacoPlsko to by sa dalo.

**Comment by LacoPlsko** [comment]
Vďaka, bolo by to fajn.

**Comment by zdila** [comment]
![image](https://user-images.githubusercontent.com/636095/67753849-ae89fc00-fa35-11e9-8169-8bfd30b2fc29.png)
