### ISSUE TITLE
pridat donate dlacitko

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-v3-react#48]

**Comment by petervojtek** [comment]
kolko ludi (a akou sumou) prispelo cez Donate tlacidlo na aktualnom freemape sa posledny rok? (t.j. ci to ma zmysel :)

**Comment by zdila** [comment]
> kolko ludi (a akou sumou) prispelo cez Donate tlacidlo na aktualnom freemape sa posledny rok? (t.j. ci to ma zmysel :)

@kaylesk mas nejake info?

**Comment by kaylesk** [comment]
Môže to ostať ako "low priority". Za posledné 2 roky v priemere 3 ľudia (15€) za rok.

**Comment by petervojtek** [comment]
to tam radsej dajme plochou rovnako velky adsense, verim ze zarobi viac :)

**Comment by zdila** [comment]
@didoa, @tjamecny  alebo niekto, viete mi prosim dat html kod pre donate button (zo stareho freemapu)?
