### ISSUE TITLE
andorid 9 vs app

### ISSUE THREAD

**Issue by PertR** [FreemapSlovakia/freemap-v3-react#482]
Ahoj,mam stock android . Dnes mi telefon zahlasil cca toto : 

"freemap app ma vysoku spotrebu energie na pozadi..."

(chapem ze ta app nie je stavana na Pie,davam to sem, len aby sa o tom vedelo)

**Comment by zdila** [comment]
mne sa to nepodarilo, naviac odvtedy  bolo spravenych v kode vela zmien. ak sa to prejavi znova tak kludne otvor.
