### ISSUE TITLE
navigacia - nekonzistentne chybove hlasky

### ISSUE THREAD

**Issue by jose1711** [FreemapSlovakia/freemap-v3-react#487]
https://www.freemap.sk/?map=13/48.138714/17.144508&layers=T&tool=route-planner&points=48.166200/17.177811,48.115454/17.112751&transport=bikesharing

niekedy zobrazi text "Cez zvolené body sa nepodarilo vyhľadať trasu. Skúste zmeniť parametre alebo posunúť body trasy." a niekedy (po opakovanom nacitani tejto stranky) takyto text:

![obrázok](https://user-images.githubusercontent.com/1406222/69492894-47326100-0ea8-11ea-8f4f-0e6bb983cd9d.png)

Bolo by dobre, aby boli tieto hlasky konzistentne.

**Comment by zdila** [comment]
Ta druha chyba je nieco ako "internal error" :)

**Comment by zdila** [comment]
Vies prosim mi poslat URL ktora sposobi tuto chybu?

**Comment by jose1711** [comment]
pozri zaciatok issue, mas ju tam :-)

**Comment by MichalPP** [comment]
backend sa nemenil, dokonca aj trasu nájde. 

píše že očakáva `$.extra: expected 'price' in object`

**Comment by zdila** [comment]
Vdaka za report.

**Comment by jose1711** [comment]
> backend sa nemenil, dokonca aj trasu nájde.
> 
> píše že očakáva `$.extra: expected 'price' in object`

mne trasu nenajde. zrejme preto, lebo start je prilis daleko od bicyklovej stanice.
