### ISSUE TITLE
Specifikovat bike sharing

### ISSUE THREAD

**Issue by jose1711** [FreemapSlovakia/freemap-v3-react#488]
V Bratislave su t. c. dva projekty bike-sharingu - whitebikes a slovnaftbajk. Bolo by fajn vediet, o ktory sa pri vybere v Route finderi jedna.

**Comment by zdila** [comment]
@MichalPP ktory teda podporujeme?

**Comment by MichalPP** [comment]
ak si dobre pamatam, slovnaftbajk neposkytuje data. 

whitebikes su tie s kapitalkami.

**Comment by zdila** [comment]
Dal som do popisu Whitebikes v Bratislave ale pozaram ze sluzba funguje aj v Kezmarku a Presove a mozno aj niekde inde. A tam sa to asi nevola white bikes. @MichalPP  Ako to teda nazvat? Komunitny bikesharing?

**Comment by MichalPP** [comment]
nazov iba bikesharing. 

[tu je aktuálny zoznam](http://routing.epsilon.sk/bikesharing.php) bikesharingov čo sú v systéme. ak chceš pridať další, daj [link z tohto](https://citybik.es/l)

**Comment by zdila** [comment]
> ak chceš pridať další
kde ak chcem pridat dalsi?

**Comment by MichalPP** [comment]
uz ide aj [vieden](https://www.freemap.sk/?map=14/48.196446/16.384735&layers=X&tool=route-planner&points=48.207287/16.338043%2C48.187148/16.366196&transport=bikesharing) a aj budapest.
