### ISSUE TITLE
Otvoriť v ZBGIS

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#489]
Bolo by možné pridať do ponuky Otvoriť v externej aplikácií portál ZBGIS (https://zbgis.skgeodesy.sk/mkzbgis)
Najlepšie asi v zobrazení katastra ale prakticky je to jedno.

Tiež sa asi môže odstrániť voľba mojamapa.sk - spôsob otovrenia nefunguje už niekoľko mesiacov a keďže sa nik neozval tak to asi ani nik okrem mňa nevyužíval :D.

**Comment by zdila** [comment]
mojamapa som uz davnejsie odstranil ale este neprislo na deployment
