### ISSUE TITLE
Hungarian translation ready

### ISSUE THREAD

**Issue by debyos** [FreemapSlovakia/freemap-v3-react#490]
Dear All,

I have updated the [Hungarian](https://github.com/FreemapSlovakia/freemap-v3-react/blob/cb52150288c8bca8cb21064d09445a01aa872d48/src/translations/hu.tsx) translations. Here you get [the file](https://github.com/FreemapSlovakia/freemap-v3-react/files/4008479/hu_tsx.zip).

Cheers

Gábor

**Comment by zdila** [comment]
Thank you Gábor for the translation update.

I plan to improve / add some features before deploying to production. I expect deploy in following days or weeks.

**Comment by zdila** [comment]
Hi @debyos. If you have a time and will then you can update the translations again. To make it easier you can dirctly edit the file [here on github](https://github.com/FreemapSlovakia/freemap-v3-react/edit/master/src/translations/hu.tsx) which will create a pull request that I can merge with single click.

Thank you!
