### ISSUE TITLE
HU translation updated

### ISSUE THREAD

**Issue by debyos** [FreemapSlovakia/freemap-v3-react#492]
Hi,

I have [updated the HU translation on a fork](https://github.com/FreemapSlovakia/freemap-v3-react/compare/master...debyos:patch-1#diff-772c710d6a5c76f25e0dbee24da6ada6) but I don't want to create a Pull request, because an error remained in it and I don't know how I could edit it again.

[Line 82 ConvertToMeasurment has become accidentally ToMeasurement]

Sorry,

Gábor

**Comment by zdila** [comment]
You have probably modified that key by accident. You were able to fix it but I did it and merged to `master`. Thanks!
