### ISSUE TITLE
2h 60min

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#495]
[trafil som](https://www.freemap.sk/?map=13/48.172268/17.158756&layers=O&tool=route-planner&points=48.919792/19.605103,48.155207/17.114296&transport=car) krásne zaokrúhľovanie :)
![image](https://user-images.githubusercontent.com/3583700/72436046-d15bbf00-379f-11ea-8744-b6cfd7396f5e.png)

**Comment by zdila** [comment]
Prestupna hodina.
