### ISSUE TITLE
Automatické zapnutie vrstvy Názvy (Auto)

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#498]
Keď zapnem zobrazovanie vrstiev Strava (Cyklojazdy), Strava (beh), Strava (Vodné aktivity), tak sa zapne aj vrstva Názvy (auto) a nedá sa vypnúť pokiaľ je jedna z horeuvedených vrstiev zapnutá.

**Comment by seg-on** [comment]
Oprava.
Strava (Cyklojazdy) zapína vrstvu Názvy (auto)
Strava (beh) zapína vrstvu Názvy (turistika)
Strava (Vodné aktivity) zapína vrstvu Názvy (cyklo)

**Comment by zdila** [comment]
Vdaka za report!
