### ISSUE TITLE
zobrazit legendu mapy

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#5]

**Comment by petervojtek** [comment]
namet -- zobrazovat polozky legendy priamo na mape

**Comment by tjamecny** [comment]
Na starom FM sa legenda načítava z [http://old.freemap.sk/?c=core.map.legend](url). Navrhnite si JSON formát, a naimplementujem to v API. Aktuálne legenda vyzerá takto:

![legenda_fm_old](https://user-images.githubusercontent.com/16599347/33146274-ce20e1bc-cfc3-11e7-8174-f5ec6025ebc9.png)

Neskôr sa bude obsah legendy aktualizovať.

**Comment by zdila** [comment]
Aka je vyhoda mat to v API? Ak to nepotrebujeme inde ako vo webappke, tak by som to dal priamo do nej.

**Comment by tjamecny** [comment]
Nepozeral som aktuálny kód, ale mám pocit, že obsah sa generuje automaticky z DB (asi z tabuľky pre POI kategórie/podkategórie). Do budúcnosti ale plánujem presun renderovania POI na DiSK klienta, takže kľudne to môžeš pripraviť ako obsah priamo vo webappke (stačí prvé dva záznamy, zvyšok už doplním ja). Ikonky chceš mať tiež priamo vo webappke, alebo ich budeš len referencovať (buď z aktuálneho umiestnenia, alebo ich skopírujem na nejaké logickejšie umiestnenie)?

**Comment by zdila** [comment]
> Ikonky chceš mať tiež priamo vo webappke

ano, ak ich inde netreba

**Comment by zdila** [comment]
Pozrite tiez #274
