### ISSUE TITLE
pridat wizard na embednutie freemapu do vlastnej stranky

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-v3-react#50]
Wizard:

* default pozicia a typ mapy
* velkost mapy
* ci mapa ma mat prepinac typu
* pridanie bodu do mapy (neskor viacero objektov - anotovana mapa - inspiracia z umap)

Sucansa verzia je na http://embed2.freemap.sk/wizard.html

**Comment by petervojtek** [comment]
rozmyslam nad alternativami ako spravit ten wizard.
jedna moznost je separatny komponent (mimo Main), ktory bude vyzerat podobne ako stary embed wizard.

druha moznost je wizard v popupe nad Mainom a mame aspon dve moznosti:
* v popupe bude druha leaflet mapa
* v popupe bude mapa embednuta cez iframe /v iframe src vlastne bude vysledok wizardu/ (pripomina to rekurziu :) -- ale tu by sme museli zrejme pouzit `window.parent.postMessage` a `window.addEventListener` aby sme dokazali spravit nastavovanie markeru.

**Comment by zdila** [comment]
Pridam, ze ked budeme mat niektore tooly v URL (napr route planner) tak embed mapa by mohla obsahovat aj vysledok daneho toolu (naplanovanu cestu).

> ale tu by sme museli zrejme pouzit window.parent.postMessage a window.addEventListener aby sme dokazali spravit nastavovanie markeru.

tie parametre budu prave v tom URL

iframe riesenie je podla mna ok.

**Comment by petervojtek** [comment]
> tie parametre budu prave v tom URL

skusim prejst cez pripady pouzitia z pohladu z wizard popupu (ktory je parent iframu):

* zmena velkosti iframu -- staci nam menit iframe width a height z popupu
* posun mapy -- deje sa cele len v iframe, parent len na zaver zoberie aktualnu src url iframu
* kliknutie na tlacidlo pridat marker (ktore je v popupe) -- moze to fungovat tak, ze z popupu zmenime iframe src aby bol marker v strede (prilepime do iframe src nieco ako `marker=<position>`
* ako posunut marker -- iframe src leaflet musi vediet, ze je mozne marker posunut (lebo vysledny produkt uz posun markeru umoznovat nebude) -- mozno mozeme vo wizarde dat do iframe src `&wizard=true` a tym bude iframe apka vediet ze sa moze marker posuvat. iframe si sam updatne url
* zmazat marker -- kliknutie na na marker zobrazi leaflet popup s moznostou zmazat (iba ak je `&wizard=true`). iframe si sam updatne url

**Comment by zdila** [comment]
funkciu pridavania markeru by som teraz asi neriesil. raz bude funkcia anotacie mapy (co zahrna aj jeden bod) a potom to budes vediet zdielat cele. tak ako to riesi umap :-)

**Comment by petervojtek** [comment]
este jedna vec na diskusiu -- neviem sa rozhodnut ci je lepsie ked embedovatelnu verziu bude servirovat vlatny top-level komponent (napr. s nazvom `Embed`), nez keby sme mali do `Main`-u zavadzat if-y v style `if !embedded zobraz horne menu`.

nevyhoda vlastneho komponentu `Embed` je ak ho chceme zaroven pouzit na tvorbu jeho samotneho cez iframe, tak budeme v nom mat ten isty kod co Main-e co sa tyka updatu URL po posune mapy (posun mapy v Embed chceme reflektovat v url len preto, aby sme vyslednu url vedeli zobrat z iframe src a ponuknut pouzivatelovi ako vysledok wizardu). 
tiez ked to bude vlastny komponent `Embed`, tak nanho rychlejsie zabudneme a nechtiac ho casom rozbijeme zmenami inde. keby bol embed layout cez Main, tak je to viac na ociach.

**Comment by petervojtek** [comment]
zistit kto pouziva stare embednute freemap mapy -- idealne by sme im mali zabezpecit transparentny prechod na next.freemap.sk

**Comment by tjamecny** [comment]
Zoznam sa dá nájsť na http://wiki.freemap.sk/EmbeddedFreemapRef , len určite nie je kompletný. Minimálne sa dá použiť na kontrolu, či compatibility vrstva funguje na 100%.

**Comment by petervojtek** [comment]
zakladna verzia spravena v ramci a8ba700 (#143):

<img width="753" alt="screen shot 2017-06-21 at 11 25 21 am" src="https://user-images.githubusercontent.com/225506/27377141-6a83511c-5674-11e7-84fa-4c2f667fecec.png">
