### ISSUE TITLE
Flag or automatically eliminate duplicates of photos

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#508]
There are many duplicate images in "the map" and this lowers its usability, because not only it takes time to page through a set of images, but also eats bandwidth/data credit used when downloading. It would be great to have some kind of mechanism that would allow removing such images and/or to prevent uploading dupes in the first place. Apparently one of the key issues is how to identify them - as a first approximation I would filter by EXIF data - if available - in particular the coordinates. Another parameter that comes to mind is the file size.

**Comment by zdila** [comment]
I've written [tool](https://github.com/FreemapSlovakia/freemap-gallery-dupe-removal) for manual duplicate removal based on GPS coordinates and have removed ~10k photos.

**Comment by alexanderzatko** [comment]
skvela sprava. dakujem.
