### ISSUE TITLE
na mobiloch vypustiť export mapy

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#510]
na mobilných zariadeniach vypustiť z menu možnosť export mapy (alebo to nejak zakázať, zmeniť na popis možnosti).

dosť to zahulí mobil ak na to omylom kliknem.

**Comment by zdila** [comment]
ako sa to da spustit omylom? na to treba aspon 3 kliky. a ako to moze zahulit mobil?

**Comment by zdila** [comment]
Bez reakcie.
