### ISSUE TITLE
fotky - filter - bez tagov

### ISSUE THREAD

**Issue by kaylesk** [FreemapSlovakia/freemap-v3-react#516]
Bolo by možné pridať do filtra položku "bez tagov", "žiadny tag" alebo niečo podobné. Zobrazilo by iba fotky, čo nemajú priradený tag. Tie čo nejaký majú nebudú vidieť.
Takto nejako by to mohlo vyzerať (alebo aj na konci ten text, nemusí byť na začiatku).
![obrázok](https://user-images.githubusercontent.com/8353866/81169102-8d800600-8f98-11ea-8cb3-46ff2ccfbbe3.png)

A ako toto píšem si uvedomujem, či nebude ten prázdny riadok (bez filtra) mätúci. Označiť ho ako  "všetky fotky"?

ďakovalo

**Comment by zdila** [comment]
Chces pridavat tagy?

Inac tu su nejake dalsie tipy na filtre: #170

**Comment by kaylesk** [comment]
Vidíš medzi uzavretými som nepozeral. A áno, občas keď mám náladu obklikávam foto a keď sa mi zdá vhodné, tak pridám tag.
