### ISSUE TITLE
viac faviconov ikonov

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#518]
[favicon generator](https://realfavicongenerator.net/favicon_checker?protocol=https&site=www.freemap.sk#.XsLOFBbgrr1) ukazuje zopár chýb, najmä [microsoft](https://webdesign.tutsplus.com/tutorials/how-to-add-windows-tiles-to-your-website--cms-23099) a iOS

**Comment by zdila** [comment]
> The mask icon for Safari pinned tabs is absent

nemam svg logo.
