### ISSUE TITLE
Vyhľadávač trás prehodí Štart a bod č. 1

### ISSUE THREAD

**Issue by talbotsk** [FreemapSlovakia/freemap-v3-react#519]
Vyhľadávač trás prehodí Štart a bod č. 1 pri naplánovaní troch a viacerých bodov trasy. Napr.:

1. kliknem do mapy a vyberiem Štart,
2. kliknem do mapy a vyberiem Cieľ,
3. kliknem do mapy a vyberiem nový Cieľ. Z predchádzajúceho Cieľa by sa mal stať bod č. 1, ale stane sa z neho Štart a predchádzajúci Štart sa zmení na bod č. 1. To je podľa mňa chyba.

**Comment by zdila** [comment]
Funguje to spravne:

![image](https://user-images.githubusercontent.com/636095/82529618-b5946b00-9b3b-11ea-93e2-cf41e4570c38.png)

Posli viac detailov ak ti to neide.

**Comment by tjamecny** [comment]
Po novom načítaní stránky (alebo CTRL+F5) to funguje správne (body klikané z ľavého horného rohu do pravého dolného rohu):
![obrázok](https://user-images.githubusercontent.com/16599347/82530138-e923c500-9b3c-11ea-81c7-5d518081864b.png)

Potom kliknem na tlačítko "Zmazať [Del]" a naklikám body v rovnakom poradí:
![obrázok](https://user-images.githubusercontent.com/16599347/82530207-1b352700-9b3d-11ea-995d-405751ace2bf.png)

Druhý bod už vymení pozície štartu a cieľa:
![obrázok](https://user-images.githubusercontent.com/16599347/82530244-2e47f700-9b3d-11ea-82eb-ef7e0a97ea9f.png)

A tretí už len posunie cieľ na novú pozíciu, čo je OK:
![obrázok](https://user-images.githubusercontent.com/16599347/82530305-4fa8e300-9b3d-11ea-80ac-9d32f501852d.png)

Takže tento problém má niečo spoločné s nedostatočným mazaním predchádzajúceho hľadania.
