### ISSUE TITLE
funkcia spustenia editora vyrezu mapy

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-v3-react#52]
JOSM remote control, iD, ...

**Comment by petervojtek** [comment]
navrhoval by som do Nastaveni dal prepinac "Expert mode" (podobne ako ma josm), a funkcie ako tato sa zobrazia iba v expert mode.

**Comment by zdila** [comment]
som za expert mode. to by mohlo naviac pridat aj dalsie vrstvy map -  minimalne OSM mapnik
