### ISSUE TITLE
Add undo/redo button and delete waypoint in route finder

### ISSUE THREAD

**Issue by edgarbilliet** [FreemapSlovakia/freemap-v3-react#520]
Loving this website. Especially the combo Strava Heatmap - Route building.

It would be very handy though to have a undo/redo button, as well as a delete waypoint function when drawing a route. If I accidentally click the map now, it adds a new finish point. Not very convenient when zoomed in a 100km away from your meant-to-be finish point.

Other suggestions:
- Create manual routing option between 2 waypoints. Currently there is no way back when converted to 'drawing'

- Add google streetview option, even when in openstreetmap. Gpxeditor.co.uk can do this for instance.

- Surface analysis. Komoot, maps.openrouteservice.org and now Strava fetch surface information from Openstreetmap.

Otherwise, great job! Seriously considering dropping my strava membership for this route builder

**Comment by zdila** [comment]
Thanks.

Thanks. Please create separate issues for every topic.

Undo and redo is possible since beginning using browser's back and forward actions.
