### ISSUE TITLE
sparava pri nacitavani stranky - Aplikáciu sa nepodarilo spustiť

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#521]
Pri nacitani URL (v novom okne/tabe), ktory som "pred casom" navstivil, napriklad https://www.freemap.sk/#/T/14/48.437999/19.194145 vidam spravu uvedenu nizsie.

Ak urobim refresh sprava zmizne a je nahradena pozadovanou strankou.

> Aplikáciu sa nepodarilo spustiť
Uistite sa, že používate aktuálnu verziu niektorého zo súčasných prehliadačov (Google Chrome, Firefox, Safari, Opera, Edge, Chromium). Praveký Internet Explorer už viac podporovaný nie je.
Problem starting application
Please make sure you are using recent version of some modern browser (Google Chrome, Firefox, Safari, Opera, Edge, Chromium). Ancient Internet Explorer is no more supported.
Hiba történt az alkalmazás elindításánál
Győződjék meg arról, hogy egy modern böngésző (Google Chrome, Firefox, Safari, Opera, Edge, Chromium) friss verzióját használja. Az ősi Internet Explorer már nem támogatott.

**Comment by zdila** [comment]
Prilis malo info pre analyzu chyby. Hodil by sa minimalne vypis z JS konzoly.

**Comment by alexanderzatko** [comment]
Browser: Firefox 76.01
MacOS X
cookies zapnute

konzola ukazuje nasledovne problemy (ak treba, vlepim aj podrobnejsie stack traces):

**errors**

09:01:44.547 Startup error. 
error { target: Window, isTrusted: true, message: "TypeGuardError: validation failed at $.map: expected 'tileFormat' in object", filename: "https://www.freemap.sk/main.f2fdbd19cc2a316c8c74.js", lineno: 1, colno: 5848, error: TypeGuardError, srcElement: Window, eventPhase: 0, bubbles: true, … }
www.freemap.sk:25:17

09:01:44.547 Application error: 
Object { kind: "global", message: "TypeGuardError: validation failed at $.map: expected 'tileFormat' in object", filename: "https://www.freemap.sk/main.f2fdbd19cc2a316c8c74.js", lineno: 1, colno: 5848, error: TypeGuardError }
main.f2fdbd19cc2a316c8c74.js:1:367187


**warnings**

09:01:44.339 Loading failed for the <script> with source “https://cdn.trackjs.com/agent/v3/latest/t.js”. www.freemap.sk:1:1

09:01:44.356 This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. www.freemap.sk

09:01:44.585 <script> source URI is not allowed in this document: “https://connect.facebook.net/en_US/fbevents.js”. www.freemap.sk:1:1

09:01:44.587 <script> source URI is not allowed in this document: “https://www.google-analytics.com/analytics.js”. www.freemap.sk:59:1

09:02:14.442 Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://dbaef000-76ef-7340-a72c-6f1a12dd5e10/browser-polyfill.js
Source Map URL: browser-polyfill.js.map

09:02:14.531 Source map error: Error: request failed with status 404
Resource URL: https://www.freemap.sk/main.f2fdbd19cc2a316c8c74.js
Source Map URL: main.f2fdbd19cc2a316c8c74.js.map 2

**Comment by zdila** [comment]
Podla hashu na to subore vidim ze pouzivas estenejaku staru nacachovanu verziu. Appka by sa ta mala spytat ci chces aktualizovat. Ten `tileFormat` bol z kodu medzicasom uplne odstraneny.
