### ISSUE TITLE
Google maps and streetview option

### ISSUE THREAD

**Issue by edgarbilliet** [FreemapSlovakia/freemap-v3-react#523]
Is it possible to add a streetview option? Other routing websites have this, such as gpxeditor.co.uk or ridewithgps. Is incredibly useful when plotting routes in unknown areas.

**Comment by zdila** [comment]
You can view current area in various streetview applications. Freemap.sk doesn't plan to integrate streetview on tis own.

![image](https://user-images.githubusercontent.com/636095/89650481-cd6dc680-d8c2-11ea-8ab7-d90d80164aa7.png)
