### ISSUE TITLE
funkcia zistenie GPS suradnic na mape

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-v3-react#53]
* rozne formaty
* asi rozsirenim meraca vysky

inac mozno by sa dali zlucit dokopy meranie vzdialenosti, vysky a zistenie suradnic bodu do jedneto toolu. a mozno aj plochy? - @petervojtek co ty na to?

**Comment by petervojtek** [comment]
to znie dobre -- mohol by to byt nastroj napr. s nazvom Meranie, a ked je aktivny tak sa v hornej liste zobrazia jeho "podnastroje".

**Comment by zdila** [comment]
Este som to nedal pod to spolocne menu - meranie.

**Comment by petervojtek** [comment]
bolo by fajn, keby sa text v tooltipe (lat, lon, ele) dal oznacit (pre ucely copy&paste)

**Comment by zdila** [comment]
> bolo by fajn, keby sa text v tooltipe (lat, lon, ele) dal oznacit (pre ucely copy&paste)

uz zareportovane v #60
