### ISSUE TITLE
Nezobrazuje Strava heatmap (SameSite Cookie)

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#532]
Nezobrazuje sa Strava heatmap.

**Comment by zdila** [comment]
vo firefoxe (este) funguje

v chrome od verzie 85 bohuzial standardne uz nie. ale vies si to "hacknut": https://support.siteimprove.com/hc/en-gb/articles/360007364778-Turning-off-Google-Chrome-SameSite-Cookie-Enforcement

treba aspon upravit tooltip hint
