### ISSUE TITLE
Nezobrazuje trasu vo vyhľadávači trás

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#534]
Neviem či je chyba niekde u mňa, ale Vyhľadávač trás mi nezobrazuje v mape trasu, ale evidentne vyhľadáva lebo výškový profil zobrazí.

https://www.freemap.sk/?map=15/48.754109/17.948720&layers=X&tool=route-planner&points=48.758933/17.935224%2C48.748040/17.958612%2C48.758792/17.935438%2C48.758905/17.935417%2C48.757886/17.937670%2C48.758905/17.935331%2C48.759980/17.941425%2C48.761394/17.949214&transport=foot

![image](https://user-images.githubusercontent.com/19683952/91631005-62517480-e9d6-11ea-8b95-1a3494d1dd0b.png)

**Comment by zdila** [comment]
A toto si si nahodou nevypol?

![image](https://user-images.githubusercontent.com/636095/91644975-69619c80-ea41-11ea-8433-3708e0180aa0.png)

**Comment by seg-on** [comment]
hej, mal som to vypnuté. zaujímavé že na dvoch PC som to mal vypnuté.
díki. možno by stálo za to to vždy aktivovať po zapnutí funkcie vyhľadávania či podobne.
