### ISSUE TITLE
Lesné cesty NLC - chýbajú prázdne dlaždice

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#536]
Prázdne dlaždice sú asi odstránené a potom sa na ich miestach zobrazuje X
![image](https://user-images.githubusercontent.com/19683952/93855612-0e296f80-fcb8-11ea-877e-75c4897f9335.png)

**Comment by zdila** [comment]
skus prosim napisat skript ktory ich vypocita

**Comment by zdila** [comment]
credits @seg-on
