### ISSUE TITLE
Problem s prihlasovanim

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#537]
**Na MacOS v Chrome a Safari sa mi nedari prihlasit cez google.**

1. v otvorenom tabe som prihlaseny do google s uctom x
2. otvorim freemap v novom tabe a skusam sa prihlasit pouzitim google login - s uctom x.
3. prihlasovanie vyzera ze prebehne ok, ale po tom co zmizne prihlasovacia obrazovka nie som prhlaseny. Zobrazi sa hlaska "Nepodarilo sa prihlásiť."

pripajam log z Chrome konzoly

[www.freemap.sk-1602007999174.log](https://github.com/FreemapSlovakia/freemap-v3-react/files/5336113/www.freemap.sk-1602007999174.log)

**Na MacOS v Chrome a Safari sa mi nedari prihlasit cez facebook.**

1. kliknem na "Prihlasit sa s pomocou Facebooku"
2. otvori sa nove okno v ktorom vidim pripojenu chybovu hlasku.

<img width="712" alt="Screenshot 2020-10-06 at 19 30 33" src="https://user-images.githubusercontent.com/3430677/95248303-65325700-0817-11eb-8180-c25961840027.png">

**Comment by zdila** [comment]
> pripajam log z Chrome konzoly

to vyzera na error z gmail auth externej js kniznice kedze je anonymizovany

skusal som prihlasenie aj v novom profile ide mi. aj som skusil iny ucet.

skus pls napr FF, alebo novy chrome profil.

> Na MacOS v Chrome a Safari sa mi nedari prihlasit cez facebook.

Vdaka za info. Pozeram ze app bola v dev mode a slo prihlasit asi iba mne kedze som admin. Divne ze to doteraz nikto nereportoval.

**Comment by alexanderzatko** [comment]
re. goole login: Vo FF sa mi dari prihlasit a nakoniec aj v Safari. 

V Chrome sa mi podarilo prihlasit len ak sa odhlasim z google a v prepinaci profilu zvolim "guest". Potom sa mozem prihlasit do freemapu z google uctom.

**Comment by zdila** [comment]
@alexanderzatko stale mas tento problem?

**Comment by alexanderzatko** [comment]
1. v Safari som sa prihlasil cez facebook s adresou sano@strings.net, co je adresa mojho existujuceho konta, ktore uz na freemap.sk pouzivam roky. Predpokladal som, ze novo pridana identita (vytvorena s FB uctom) bude automaticky priradena k mojmu existujucemu uctu (kedze maju rovnaky email), ale nie je to tak - po prihlaseni cez FB vidim reklamy., takze to vyzera ako keby mi bol vytvoreny na freemap novy ucet.
2. Chrome -  ked som odhlaseny a skusam sa prihlasit cez google ucet, ktory ma inu email adresu ako je ta v mojom registrovanom freemap konte, tak by som ocakaval ze po odobreni googlom-prezentovanych povoleni mi bude vytvoreny na freemap ucet a operacia sa skonci tak, ze som prihlaseny. Toto sa vsak nedeje - po ukonceni Oauth (?) procesu som stale neprihlaseny.

Scenar, kedy mam v google ucet s rovnakou email adresou ako ma moj freemap ucet som neskusal, musel by som si menit email adresu v jednom, alebo druhom.

**Comment by zdila** [comment]
dovolim si zavriet tuto issue. prosim urob zvlast issues pre kazdy sposob prihlasenia. parovanie uctov zatial implementovane nie je (vid. https://github.com/FreemapSlovakia/freemap-v3-react/issues/481).
