### ISSUE TITLE
zakazy do vektorovej mapy

### ISSUE THREAD

**Issue by PertR** [FreemapSlovakia/freemap-v3-react#539]
vsimol som si,ze vo web verzii freemaps.sk su na danej trase zobrazuje zakaz pre biky
vo vektorovej V5 pre locus by sa to tiez hodilo dat "zakazy" ako moznost do temy

**Comment by kaylesk** [comment]
Trocha vedľa, vektor mapa má problémy tu https://github.com/FreemapSlovakia/mapsforge-v5/issues
Ale späť k problému. Vektor mapa (V5) má obmedzenia. V ponuke vrstiev treba zapnúť "Obmedzenia vstupu" a pribudnú od z15 (nevravím že na 100% správne, lebo som to detailne neoveroval a neskúmal rôzne podivné kolízie) značky, označujúce obmedzenia vstupu. Ako napr. zákaz vjazdu všetkým vozidlám (vehicle), motorovým vozidlám (motorvehicle), cyklistom (bicycle) a aj chodcom (foot). Všeobecný access=no sú červené krížiky.
Mimochodom, mierny offtopic, keď sa na výbere témy (ponuka "Mapové motívy") dlhšie podrží prst na názve freemapV5, tak sa zobrazí ponuka a je tam aj legenda k mapke.
![Screenshot_20201106-070138_Locus_Map](https://user-images.githubusercontent.com/8353866/98331981-09b5dd80-1ffe-11eb-90c0-e5f632ab5e65.jpg)
