### ISSUE TITLE
funkcia zobrazenia blizkych objektov v okoli miesta kliknutia do mapy

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-v3-react#54]

**Comment by MichalPP** [comment]
http://www.oma.sk/api je vyriešené, rovnako ako zobraziť kategóriu vo viewporte, načo duplikovať?

**Comment by zdila** [comment]
> načo duplikovať?

nerozumiem co by sa tu malo duplikovat. to api je backend a my tu riesime frontend.

**Comment by MichalPP** [comment]
to api funguje, vracia čo treba. backend je hotový, len dorobiť frontend.

**Comment by zdila** [comment]
duplicated by #93
