### ISSUE TITLE
Zobrazenie clanku wikipedie zlyha ak neobsahuje obrazok

### ISSUE THREAD

**Issue by aceman444** [FreemapSlovakia/freemap-v3-react#542]
Po zobrazeni bodov Wikipedie a kliknuti na "Nitriansky mestský park" (https://www.openstreetmap.org/way/34580856) dostanem namiesto clanku v bubline na pravej strane stranky bublinu s chybou:
"Chyba načítania: validation failed at data.query.pages.565093: expected 'thumbnail' in object, found: { pageid: 565093, ns: 0, title: 'Nitriansky mestský park', extract: '<p><b>Mestský park</b> sa nachádza ... "

**Comment by zdila** [comment]
vdaka za report

**Comment by aceman444** [comment]
Dakujem, funguje:)
Malo to byt nahlasene v inom projekte?

**Comment by zdila** [comment]
> Malo to byt nahlasene v inom projekte?

Ano, preto som to premiestnil sem.

**Comment by aceman444** [comment]
OK, dam pozor :)
