### ISSUE TITLE
zmenšené logo na NEXT

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#544]
Neivem či je to cieľom ale vo vývojovej verzii je zmenšené logo freemap.
![image](https://user-images.githubusercontent.com/19683952/102046149-fe16bd00-3dda-11eb-8008-776beaecfea1.png)
![image](https://user-images.githubusercontent.com/19683952/102046179-1090f680-3ddb-11eb-84ec-633f5c5f9b14.png)
Príde mi v tejto zmenšenej verzií horšie čitateľné

**Comment by zdila** [comment]
je to cielom
