### ISSUE TITLE
Obrázok sa nezobrazí pri nahrávaní (ale nahrá sa)

### ISSUE THREAD

**Issue by pdragun** [FreemapSlovakia/freemap-v3-react#550]
Ahoj. Pri nahrávaní obrázku, po pridaní obrázku sa nezobrazí väčší vložený obrázok (väčší, t. j. viac ako 844 kB). Stále sa len točí "loader", ak kliknem uložiť obrázok sa správne uloží a všetko je v poriadku. K tej veľkosti: 844 kB - mi nezobrazilo, 75,5 kB mi zobrazilo.
Ubuntu, Firefox, Chromium, stránka: freemap.sk

Vďaka

**Comment by zdila** [comment]
Mne zobrazi aj 4MB obrazky. Zozdielaj niekam original obrazok ktory ti neide aby som vyskusal.

**Comment by pdragun** [comment]
Tieto dva:
https://photos.app.goo.gl/v5UZeQepiE1NUuJr8
https://photos.app.goo.gl/1V1NcVQFzcofP6Mx8
Oba obrázky tam už sú: 
https://backend.freemap.sk/gallery/pictures/282379/image
https://backend.freemap.sk/gallery/pictures/282380/image

**Comment by zdila** [comment]
fixed in c5d5eb1

**Comment by pdragun** [comment]
Ďakujem

**Comment by zdila** [comment]
vdaka za nahlasenie
