### ISSUE TITLE
When displaying ATM from the POI toolbox, show bank name

### ISSUE THREAD

**Issue by Zaijo** [FreemapSlovakia/freemap-v3-react#551]
Currently the tooltip shows useless: "Bankomat" title.

![Image 28-12-2020 at 18 21](https://user-images.githubusercontent.com/1964908/103231980-8d72b300-4939-11eb-98f6-da811169357f.jpg)

**Comment by Zaijo** [comment]
I'm also willing to implement this, but I'll use some help.

**Comment by zdila** [comment]
deployed on https://next.freemap.sk
