### ISSUE TITLE
Mark cathedrals as churches

### ISSUE THREAD

**Issue by Zaijo** [FreemapSlovakia/freemap-v3-react#552]
This cathedral will not be marked when selecting POI "Kostol" i.e. "Church" https://www.openstreetmap.org/way/84590208

**Comment by zdila** [comment]
What about temples? (just asking, I have no clear opinion)

**Comment by Zaijo** [comment]
If you mean `building=temple` it doesn't seem very relevant for Slovakia. Even those that matched are probably churches too.

https://overpass-turbo.eu/s/11IK

Considering various religions could be a different issue.

**Comment by zdila** [comment]
OK. BTW freemap focus not only on Slovakia.

**Comment by Zaijo** [comment]
The cross sign on the markers definitely means christian religions, which moves the `building=temple` "out of scope" of this issue.

**Comment by zdila** [comment]
deployed on https://next.freemap.sk
