### ISSUE TITLE
OpenTopoMap

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#556]
Mapa OpenTopoMap bola odstránená úmyselne alebo nedopatrením?

**Comment by zdila** [comment]
![image](https://user-images.githubusercontent.com/636095/105614540-5b366300-5dca-11eb-9420-92e59e73f4fe.png)

**Comment by seg-on** [comment]
aha nič je tam len pod inou klávesovou skratkou a prehliadol som ju v menu
