### ISSUE TITLE
mtbmap.cz

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#557]
Nedoťahuje dlaždice a nefunguje klávesová skratka _Shift + 1_

**Comment by zdila** [comment]
nedotahovanie je uz problem servera mtbmap.cz. skus reloadnut stranku.

**Comment by seg-on** [comment]
tá klávesová skratka nefunguje stále. _Shift + 2_ a _Shift + 3_ idú ale _Shift + 1_ nespraví nič. Keby nejde ani jedna tak to chápem ale takto je to divné.

**Comment by zdila** [comment]
Opravene neznamena nasadene. Ak si to rozbehnes lokalne cerstve z gitu tak ti to uz pojde.

**Comment by seg-on** [comment]
aha. ja že keď si napísal skús reloadnuť stránku tak už je to aj nasadené :)
už to funguje ;)
