### ISSUE TITLE
Nastroj 'info o POI na tomto bode'

### ISSUE THREAD

**Issue by miro-janosik** [FreemapSlovakia/freemap-v3-react#558]
Chyba mi nastroj, ktorym by som si kliknutim pozrel otvaracie hodiny obchodu, detaily muzea, podniku, zastavky atd.
Presne taky nastroj ako je "otaznicek" ktory je na osm.org - zobrazi to na co som klikol a zoznam atributov toho bodu/arey.

Mohlo by to byt pod 'detaily na mape'.

**Comment by zdila** [comment]
cca duplikuje #93, #54, #159
