### ISSUE TITLE
Wikipedia na mape zblbne po chvíľke

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#559]
pri prezeraní tagow Wikipedia dôjde po  asi 3ťom otvoení náhľadu k chybe
"Chyba načítania: Request failed with status code 404"
Súčasne som to skúšal na next a na stabilnej verzi a keď ktomu došlo na jednej tak som skúšal druhú  a tam sa objavila chybový hláška:
"Chyba načítania: Maximum call stack size exceeded"
A "Wikipedia" na mape prestane fungovať.

**Comment by seg-on** [comment]
Problém stále pretrváva.
![image](https://user-images.githubusercontent.com/19683952/107183884-dcebda80-69df-11eb-8478-8c1206ddc92f.png)

**Comment by zdila** [comment]
nasadil som to len na www, nie na next.

naviac ak na githube zavriem issue, tak neznamena ze je nasadena. pre overenie si je nutne to rozbehat lokalne, alebo pockat na announceent na mailing liste.
