### ISSUE TITLE
maly displej: presunut tlacidlo Zavriet (nastroj) napravo do toho isteho riadku ako je nazov nastroja

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#56]
teraz Zavriet zbytocne zabera jeden riadok, mozeme si dovolit dat nazov nastroja a Zavriet na jeden riadok

<img width="380" alt="screen shot 2017-03-15 at 7 43 55 pm" src="https://cloud.githubusercontent.com/assets/225506/23965309/d6ba3bde-09b7-11e7-97b0-2295c6349756.png">

**Comment by petervojtek** [comment]
Martin @zdila , navrhujem taketo zatvaranie nastrojov -- ma to nasledovne vlastnosti:
* kod je jednoduchy a rovnaky pre mobil aj velky displej
* z popisu je zrejme aky nastroj je aktivny (aj ked nie je tam ta pekna ikonka nastroja)
* na mobile to nezabera vela miesta a velkom displeji to vyzera celkom obstojne



<img width="335" alt="screen shot 2017-03-16 at 2 49 37 pm" src="https://cloud.githubusercontent.com/assets/225506/23999255/15d1b400-0a58-11e7-94a8-09626b98e857.png">

<img width="955" alt="screen shot 2017-03-16 at 2 49 28 pm" src="https://cloud.githubusercontent.com/assets/225506/23999260/19ca16e2-0a58-11e7-9395-601daefaf236.png">

**Comment by zdila** [comment]
Skusil by som to nechat ako to je, len "Zavriet..." by som nedal ako menu item, ale ako tlacitko. Podla mna to aj je semanticky zle ze "Zavriet..." je menu item. Tym padom by to v mobile nerenderovalo do zvlast riadku.

**Comment by petervojtek** [comment]
> Podla mna to aj je semanticky zle ze "Zavriet..." je menu item. Tym padom by to v mobile nerenderovalo do zvlast riadku.

asi ti nerozumiem -- prvy screenshot je z (emulovaneho) mobilu a je to na zvlast riadku.

inak ked je nazov nastroja uvedeny tak ako je (Navbar.Text) tak je to vlastne neintuitivne, lebo vyzera to takmer identicky ako NavItem, lenze neda sa na to kliknut.

**Comment by zdila** [comment]
Pozri moju zmenu. Musel som odstranit tie specialne styly lebo ak obrazovka nebola celkom uzka, tak buttoun groups neboli vertikalne vycentrovane. To ze sa pri uzkej obrazovke potom lepia na seba treba poriesit nejako inac.

To ze Navbar.Text vyzera divne je chyba stylovania. Mozno skusit ten text dat boldom, nejake h1 / b / strong?

Ale dalsi problem je ze my tie custom menu zabalujeme do `div` co nie je spravne, lebo to vtrobi html typu `<ul><li>...</li><div>...</div>`. Toto sa mi vsak zatial nepodarilo vyriesit ale vie sa o tom ;-) https://github.com/facebook/react/issues/2127

**Comment by zdila** [comment]
dal som to bold

**Comment by petervojtek** [comment]
rozumiem, ale teraz vznika situacia ktorej som sa chcel vyhnut -- ze nechtiac si to cele zavries ked kliknes trochu mimo dropdownu. a tiez je ten nazov nastroja skaredo pri lavom okraji.

<img width="337" alt="screen shot 2017-03-16 at 3 54 51 pm" src="https://cloud.githubusercontent.com/assets/225506/24002412/f26f545a-0a60-11e7-8ebd-889e2ce5349d.png">

**Comment by zdila** [comment]
> ze nechtiac si to cele zavries ked kliknes trochu mimo dropdownu

podla mna su tie plochy dost velke na to aby si sa netrafil. S dropdown je skor problem ze ho orezava: 
![image](https://cloud.githubusercontent.com/assets/636095/24002886/2ced932a-0a62-11e7-8dc6-4ce3a6781caf.png)

> a tiez je ten nazov nastroja skaredo pri lavom okraji.

To ze je nazov skaredo treba zistit preco. Ci nie koli tomu nevalidnemu HTML. Myslim ze bootstrap by mal mat taketo veci davno vychytane a pisat vlastne CSS by malo byt az v krajinom pripade.

**Comment by petervojtek** [comment]
ten aktualny dizajn vyzera fajn na velkom displeji, ale na mobile je to odpudive.. prve dva riadky su poloprazdne a potom v dalsich dvoch riadkoch je natlacenych vela tlacidiel.

dalsi navrh:
* dat nazov nastroja dat do prveho riadku k logu (ked to premenujeme iba na "Planovac". aj tak chceme skratit nazvy nastrojov).
* tlacidlo Zavriet bude na vlastnom (poslednom) riadku, cim zaroven vytvori priestor kam sa rozbali dropdown menu.

**Comment by zdila** [comment]
OK, skus. Inac ja beriem  ten portal ze je primarne pre desktopy (ale pekny by mal byt aj na mobiloch).

**Comment by petervojtek** [comment]
ok, tu je to: ac7de0.

vyzera to podla mna celkom znesitelne. tlacidlo Zrusit nastroj som ale z nudze spravil z NavItem, lebo Button nebol spravne centrovany a nechcel som sa v tom velmi vrtat.

<img width="342" alt="screen shot 2017-03-16 at 4 51 52 pm" src="https://cloud.githubusercontent.com/assets/225506/24005288/e08ea42c-0a68-11e7-892c-20d427e89969.png">



> ten portal ze je primarne pre desktopy

taky jeden portal uz mame hotovy, aktualne bezi na freemap.sk :)
