### ISSUE TITLE
Posun spodného panelu pri prepínaní

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#561]
Pri prepnutí na Ortofotomozaiku sa posunie celý panel s tlačítkami. pripprepnutí na OSM alebo Xvrstvu sa vráti späť.

**Comment by seg-on** [comment]
To isté platí pre vrstvu z Lietadla.

**Comment by tjamecny** [comment]
Posun je spôsobený zobrazením/skrytím tlačítka legendy mapy v pravom dolnom rohu pri OSM/X vrstvách.
