### ISSUE TITLE
Pridať možnosť úplne vypnúť podkladovú mapu

### ISSUE THREAD

**Issue by jose1711** [FreemapSlovakia/freemap-v3-react#567]
Niekedy by sa zišlo mať možnosť (napr. pri študovaní reliéfnej DMR5 - aj keď táto momentálne nie je dostupná ako samostatná vrstva) úplne vypnúť podkladovú mapu a nechať si zobrazovať len vrstvu/y nad ňou.

**Comment by zdila** [comment]
DMR5 bolo ako samostatna vrstva medzicasom odstranena :-)
