### ISSUE TITLE
robustnejsie natiahnutie ulozenych nastaveni

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#57]
je tam takyto potencialne zradny scenar:

ked nahodou premenujeme nejaky nastroj (napr. z `route-planner` na `route-planner-2`), tak aktualne pouzivatel [skonci s hornou listou bez tlacidiel](https://github.com/FreemapSlovakia/freemap-v3-react/blob/master/src/components/Main.js#L143), co nechceme.

**Comment by zdila** [comment]
premenovanie nastroja som ostertil, ale treba to spravit genericky, ako pises

**Comment by petervojtek** [comment]
nejdeme to riesit konceptualne hned, takze zatvarame
