### ISSUE TITLE
Wikipedia - Loading error: validation failed

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#571]
In Firefox on Mac:

1. navigate to https://www.freemap.sk/?map=14/48.613307/19.245729&layers=Xw
2. click the Ocova Letisko wikipedia marker

error is thrown:

<img width="610" alt="Screenshot 2021-03-08 at 09 39 10" src="https://user-images.githubusercontent.com/3430677/110296579-c5aa0800-7ff2-11eb-9594-b93dffe8924b.png">

**Comment by zdila** [comment]
Can't reproduce...

**Comment by alexanderzatko** [comment]
further tested in Safari and Opera on Mac via two different ISPs (one is the O2 mobile network).

Results:

Firefox, Safari - the same problem
Opera, Chrome - works without problems

Tested also on an iPhone with Safari and Firefox and see the same problem
