### ISSUE TITLE
Kreslenie neumerne vytazuje CPU

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#572]
Na Firefox-e na MacOS sposobuje kreslenie neumerne vytazenie CPU. Pocas pridavania alebo presuvania bodov na linii sa zvysuje vyuzitie CPU a moze to vyustit do situacie, ked je nie len tab s freemap neresponzivny, ale aj reakcne doby v inych programoch sa predlzuju.

Kroky veduce k problemu:

Zvol si kreslenie linii a zacni kreslit. Postupne pridavaj body - po niekolkych minutach sa reakcne casy zacnu predlzovat a ventilatory zvysuju frekvenciu. Eventualne prestava aplikacia na prikazy odpovedat.

V Chrome na MacOS tento problem nevidim.

Priklad zlozitejsej  URL, ktora vznikla skonvertovanim najdenej route do kresliaceho modu a nasledne jeho upravovanim: 

https://www.freemap.sk/?map=15/48.486448/19.229035&layers=Xl&line=48.482636/19.238742%2C48.482853/19.238581%2C48.483491/19.237742%2C48.484077/19.237216%2C48.484326/19.236919%2C48.484847/19.236571%2C48.485153/19.236446%2C48.485257/19.236446%2C48.485420/19.236479%2C48.485704/19.236384%2C48.485954/19.236399%2C48.486337/19.236451%2C48.486548/19.236657%2C48.486686/19.237083%2C48.486714/19.237215%2C48.486711/19.237359%2C48.486616/19.238204%2C48.486512/19.238652%2C48.486517/19.239207%2C48.486565/19.239450%2C48.486675/19.239786%2C48.486801/19.240068%2C48.487157/19.240451%2C48.487432/19.240583%2C48.487754/19.240625%2C48.488499/19.240658%2C48.488834/19.240940%2C48.488979/19.241140%2C48.489231/19.241611%2C48.489303/19.241978%2C48.489450/19.242226%2C48.489544/19.242442%2C48.489809/19.242650%2C48.490104/19.242789%2C48.490257/19.242949%2C48.490391/19.243300%2C48.490490/19.243710%2C48.490533/19.244132%2C48.490531/19.244572%2C48.490610/19.244547%2C48.490676/19.244471%2C48.490898/19.244516%2C48.491207/19.244564%2C48.491417/19.244640%2C48.491627/19.244627%2C48.492176/19.244356%2C48.492344/19.244406%2C48.492447/19.244581%2C48.492523/19.244867%2C48.492565/19.245056%2C48.492649/19.245243%2C48.492794/19.245436%2C48.493137/19.245770%2C48.493245/19.245867%2C48.493538/19.246128%2C48.493710/19.246212%2C48.494049/19.246229%2C48.494362/19.246309%2C48.494484/19.246311%2C48.494820/19.246168%2C48.495247/19.246033%2C48.495529/19.245981%2C48.495888/19.245838%2C48.496548/19.245430%2C48.496773/19.245152%2C48.496922/19.245035%2C48.497524/19.244936%2C48.497768/19.244989%2C48.497913/19.244963%2C48.498062/19.244894%2C48.498314/19.244576%2C48.498699/19.243952%2C48.498947/19.243527%2C48.499482/19.242752%2C48.499676/19.242611%2C48.499931/19.242474%2C48.500435/19.242365%2C48.500600/19.242294%2C48.500729/19.242197%2C48.500790/19.242064%2C48.501007/19.241966%2C48.501999/19.241520%2C48.502626/19.241260%2C48.502818/19.240958%2C48.502937/19.240639%2C48.502955/19.240591%2C48.502523/19.240185%2C48.502305/19.239895%2C48.502129/19.239503%2C48.502006/19.239117%2C48.501915/19.238652%2C48.501833/19.238364%2C48.501670/19.238017%2C48.501129/19.237520%2C48.500961/19.237289%2C48.500900/19.237082%2C48.500923/19.236689%2C48.501019/19.236162%2C48.501061/19.235325%2C48.501093/19.234933%2C48.501027/19.232363%2C48.501097/19.231836%2C48.501061/19.231387%2C48.501092/19.230823%2C48.501481/19.229145%2C48.501550/19.227992%2C48.501446/19.227383%2C48.501300/19.226992%2C48.500945/19.225842%2C48.500907/19.225527%2C48.501080/19.224843%2C48.501322/19.224556%2C48.501399/19.224371%2C48.501437/19.222863%2C48.501230/19.222174%2C48.501016/19.221591%2C48.500837/19.221370%2C48.500668/19.221288%2C48.500486/19.221282%2C48.500427/19.221669%2C48.500359/19.221951%2C48.500382/19.222412%2C48.500374/19.222452%2C48.500397/19.222576%2C48.500393/19.222616%2C48.500427/19.222925%2C48.500473/19.223316%2C48.500567/19.223987%2C48.500507/19.224539%2C48.500519/19.224644%2C48.500426/19.225048%2C48.500006/19.225223%2C48.499547/19.225789%2C48.499463/19.225959%2C48.499256/19.226378%2C48.498338/19.227106%2C48.496846/19.229598%2C48.496442/19.230248%2C48.495879/19.231203%2C48.495405/19.231958%2C48.495229/19.232131%2C48.495054/19.232157%2C48.494887/19.231985%2C48.494887/19.231667%2C48.495036/19.231097%2C48.495423/19.229665%2C48.495669/19.228100%2C48.495748/19.227053%2C48.495651/19.226324%2C48.495484/19.225628%2C48.494975/19.224786%2C48.494746/19.224448%2C48.493982/19.223241%2C48.493566/19.222935%2C48.493132/19.222817%2C48.492883/19.222828%2C48.492450/19.223053%2C48.492179/19.223342%2C48.487714/19.228563%2C48.485239/19.232726%2C48.485552/19.235215%2C48.485353/19.236288%2C48.484244/19.237103%2C48.482736/19.238477

**Comment by zdila** [comment]
Neviem zreprodukovat na Firefoxe v Linuxe. CPU je na nula celych nula celych nula do p... ;-). Inac Firefox je moj primarny browser a pouzivam ho aj na vyvoj.

![image](https://user-images.githubusercontent.com/636095/110436186-37965600-80b4-11eb-9838-eb535548ef33.png)

https://www.freemap.sk/?map=14/48.496929/19.232811&layers=X&line=48.487314/19.218559%2C48.487939/19.217744%2C48.488964/19.216671%2C48.490102/19.215513%2C48.491467/19.214783%2C48.492719/19.214311%2C48.493828/19.214097%2C48.494994/19.214225%2C48.495762/19.213796%2C48.496672/19.209377%2C48.495108/19.206802%2C48.493626/19.207060%2C48.492432/19.207661%2C48.490896/19.208734%2C48.488990/19.210536%2C48.487709/19.212424%2C48.487055/19.213797%2C48.486742/19.214870%2C48.486372/19.216801%2C48.486372/19.217659%2C48.486429/19.219075%2C48.486828/19.220105%2C48.487510/19.220534%2C48.488421/19.220877%2C48.490440/19.220791%2C48.492261/19.220577%2C48.493086/19.220534%2C48.494394/19.220405%2C48.495191/19.220448%2C48.496016/19.220319%2C48.497154/19.220362%2C48.499457/19.220319%2C48.500879/19.221564%2C48.503325/19.224653%2C48.503667/19.228129%2C48.504008/19.230231%2C48.503723/19.233321%2C48.503297/19.234479%2C48.502074/19.235252%2C48.499912/19.235252%2C48.499287/19.235123%2C48.498746/19.234822%2C48.497779/19.234265%2C48.496442/19.232763%2C48.494622/19.230875%2C48.493598/19.230703%2C48.492858/19.230746%2C48.491834/19.231261%2C48.490953/19.233106%2C48.490839/19.234565%2C48.490782/19.236453%2C48.491123/19.237397%2C48.491550/19.237783%2C48.492033/19.238169%2C48.492716/19.238513%2C48.493200/19.238598%2C48.493882/19.238770%2C48.496272/19.239414%2C48.496841/19.238084%2C48.497865/19.238727%2C48.498860/19.238513%2C48.499969/19.238427%2C48.501022/19.238770%2C48.502273/19.239800%2C48.503268/19.241473%2C48.503354/19.242374%2C48.503524/19.243748%2C48.503354/19.246665%2C48.502074/19.247738%2C48.498917/19.249412%2C48.498007/19.249497%2C48.497353/19.249497%2C48.496613/19.249454%2C48.495760/19.249240%2C48.495134/19.249154%2C48.494366/19.248682%2C48.492802/19.247524%2C48.491436/19.245764%2C48.489644/19.242846%2C48.488478/19.239929%2C48.488108/19.238212%2C48.487880/19.236668%2C48.487681/19.235166%2C48.487567/19.234050%2C48.487567/19.231862%2C48.487738/19.231089%2C48.488051/19.230145%2C48.488705/19.228815%2C48.489018/19.228558%2C48.489985/19.227614%2C48.490327/19.227442%2C48.490924/19.227313%2C48.491550/19.227270%2C48.492204/19.227228%2C48.492944/19.227313%2C48.493655/19.227528%2C48.494338/19.227700%2C48.495020/19.227742%2C48.495618/19.227742%2C48.496300/19.227657%2C48.497125/19.227442%2C48.497978/19.227185%2C48.498576/19.226756%2C48.499088/19.226284%2C48.499742/19.225640%2C48.500823/19.224610%2C48.501221/19.224310%2C48.502188/19.224610%2C48.503468/19.223237%2C48.503951/19.221649%2C48.504008/19.220877%2C48.503979/19.219461%2C48.503923/19.218260%2C48.503610/19.217273%2C48.503126/19.215213%2C48.502501/19.213582%2C48.501818/19.211909%2C48.501306/19.210622%2C48.500965/19.209935%2C48.500424/19.209206%2C48.499059/19.207232%2C48.497950/19.206030%2C48.497267/19.205558%2C48.495276/19.204486%2C48.493598/19.204185%2C48.492688/19.203971%2C48.489502/19.205558%2C48.488847/19.206202%2C48.488022/19.207017%2C48.487254/19.207876%2C48.486600/19.209034%2C48.485974/19.210278%2C48.485576/19.211180%2C48.485206/19.212681%2C48.485092/19.213540%2C48.485007/19.215256%2C48.485035/19.215942%2C48.485035/19.218646%2C48.485178/19.221778%2C48.485661/19.222250%2C48.485775/19.223580%2C48.485434/19.228515%2C48.485320/19.229244%2C48.484893/19.232420%2C48.485178/19.235852%2C48.485860/19.240358%2C48.486572/19.243061%2C48.488335/19.245721%2C48.488478/19.249025%2C48.487596/19.249626%2C48.486884/19.250356%2C48.486031/19.251943%2C48.486031/19.254089%2C48.488449/19.256749%2C48.490327/19.261083%2C48.491265/19.260096%2C48.491948/19.259838%2C48.492745/19.258422%2C48.493740/19.257736%2C48.494252/19.257521%2C48.495219/19.257564%2C48.496016/19.257779%2C48.496812/19.257950%2C48.497666/19.258894%2C48.497921/19.260353%2C48.498035/19.262971%2C48.496954/19.264558%2C48.495276/19.264430%2C48.494252/19.264644%2C48.493598/19.264644%2C48.492346/19.264988%2C48.490810/19.264601%2C48.489502/19.264644%2C48.488762/19.264001%2C48.488022/19.263486%2C48.487254/19.262928%2C48.486486/19.262113%2C48.485690/19.260697%2C48.485035/19.259538%2C48.484523/19.257264%2C48.484210/19.255505%2C48.483983/19.252887%2C48.483840/19.250227%2C48.483812/19.249197%2C48.483897/19.247738%2C48.483926/19.246494%2C48.483983/19.245292%2C48.484040/19.243533%2C48.484125/19.241602%2C48.484153/19.240358%2C48.484210/19.238856%2C48.484296/19.236968%2C48.484296/19.235681%2C48.484239/19.234694%2C48.484125/19.233321%2C48.483983/19.231905%2C48.483954/19.230746%2C48.483926/19.228644%2C48.483812/19.227571%2C48.483783/19.226498%2C48.483727/19.225039%2C48.483613/19.223452%2C48.483499/19.219890%2C48.483499/19.218174%2C48.483470/19.216414%2C48.483442/19.215256%2C48.483499/19.212553%2C48.483641/19.210922%2C48.483727/19.210321%2C48.484267/19.208905%2C48.484665/19.208605%2C48.485007/19.208133%2C48.485377/19.207189%2C48.486003/19.205988%2C48.488335/19.204142%2C48.490469/19.202469%2C48.491521/19.202469%2C48.492489/19.202469%2C48.493342/19.202555%2C48.494167/19.202641%2C48.496357/19.203027%2C48.498405/19.204357%2C48.499600/19.206073%2C48.501420/19.209163%2C48.503325/19.210965%2C48.504065/19.212724%2C48.504719/19.216114%2C48.505316/19.218259%2C48.505544/19.222036%2C48.505487/19.226198%2C48.505089/19.227142%2C48.505288/19.228343%2C48.505544/19.229116%2C48.505771/19.231089%2C48.505771/19.231948%2C48.505743/19.233621%2C48.505601/19.235466%2C48.505601/19.238255%2C48.505515/19.241173%2C48.505259/19.243876%2C48.505117/19.245850%2C48.504662/19.248124%2C48.504036/19.250098%2C48.503382/19.251686%2C48.501875/19.254003%2C48.500453/19.252029%2C48.499742/19.252029%2C48.498832/19.251986%2C48.497438/19.251729%2C48.495561/19.252115%2C48.494110/19.251171%2C48.493399/19.250441%2C48.492688/19.250012%2C48.491778/19.249755%2C48.490839/19.250398%2C48.490156/19.252201%2C48.490469/19.254089%2C48.491180/19.254174%2C48.492090/19.254303%2C48.492802/19.254217%2C48.494451/19.254003%2C48.495276/19.254046%2C48.495987/19.254089%2C48.497438/19.254561%2C48.499031/19.254990%2C48.500709/19.255462%2C48.502017/19.255719%2C48.503297/19.256191%2C48.504463/19.257865%2C48.504406/19.261083%2C48.503439/19.261469%2C48.501847/19.261898%2C48.500282/19.258894%2C48.499173/19.257736%2C48.498064/19.256792%2C48.496784/19.256492

**Comment by zdila** [comment]
Skus poslat video...

**Comment by alexanderzatko** [comment]
Nainstaloval som fungl novy firefox na druhy Mac a tam je to ok. Takze problem bude asi v niektorych z mojich miliona FF doplnkov. Asi mozme teda toto zatvorit. Pardon. :-)
