### ISSUE TITLE
Reklamy vo Freemape

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#576]
tl;dr - pozri sekciu **Integrácia** dolu, kde je opísané ako túto funkciu implementovať s pomocou [Rovasa](https://rovas.merit.world/)

**Úvod**

Na ostatnom stretnutí v Smižanoch sme sa [dohovorili](https://groups.google.com/g/oz-freemap/c/qms4oGJHuEQ/m/31QQV5p8BAAJ), že skúsime na freemap umiestniť reklamy. Hlavné ciele, ktoré týmto sledujeme sú:

1. získať peniaze pre združenie; tieto môžme použiť na investíciu do hardvéru a iných služieb a produktov, ktoré pomáhajú napĺňať ciele o.z., 
2. zvýšiť záujem verejnosti o účasť na projektoch Freemap, OSM alebo projektoch, ktoré s nimi súvisia.

Aj keď je pomerne jednoduché do aplikácie umiestniť napríklad AdSense reklamy od Googlu čím by bola naplnená požiadavka č. 1, tento prístup má niekoľko nevýhod:

- návštevník nemá možnosť reklamy vypnúť,
- finančný efekt je prevažne diktovaný poskytovateľom reklám (Google),
- návštevníci, ktorí prispievajú do projektu OSM/freemap alebo iných dobrovoľníckych projektov sú "potrestaní" reklamami rovnako ako pasívni konzumenti, ktorí do podobných projektov neprispievajú,
- je nepravdepodobné, že by tento variant mohol motivovať návštevníkov aplikácie pracovať na akomkoľvek dobrovoľníckom projekte,

Tento prístup samozrejme nie je jediný, ktorý by sa dal implementovať. Bol diskutovaný aj model, kde by niektoré typy návštevníkov reklamy nevideli. Napríklad OSM maperi s viac ako X changesetmi, alebo registrovaní používatelia, ktorí pravidelne vkladajú do aplikácie fotky. Aj tento prístup má však problémy. Okrem toho že finančný aspekt je stále v doméne poskytovateľa reklám, je tento prístup diskriminačný (prinajmenšom teoreticky). Neumožňuje totiž iným typom dobrovoľníkov - napríklad Wikipedia editorom alebo FOSS programátorom - bezreklamový prístup, aj keď bez ich práce by projekty Freemap alebo OSM neexistovali.

**NEO**
Portál nabezky.sk na dosiahnutie cieľov opísaných v bode 1 a 2 vyššie už niekoľko zimných sezón testuje "komunitný" ekonomický systém NEO, ktorý okrem iného umožňuje (všetkým typom) dobrovoľníkov odmeňovať sa navzájom vlastnou prácou. V sezóne 2020-21 bolo v portáli predaných za 5 eur viac ako 80 sezónnych pasov, ktoré umožňujú návštevníkom prístup k prémiovému obsahu. Prístup k tomu obsahu je možné získať aj za chrony - menu NEO. Túto možnosť využilo 60 používateľov, ktorí si chrony zarobili za tvorbu obsahu portálu a 11 návštevníkov si ich priamo kúpilo za eurá. Dôležité je aj to, že zavedenie systému nielen že neodradilo "skalných" prispievateľov, ale prilákalo aj používateľov nových. Niektorí dokonca ponúkli pomoc pri prekladaní UI do iných jazykov.

Vzhľadom na tieto fakty je na zváženie, či by nebolo vhodné NEO použiť aj v kontexte projektu Freemap. Nižšie opíšem ako by to mohlo byť vyzerať.

**Integrácia**
[Celková schéma integrácie](https://drive.google.com/file/d/1EpCsBHuCNC7jx3fw2chqKq0Y3tw3JAGN/view?usp=sharing) Pre zobrazenie v originálnom formáte treba súbor .drawio otvoriť v [https://app.diagrams.net/](https://app.diagrams.net/)

_Funkcia z pohľadu používateľa_

1. Pri návšteve freemap.sk, návštevník uvidí reklamný baner servírovaný napríklad cez AdSense. Vedľa banera je link "Odstrániť túto reklamu": <img width="1436" alt="Screenshot 2021-04-07 at 11 16 06" src="https://user-images.githubusercontent.com/3430677/113922897-28581480-97e8-11eb-81b4-f913b051aeb8.png">
2. Po kliknutí na link sa môže návštevník prihlásiť do Freemapu, alebo si v aplikácii vytvoriť účet. Ak sa chce dozvedieť viac o možnosti zarobiť si na prístup bez reklám svojou prácou, klikne na otáznik. <img width="1439" alt="Screenshot 2021-04-07 at 11 16 17" src="https://user-images.githubusercontent.com/3430677/113923469-dcf23600-97e8-11eb-9730-59edb5588982.png">
3. Informácia o tom, ako získať prístup bez reklám svojou prácou. Je plánovaný aj plugin do JOSM, ktorý umožní editorom zarábať chrony bez toho aby museli vypĺňať pracovný výkaz. Takto je to urobené aj v nabezky.sk. Akonáhle bude plugin naprogramovaný, info text môže byť v tom zmysle upravený. <img width="1435" alt="Screenshot 2021-04-07 at 11 16 28" src="https://user-images.githubusercontent.com/3430677/113923830-4f631600-97e9-11eb-82c1-cbc8de5d714a.png">
4. Po prečítaní si textu o Rovasi a chronoch sa môže vrátiť späť na predošlú stránku, kde sa môže prihlásiť do Freemapu, alebo si tam vytvoriť účet. <img width="503" alt="Screenshot 2021-04-07 at 11 40 10" src="https://user-images.githubusercontent.com/3430677/113924767-7b32cb80-97ea-11eb-935d-93c47ebe6600.png">
5. Po prihlásení sa/vytvorení účtu je používateľ presmerovaný do Rovasa na link [https://dev.merit.world/rewpro?paytype=project&recipient=24130&callbackurl=https://freemap.sk](https://dev.merit.world/rewpro?paytype=project&recipient=24130&callbackurl=https://freemap.sk). Otvorí sa stránka, kde je možné zaplatiť za bezreklamový prístup.
6. Po ukončení platby (nech sa páči vyskúšať. Je to v sandboxe) Rovas zavolá URL uvedené v parametri callback a pripojí parameter status. Zaplatené eurá sú konvertované na chrony a vložené na Rovas účet uvedený v projekte Freemap. Tieto je možné kedykoľvek vymeniť za eurá.

testovacie čísla kreditiek

> 4242424242424242 	Visa 	Any 3 digits 	Any future date
> 4000056655665556 	Visa (debit) 	Any 3 digits 	Any future date
> 5555555555554444 	Mastercard 	Any 3 digits 	Any future date
> 2223003122003222 	Mastercard (2-series) 	Any 3 digits 	Any future date
> 5200828282828210 	Mastercard (debit) 	Any 3 digits 	Any future date
> 5105105105105100 	Mastercard (prepaid) 	Any 3 digits 	Any future date
> 378282246310005 	American Express 	Any 4 digits 	Any future date

O tom ako používať Rovas je možné sa dočítať na [stránke pravidiel](https://rovas.merit.world/rules).

**Comment by alexanderzatko** [comment]
pripajam koncept reklamy, ktora moze byt zobrazena ak ma pouzivatel zapnuty adblocker.

[rovas_reklama.svg.zip](https://github.com/FreemapSlovakia/freemap-v3-react/files/6884458/rovas_reklama.svg.zip)

**Comment by alexanderzatko** [comment]
nova verzia reklamy ktora ma byt zobrazena ak ma pouzivatel zapnuty adblocker.
[rovas_reklama.svg.zip](https://github.com/FreemapSlovakia/freemap-v3-react/files/6890702/rovas_reklama.svg.zip)

**Comment by zdila** [comment]
vies dat aj verziu kde nebude text prevedeny na krivky? lebo dost obrovske je to SVG.

**Comment by alexanderzatko** [comment]
viem. Musim si nastudovat ako to riesit s fontami v svg. Asi to bude podobne ako pri css

**Comment by zdila** [comment]
ak nepouzivas nejake specialne fonty tak len specifikuj font family a hotovo. netreba ich embedovat.

**Comment by alexanderzatko** [comment]
skusme toto
[rovas_reklama.svg.zip](https://github.com/FreemapSlovakia/freemap-v3-react/files/6891359/rovas_reklama.svg.zip)
