### ISSUE TITLE
Nefunguje vyhľadávanie pre Pešo

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#579]
Pri vyhľadávaní trasy _Pešo_ vyhodí chybu:
Nastala chyba pri hľadaní trasy: Network Error
Iné druhy trasovania fungujú.

Pešo:
https://www.freemap.sk/?map=16/48.683410/17.893295&layers=X&tool=route-planner&points=48.694501/17.884240%2C48.680506/17.896643%2C48.682121/17.906256&transport=foot-osm

S kočíkom:
https://www.freemap.sk/?map=16/48.683410/17.893295&layers=X&tool=route-planner&points=48.694501/17.884240%2C48.680506/17.896643%2C48.682121/17.906256&transport=foot-stroller

**Comment by zdila** [comment]
pouzivame externy router kym niekto nerozbeha novy na nasom serveri

skus tiez: https://www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=48.6630%2C20.1800%3B48.6613%2C20.1838
