### ISSUE TITLE
Pay-by-square na stranku https://www.freemap.sk/?show=supportUs

### ISSUE THREAD

**Issue by jose1711** [FreemapSlovakia/freemap-v3-react#580]
Isto by niektori prispievatelia uvitali mat na stranke s prispevkom aj pay-by-square QR kod.

**Comment by zdila** [comment]
prosim prekontroluj ci v tom qr su spravne udaje

**Comment by jose1711** [comment]
Dakujem, skusil som cez QR poslat 3 eurony. Ak pridu, budeme vediet, ze to funguje :-)

**Comment by kaylesk** [comment]
Vidím to vo výpise, takže funguje.

**Comment by zdila** [comment]
No ale testovacie platby sa zvyknu vraciat ;-)

**Comment by kaylesk** [comment]
Prep..č vchádz..m do tune... spoj..nie.. vyp..dáv... 
Šlo by tam hodiť ešte VS, aby sme vedeli identifikovať akým spôsobom to prišlo?
napr. : 6255417 (úplne vymyslené ale dosť "jedinečné")

**Comment by zdila** [comment]
ok, pridam to tam

**Comment by zdila** [comment]
alebo mi rovno vygeneruj QR kod, napr pomocou https://bsqr.co/generator/

VS: 119101098 (119 101 098 - ASCII "web")

**Comment by zdila** [comment]
@kaylesk riesis to?
