### ISSUE TITLE
Gallery upload - Network Error

### ISSUE THREAD

**Issue by tjamecny** [FreemapSlovakia/freemap-v3-react#585]
Po vyplnení formulára a kliknutí na tlačidlo "Nahrať" sa pod náhľadom fotky vypíše "Network error".
V konzole sú tieto chyby:
```
/?map=10/49.211766/18.993301&layers=T&show=gallery-upload:1 Access to XMLHttpRequest at 'https://backend.freemap.sk/gallery/pictures' from origin 'https://www.freemap.sk' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
t.js:25 POST https://backend.freemap.sk/gallery/pictures net::ERR_FAILED
```
Skúšané vo FF 78.10.0esr a Chromiu 90.0.4430.212, OS Debian 10.9.

(Problém nahlásený cez freemap email 4.6.2021, 15:03)

**Comment by zdila** [comment]
Cause: no space lenf on the device

Nieco som pomazal a uz ide. @tjamecny pls pozri co by sa dalo este pomazat.
