### ISSUE TITLE
Zosuladit uvadzanie zdroja s novymi Attribution Guidelines

### ISSUE THREAD

**Issue by Mashin6** [FreemapSlovakia/freemap-v3-react#591]
Moznosti:

1. Pridat jemny watermark niekam do rohu.
2. Spravit spash screen alebo pridat zmienku o OSM niekam na spodnu hranu "Tipy" dialogu. + nejaky text pri exporte/tlaci mapy.
3. ...?

**Comment by zdila** [comment]
Prosim pridaj sem odkaz na guidelines nech viem co je mandatory.

**Comment by Mashin6** [comment]
Zatial je to draft, o ktorom prebieha ziva diskusia, ale nepredpokladam, ze by sa to dramaticky zmenilo

https://wiki.openstreetmap.org/wiki/Draft_Attribution_Guideline/2021v0.9

**Comment by zdila** [comment]
follow-ups:
* #594
* https://github.com/FreemapSlovakia/freemap-mapserver/issues/10
