### ISSUE TITLE
spravit text v mapovych tooltipoch oznacovatelny myskou

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-v3-react#60]
... napr. aby si user vedel skopirovat zistene suradnice, vysku, vzdialenost...

**Comment by petervojtek** [comment]
no, spravil som to pre elevation tool, ale musel som vymenit Tooltip za Popup. 

neviem ale ci je to vhodne aj pre meranie vzdialenosti, lebo tam je zobrazenych viac tooltipov naraz tak aby to vyzeralo slusne (a pri merani vzdialenosti nie je podla mna az take dolezite vediet oznacit text)

**Comment by zdila** [comment]
Ja som rozmyslal zobrazenie vysledku merania aj hore v toolbare kde by ho nebol problem oznacit. Len tiez sa mi to nezda idealne. Pravdepodobne ale spravym vlastny `DivOverlay`.

**Comment by petervojtek** [comment]
mozno este pohodlnejsie by bolo mat tam niekde tlacidlo "skopiruj vysledok do clipboardu" (najma na mobile je to jednoduchsie nez oznacovat text)

**Comment by zdila** [comment]
No len v tom toolitpe na meranie vysky a pozicie je vela textu a clovek bude chciet skopirovat iba malu cast z toho.

Inac pre istotu sa tu pytam: http://stackoverflow.com/questions/42886052/how-to-make-leaflet-tooltip-text-selectable/

**Comment by zdila** [comment]
Po novom je vysledok merania zobrazeny v tooltipe ktory je oznacovatelny.
