### ISSUE TITLE
Nahlad fotiek ci vyhladavanie adresy nefunguje - `400` response

### ISSUE THREAD

**Issue by michalsisak** [FreemapSlovakia/freemap-v3-react#603]
Zdravim, uz istu dobu mam problem hladat adresy ci pozerat fotky. Nehladiac ci na Chrome ci na Safari. Vymazal som cache a stale nic. 

Request fotky:
`https://backend.freemap.sk/gallery/pictures?by=radius&lat=48.67939812816151&lon=-340.7813176438864&distance=0.6103515625`

Response:
`detail: ["invalid parameter lon: lon must be between -180 and 180"]
error: "invalid_query_parameters"`

Request Bratislavy:
`https://nominatim.openstreetmap.org/search?q=bratislava&format=json&polygon_geojson=1&extratags=1&namedetails=0&limit=20&accept-language=en&viewbox=-340.8243942260743,48.548432866542676,-340.63093185424805,48.68631417382459`

Response:
`error: {code: 400, message: "Bad parameter 'viewbox'. Not a box."}`

**Comment by zdila** [comment]
vdaka za report. pre rychle vyriesenie vasho problemu kliknite na logo freemapu.
