### ISSUE TITLE
Pridat moznost volby zobrazenia ikony POI

### ISSUE THREAD

**Issue by jose1711** [FreemapSlovakia/freemap-v3-react#606]
Pri velkej hustote POI nemusi predvoleny "spendlik" vzdy vyhovovat, kedze sa susediace POI prekryvaju.

![obrázok](https://user-images.githubusercontent.com/1406222/124473492-b1f39000-dd9f-11eb-897c-f7fcbe493547.png)

Preto by bolo super, ak by pouzivatel mal na vyber z viacerych ikoniek. Napr. GpsPrune ponuka toto:
![obrázok](https://user-images.githubusercontent.com/1406222/124473887-24647000-dda0-11eb-8e6b-7a32b694615c.png)

**Comment by IvanSipka** [comment]
za toto som aj ja !!!

**Comment by jose1711** [comment]
> za toto som aj ja !!!

:smile: Nabuduce staci dat :+1: (na githube sa tak oznacuju veci, o ktore sa clovek zaujima/s ktorymi suhlasi).

Inak takym riesenim na hulvata moze byt otvorenie vyvojarskej konzole (Ctrl-Shift-I) a zadanie:
```
setInterval(() => {Array.from(document.querySelectorAll(".leaflet-marker-icon")).forEach((e) => {e.innerHTML = '<svg><ellipse ry="5" rx="5" cy="10" cx="10" stroke-width="0" stroke="#000000" fill="#000000"/></svg>'})}, 1000)
```
Kazdu sekundu budu potom tie markery nahradene bodkou.

**Comment by IvanSipka** [comment]
asi tak ? ;-)

**Comment by robo311** [comment]
Rád by som na tomto pracoval. Je stále tato issue relevantná?

**Comment by zdila** [comment]
@robo311 áno, je to stále relevantné. V prvom rade treba navrhnúť ako to vyriešiť v UX. Či ako globálne nastavenie, alebo podľa funkcie (keďže piny sa zobrazujú na rôzne účely).

**Comment by robo311** [comment]
@zdila Pravdepodobne by som to zakomponoval globálne pre všetky objekty. Výber by sa nachádzal namiesto fixnej ikonky vedľa názvu "objekty (POI)". Teoreticky by sa tam mohol zakomponovať aj slajder alebo niečo podobné na zväčšenie/zmenšenie ikonky.

**Comment by zdila** [comment]
> Pravdepodobne by som to zakomponoval globálne pre všetky objekty

Kotre vsetky objekty (ktore funkcie)? Napr. markery sa zobrazuju aj pri planovani trasy, changesetoch, live trackovani - aj tam? Aky by to malo tam vyznam?

Tiez treba mysliet ake ikony - ci uplne volitelne (upload from disk) alebo preddefinovane. Treba mysliet aj na rozne exporty a importy co robime, aby toho bolo podporovane cim viac (gpx s rozsireniami pre garmin, locus..., kml, ...)

> Teoreticky by sa tam mohol zakomponovať aj slajder alebo niečo podobné na zväčšenie/zmenšenie ikonky.

To by bola dost nestandardna vec. Ma take nieco niekto iny relevantny?

**Comment by robo311** [comment]
> Ktore vsetky objekty (ktore funkcie)? Napr. markery sa zobrazuju aj pri planovani trasy, changesetoch, live trackovani - aj tam? Aky by to malo tam vyznam?
Myslel som konkrétne pre všetky POI objekty. 

> Tiez treba mysliet ake ikony - ci uplne volitelne (upload from disk) alebo preddefinovane. Treba mysliet aj na rozne exporty a importy co robime, aby toho bolo podporovane cim viac (gpx s rozsireniami pre garmin, locus..., kml, ...)
Ikony by boli preddefinované. 

> To by bola dost nestandardna vec. Ma take nieco niekto iny relevantny?
Hore na obrázku je zobrazené pod voľbou ikoniek nejaká takáto možnosť. Slajder som len navrhol, kľudne by to mohla byť len voliteľná možnosť. Mohlo by to pomôcť nejakej lepšej orientácie.

**Comment by zdila** [comment]
> Hore na obrázku je zobrazené pod voľbou ikoniek nejaká takáto možnosť.

Aha. To som teraz prehliadol. Toto by mohlo byt, ale ako globalne nastavenie.

Co sa tyka "len pre POI a preddefinovane" tak to za mna moze byt.

Este by to malo byt podporovane pri konverzii vyhladanych objektov (napr. pramene, skoly...) alebo vysledku hladania (search), na krelsenie, kde by to preklopilo aj ikony.

**Comment by zdila** [comment]
Implemented by @robo311 . Thanks!

**Comment by zdila** [comment]
poznamka: je to zatial iba na funkcii "Objekty". a ajmensi marker bez ikony (ako v screenshote) implementovany nateraz nie je.
