### ISSUE TITLE
mobil - kliknutie na tlacidlo vrstvy mapy automaticky zmeni mapu na Auto

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#62]

**Comment by zdila** [comment]
Skusas na realnom mobile? Lebo v browseri ked dam mobilny pohlad tak tam mi to ide.

**Comment by petervojtek** [comment]
praveze mi to robi browser v "mobilnom mode", na mobile som to este neskusal.

**Comment by zdila** [comment]
mne to ide. skus zmazat `node_modules` a spust `npm i`

**Comment by zdila** [comment]
A uz to robi aj mne :-)

Ale nenastavi stale iba automapu, ale to, co sa zobrazi vo vybere vrstiev pod kurzorom "mysi".

**Comment by petervojtek** [comment]
na skutocnom androide sa to nedeje (android 6, chrome).
