### ISSUE TITLE
Vyskovy profil by mal mat moznost presunu

### ISSUE THREAD

**Issue by jose1711** [FreemapSlovakia/freemap-v3-react#623]
Momentalne sa profil trasy zobrazi vzdy v lavom hornom rohu mapy, co nemusi vzdy vyhovovat. Bolo by fajn mat moznost pomocou drag&drop profil posunut ~~a/alebo zmensit jeho velkost~~.

**Comment by zdila** [comment]
A tento roh si uz skusil potiahnut?

![image](https://user-images.githubusercontent.com/636095/129045025-16128cf5-518e-4ee8-a5a7-62cbb82ad347.png)

**Comment by jose1711** [comment]
Ah, tak ten je doost nenapadny. Dik - 50 % done.

**Comment by zdila** [comment]
> Ah, tak ten je doost nenapadny

To je default ako to renderuje samotny browser na resizable elementy

> a/alebo

Alebo. 100% done ;-)

**Comment by jose1711** [comment]
jeee, vdaka!
