### ISSUE TITLE
Routing - cykloturistika - network error.

### ISSUE THREAD

**Issue by miro-janosik** [FreemapSlovakia/freemap-v3-react#627]
Iné typy routingu idú, iba cykloturistika vypíše chybu a nič nezobrazí:

"Nastala chyba pri hľadaní trasy: Network Error"
Browser: Firefox 91.0.2 Ubuntu

V debug konzole vidím:
Žiadosť Cross-Origin zablokovaná: zásada rovnakého pôvodu neumožňuje načítanie vzdialeného zdroja https://routing.freemap.sk/route/v1/bike/16.91498204659618,48.2714213441095;17.016753500680736,48.25198899134243?alternatives=true&steps=true&geometries=geojson (dôvod: požiadavka CORS nebola úspešná).

**Comment by zdila** [comment]
Po reštarte freemap servera sa to samo nepustili. Skús napísať na fórum, tu to je offtopic.
