### ISSUE TITLE
meranie plochy: vylepsit editovanie polygonu

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-v3-react#64]
* vlozit bod medzi lubovolne 2 vedlajsie
* zmazat bod

**Comment by zdila** [comment]
Nie je to dobre. Ked klikam body do kruhu tak mi to spravi toto:

![image](https://cloud.githubusercontent.com/assets/636095/24193752/b3c21660-0ef3-11e7-95e3-20cdc56bebe9.png)

Vkladanie bodu by som navrhoval spravit ako v umap-e.

**Comment by petervojtek** [comment]
vkladanie bodu -- cize medzi dvomi existujuci bodmi zobrazovat polopriehladny bod?

<img width="318" alt="screenshot 2017-03-22 11 59 07" src="https://cloud.githubusercontent.com/assets/225506/24194620/06f3bbc4-0ef7-11e7-982c-e648f3af9af1.png">

**Comment by zdila** [comment]
ano

**Comment by petervojtek** [comment]
suhlasim, je to sikovnejsie riesenie

**Comment by petervojtek** [comment]
inak rozmyslam ci by sme chceli takyto umap sposob vyberu medzi bodov mat aj v planovaci (midpoints). tam by ale hladanie polohy  "buduceho medzibodu" bolo zlozitejsie, kedze by to nebolo na usecke, ale na polyline, ale [turf.js na to ma funkciu](http://turfjs.org/docs/#along)

**Comment by petervojtek** [comment]
aktualne to vyzera takto. este by bolo pekne keby sa ukazovali guidelines ked pouzivatel taha tu modru bodku, ale ked som to skusal spravit tak som mal problem s drag vs dragend eventami, takze to uz necham tam;

<img width="557" alt="screenshot 2017-03-26 14 35 27" src="https://cloud.githubusercontent.com/assets/225506/24331292/7d5d1e30-1231-11e7-877d-65099112ce5a.png">

**Comment by zdila** [comment]
vyzera to super. este to tak pridat pre length measurement tool (ale to uz je tu offtopic)

**Comment by zdila** [comment]
> este by bolo pekne keby sa ukazovali guidelines ked pouzivatel taha tu modru bodku

ta bodka by sa mohla rovno zmenit na marker ktory bi si tahal. ale ked je to zlozitejsie na handlovanie tych drag eventov, tak zatial postacuje takto.

**Comment by zdila** [comment]
a este by mohlo ignorovat kliknutie na ten modry kruh.

**Comment by zdila** [comment]
a este mierny offtopic: potvrdenie mazania markeru by mohlo byt v jeho popupe nech netreba vela cestovat myskou :)

**Comment by petervojtek** [comment]
> potvrdenie mazania markeru by mohlo byt v jeho popupe

bolo by fajn keby sme to mali jednotne v celej aplikacii.
keby to bolo cez popup, tak to moze byt trochu zmatocne v planovaci, kde kliknes na midpoint, zobrazil by sa popup, ale ty zistis ze ho vlastne zmazat nechces a rozmyslas ako ten popup schovat. kliknut na 'x' v popupe moze byt na mobile problem, a ked kliknes mimo popupu na mapu (co by mohlo popup schovat) ale moze pridat dalsi bod.

**Comment by petervojtek** [comment]
ale vlastne v tom popupe by mohli byt tiez dve tlacidla "Ano" a "Nie" a na nie sa clovek trafi aj na mobile.
