### ISSUE TITLE
Unexpected status 415 pri pokuse o nacitavanie fotiek 

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#642]
z JS konzoly:

Status
415
Unsupported Media Type
VersionHTTP/1.1
Transferred0 B (22 B size)
Referrer Policystrict-origin-when-cross-origin

fotku pripajam

![IMG_2607](https://user-images.githubusercontent.com/3430677/146327627-9ae22a18-d777-4c71-a213-6adffb4f6087.jpg)

**Comment by zdila** [comment]
vdaka za report

**Comment by alexanderzatko** [comment]
aj ja dakujem za opravu
