### ISSUE TITLE
Error fetching OSM data: JSON.parse

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#643]
Pri nacitavani detailu v mape vidim chybu:

Error fetching OSM data: JSON.parse: unexpected character at line 1 column 1 of the JSON data

steps to repro:

1. pravym tlacidlom klikni do mapy
2. zvol detail v mape
3. z ponuky v menu vyber ziadany objekt

**Comment by zdila** [comment]
vdaka za testing, kludne v nom pokracuj :-)
