### ISSUE TITLE
Problem with GPX in iframe

### ISSUE THREAD

**Issue by pdragun** [FreemapSlovakia/freemap-v3-react#645]
Error when embed Freemap iframe load external GPX file:
`Nastala chyba pri získavaní záznamu trasy: JSON.parse: unexpected character at line 1 column 1 of the JSON data`
GPX is in XML format, not JSON.
It worked before without any problems.

Example: http://devcors.zochar.sk/
Discussion: https://groups.google.com/g/osm_sk/c/N3QJfw1gXUQ/m/fRhkHeXDCwAJ?pli=1

Thanks a lot

**Comment by zdila** [comment]
vdaka za report

**Comment by pdragun** [comment]
To ja ďakujem za fixnutie :+1:
