### ISSUE TITLE
Zmeny v mape - všetci autori - nefunguje

### ISSUE THREAD

**Issue by IvanSipka** [FreemapSlovakia/freemap-v3-react#646]
https://www.freemap.sk/?map=9/48.544796/18.783875&layers=X&tool=changesets&changesets-days=3

to bude asi bug;

**Comment by tjamecny** [comment]
Ano, je to bug. V pripade, ze parameter **display_name** nema hodnotu, nemal by sa posielat na OSM [API](https://wiki.openstreetmap.org/wiki/API_v0.6#Query:_GET_.2Fapi.2F0.6.2Fchangesets).
