### ISSUE TITLE
Nezobrazuje sa výzva na akceptovanie cookies

### ISSUE THREAD

**Issue by tjamecny** [FreemapSlovakia/freemap-v3-react#647]
Pri prvej návšteve stránky (alebo po vymazaní cookies) sa už nezobrazí výzva na akceptovanie cookies, následkom čoho nie sú dostupné viaceré funkcie, napr. prihlásenie:
![obrázok](https://user-images.githubusercontent.com/16599347/146985806-9fbf9c6e-4ac2-4f42-a17b-f379303ded9e.png)

Otestované na mobilnom Chrome aj dekstopovom Firefoxe, vždy sa zobrazuje varovanie "Táto funkcionalita vyžaduje prijatie súhlasu cookies.", ale dialóg, kde sa predtým povoľovali cookies sa už nezobrazil.

**Comment by zdila** [comment]
vdaka za report; pls otestovat rozne kombinacie (staci v jednom browsri)

**Comment by tjamecny** [comment]
Ďakujem za opravu, prihlásenie už funguje aj vo Firefoxe na Win10 a aj v Chrome na Androide. Obe vyskúšané len s minimálnym povolením cookies, t.j. bez analytických cookies.
