### ISSUE TITLE
Moznost vygenerovania nahodneho seedu

### ISSUE THREAD

**Issue by jose1711** [FreemapSlovakia/freemap-v3-react#648]
Sikovne by bolo mat pri random seede ikonku (napr. hracia kocka), ktora by "zatriasla strom" za pouzivatela, ktory by tak nemusel tukat vlastnu hodnotu

![obrázok](https://user-images.githubusercontent.com/1406222/147849249-09a86c99-e31f-4f64-9535-d2cc145a66ae.png)

**Comment by zdila** [comment]
Staci stlacit tu sipku hore.
