### ISSUE TITLE
Pridanie moznosti otvorenia aktualneho pohladu v demo.f4map.com

### ISSUE THREAD

**Issue by jose1711** [FreemapSlovakia/freemap-v3-react#649]
narhovane url: https://demo.f4map.com/#lat=$lat&lon=$lon&zoom=17
klavesova skratka by mohla byt `j4`

**Comment by zdila** [comment]
Tiles su dost skarede a nevidim v nich ziadnu pridanu hodnotu voci mapam ktore uz mame a 3D nie je podporovane Leafletom.

**Comment by jose1711** [comment]
Nemyslel som to ako dalsiu vrstvu, ale len do menu "Zdielat/otvorit v ext. aplikacii".

**Comment by zdila** [comment]
aha, slabo som precital :-)
