### ISSUE TITLE
Google Analytics incorrect visitor count

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#650]
It seems, on december 21st something happened that affected visitor counts and related statistics, as reported in GA.

Tracking ID: UA-89861822-3

**Comment by alexanderzatko** [comment]
Below is a chart comparing situation 1 month before and after the change. What seems conspicuous to me is the **New Sessions** param, as that is the only one that grew after the change. Maybe this is Google fooling around with their visit counting algorithm?

![freemap_Analytics_20220101-20220124_20211128-20211221](https://user-images.githubusercontent.com/3430677/152590508-24c37c87-08e0-4e2e-99f6-510028eca814.png)

**Comment by zdila** [comment]
I wonder if it haven't started since we added asking for cookie consent...

**Comment by zdila** [comment]
It must be caused by not accepting the cookie consent. Maybe users just [X] the pop-up. I am closing this issue but feel free to comment if you have any idea how to improve it.

**Comment by alexanderzatko** [comment]
This does not seem to be a good theory, as refusing cookies would only change the ratio between new and returning users, but not the daily user count.
