### ISSUE TITLE
Venujte 2% z daní Freemapu - mrtvý link

### ISSUE THREAD

**Issue by IvanSipka** [FreemapSlovakia/freemap-v3-react#655]
tento link je mrtvy ( 404 Not Found nginx/1.14.2)
[potvrdenie o zaplatení dane z príjmov zo závyslej činnosti](https://www.freemap.sk/Potvrdenie-2percenta-2021-prazdne.pdf)

**Comment by zdila** [comment]
fixnute, vdaka za report
