### ISSUE TITLE
Freemap a kreslenie

### ISSUE THREAD

**Issue by Mirecnet** [FreemapSlovakia/freemap-v3-react#658]
Skusal som teraz to kreslenie pre jeden moj clanok. Je to funkcne. 
Ked vsak oznacim bod, tak po exporte mapy sa mi nezobrazi vlajocka, ale mala nevyrazna cervena bodka. To sa mi v obrazku strati. Ked zadam POI body, tak po exporte mapy sa uz nezobrazi nic. Len hola mapa. Nedalo by sa s tym daco robit? Pomohli by naprikald sipky, ktore by jasne ukazali na objekt. 
Ukazka objektu bane, ktoru nevidno po exporte > https://i.postimg.cc/j2NQPQxQ/Bane-v-Jasenovej1.png

**Comment by zdila** [comment]
naimplementovane, nenasadene
