### ISSUE TITLE
some forms of "disused" tags are not recognized by the renderer

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#659]
For example, for adit, the FM renderer seems to recognize the combination ([example](https://www.freemap.sk/?map=18/48.468038/18.892890&layers=X&osm-node=3448245981)):
disused=yes + man_made=adit

...but the (recommended) way to [tag lifecycle info](https://wiki.openstreetmap.org/wiki/Key:disused:) is not ([example](https://www.openstreetmap.org/node/3997482778)):

disused:man_made=adit

**Comment by zdila** [comment]
For adits or mined tag disused=yes is still perfectly letit: https://wiki.openstreetmap.org/wiki/Tag:man_made=adit

Page doesn't even mention lifecycle prefix.

https://wiki.openstreetmap.org/wiki/Tag:man_made=mineshaft mentions that disused: prefix should be used if the former existence is non-verifiable and in this case I don't want it to be in the map.
