### ISSUE TITLE
NetworkError when attempting to fetch resource

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#662]
When uploading photos, I often times see "NetworkError when attempting to fetch resource." Re-uploading sometimes solve the problem, but often even that strategy fails.

This might be the result of a not very reliable internet connection, but maybe the upload function could be made more robust to minimize occurrence of this error.

**Comment by zdila** [comment]
i never see this error and i upload tons of photos
