### ISSUE TITLE
Misplaced Wikipedia tags for linear relations

### ISSUE THREAD

**Issue by DujaOSM** [FreemapSlovakia/freemap-v3-react#665]
Wikipedia tags associated with waterway and road route relations are rendered at wrong places. One would expect them placed on a member way, preferably a central one. Instead, they seem to be placed at some kind of polygon centroid, which may be way off the user expectations. Here's one example:
![Kudoš](https://user-images.githubusercontent.com/48584318/161701466-8ff1125a-d529-4a4f-9586-15b4287d40bf.png)

**Comment by zdila** [comment]
Thanks for the report. This is a known (by me ;-)) issue. We use overpass to get only the centers of feature bboxes, otherwise the response would be very expensive. But maybe you can help me with overpass query that returns point on the line or ask about that on overpass support forum.

**Comment by DujaOSM** [comment]
Ah I see; a fix would be much harder than I anticipated (and justified by gravity of the problem). Unfortunately, my Overpass knowledge is far from adequate for that :(. It seems it would be easier resolved by additional development on Overpass side than on the API consumers.

**Comment by zdila** [comment]
https://groups.google.com/g/osm_sk/c/svQXL0Xh37Q
