### ISSUE TITLE
Moznost kopirovat suradnice

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#67]
klikni "meranie"
klikni "vyska a poloha"
V okienku zobrazene suradnice urobit selektovatelne alebo umoznit ich skopirovat inym sposobom.

(osobne by som hlasoval aj za zmenu formatu na desatinny: 48.28292 19.338389)

**Comment by zdila** [comment]
to je duplicita #60. co sa tyka formatu suradnic, poprosim do zvlast issue.
