### ISSUE TITLE
the app allows accounts to share identical username

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#671]
It seems the app allows different accounts (emails) to share the same username. If possible, please unify the two depicted accounts into the older one (has more pics).

![doubleAccount](https://user-images.githubusercontent.com/3430677/163704429-9738c2c6-7325-44a4-a985-e7bd9b63550e.png)

**Comment by zdila** [comment]
duplicate of https://github.com/FreemapSlovakia/freemap-v3-react/issues/481
