### ISSUE TITLE
Zmenit format suradnic

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#68]
Pri zistovani polohy by som bol za zmenu formatu suradnic na desatinny: 48.28292 19.338389

**Comment by tjamecny** [comment]
Alebo dať užívateľovi možnosť prepnúť si formát v nastaveniach profilu. Mne tiež viac vyhoduje desatinný formát.

**Comment by zdila** [comment]
Takto to bude: 
![image](https://cloud.githubusercontent.com/assets/636095/24060405/6290e828-0b53-11e7-893d-0c18bcdba9a2.png)

**Comment by zdila** [comment]
(+ este nadmorsku vysku sformatuje po slovensky)
