### ISSUE TITLE
nastroj na zobrazenie gpx zaznamu

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#69]
vlastne si nie som isty ci to chceme mat v portali freemap (je mozno vhodnejsie aby to raz niekto spravil ako separatny nastroj podobne ako toposcope ;)

ale keby nahodou, predstavujem si to tak, ze pouzivatel moze spravit drag&drop gpx suboru hocikde do plochy portalu, zobrazi to trasu
* v hornom menu bude moznost zdielat odkaz na trasu
* onhover mysou nad bod trasy sa zobrazi tooltip so vzdialenostou od zaciatku trasy a cas v danom mieste. 
* start zobrazuje fixne tooltip - cas a datum startu.
* ciel zobrazuje fixne tooltip - cas a datum finishu a vzdialenost od startu
* v hornom menu je toggle "zobrazit/schovat graf" - zobrazi graf s elevation/time/distance

**Comment by zdila** [comment]
urcite raz chcem na fm portali taky tool :)

**Comment by petervojtek** [comment]
ok, takze vie to tieto veci:
* dragndrop area pre nahratie suboru (pripadne cez klik sa zobrazi tradicny file picker dialog)
* vie to zobrazit gpx trasu (resp ak ich je v gpx viac, tak by mal zobrazit vsetky) a wpts
* pre wpts to onhover zobrazuje popis waypointu
* pre trasu to onhover/onclick na trasu zobrazi pre dany bod vzdialenost od startu

dalsie vylepsenia a bugy uz riesme v separatnych issues.
