### ISSUE TITLE
Problem with responsiveness

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#692]
An user reported to me via email the following (slightly edited for clarity):

_Na mojom galaxy a13 android12
Sa to správa divne
Po otvorení je všetko drobné aj ovládacie prvky.
Po natočení na lezato sa to zvatsi.
Po natočení naspäť na stojato. Sa využíva len časť obrazovky :-(_

more info:

_Pri starte nalezato su tlacitka ok. :-)
Pri starte na stojato su tlacitka pre mikroprstych :-|
Po natoceni na lezato sa zvacsia a potom pri natoceni nastojato uz zostanu pouzitelne :-)
Vyzera ze pri starte na stojato vyhodnoti nejeku vysoku rozlisovacku displeja :-|_

**Comment by jozovasko** [comment]
fotky obrazoviek [https://photos.app.goo.gl/KwqdLydnvhnUm64N6]

**Comment by zdila** [comment]
Aky prehliadač? V Chrome, Vivaldi aj Firefox na Androide mi to ide ok. Mozno ma nastavene "desktop site" alebo nieco ine. Skusit vymazat nastavenia a cache prehliadaca.

**Comment by zdila** [comment]
bez odpovede. zatvaram.
