### ISSUE TITLE
(UX) Navigacna lista by sa mala prisposobit obrazovke / Navigation bar should adjust to screen width

### ISSUE THREAD

**Issue by jose1711** [FreemapSlovakia/freemap-v3-react#694]
Monitor s rozlisenim 1280x1024 a navigacia A &rarr; B:

![obrázok](https://user-images.githubusercontent.com/1406222/197379899-3e69016c-febd-4a07-83e4-eb72e4e6ece7.png)

Komu by napadlo, ze toto nie je vsetko?

![obrázok](https://user-images.githubusercontent.com/1406222/197379980-76e3dcc4-5265-4d3b-8ce0-057d2a3f6767.png)

V Gnome navyse scrollbar rychlo zmizne a aj ked je zobrazeny je velmi uzucky a je celkom "kumst" nan trafit.

Bolo by dobre, keby sa ta lista trochu prisposobila obrazovke. Alternativne widgety v nej zmensit, aby nebola taka dlhocizna alebo ju rozdelit na 2 riadky.

**Comment by zdila** [comment]
extra funkcie boli zlucene do dropdown tlacitka
