### ISSUE TITLE
[Edit in JOSM] Operation error: TypeError: Load failed

### ISSUE THREAD

**Issue by BelKed** [FreemapSlovakia/freemap-v3-react#696]
Every time I click the <kbd>Edit in JOSM</kbd> button, the error `Operation error: TypeError: Load failed` is displayed.

<img width="489" alt="Error Screenshot" src="https://user-images.githubusercontent.com/66956532/198844662-2af8cbb8-a74f-454e-bc78-cee6e8ceb610.png">

---

The console (from Safari) shows the following errors:

<img width="694" alt="Console Screenshot" src="https://user-images.githubusercontent.com/66956532/198844710-a8180182-7c68-4363-b578-202b7f0aebf9.png">

So this is the related line:
https://github.com/FreemapSlovakia/freemap-v3-react/blob/97e6cd4123a8652b71e311433bbfcbd641af1c75/src/processors/openInExternalAppProcessor.ts#L129

---

Weird is that only some browsers I've tested (Chrome, Brave and Safari) are affected. On Firefox and Opera, it works just fine (the area is loaded in JOSM without any problems).

**System info:** macOS Monterey 12.6
**Browsers info:**
- Safari `16.1`
- Brave `1.45.113` – Chromium: 107.0.5304.62 (Official Build) (x86_64)
- Chrome `106.0.5249.119` (Official Build) (x86_64)
- Firefox Developer Edition `107.0b6` (64-bit version)
- Opera `92.0.4561.33` (x86_64)

---

After some research, I found it's a CORS issue (or something related). However, after more than two hours, I haven't found a workaround for this issue :(

**Comment by zdila** [comment]
For me ti works in Vivaldi, Chrome and Firefox. Do you have it enabled in JOSM? Does it work for you from www.osm.org?

![image](https://user-images.githubusercontent.com/636095/198846027-b729e16d-45f4-40d5-83d5-97f38760531a.png)

**Comment by zdila** [comment]
> I found it's a CORS issue

It is a server responsibility to handle CORS properly. In this case it is JOSM who is a server.

**Comment by BelKed** [comment]
> Do you have it enabled in JOSM?

Yes :D If I didn't have it enabled, it wouldn't be able to open links from Firefox and Opera...

<img width="800" alt="Settings Screenshot" src="https://user-images.githubusercontent.com/66956532/198848041-329ef6a0-0d17-41ff-b901-5fe3bc4b522b.png">

> Does it work for you from www.osm.org?

Sadly, not. I tried it before, and I just forgot to mention that...

**Comment by zdila** [comment]
>> Does it work for you from www.osm.org?

> Sadly, not. I tried it before, and I just forgot to mention that...

Then I am afraid we can't do nothing in the code. Maybe ask for support on osm_sk@googlegroups.com.
