### ISSUE TITLE
Implementovať Galériu

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-v3-react#7]

**Comment by zdila** [comment]
tu bude treba spravit najprv rozumne server API

**Comment by petervojtek** [comment]
o.i. tam nahrame fotky rozcestnikov

**Comment by zdila** [comment]
> o.i. tam nahrame fotky razcestnikov

to mozeme aj teraz cez stary freemap alebo hromadne pomocou `curl`

**Comment by zdila** [comment]
zatvaram, jednotlive podfunkcie budu pokryte v zvlast issues
