### ISSUE TITLE
funguje portal na iphone?

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#70]
ja mam iba stary iphone 4s, iOS 9.3.5,  a tam sa v Safari zobrazi iba biela obrazovka (rovnako ked kliknem na "request desktop version")

**Comment by zdila** [comment]
funguje na iPhone 5s

**Comment by petervojtek** [comment]
ok, tak iphone 4s nas zatial netrapi.
