### ISSUE TITLE
Prevod uzavretej čiary na polygón.

### ISSUE THREAD

**Issue by IvanSipka** [FreemapSlovakia/freemap-v3-react#700]
Nazdar,
Keď si cez nástroj "Zistiť detaily v okolí" vyznačím nejakú oblasť, napr. hranicu katastra, a následne ju prevediem na kreslenie, neje tam možnosť farebnej výplne.
Nie je to v tom že sa neprevádza tá hranica na polygón?
Ak by tá farebná výplň šla realizovať bol by som rád.

Ďakujem Ivan.

**Comment by zdila** [comment]
workaround - v URL zmen `line=` za `polygon=`

**Comment by IvanSipka** [comment]
toto funguje ale chcelo by to tlačidlo napr. "Vytvoriť polygón" alebo "Zmeniť na plochu"... atď.
Pretože ak kreslíš niečo malé tak sa to v tom adresnom riadku dá nájsť ale očakávať od bežného človeka že vytvorí niečo takéto 
[Pokus](https://www.freemap.sk/#map=10/48.235193/17.616577&layers=X&point=48.285454/17.270194%1EC%23000000%1ELPezinok&point=48.151699/17.109306%1EC%23000000%1ELBratislava&polygon=48.312572/17.460255%2C48.316237/17.453248%2C48.319614/17.449266%2C48.327222/17.456519%2C48.327405/17.457596%2C48.325697/17.458785%2C48.326001/17.460377%2C48.325131/17.462121%2C48.330735/17.462877%2C48.336554/17.466723%2C48.341321/17.473057%2C48.347883/17.473651%2C48.352580/17.477524%2C48.357887/17.468391%2C48.358917/17.467275%2C48.360192/17.468624%2C48.374494/17.452167%2C48.372488/17.449405%2C48.374348/17.445435%2C48.370093/17.437279%2C48.374989/17.426309%2C48.378495/17.425480%2C48.380879/17.431119%2C48.386653/17.420609%2C48.391737/17.424427%2C48.394098/17.418707%2C48.395481/17.419753%2C48.396031/17.418039%2C48.398502/17.417771%2C48.401928/17.415415%2C48.400237/17.411264%2C48.400578/17.410615%2C48.402738/17.415472%2C48.404998/17.417223%2C48.408306/17.406320%2C48.406233/17.400916%2C48.406719/17.400331%2C48.407216/17.401136%2C48.407729/17.400197%2C48.409116/17.403679%2C48.410716/17.401605%2C48.412536/17.403977%2C48.413499/17.403405%2C48.413263/17.404887%2C48.414713/17.405058%2C48.416048/17.403651%2C48.417371/17.404386%2C48.419101/17.396799%2C48.419213/17.389779%2C48.421715/17.386539%2C48.422322/17.387034%2C48.423832/17.386089%2C48.424250/17.384834%2C48.426340/17.384527%2C48.429181/17.379882%2C48.428934/17.383941%2C48.429701/17.385613%2C48.430176/17.384894%2C48.431153/17.385408%2C48.430457/17.387372%2C48.430872/17.389341%2C48.432858/17.390662%2C48.432265/17.392927%2C48.432945/17.393883%2C48.434167/17.390547%2C48.437628/17.394104%2C48.438685/17.392166%2C48.439172/17.378460%2C48.438548/17.361562%2C48.439187/17.361709%2C48.443750/17.357636%2C48.444995/17.357691%2C48.445236/17.354234%2C48.448350/17.348143%2C48.449271/17.347151%2C48.451394/17.347232%2C48.451865/17.346438%2C48.451533/17.316894%2C48.453907/17.317698%2C48.455646/17.315158%2C48.456074/17.308761%2C48.454267/17.305855%2C48.453997/17.303653%2C48.447213/17.295194%2C48.444229/17.295383%2C48.439661/17.290516%2C48.439153/17.291992%2C48.435926/17.289829%2C48.432389/17.283668%2C48.431606/17.280736%2C48.428378/17.279300%2C48.426575/17.276965%2C48.428925/17.263134%2C48.428623/17.259455%2C48.422730/17.261702%2C48.422411/17.256841%2C48.421610/17.255138%2C48.420552/17.254942%2C48.417130/17.256919%2C48.414970/17.256880%2C48.414484/17.251144%2C48.412685/17.250128%2C48.411002/17.251241%2C48.410716/17.252519%2C48.409340/17.251892%2C48.408169/17.255670%2C48.405774/17.258533%2C48.402671/17.253400%2C48.399291/17.253542%2C48.398526/17.251802%2C48.397358/17.252996%2C48.396294/17.252698%2C48.396562/17.250541%2C48.395147/17.246957%2C48.393839/17.247062%2C48.390938/17.242219%2C48.387586/17.246370%2C48.384211/17.245719%2C48.383522/17.244794%2C48.381789/17.245490%2C48.379269/17.244876%2C48.378763/17.243947%2C48.377428/17.244522%2C48.378130/17.241917%2C48.381545/17.236895%2C48.381143/17.229362%2C48.378610/17.223147%2C48.379471/17.215236%2C48.378976/17.209878%2C48.376034/17.205609%2C48.374347/17.204579%2C48.373601/17.200965%2C48.371037/17.196673%2C48.368355/17.197166%2C48.366228/17.195379%2C48.364250/17.197901%2C48.362611/17.198613%2C48.359110/17.193213%2C48.355174/17.190182%2C48.351710/17.188703%2C48.346159/17.191975%2C48.341431/17.197335%2C48.339375/17.194380%2C48.338970/17.189212%2C48.336266/17.187476%2C48.334089/17.181793%2C48.331361/17.183411%2C48.328401/17.187069%2C48.326291/17.186604%2C48.324063/17.188264%2C48.321956/17.187310%2C48.320228/17.182890%2C48.312007/17.175947%2C48.310860/17.173454%2C48.312347/17.170128%2C48.312184/17.166729%2C48.314000/17.160849%2C48.309277/17.154847%2C48.306058/17.156352%2C48.302495/17.151972%2C48.297711/17.151070%2C48.295914/17.152801%2C48.292030/17.154056%2C48.290423/17.153441%2C48.289616/17.153903%2C48.282234/17.161463%2C48.279673/17.162885%2C48.279112/17.164511%2C48.273448/17.159041%2C48.269912/17.156770%2C48.268503/17.154726%2C48.266402/17.156901%2C48.264511/17.155748%2C48.263947/17.153638%2C48.260570/17.153230%2C48.258350/17.148985%2C48.255565/17.149126%2C48.252642/17.144706%2C48.251009/17.144793%2C48.250071/17.142177%2C48.247550/17.139564%2C48.247451/17.137208%2C48.243303/17.135383%2C48.242837/17.134222%2C48.242065/17.138976%2C48.243756/17.143119%2C48.242518/17.144744%2C48.240076/17.145458%2C48.238380/17.153336%2C48.239324/17.156469%2C48.243955/17.161649%2C48.244551/17.164588%2C48.241622/17.165289%2C48.238940/17.167959%2C48.237335/17.171060%2C48.235507/17.178442%2C48.230205/17.189599%2C48.225155/17.196922%2C48.218475/17.209258%2C48.213768/17.215583%2C48.206660/17.222288%2C48.204046/17.227151%2C48.204572/17.228627%2C48.203870/17.232092%2C48.205553/17.234343%2C48.208096/17.243033%2C48.210150/17.241936%2C48.215768/17.229154%2C48.219958/17.225786%2C48.222207/17.220420%2C48.224394/17.219331%2C48.227724/17.221275%2C48.229066/17.222294%2C48.230657/17.225467%2C48.231020/17.230024%2C48.227363/17.232088%2C48.227076/17.237331%2C48.234439/17.247307%2C48.236092/17.250797%2C48.241788/17.257496%2C48.238216/17.261388%2C48.239988/17.274130%2C48.239053/17.277321%2C48.239446/17.280350%2C48.239975/17.282056%2C48.241557/17.282927%2C48.242098/17.287379%2C48.239353/17.293139%2C48.237390/17.294169%2C48.238876/17.317695%2C48.246953/17.332606%2C48.251192/17.338731%2C48.253678/17.346574%2C48.262378/17.347670%2C48.273407/17.347305%2C48.275621/17.348600%2C48.278545/17.348844%2C48.273884/17.366841%2C48.273805/17.370315%2C48.278290/17.373620%2C48.276993/17.377481%2C48.282210/17.381032%2C48.281344/17.385025%2C48.284501/17.386855%2C48.286960/17.390373%2C48.288505/17.386309%2C48.291051/17.388160%2C48.295858/17.398447%2C48.292995/17.402881%2C48.295387/17.405930%2C48.286443/17.424516%2C48.289783/17.431155%2C48.295992/17.440656%2C48.305019/17.458705%2C48.305813/17.459697%2C48.309650/17.457596%2C48.312572/17.460255%1EW4%1EC%23000000%1ELokres%20Pezinok&polygon=48.148490/17.018440%2C48.153156/17.012936%2C48.160061/16.996292%2C48.168380/16.983885%2C48.171777/16.976223%2C48.176601/16.975490%2C48.182305/16.977445%2C48.189369/16.976437%2C48.195767/16.971828%2C48.201681/16.969795%2C48.205269/16.967054%2C48.210226/16.965221%2C48.213566/16.962463%2C48.220827/16.961780%2C48.226499/16.957548%2C48.231885/16.949038%2C48.235881/16.946121%2C48.241662/16.946718%2C48.243902/16.948264%2C48.248759/16.949759%2C48.252242/16.949782%2C48.256652/16.951432%2C48.261975/16.956716%2C48.265068/16.958477%2C48.263154/16.970956%2C48.255159/16.983479%2C48.253361/16.985104%2C48.253418/16.986555%2C48.252251/16.987222%2C48.252606/16.995964%2C48.252003/16.998202%2C48.251230/16.997881%2C48.250896/17.003850%2C48.248052/17.018370%2C48.250122/17.020771%2C48.250985/17.028870%2C48.250178/17.029460%2C48.251136/17.034240%2C48.250534/17.034883%2C48.250769/17.040328%2C48.252069/17.044192%2C48.251167/17.045720%2C48.250351/17.044442%2C48.245508/17.047170%2C48.243832/17.057774%2C48.242664/17.059861%2C48.242156/17.067359%2C48.241275/17.068215%2C48.239600/17.067873%2C48.237433/17.069621%2C48.235631/17.073779%2C48.235916/17.076670%2C48.240102/17.076364%2C48.242033/17.078003%2C48.242834/17.080811%2C48.243822/17.081554%2C48.246985/17.081473%2C48.247403/17.082556%2C48.249643/17.080919%2C48.249849/17.081415%2C48.246694/17.091048%2C48.247211/17.093711%2C48.249229/17.095271%2C48.249376/17.099352%2C48.247186/17.111117%2C48.245592/17.113985%2C48.244372/17.120500%2C48.247963/17.129266%2C48.247577/17.136981%2C48.243593/17.135561%2C48.242837/17.134222%2C48.242065/17.138976%2C48.243756/17.143119%2C48.242518/17.144744%2C48.240076/17.145458%2C48.238380/17.153336%2C48.239324/17.156469%2C48.243955/17.161649%2C48.244551/17.164588%2C48.241622/17.165289%2C48.238940/17.167959%2C48.237335/17.171060%2C48.235507/17.178442%2C48.229095/17.191564%2C48.225155/17.196922%2C48.218475/17.209258%2C48.213768/17.215583%2C48.206660/17.222288%2C48.204046/17.227151%2C48.198481/17.231598%2C48.197707/17.229173%2C48.194752/17.228584%2C48.194595/17.225496%2C48.193364/17.224153%2C48.186388/17.225134%2C48.184720/17.222473%2C48.182514/17.221054%2C48.181832/17.217919%2C48.174124/17.224240%2C48.169810/17.229601%2C48.169848/17.234221%2C48.168140/17.237288%2C48.166594/17.235754%2C48.167146/17.229084%2C48.163997/17.227177%2C48.164396/17.231765%2C48.163130/17.231783%2C48.162075/17.234278%2C48.158480/17.234216%2C48.157353/17.235245%2C48.156303/17.233599%2C48.153767/17.236625%2C48.153284/17.238386%2C48.151135/17.238707%2C48.149760/17.237686%2C48.148447/17.238984%2C48.144179/17.237439%2C48.142475/17.240338%2C48.138922/17.241871%2C48.137693/17.253563%2C48.136908/17.253491%2C48.135713/17.258679%2C48.123836/17.264997%2C48.122671/17.274727%2C48.123411/17.280106%2C48.120779/17.282770%2C48.116947/17.279331%2C48.116683/17.284531%2C48.110198/17.283186%2C48.100122/17.276152%2C48.103456/17.266601%2C48.106751/17.262182%2C48.110244/17.248831%2C48.112253/17.245521%2C48.111431/17.244310%2C48.112262/17.240615%2C48.111441/17.239183%2C48.111580/17.236059%2C48.103765/17.220384%2C48.103495/17.217309%2C48.102314/17.216670%2C48.100991/17.217526%2C48.099634/17.216335%2C48.097697/17.218078%2C48.095654/17.217746%2C48.093439/17.214891%2C48.092712/17.215099%2C48.092195/17.213747%2C48.092760/17.213048%2C48.085737/17.206720%2C48.082656/17.211361%2C48.079488/17.211876%2C48.076655/17.209052%2C48.075429/17.204329%2C48.070543/17.200828%2C48.070058/17.202079%2C48.068324/17.200725%2C48.067077/17.201695%2C48.065372/17.200800%2C48.061663/17.202084%2C48.063892/17.194428%2C48.053795/17.187371%2C48.052183/17.192569%2C48.045912/17.205178%2C48.039564/17.223117%2C48.029581/17.231963%2C48.022465/17.241769%2C48.021580/17.240307%2C48.020563/17.240453%2C48.018563/17.236085%2C48.016229/17.226627%2C48.016466/17.220742%2C48.019078/17.214137%2C48.019992/17.201029%2C48.019456/17.199388%2C48.017686/17.198346%2C48.018204/17.193163%2C48.012237/17.173210%2C48.008289/17.162888%2C48.006664/17.160773%2C48.013552/17.150090%2C48.020188/17.143822%2C48.019520/17.142364%2C48.022911/17.136379%2C48.022386/17.133011%2C48.022975/17.130839%2C48.020938/17.126745%2C48.028236/17.117482%2C48.031224/17.110060%2C48.019783/17.089866%2C48.023837/17.084834%2C48.031428/17.067423%2C48.035773/17.075079%2C48.036339/17.074245%2C48.045676/17.087790%2C48.050384/17.084257%2C48.052861/17.074005%2C48.055395/17.068250%2C48.057003/17.070170%2C48.056238/17.071712%2C48.065356/17.086791%2C48.070457/17.072230%2C48.078236/17.078914%2C48.080940/17.071572%2C48.082647/17.074849%2C48.083381/17.073132%2C48.085922/17.074556%2C48.092232/17.089641%2C48.090566/17.091328%2C48.091431/17.093140%2C48.096557/17.087769%2C48.099645/17.092707%2C48.103006/17.083723%2C48.102520/17.083339%2C48.105950/17.077419%2C48.107894/17.079081%2C48.110292/17.072873%2C48.115105/17.077065%2C48.114511/17.072821%2C48.116125/17.068641%2C48.118170/17.067969%2C48.121480/17.062786%2C48.123233/17.062369%2C48.123533/17.067974%2C48.124208/17.068816%2C48.126424/17.067137%2C48.127432/17.067623%2C48.128111/17.064299%2C48.128742/17.064079%2C48.129345/17.065562%2C48.133468/17.061422%2C48.135756/17.060145%2C48.135997/17.061636%2C48.138212/17.061262%2C48.140350/17.059356%2C48.141226/17.059449%2C48.141775/17.057362%2C48.143766/17.057186%2C48.140003/17.039201%2C48.139975/17.032396%2C48.142742/17.024113%2C48.148490/17.018440%1EW4%1EC%23000000%1ELBratislava)
Ja sa do takýchto vecí nevyznám ale prenášať údaje o kreslení v adresnom riadku je pri väčších kresbách asi neúnosné že?
Ivan

**Comment by zdila** [comment]
![image](https://user-images.githubusercontent.com/636095/210167945-80ac1599-7232-4f96-b316-0278f8a4149d.png)
