### ISSUE TITLE
Vypnutie "Objektov (POI)" bodov...

### ISSUE THREAD

**Issue by IvanSipka** [FreemapSlovakia/freemap-v3-react#701]
Serus,
neviem či to je zámer, ak áno chcem vysvetlenie, ale ak zapnem Objekt (POI) body a vyberiem si napr. Vrchol tak sa krásne zobrazujú  ale ak tú ponuku vypnem (napr. aj ESC) tak tie body (vdcholy) zobrazuje ďalej. Nedajú sa nijak vypnúť, iba ak tak tlačidlom
 "Vyčistiť mapu (gc)", čo je v prípade že už mám niečo nakreslené a samozrejme neuložené, dosť nepríjemné.
Dik.
Ivan.

**Comment by zdila** [comment]
da sa vypnut tak, ze v dropdowne vyberu objektov na neho znova kliknes
