### ISSUE TITLE
rampa brani vytvoreniu pesej trasy

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#706]
Routing algoritmus ma problem s (touto) rampou - nechce cez nu navigovat, aj ked zvolim navigaciu pre chodzu (walking).

https://www.freemap.sk/#map=18/48.728621/19.028304&layers=X&osm-node=6553799934

**Comment by zdila** [comment]
toto pls reportuj https://github.com/graphhopper/graphhopper/issues ak to vies zreprodukovat na https://graphhopper.com/maps/?profile=car&layer=Omniscale

**Comment by alexanderzatko** [comment]
Zda sa, ze na GH mape ten routing funguje...

https://graphhopper.com/maps/?point=48.726876%2C19.031094&point=48.728872%2C19.026041&profile=foot&layer=TF+Outdoors

**Comment by zdila** [comment]
tak treba updatnut graphopper na novsiu verziu. ak chces zareportuj do freemap-operations

**Comment by tjamecny** [comment]
@alexanderzatko Mne to funguje aj na [freemap.sk](https://www.freemap.sk/#map=18/48.728976/19.029120&layers=X&tool=route-planner&points=48.727864/19.030477%2C48.728904/19.025424&transport=foot&osm-node=6553799934):
![obrázok](https://user-images.githubusercontent.com/16599347/208400174-baa6716a-5d96-41b8-894a-a1e10b9394ec.png)

Ale nie som proti aktualizácii GH.

**Comment by alexanderzatko** [comment]
hmm, v Chrome to funguje aj mne, ale nie vo FF (Mac)

**Comment by alexanderzatko** [comment]
v private mode to funguje aj vo FF.  :-)
