### ISSUE TITLE
Problem s exportom mapy

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#707]
Snazim sa [vyexportovat z polygonu](https://www.freemap.sk/#map=15/48.732332/17.323809&layers=X&point=48.737931/17.323892&point=48.741122/17.331021&point=48.739594/17.341535&point=48.736155/17.345848&point=48.736959/17.333478&point=48.732246/17.335431&point=48.802981/17.180922%1EC%23000000&line=48.711127/17.309303%2C48.802977/17.180922%2C48.767391/17.359428&line=48.802974/17.180926%2C48.738758/17.335911&line=48.766599/17.361145%2C48.710900/17.307930&polygon=48.819524/17.155838%2C48.651057/17.159958%2C48.652871/17.499847%2C48.821785/17.495728) do PDF, ale generovany dokument sa neda stiahnut.

https://outdoor.tiles.freemap.sk/export?token=0a11f4807087becf693637d88769a6c7

**Comment by zdila** [comment]
podla zoomu sa snazit vyexportovat obrovsku mapu

ide mi s mensim zoomom: https://outdoor.tiles.freemap.sk/export?token=4aa4ca0248a0126ca854ab2a682f11da
