### ISSUE TITLE
Nastavenie farby pri importe

### ISSUE THREAD

**Issue by IvanSipka** [FreemapSlovakia/freemap-v3-react#710]
Serus,

Hodila by sa mi takáto fičúra:
buď:
pri importe z gpx mať možnosť nastaviť farbu importovaných bodov. čiar....
alebo:
po importe ich mať možnosť hromadne označiť a následne všetkým naraz zmeniť farbu

Príklad použitia u mňa. Importujem do svojej mapy viacero rôznych a početných skupín bodov zozbieraných v teréne a chcem mať každú skupinu v inej farbe tak mi nič iné nezostáva len ich po jednom prefarbovať.
A k tomu ma napadá ďalšia fičúra a to mať v palete možnosť preddefinovať vlastné farby aspoň 4 niečo ako rýchla voľba.
 
Za rýchle implementovanie ďakujem ;-)

Ivan

**Comment by zdila** [comment]
![image](https://user-images.githubusercontent.com/636095/210167892-83aff2d2-7120-4708-8a19-a5620df7a949.png)
