### ISSUE TITLE
Converting gpx to drawing duplicates segments

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#718]
When converting gpx files like the attached one to a drawing with tolerance 0, the created line segments are duplicated.

[all.gpx.zip](https://github.com/FreemapSlovakia/freemap-v3-react/files/11210288/all.gpx.zip)

steps to repro:

1. upload the attached file to the application,
2. convert to a drawing, with tolerance 0,
3. click to select one segment and delete it

expected outcome - the selected segment should be deleted and no other should be seen in its place

**Comment by zdila** [comment]
GPX file is invalid - contains nester `<trk>` element.
