### ISSUE TITLE
Uploading photos - tags dropdown does not collapse

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#720]
When tagging photos while uploading, the drop-down offering tag candidates does not collapse after selecting a tag. This is inconvenient when a single selection is made.

I understand this is likely done intentionally, to allow selecting multiple tags in one go, but maybe a checkbox next to the tag entry field could be added, allowing user to switch into a multiple selection mode, when checked. The default should be likely the single selection mode (checkbox unchecked), as most photos are tagged with a single tag (I guess).

<img width="786" alt="Screenshot 2023-05-12 at 08 29 21" src="https://github.com/FreemapSlovakia/freemap-v3-react/assets/3430677/793ccec1-de52-4a36-aebd-ba0d7cf0b5fe">

**Comment by zdila** [comment]
Used component https://github.com/i-like-robots/react-tags has no such feature. Feel free to report it there.

**Comment by alexanderzatko** [comment]
The component you are referring to [seems to collapse after selection](http://i-like-robots.github.io/react-tags/). In fact, the page you are linking to has an example of selecting multiple countries, where the illustration image included suggests that the user is supposed to pick countries on-by-obe, and not in a single action, the way it is implemented in freemap. It looks like either a different component was used in freemap, or the function of this component was modified, before inclusion. Ultimately I might not know what I am talking about, as I do not know react :-)

**Comment by zdila** [comment]
Actually we use newer version: https://github.com/i-like-robots/react-tag-autocomplete. I'll check the options there.

**Comment by alexanderzatko** [comment]
velka vdaka. Na mobiloch to dost otravovalo.

**Comment by zdila** [comment]
ale nasadim to neskor :-)

**Comment by alexanderzatko** [comment]
"nasadim" je klucove slovo a dakujem :-)

**Comment by zdila** [comment]
deployed
