### ISSUE TITLE
Matomo: missing css on FF?

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#727]
When visiting the login page the css is not applied when viewing matomo on FF (MacOS). Even after logging in, the page is not styled.

<img width="376" alt="Screenshot 2023-12-28 at 07 55 36" src="https://github.com/FreemapSlovakia/freemap-v3-react/assets/3430677/f8caa6be-b18d-479d-8367-04888baa4342">

**Comment by alexanderzatko** [comment]
On other browsers of the same OS the styling work ok

**Comment by tjamecny** [comment]
If you are using any AdBlocker plugin in webbrowser, try to disable it (at least it helped in my case).

**Comment by alexanderzatko** [comment]
uBlock Origin was the culprit in my case
