### ISSUE TITLE
Find coordinates and elevation - request

### ISSUE THREAD

**Issue by matic13** [FreemapSlovakia/freemap-v3-react#728]
When right-clicking on the map to find coordinates and elevation, you provide coordinates in various formats.

Random example:

N 45,276819°, E 13,375854°
N 45° 16,6092', E 13° 22,5513'
N 45° 16' 36,549", E 13° 22' 33,076"

But the most basic one is missing: the one with dots and commas that work universally in any map supporting coordinates, **45.276819, 13.375854** in this particular example. So it's quite inconvenient to just quickly copy-paste coordinates from Freemap into any other map, OSM.org included, because you always have to change commas into dots at the very least, otherwise, it won't work in other apps.

Please could you add the most basic format option as well?

Thanks

**Comment by matic13** [comment]
I noticed lately that coordinate lookup results in only one format:

<img width="342" alt="Image" src="https://github.com/user-attachments/assets/9ff6dc5a-6de4-4f53-b309-acd3d34b43ea" />

The blue "left and right" arrows don't work. Please can you check?

**Comment by alexanderzatko** [comment]
works for me, in both - logged in, as well as anonymous states. Tested in FF (logged in) and Safari (anon).

**Comment by zdila** [comment]
Tried Vivaldi, Chrome, Firefox - all works.

**Comment by matic13** [comment]
It works on my Lenovo Windows laptop, but not on my Mac.

**Comment by matic13** [comment]
Hi,

Now I noticed that it no longer works even on my Lenovo Windows laptop in Firefox. Nor Chrome for that matter!

Please can you check what seems to be the problem? It can’t be only on my side.

**Comment by zdila** [comment]
Please provide output from your browser's developer console.

**Comment by matic13** [comment]
Which part exactly?

![Image](https://github.com/user-attachments/assets/e35b39c1-988f-4a83-b591-3a64e1407b60)

**Comment by zdila** [comment]
I see no errors there. Please post video showing the issue with the console open.

**Comment by zdila** [comment]
Thanks. Can you try if it works for you in new Firefox profile (ie. clear history / cookies / no browser extensions...)?

**Comment by matic13** [comment]
I tried opening Firefox in 'Troubleshoot Mode' - same story. It just doesn't work.

**Comment by zdila** [comment]
I changed the UI and added some debug logs. Please try and post (screenshot of) logs after clicking this button several times:

<img width="589" height="253" alt="Image" src="https://github.com/user-attachments/assets/e073fc60-c57b-4260-8b2c-d4e59b505672" />

**Comment by matic13** [comment]
I'm happy to report that the issue seems to have been solved both on Mac and Windows now! Thanks
