### ISSUE TITLE
Možnosť nastaviť priehľadnosť krycej vrstvy

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#73]
Všimol som si že v najnovšej verzii je vrstva lesných ciest a hrebeňov čo je super.
Mohla by byť možnosť nastaviť sýtosť prekryvu aby vrstva lesných ciest bola polopriehľadná.

**Comment by petervojtek** [comment]
zda sa ze v leaflet-react je bug a nie je mozne menit opacity TileLayer on-the-fly:
https://github.com/PaulLeCam/react-leaflet/issues/304

**Comment by zdila** [comment]
> Thanks for reporting this, should be fixed in v1.1.4.

**Comment by petervojtek** [comment]
inak keby sme to velmi chceli mat hned, tak si mozeme zdedit TileLayer a implementovat to tam, ale povedzme ze pockame 1 mesiac ci dovtedy spravia release..

**Comment by zdila** [comment]
react-leaflet rychlo reaguje na bugreporty. naviac lepsie je asi fixnut v danom projekte a poslat pull request.

**Comment by zdila** [comment]
Preco blocked? Uz to ma byt opravene v leaflete.

**Comment by petervojtek** [comment]
kym nebude novy release leaflet tak je to blokovane, nie ?

**Comment by zdila** [comment]
No ved v 1.1.4 to opravili, release uz je a uz aj v package.conf na novy release odkazujeme.

**Comment by petervojtek** [comment]
a-ha, tak to som cele prehliadol, necakal som taku agilnost :)

**Comment by petervojtek** [comment]
ok, spravil som to cez slider v Settings popup-e. nie je to idealne, lepsie by bolo keby clovek priamo videl na mape ako sa meni transparentnost. napada ma takato alternativa, ale tiez to nie je idealne:
* v Settings popupe bude tlacidlo "Zmenit viditelnost NLC" a ked sa nan klikne, popup sa zavrie a zobrazi sa permanentny Toast v ktorom sa bude nachadza slider a tlacidla Ulozit/Zrusit (ktovie ci sa to tam cele zmesti).

**Comment by zdila** [comment]
Podla mna ako si to spravil zatial uplne postacuje a mozes zavriet tuto issue :-)
