### ISSUE TITLE
Pridať možnosť lokalizácie

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#75]
V prípade že človek prehliada mapu na mobilnom zariadení je fajn ak poskytuje mapa možnosť zobraziť polohu podla informácií o polohe zariadenia.
Na stránke https://parcela.app4u.sk/ to majú spravené tak že pokiaľ je aktivované Sledovanie polohy tak mapa sa aj aktualizuje podľa zmien polohy.

**Comment by petervojtek** [comment]
toto je vlastne specialny pripad "Sledovania polohy" (#3) -- kedy sledujem sam vlastnu polohu :)
mohli by sme zacat tak, ze pridame do menu Viac polozku "Sledovanie polohy". Po kliknuti sa zobrazi popup a tam si clovek zapne "Automaticky updatovat polohy mapy podla aktualnej polohy" a pripadne tam budu dalsie prepinace ako refresh interval.  ked je to aktivne, na mape je zobrazeny marker mojej polohy a jeho poloha sa pravidelne updatuje a tiez sa updatuje map view (myslim ze to ako to robi locus je fajn).

**Comment by petervojtek** [comment]
bude treba mysliet na jednu vec -- ked vypnem telefon a po par minutach ho znova zapnem a otvorim prehliadac, android chrome zvykne reloadnut stranku (inak nechapem preco to robi, dost mi to vadi). aby sa zachovalo nastavenie sleduj polohu, to ze je to zapnute sa musi reflektovat v url (parametre sledovania staci mat v local storage)

**Comment by zdila** [comment]
pridal som preview funkcie. namiesto tlacitka v hlavnom menu by som to dal do mapy ako je to na https://openstreetmap.cz. a este budem upratovat kod (zvlast komponent a mozno aj reducer...). tiez to bude vypinatelne, a funckia sledovania - napr. tak, po zaostreni bude posuvat mapu podla GPS az kym ju user manualne neposunie.

**Comment by zdila** [comment]
A ked sa [toto](https://github.com/Leaflet/Leaflet/issues/1686#issuecomment-290160863) poriesi tak to vylepsim.
