### ISSUE TITLE
zoomovanie na mobile pomocou +/- odstrani horne menu

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-v3-react#78]

**Comment by zdila** [comment]
> nedame na mobile to +/- prec ? ludia by uz mali byt zvyknuty zoomovat cez dotykovane pohyby.

ja na mobile vyuzivam na zoomovanie vzdy tlacitka, ak su, lebo viem, ze mi to zoomne spolahlivo o jeden level, bez posunu (nebodaj rotacie) mapy

**Comment by zdila** [comment]
Sposobuje to toto CSS:
```
.leaflet-container {
  height: calc(100vh - 56px);
}
```

**Comment by zdila** [comment]
Na iPhone 5s sa tento problem neprejavuje.

**Comment by petervojtek** [comment]
no je to zahada. virtualne tlacidla na androide to nesposobuju, lebo mam dva telefony (oba s virtualnymi klavesmi, oba full hd displeje) a na jednom sa horne menu strati a na druhom nie.

na tom telefone kde sa horne menu straca sa problem fixne tak, ze sa nastavi:

```
.leaflet-container {
  height: calc(100vh - 112px); // 2 x 56px
}
```

ale nerozumiem preco sa to tak sprava.

inak tu riesili rovnaky problem, ale ked som skusal pouzit ich riesenie, tak sa ani nezobrazila mapa:
http://stackoverflow.com/questions/28820335/leaflet-clicking-zoom-control-removes-pagging-top

mne ako najjednoduchsie riesenie pride odstranit tie zoom tlacidla, ja ich vobec nepouzivam :)

**Comment by petervojtek** [comment]
ale treba to vyriesit.
lebo problem je aj v tom, ze mapa je vtedy vyssia nez obrazovka a nevidiet attribution.

**Comment by petervojtek** [comment]
no dobre, na mojich vsetkych zariadeniach zoom buttons funguju a je vidiet aj attribution. napokon pomohlo to riesenie zo stackoverflow (ale najprv som si neuvedomil kde vsade musi byt nastavene `height: 100%`). ale celkovo sa mi to riesenie az tak velmi nepaci.
