### ISSUE TITLE
meranie vzdialenosti  - optimalizovat gui pre vela markerov/tooltipov

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#79]
povodne to bolo [tu](https://github.com/FreemapSlovakia/freemap-v3-react/issues/31#issuecomment-287689564): 

Merac vzdialenosti je dost problematicke pouzivat, kedze "kvapky" casto krat zakryvaju miesta kam chce clovek kliknut. Zistil som, ze stitky s udajom o vzdialenosti dovoluju kliknut na miesto ktore zakryvaju, ale ani to nie je velka vyhra z hladiska pouzivatela.

Asi by som viac privital, ak by sa vzdialenost ukazovala pri umiestneni kurzora nad uzol naklikanej trasy v okienku, niekde na okraji mapy alebo inom vhodnom mieste.

<img width="490" alt="screen shot 2017-03-20 at 07 47 15" src="https://cloud.githubusercontent.com/assets/3430677/24090810/c805efc2-0d43-11e7-87fa-6d3040981f6b.png">

**Comment by petervojtek** [comment]
> ak by sa vzdialenost ukazovala pri umiestneni kurzora nad uzol naklikanej trasy v okienku

toto nebude fungovat ma dotykovych displejoch.

co keby bolo v hornom menu tlacidlo "zobraz vsetky stitky", ktore ak by bolo apnute, tak by si videl to co teraz, a keby bolo vypnute, tak by si videl iba stitok na poslednom markery (cize celu dlzku trasy)

**Comment by zdila** [comment]
Vseobecne tie markery do buducna planujem mensie (nie iba tu) a tooltip by sa tu mohol odsadit trosku viac do prava.

**Comment by petervojtek** [comment]
je pravdou ze tie tooltipy maju zbytocne velky padding (ale velkost textu by som nechal aka je)

**Comment by zdila** [comment]
ok, casom doladme. teraz by som sa sustredil na prioritnejsie veci :-)

**Comment by petervojtek** [comment]
inak navrhujem zaviest dva labels pre issues: `low-priority` a `high-priority` (a implicitne ma issue medium priority), aby sme vedeli co povazujes za priority :)

**Comment by petervojtek** [comment]
>  markery do buducna planujem mensie

**Comment by petervojtek** [comment]
>  markery do buducna planujem mensie

az teraz som si vsimol ze ty si pisal o markeroch a ja o tooltipoch :)

v f94baa9 som spravil to, ze som zmensil tooltip padding (a tiez ho posunul blizsie k markeru):

vyzera to nasledovne a aplikuje sa to len vtedy, ked das tooltipu triedu `compact`

<img width="452" alt="screenshot 2017-03-24 17 11 51" src="https://cloud.githubusercontent.com/assets/225506/24303170/4d240a08-10b5-11e7-8cb1-468adb1942d5.png">
