### ISSUE TITLE
link na naplánovanú trasu

### ISSUE THREAD

**Issue by DurkoMajling** [FreemapSlovakia/freemap-v3-react#80]
Ahojte,
som zvyknuty z inych web-ov, ze po vytvoreni trasy v planovaci (napr. autorouting), koordinaty startu a ciela sa daju do linku. Vo freemap sa len nazoomuje mapa (http://next.freemap.sk/#/T/14/48.309574/18.523464)

predpokladal som takyto link: http://www.openstreetmap.org/directions?engine=osrm_car&route=48.3166%2C18.5223%3B48.2897%2C18.5301#map=14/48.3032/18.5295 

Vdaka Durko

**Comment by petervojtek** [comment]
Martin @zdila ,  mohli by sme sa zamysliet ake URL parametre vo vseobecnosti ocakavame, mozno nieco taketo?

planovac:
```
http://next.freemap.sk/#/T/14/48.309574/18.523464?tool=route_planner&points=48.3166%2C18.5223%3B48.2897%2C18.5301&movement_type=bicycle
```

odkaz na objekt na mape (ktory sme dostali napr. cez vyhladavanie a zobrazi sa napr. ako polygon):

```
http://next.freemap.sk/#/T/14/48.309574/18.523464?tool=show_item&item_id=34567
```

este by mohlo byt uzitocne vediet zdielat polyline naklikany cez meranie vzdialenosti (niektori ludia tak planuju trasy)

```
http://next.freemap.sk/#/T/14/48.309574/18.523464?tool=measure_distance&points=48.3166%2C18.5223%3B48.2897%2C18.5301
```

**Comment by zdila** [comment]
Navrh sa mi paci. Len `movement_type` by som nahradil napr. za `transport_type`.
A mozno by sme mohli zmenit aj reprezentaciu stavu mapy z `T/14/48.309574/18.523464` na `mapType=T&zoom=14&lat=48.309574&lon=18.523464`. Je to sice dlhsie, ale semanticky spravnejsie.

**Comment by petervojtek** [comment]
> transport_type

suhlasim, to je lepsie.

> mapType=T&zoom=14&lat=48.309574&lon=18.523464

sucasne riesenie ("osm standard") ma podla mna velku vyhodu ze mozes jednoducho copy&pastovat zoom/lat/lon z inych osm-based nastrojov a portalov bez editovania.

**Comment by zdila** [comment]
tak potom ako to ma osm.org - nie priamo v ceste ale parameter `map`:
http://www.openstreetmap.org/#map=7/52.600/16.891

**Comment by petervojtek** [comment]
suhlasim.
