### ISSUE TITLE
ake farby pouzit defaultne pre markery a plochy

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#81]
teraz to nemame jednotne.
ja som zacal pouzivat vo vyhladavani zkombinaciu sedej (highlight) a zelenej (oznaceny vysledok), ale v lese to nie je dobre viditelne.

v merani sa pouziva modra, co prilis neladi s farbou toastu:

<img width="780" alt="screenshot 2017-03-22 11 29 19" src="https://cloud.githubusercontent.com/assets/225506/24193602/21b4d4ce-0ef3-11e7-90b6-9f8c1b67f94c.png">

potrebujeme zladit nasledobne farby:
* marker
* polyline (vysledok vyhladavania, measure distance, vysledok routovania)
* area
* toast

a zaroven farba prvych troch musi byt viditelna na mape nad lesom a vsetkymi farebnymi TZT. toto splna napriklad ruzova farba :)

**Comment by zdila** [comment]
Mne farba toho toastu pride divoka :-). Zvolil by som nejaku sivu (kompatibilnu s bootstrap farbami).

Marker / polyline / area by som zatial nechal default modre.

**Comment by petervojtek** [comment]
ok, mozeme mat default farbu modru (aj info toast bude modry) a pri vyhladavani nemusime rozlisovat medzi onhover farbou a ked-je-vybrany-vysledok farbou (oba mozu byt modre).
