### ISSUE TITLE
cislovat markery v planovaci trasy

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-v3-react#82]
ak ma trasa viacero midpoints, bolo by pekne mat markery cislovane, lebo inac sa tazsie orientuje v niecom takom:

![image](https://cloud.githubusercontent.com/assets/636095/24194806/bcab0314-0ef7-11e7-916a-27f6bf6ccb95.png)

Cislovanie dat idalne priamo do markera.

**Comment by petervojtek** [comment]
toto som uz v jednom projekte robil tak, ze marker som mal v JS kode v svg podobe (ako template) a  vyrendroval som ho s danym cislom. vykonnostne je to v pohode lebo tych markerov nebude vela, len si nie som isty ci uz je podpora svg dostatocne widespread. 
ine riesenie je spravit to cez div marker (ktory leaflet podporuje), ale to cez svg je to jednoduchsie.

**Comment by zdila** [comment]
Toposcope maker ma markery v svg kde vyuzivam "generovanie" makerov roznej farby (az troch ;-) ).

SVG je podla mna uz dost rozsirene. Aleternativa je ich generovat cez canvas (placnes obrazok markeru a vpises text s cislom). Pri canvase treba mysliet aj na retinu.

**Comment by petervojtek** [comment]
ok, tak svg.
vyrobim pre ten ucel komponent, a ten potom pouzijeme aj v planovaci namiesto sucasneho png cerveneho a zeleneho markeru.

**Comment by zdila** [comment]
...a mohol by byt trosku mensi :-)

**Comment by petervojtek** [comment]
ak ho spravime mensi, na mobile bude problem nan kliknut.

**Comment by zdila** [comment]
tak "if mobil then smaller" ;-). alebo nechaj potom povodnu velkost.

**Comment by petervojtek** [comment]
tu je prva verzia. start a stop su este povodne ikony a velmi k tym cislovanym neladia. keby sme pre start/stop mali pouzit rovnaky styl ako pre midpoints, otazkou je co dat tam kde ma je v midpoint-e cislo. dala by sa tam dat ikonka z font-awesome/glyphicon podobne ako to [robia tu](http://codepen.io/anon/pen/Jdayb).

zatial som neriesil velkost ikoniek pre mobil/desktop (ale ta nova je trochu mensia).
mne na 5.5" fullhd displeji pridu sucasne ikonky aurat velke, mensie sa mi uz nezdaju vhodne. pre svg ikonky ale vieme lahko pridat skalovanie, a parametrizovat to napr. s meniacim sa zoom-levelom, alebo tym docielit ze start a stop mozu byt trochu vacsie ako midpoints (a podobne pre meranie vzdialenosti).

ak by sme velmi chceli mensie ikonky, dala by sa lahko spravit aj taka finta, ze ikonka bude mensia, ale bude mat padding takze sa bude dat chytit aj trochu mimo nej. 

<img width="500" alt="screenshot 2017-03-22 17 58 32" src="https://cloud.githubusercontent.com/assets/225506/24210417/50e562fa-0f29-11e7-938f-cd744ede88b7.png">

**Comment by tjamecny** [comment]
Aktualne vyzeraju markery na starom freemape takto:
![fm_markery_na_trase](https://cloud.githubusercontent.com/assets/16599347/24212266/05876adc-0f2f-11e7-9c4a-fab073c8c366.jpg)

Su zbytocne velke, ale paci sa mi to farebne odlisenie od medzizastavok. Taktiez by som tie symboly "pretacania kazety" pouzil na startovom/cielovom markeri. Telo markera by mohlo ostat modro-biele, len miesto cisla by sa zobrazoval zeleny symbol na prvom a cerveny na poslednom markeri (ale neviem, ci sa tie farby nebudu bit).

**Comment by petervojtek** [comment]
mňo, v 31dbd7c6 som pridal podporu pre font-awesome ikony v markeri a planovac vyzera takto:

<img width="644" alt="screenshot 2017-03-24 10 24 43" src="https://cloud.githubusercontent.com/assets/225506/24288286/0fb0911a-107d-11e7-8472-5be6250c94e0.png">

ale ten kod v MarkerWithInnerLabel.js tusim zacina opustat React paradigmu :)
Martin @zdila , usudzujem ze keby sme to chceli mat krajsie (pouzit jsx a komponenty pri rendrovani svg a tej fa ikony), asi by sme museli zdedit L.divIcon (aby sme do jej `html` atributu mohli dat jsx). pripadne [nieco taketo divne](https://github.com/grommet/jsx-to-string)..

**Comment by petervojtek** [comment]
Ale nie je lahke dobre vycentrovat tie fa ikonky, napriklad na mobile su trosku posunute. so statickymi png ikonkami by to bolo asi jednoduchsie, ale tym zase nevieme menit farbu on the fly

![screenshot_20170324-103836](https://cloud.githubusercontent.com/assets/225506/24288584/3eb29cdc-107e-11e7-97fe-b4d734bf559c.png)

**Comment by zdila** [comment]
> ale ten kod v MarkerWithInnerLabel.js tusim zacina opustat React paradigmu

opusta react, ale priblizuje sa leaflet paradigme, takze je to ok ;-)

inac sa mi to cele paci, len mozno by som volil trochu menej saturovane farby aby boli viac kompatibilne s default bootstrap temou: http://getbootstrap.com/css/#less-variables-colors

**Comment by petervojtek** [comment]
zmenil som farby takto:
* ciel - boostrap error
* default farba nasho custom markeru (a zaroven midpoint trasy) - boostrap primary

ale toto je zle viditelne a nepouzil som to:
* ciel -- boostrap success (pouzil som namiesto toho silnejsiu zelenu)
* najdena trasa -- bootstrap primary (radsej som to nechal default leaflet farba)

<img width="644" alt="screenshot 2017-03-24 10 24 43" src="https://cloud.githubusercontent.com/assets/225506/24290806/a03ebf14-1086-11e7-8959-1b54eb24d817.png">

**Comment by zdila** [comment]
moje oko nepostrehlo zmenu, ale ok :)

**Comment by petervojtek** [comment]
aha prepac, to bol zly screenshot :) 

<img width="633" alt="screenshot 2017-03-24 11 43 57" src="https://cloud.githubusercontent.com/assets/225506/24290925/35bd01f4-1087-11e7-9870-be2d632f1af9.png">

**Comment by zdila** [comment]
Toto uz je krajsie. Dakujem :-)
