### ISSUE TITLE
Meranie vyska a poloha - bug

### ISSUE THREAD

**Issue by Mashin6** [FreemapSlovakia/freemap-v3-react#83]
Pri merani vysky a polohy sa mapa refokusuje na polohu predchadzajuceho merania.

1. Zmeraj prvu vysku/polohu
2. Posun mapu prec aspon dve obrazovky.
3. Zmeraj druhu vysku/polohu
4. Poloha sa zmeria spravne ale mapa sa posunie na miesto predchadajuceho merania.

Mac, Chrome Version 56.0.2924.87 (64-bit) ale aj ine browsery.

**Comment by zdila** [comment]
Vdaka za report. Oprava bude viditelna v dalsom release.
