### ISSUE TITLE
Meranie plochy - bug

### ISSUE THREAD

**Issue by Mashin6** [FreemapSlovakia/freemap-v3-react#84]
Meranie plochy obcas blbne, ale nerobi to vzdy. Snazil som sa zistit od coho to zavisi a mysim, ze problem je, ak je velkost prveho uhla viac ako cca 90˚.

Mac Chrome, Safari

![freemap3_plocha](https://cloud.githubusercontent.com/assets/5265707/24227399/2b485736-0f43-11e7-8dd8-1d61b2843c46.gif)

**Comment by zdila** [comment]
Dakujeme za report. Uz je to spominane na https://github.com/FreemapSlovakia/freemap-v3-react/issues/64#issuecomment-288359373. @petervojtek navrhujem odstranit featuru pridavania noveho bodu medzi dva najblizsie. Co ty na to?

**Comment by petervojtek** [comment]
uplne som nepochopil v com je tento bug, ale bez ohladu na to :) suhlasim s odstranenim pridavania bodu medzi dva najblizsie a nahradit to tym "umap" sposobom.

**Comment by zdila** [comment]
No len implementacia umap sposobu nieco potrva. Takze nateraz by som len odstranil tu feature pridavania bodu medzi (mazanie ostane).

**Comment by petervojtek** [comment]
ok, dal prec tu feature a teraz to pridava body vzdy na koniec (ako predtym) c0342a35
