### ISSUE TITLE
Graficka mierka u uroven priblizenia

### ISSUE THREAD

**Issue by Mirecnet** [FreemapSlovakia/freemap-v3-react#85]
Zdravim,
v novej mape mi este chyba graficka mierka u uroven priblizenia.

Planuje sa ?

Miro

**Comment by petervojtek** [comment]
ahoj Miro,


> uroven priblizenia

myslis nieco ako ten vertikalny slider na lavej strane na starom freemape?
ak ano - aku to ma pre pouzivatelov pridanu informacnu hodnotu?

> graficka mierka

len nahlas rozmyslam, ci by sa nevedela zmestit do horizontalneho pasiku, v ktorom sa zobrazuje progress indikator. cize ked je progress bar neaktivny (sedy), tak nejako zobrazuje mierku.

<img width="353" alt="screenshot 2017-03-23 20 26 43" src="https://cloud.githubusercontent.com/assets/225506/24266522/5505aae6-1007-11e7-8f35-1c1eefbbcdfc.png">

**Comment by Mirecnet** [comment]
jj, to som myslel. Dobre je mat daku mierku na prirovananie, aby clovek vedel o akej vzdialenosti sa jedna. Bez toho, aby musel stale nieco premeriavat. Kazda mapa takuto mierku ma.
https://sk.wikipedia.org/wiki/Mierka_mapy
Myslim, ze tam hore, ako si navrhol by bola dobra. Len by to muselo byt dako pekne graficky zakomponovane, aby to zase neposobilo moc rusivo. Lebo obycajne je mierka v mape vzdy dole.
![mierka](https://cloud.githubusercontent.com/assets/24828961/24295199/e785069a-1099-11e7-8d97-05081953fd46.jpg)

**Comment by petervojtek** [comment]
skusal som tu mierku zmestit do progress baru, ale pri sucasnej vyske 4px nie je sanca vidiet text (napr. "100m"), a az niekde pri 10px to zacina byt citatelne, to uz bolo prilis hrube.

tak som tam zatial dal len tradicny leaflet scale, ale s dvoma upravami:
* zobrazuje sa iba ked je aktivny nastroj Meranie (mam taku /mozno zlu/ predstavu, ze ked uz cloveka zaujima mierka tak vlastne chce nieco merat :)
* je to v vpravom dolnom rohu nad attribution (default je lavy dolny roh), lebo keby to bolo v lavom dolnom rohu tak to na mobiloch bude prekryte attribution.

<img width="377" alt="screenshot 2017-03-24 16 24 43" src="https://cloud.githubusercontent.com/assets/225506/24300995/941c1e2a-10ae-11e7-8525-980c56dbd4fc.png">

**Comment by zdila** [comment]
> zobrazuje sa iba ked je aktivny nastroj Meranie (mam taku /mozno zlu/ predstavu, ze ked uz cloveka zaujima mierka tak vlastne chce nieco merat :)

Prave ze ak uz si niekto zapne meranie tak moze okaslat mierku ked ma v ruchach silnejsi tool.

Ta mierka tam podla mna moze byt stale.

**Comment by petervojtek** [comment]
a rozmyslal som, ze skala zoomu by mohla byt zobrazena v priestore neaktivneho horizontalneho progress baru (ako horizontalny stlpec -- uplne schovany pri zoom=8, uplne vysunuty pri zoom=16) - lenze to by si ludia mohli mysliet, ze "zamrzol" progress bar.

**Comment by zdila** [comment]
progress bar by som nechal progress barom

**Comment by petervojtek** [comment]
ok.

**Comment by petervojtek** [comment]
835edd3c501fa8
