### ISSUE TITLE
satelitna mapa by mohla byt overlay (aby sa dala menit jej priehladost nad podkladovou mapu)

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#86]
na samotnej satelitnej mape sa tazko orientuje

**Comment by zdila** [comment]
od bingu je aj hybridna mapa. overlay zo satelitnej mapy je dost bolehlav.

**Comment by zdila** [comment]
a aj ine klasicke mapove portaly maju satelitnu ako normalnu vrstvu. naviac vacsinou si najdes na mape miesto napr na turistickej vrstve a potom si pre zaujimavost prepnes na satelitnu, takze vies kde si.

**Comment by petervojtek** [comment]
ok
