### ISSUE TITLE
pridat podporu pre webpack-hmr

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#88]
vid
https://github.com/FreemapSlovakia/freemap-v3-react/commit/27f32d45db6841e6c2af68bbd0521853aae1ec85#commitcomment-21482135

**Comment by petervojtek** [comment]
pridal som podporu pre livereload, spusta sa to cez 

```
npm run-script livereload
```

ale nesmu v kode zostat ziadne `console.*` , lebo to spravi `[WDS] Errors while compiling. Reload prevented.` (inak to pravidlo ze console.log su zakazane mi nedava velky zmysel, lebo potom clovek z nudze zacne pouzivat alert, co je este vacsie zlo).

hot module reload sa mi nepodarilo spojazdnit, skusil som pouzit aj plugin [webpack-module-hot-accept](https://www.npmjs.com/package/webpack-module-hot-accept), ale aj tak to stale robilo fullreload, preto som prepinac `--hot` vyhodil z `npm run-script livereload`.

mne zatial fullreload staci.

**Comment by zdila** [comment]
> inak to pravidlo ze console.log su zakazane mi nedava velky zmysel, lebo potom clovek z nudze zacne pouzivat alert, co je este vacsie zlo

to je default v `eslintrc` a nemal cas som to zmenit na warning lebo som chcel viac veci vytunovat. alebo dat rovno aurbnb pravidla ktore si ludia pochvaluju.

ked si najdem cas, pozriem sa na to hmr.

**Comment by petervojtek** [comment]
mne hmr nechyba, takze ak sa ti s tym nechce zaoberat, mne sucasny stav vyhovuje.

**Comment by zdila** [comment]
Vela stavu sa zachovava v URL takze toto uz viacmenej netreba
