### ISSUE TITLE
Pridať ďalšie kategórie do objektov

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-v3-react#9]
Sem: https://github.com/FreemapSlovakia/freemap-v3-react/blob/master/src/poiTypes.js

Bonus - pridať ikony.

Zobral by som to zo súčasneho freemapu.

**Comment by petervojtek** [comment]
Martin @zdila , v tomto kontexte sa chcem spytat naco ma  pouzivatelovi sluzit v hlavnom menu polozka "Objekty" ?
zda sa ze ked pouzijem vyhladavanie, ma to asi sluzit ako filter na typy zobrazenych objektov? (nie je mi jasne aky je obvykly pripad pouzitia).

inak z UX hladiska to podla mna nie je velmi prijemne rozhranie - jednak nazov "Objekty" je nejasny, modalny popup by som sa snazil pouzit az ako posledne riesenie ked zlyhaju ostatne UI koncepty :)  a to ze trebakategoriu rozklikavat je nepohodlne..

**Comment by zdila** [comment]
Je to to iste ako z existujuceho freemapu:
![image](https://cloud.githubusercontent.com/assets/636095/23363089/2abeb33e-fcf9-11e6-8e26-09bad2faa9c1.png)

Zobrazi ti to vo vyreze vsetko co zaklikas a casom bude moznost exportovat to do GPX. Je to fanj vec ak napr ides na vylet do nejakej oblasti a chces povedzme GPXko so vsetkymi pramenmi a utulnami.

UX hladisko zatial doriesene nie je.

**Comment by petervojtek** [comment]
pozeral som tie freemap ikony, ale su velmi male (16x16px a iba png) - predstavujem si to tak, ze tie ikony budu nielen pri vybere, ale aj na mape.

ale tu su svg ikony (dizajn nic moc, ale nic lepsie zadarmo v takom rozsahu asi nie je): https://github.com/openstreetmap/map-icons/tree/master/svg
a hlavne tu je mapovanie z osm tagov na nazvy ikon: https://github.com/openstreetmap/gosmore/blob/master/elemstyles.xml

aby som sa vyhol manualnej praci, na uvod by som mohol zobrat kategorie tak ako su v tom prvom odkaze a pouzit ich. 

neskor by sa uz mohol najst niekto iny, ktory tie kategorie a objekty v nich rucne popresukupuje tak, aby zodpovedali napr. kategorizacii z freemapu (kedze my sme viac zamerani na turistiku, kym tie osm kategorie maju turisticke veci rozhadzane).

**Comment by petervojtek** [comment]
skusal som tie svg ikony zobrazovat aj na mape, ale ked ich je viac ako cca 20, tak to uz citit pri posuvani mapy. 

png ikony (classic.big) v tom projekte openstreetmap/map-icons su male (a hnusne) a nemaju rovnaku velkost, co robi problemy pri jednotnom pouziti ako marker icon. 

@zdila, mne sa zda najvhodnejsie sa touto feature aktualne nezaoberat, lebo:
* je to urcene len pre power users
* vyzaduje si to dost casu
* ak to nebude ako tak zoptimalizovane z UX hladiska, tak to nebude dobre a bude to treba aj tak prerobit. 

niekolko jednoduchych UI tweaks ktore tomu teraz vedia pomoct:
* v modalnom vybere pouzit buttons namiesto checkboxes (aby sa zmestilo viac objektov na riadok)
* accordeon > panel sa teraz rozbaluje iba ked sa klikne na title text. skusal som docielit aby sa rozbalil aj kliknutim hocikde na panel, ale nepodarilo sa mi to (toto je podla mna velka nevyhoda jsx -- v obycajnom html/js je to jednoducha vec, ale tu ked je to zabalene cez dve dalsie vrstvy abstrakcie je problem to ovladat a pouzit riesenia ktore clovek najde na stackoverflow)

**Comment by zdila** [comment]
> mne sa zda najvhodnejsie sa touto feature aktualne nezaoberat

kludne sa venuj inej casti a spravi sa to ked na to niekto bude mat cas alebo chut. u mna je problem hlavne len ten cas.

> je to urcene len pre power users

podla mna turista co si stiahne vsetky pramene a utulne do gpx to oceni

> vyzaduje si to dost casu

myslis to nahodenie kategorii?

> obycajnom html/js je to jednoducha vec

Ak chces obycajne js, tak si prepis `<Volaco .../>` na `React.createElement('Volaco', ...)` ;-). Podla mna ak je nieco skryte aj v "obycajnej" js kniznici tak tiez to nevies jednoducho zmenit bez toho aby si priamo menil jej zdrojak.

Nie je nutne pouzivat vsetky komponenty z react-bootstrap. Mozes si vytvorit novy komponent a vyuzit iba bootstrapovske CSS.

**Comment by zdila** [comment]
Trochu som vylepsil UI:  00909c8fb7a5f2cb79fbd799f25c2eca034354f6. Nedeployol som.

**Comment by zdila** [comment]
Robim na tom v branchi `feature-9-object-categories`. Kategorie to nacitava z API. Bude treba prerobit aj UI.

**Comment by petervojtek** [comment]
super.
navrhujem spravat sa ohladom issues tak, ze ked issue robis (alebo ju chces robit), tak si ju prirad. potom bude zrejme, ze na nepriradenych issues sa urcite nerobi.

**Comment by zdila** [comment]
@petervojtek to cele API na vyhladavanie POI je dost hrozostrasne a nie je velmi dokumentovane. Riesenia:
1. pouzivat overpass ako doteraz
1. pozistovat ako volat freemap API a dorobit to (no to api je aj tak skarede)
1. napisat novy server :-) (idealne riesenie, ale casovo narocne)

Ja som za bod 1. Tvoj nazor?

**Comment by petervojtek** [comment]
najviac sa mi pozdava tiez 1. - a mam na to aj koncepcne _vyssi_ dovod :) 

a totiz, myslim si kde je to mozne by sme sa mali snazit byt co najviac kompatibilny s OSM svetom a snazit sa pisat co najmenej vlastneho backendu (t.j. radsej len u seba hostovat backendove riesenia ktore vyvija a udrziava OSM komunita, napr osrm, nez si pisat vlastny router). 
dovody:
* usetri nam to cas, budeme musiet udrziavat menej kodu (na backende)
* moja predstava je, ze sa nechceme prilis vzdalovat od sveta OSM, pretoze OSM principy a myslienky su to, co na tu cele drzi pokope (a nie nejaky slovensky portal s mapou)

**Comment by zdila** [comment]
OK. Mudro pises :-)

**Comment by petervojtek** [comment]
ten dropdown Zvol kategoriu vyzera fajn, predpokladam ze tam este planujes nejake UI zmeny? 
len preistotu uvadzam zopar postrehov, ale predpokladam ze ich mas v plane (alebo sa s tym mozem pohrat ja):
* dropdown - ja by som obmedzil jeho vysku a spravil ho vnutorne scrollovatelny (aby nebol vyssi nez je vyska obrazovky a nesposoboval scroll celej stranky). 
* kliknutie na kategoriu by mohlo zbalit jej clenov
* oznacena polozka by mohla mat indikator.
* multiselect?

**Comment by zdila** [comment]
> predpokladam ze tam este planujes nejake UI zmeny

ano, vid #42 kde to mozeme diskutovat.
