### ISSUE TITLE
zobrazit itinerar v route planneri

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#90]

**Comment by petervojtek** [comment]
rad by som itinerar zobrazoval tak, ze v menu planovaca bude tlacidlo "toggle itinerar", a ked bude aktivny, tak sa nad trasou zobrazia body itinerara ako tooltipy. 

teoreticky je to mozne spravit aj so sucasnym `freemap.sk/api/0.1` api, kde vysledok vyzera takto:

```
	<itinerary>
		<item distance='931 m'>Continue on unknown road</item>
		<item distance='282 m'>Turn right into Cyklotrasa Novomestsk?? podhorie</item>
		<item distance='541 m'>Continue on Jursk??</item>
		<item distance='79 m'>Turn left into Bus 51: Trnavsk?? m??to => Vozov??a Kras??any</item>
		<item distance='1.9 km'>Turn left into Ra??ianska</item>
		<item distance='15 m'>Turn right into Bus 151: OD Slim??k => Lopen??cka</item>
		<item distance='471 m'>Turn right into Ra??ianska</item>
		<item distance='38 m'>Continue on unknown road</item>
	</itinerary>
```

ale museli by sme este pouzit funkciu [turg.js along](http://turfjs.org/docs/#along) aby sme vypocitali kde sa ma bod itinarara nachadzat.. otazka je, nakolko bude ta vypocitana poloha presna (co skor nakolko su presne tie vzdialenosti v itinerari .. napr. 1.9km je asi zaokruhlene, cize tam moze byt nepresnost +-50 metrov, co je dost.)

**Comment by tjamecny** [comment]
Issue https://github.com/FreemapSlovakia/FreemapBackend/issues/5 je už naimplementovaná, takže nie je treba odhadovať nejaké dodatočné informácie a ani používať staré API 0.1. Ak ešte niečo chýba v API 0.3, prosím o pridanie komentára k vyššie uvedenej Issue.

**Comment by petervojtek** [comment]
vdaka Tibor, najprv vyskusam nove api volanie v ramci  #92 a potom sa vratim k tejto issue.

**Comment by petervojtek** [comment]
no, prva verzia vyzera nasledovne. bug s `??` namiesto diakritiky je [reportovany](https://github.com/FreemapSlovakia/FreemapBackend/issues/10) backend teamu. 

rozmyslam co sa da robit aby sa tie tooltipy neprekryvali. jedna moznost je, ze cim viac pouzivatel odzoomuje, tym menej tooltipov sa bude zobrazovat (nieco v duchu ze ak su dva body itineraru od seba menej ako 100m, a zoom je menej ako 14, zobraz iba prvy).

<img width="885" alt="screen shot 2017-03-27 at 7 21 18 pm" src="https://cloud.githubusercontent.com/assets/225506/24369110/3cc8bfda-1323-11e7-82dc-ca2db9691702.png">

**Comment by petervojtek** [comment]
asi je tiez vhodnejsie pouzivat relativne vzdialenosti (od predosleho bodu itineraru), nez absolutne od startu?

**Comment by zdila** [comment]
otazne je, na co je prakticky dobry taky itinerar :-). v takejto forme tooltipov podla mna asi na nic. nejaky vyznam mozno ma ked si ho viem cely copy pastnut a vytlacit, aby som sa vedel navigovat bez mapy.

ale kto vie ci itinerar niekto v dnesnej dobe niekto pouzije a ak ano, ci to nieje marginalna skupina obyvatelov ;-)

**Comment by petervojtek** [comment]
> ci to nieje marginalna skupina obyvatelov ;-)

preto som niekolkokrat v minulosti pisal aby sa niekto kto ma pristup ku google analytics stareho freemapu pozrel ktore features sa ako casto pouzivaju. ja osobne tipujem ze vacsina ludi pouziva len mapu a vsetko ostatne (planovac, vyhladavanie, poi search) pouziva menej ako 1% navstevinkov.

**Comment by petervojtek** [comment]
inak zo zvedavosti som skusil ako by itinerar vyzeral keby bol obsah v dropdown button-e v menu (a po onhover/click na polozku sa rozsvieti zvoleny bod na trase), ale tam je problem ze bud idu polozky dropdown menu doprava, a vtedy je obsah itinerary odrezeny, alebo mozu byt zarovnane dolava (pullight), ale potom zase prekryvaju mapu. a na mobile je tu nanic ci je to dolava alebo doprava :)

**Comment by MichalPP** [comment]
https://github.com/perliedman/leaflet-routing-machine to rieši, netreba duplikovať

**Comment by zdila** [comment]
> https://github.com/perliedman/leaflet-routing-machine to rieši, netreba duplikovať

mozno ze my to chceme lepsie a krajsie

**Comment by MichalPP** [comment]
WTF, zase vyrábať niečo na kolene, nech to nikto iný nepožíva a po pár rokoch to zase skape?

**Comment by zdila** [comment]
to potom nemusime robit nic ked tu mame google :-)

**Comment by petervojtek** [comment]
je problem s diakritikou, je k tomu issue na backende.

radsej nech je zoznam itineraru na kraji a onhover sa zobrazi pozicia na mape. problem je na mobile a este sa nad zamyslime.

**Comment by zdila** [comment]
Pokracovanie v #278
