### ISSUE TITLE
Turistická a cykloturistická vrstva

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#91]
Toto bude asi komplexnejšia otázka vzhľadom aj na renderovanie. Ale ide o to či je možné aby boli turisticky značené cesty a cykloturisticky značené cesty, spolu so súvisiacimi atribúty renderované ako samostatná priehladné vrstvy, ktoré by bolo možné potom zobrazovať aj súčasne, prípadne prekrývať nimi iné podkladové mapy.

**Comment by petervojtek** [comment]
ked sa nam tym nezavazne zamyslim, su asi dve moznosti..

## Vektorove tiles

bolo by zaujimave keby sme niekedy dokazali nejako vclenit kayle-ho vektorovy freemap styl do portalu. postup by bol cca nasledovny:
* nejako zo slovakia.osm suboru pravidelne generovat vektorove tiles (https://www.mapbox.com/vector-tiles/)
*servovat ich z backendu
* a do freemap frontendu pridat zobrazovanie vektorovych tiles

ale neviem ci by sme vobec chceli ist cestou mapboxovych vektorovych tiles lebo tusim niektori clenovia OZ maju vyhrady k mapbox licencnym podmienkam. su aj nejake alternativy, ale o tych nic neviem.

## Vanilla bitmapovy podklad 

a nad nim zobrazovat TZT/cyklo/pois ako leaflet polylines/points/polygons.. v podstate nieco ako rozsirenie sucasneho vyhladavania POIs o TZT a cyklotrasy. ale zrejme by to chcelo mat api optimalizane pre tento pripad pouzitia, lebo dopytovat sa overpass-u po kazdom pohybe mapy na to ake su cyklotrasy vo vyreze asi nebude velmi svizne..

**Comment by tjamecny** [comment]
Turistické aj cyklistické trasy sú k dispozícii ako priesvitné vrstvy, takže je možné nimi prekrývať iné mapy. Dáta ale držíme iba na phenix-e, preto sa nedajú použiť a|b|c|d.freemap tile servery.
Pri turistickej mape sa môže zapnúť vrstva tiles.freemap.../cycle/z/x/y.png a na na cyklomape zase tiles.freemap.../trails/z/x/y.png. Samozrejme táto vrstva prekryje pôvodné trasy  namiestach, kde idú aj cyklotrasy aj turistické trasy, t.j. nerieši sa súbeh týchto trás.

**Comment by petervojtek** [comment]
> Turistické aj cyklistické trasy sú k dispozícii ako priesvitné vrstvy

to som nevedel. inak moj pripad pouzitia je, ze si planujem cestu na cestom bicykli a aktualna cyklovrstva je mi neuzitocna, lebo nevidim kde je asfalt (takze obvykle pouzivam lyziarsku vrstvu). mne osobne by bolo uzitocne keby som si vedel nastavit ciastocnu priehladnost farieb cyklotras (aby som videl "pod ne").

**Comment by tjamecny** [comment]
A nestačí použiť automapu? Či potrebuješ aj vrstevnice a tieňovanie kopcov? Alebo je len automapa "príliš škaredá"? ;)

**Comment by petervojtek** [comment]
lyziarsku kvoli vrstevniciam.

**Comment by petervojtek** [comment]
ok, tak mam v plane spravit to, ze v Nastaveniach bude prepinac "Expert mode" (podobne ako ma JOSM, by default off), a ked bude expert mod zapnuty, tak sa v prepinaci mapovych vrstiev zobrazia dve dalsie polozky (turisticka a cyklovrstva ako overlay) a v nastaveniach im bude mozne menit opacity.

**Comment by petervojtek** [comment]
ok, takze je to nasadene na next.freemap.sk

v Nastaveniach treba zapnut Expert mode a potom sa v mapovych vrstvach na konci zjavia dve nove polozky:

<img width="189" alt="screen shot 2017-04-17 at 5 35 05 pm" src="https://cloud.githubusercontent.com/assets/225506/25093813/3852f39a-2394-11e7-90a8-2aaffdd6361e.png">

pouzivatelsky zmysluplne kombinacie su napr:
* lyziarska mapa + turisticka vrstva
* satelitna mapa + cyklovrstva
