### ISSUE TITLE
Aktívne body v mape

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#93]
Bolo by možné spraviť aby také body/prvky v mape ktoré napríklad majú odkaz na nejakú webstránku boli v mape aktívne tj. bolo by možné kliknúť "na ne" a vyvolať bublinu s odkazom.
Prípadne využiť aj na iné veci ktoré by mohli byť užitočné pre užívateľov zobrazovať.

**Comment by MichalPP** [comment]
teda zduplikovať toto: http://freemap.epsilon.sk/#page=objekty&map=T/16/48.14562/17.1205

**Comment by zdila** [comment]
Zatial take body/prvy s odkazom nemame. Raz bude tool anotacie mapy, aky mozes vidiet napr. na umape.

> teda zduplikovať toto ...

@MichalPP kludne zduplikuj, s krajsim UX a react+redux

**Comment by petervojtek** [comment]
@seg-on, mozes uviest nejaky konkretny pripad pouzitia? nas postup by mal byt nasledovny:
1. identifikujeme ake su pripady pouzitia
2. vymyslime UI (ta ukazka na epsilon je priklad ako by to nemalo vyzerat, pricom mi nie ani je zrejme na co sa to UI vlastne ma pouzit :)
3. a implementujeme..

**Comment by tjamecny** [comment]
Mne ta poziadavka pripomina fungovanie POI na starom freemape, t.j. zvolis si kategoriu + subkategoriu a das zobrazit POI. Oblast je bud aktivny BBOX alebo cela mapa. A potom si mozes klikat na markery na mape.

Ale urcite by takato funkcia nemala byt zapnuta defaultne, a uz vobec nie aby to vyzeralo ako epsilon. Tam vidim len more fialovych kruhov o ktorych nic netusim, kedze som si este nic nezvolil...

**Comment by petervojtek** [comment]
zobrazenie POIs uz mame vo velmi zakladnej podobe implenentovane (tlacidlo Miesta v hornom menu)

**Comment by zdila** [comment]
> vo velmi zakladnej podobe

az tak velmi zakladna podla mna nie je :). vies aj exportovat do GPX, a do markerov ti pekne da ikonky a pekne popisne tooltipy.

**Comment by MichalPP** [comment]
na epsilone bola myšlienka zobrazovať typy POI podľa zapnutej vrstvy (a potom umožniť doklikať si presnejšie) a namiesto kružkov dávať ikonky (čo je to ľahšie).

ťahšie je určiť ktoré kategórie priradiť ku ktorej vrstve.

**Comment by seg-on** [comment]
Myšlienka je skôr aby nebolo nutné zapínať nejaké zobrazovanie vrstiev, vyberať určitý typ POI, alebo sa preklikávať na iný portál. Bežný užívateľ si prezerá mapu a zbadá nápis cestu, bod, budovu v mape a chce naň kliknúť.

Využitie by mohlo byť zobrazovať informácie ktoré sú obsiahnuté v tagoch ale nikde sa nijak nezobrazujú. Ako som už spomínal odkaz na webstránku, wikipédiu, otváracie hodiny obchodov, inštitúcií, dĺžka cyklotrasy (obtiažnosť),..

Funkčne by to mohlo vyzerať napíklad tak že keď užívateľ klikne v mape ľavím tlačítkom v kruhu by vyskákali ikonky POI na ktoré keď klikne tak sa zobrazí tooltip/bočný panel/.. kde by sa nachádzali podrobnosti.
Alebo iná varianta cez pravé tlačidlo a názvy POIo.
Výber POIo by bol nastavený ako body nachádzajúce sa v určitej vzdialenosti od kliknutia.

Formátovanie textu a ktoré údaje by sa zobrazovali by bolo na základe schém, ktoré by sa udržiavali cez github.

**Comment by MichalPP** [comment]
sú dva usecasy

1. čo je toto?
2. som tu, kde sa môžem najesť/kde je najbližšia MHD?

**Comment by MichalPP** [comment]
@zdila pozri si čo som urobil v https://github.com/MichalPP/freemapv3/blob/master/js.js a prehoď sem

**Comment by zdila** [comment]
a preco ja? :)

**Comment by MichalPP** [comment]
lebo píšeš že "zduplikuj", tak ti vraciam. veď sisi ani nepozrel ako som to v proof of koncept urobil

**Comment by zdila** [comment]
pozrel som ale ten jquery hardcore ma vyplasil. nechaj tak, ked bude cas dorobim. ty kludne ries freemap.epsilon.sk a my budeme next.freemap.sk. kazdy co ho bavi. kludne to moze aj zakapat o rok, ale podstatne je ze nas to teraz bavi a nechceme sa hadat.

**Comment by MichalPP** [comment]
takže to čo som posledné roky robil (epsilon UI, oma api, routing), chceš hodiť do koša bez toho aby si si to pozrel. hm.

**Comment by zdila** [comment]
kde pisem ze to chcem hodit do kosa?

**Comment by zdila** [comment]
a ten kod som si pozrel, ale nerozumiem mu.

**Comment by petervojtek** [comment]
zial ten kod je naozaj tazko zrozumitelny :(
Miso, inak toto je odpoved na tvoju davnu otazku, ze naco su vlastne dobre JS frameworky (a nerobime veci len v jquery) -- lebo o.i. zvysuju citatelnost kodu.

**Comment by MichalPP** [comment]
na www.oma.sk/api je popísané ako si pýtať POI v okolí bodu, vráti to použiteľný popis (vrátane otváraích hodín)

a keď je niečo nejasné tak sa spýtam, nie hádžem do koša.

**Comment by zdila** [comment]
inac alternativa je spytat sa ovepassu

**Comment by MichalPP** [comment]
čo sa ti na oma api nepáči?

**Comment by zdila** [comment]
> čo sa ti na oma api nepáči?

Ja len upozornujem na alternativu, moznost volby. Treba si zvolit to co je lepsie.

Ale ked sa uz pytas:

- Vracia javascript. Ocakaval by som json pripadne XML alebo CSV
- Vo vratenych datach je priamo HTML šité pre oma.sk a tiez aj linky na oma.sk
- Overpass API je "standard"

**Comment by MichalPP** [comment]
- vracia geojson/geojsonf nič štandardnejšie nepoznám (ako narvať linestringy do CSV?)
- áno, to je feature nie bug
- overpass vracia škaredé texty a treba sa tam hrať s osm tagmi. na ome nemusíš.

**Comment by zdila** [comment]
> vracia geojson/geojsonf nič štandardnejšie nepoznám (ako narvať linestringy do CSV?)

ako pisem, vracia javascript. tu je zaciatok:

```
// poskytuje http://www.oma.sk (c) prispievatelia Openstreetmap, šírené pod licenciou ODbL ( http://www.openstreetmap.org/copyright ): http://wiki.freemap.sk/Licencia 
var oma = [
```

> áno, to je feature nie bug

to je feature pre oma.sk. ak sa dohodneme ze next.freemap.sk prepojime s oma.sk, tak to bude feature aj pre freemap. ak nie tak bug.

> overpass vracia škaredé texty a treba sa tam hrať s osm tagmi. na ome nemusíš.

pravda. len to pridava na flexibilite api kedze neriesi veci co skor patria na klienta. V toole "Miesta" uz mapujeme tie skarede tagy na pekne nazvy a je to reusable.

**Comment by MichalPP** [comment]
použi štandard na konci (&callback=myfunc ) a vráti to čo potrebuje leaflet. alebo to vráti geojson načítaný do premenne oma.

je to feature.

tool miesta si robil zbytočne, zahodil si to, čo som robil ja. prečo?

**Comment by zdila** [comment]
> tool miesta si robil zbytočne, zahodil si to, čo som robil ja. prečo?

na to nemozem odpovedat inac ako: ved cely next.freemap.sk robime zbytocne a zahodili sme freemap.epsilon.sk

**Comment by MichalPP** [comment]
a čo si/ste z freemap.epsilon.sk použili/i? niečo, jednu vec.

**Comment by zdila** [comment]
Ja inšpiráciu, čo ako robiť a čo ako nerobiť. S @petervojtek sme usúdili že by to malo mať inú formu. Aj ohlasy na freemap fóre k freemap.epsilon.sk boli zmiešané. K next.freemap.sk sú zatiaľ pozitívne.

**Comment by petervojtek** [comment]
ja som [navrhoval](https://github.com/FreemapSlovakia/freemap-v3-react/issues/36) pouzit fintu z epsilon aby v planovaci typ pohybu bol implicitne odvodeny od typu mapy, ale nepreslo :)

**Comment by seg-on** [comment]
Mám pocit že diskusia sa tu začína trochu odkláňať od témy a asi by som mal trvať na tom aby ste si založili vlastné vlákno :D

Spýtam sa čo z toho čo som navrhol vidíte ako realizovateľné a čo vám príde ako zlé riešenie?

Mojim cieľom je snažiť sa tlačiť na to aby funkcionalita bola najmä užívateľsky veľmi prívetivá a používanie komfortné. Je vec ktorú často vytýkajú ľudia keď im ukážem aktuálny portál. A dôvod prečo ho nepoužívajú aj napriek tomu že poskytuje veci ktoré iné portáli nemajú.
A myslím si teda že cieľom je vytvoriť niečo čo ľudia, nielen malá skupinka nadšencov, využíva.

PS: Nie som programátor webových aplikácií takže v tejto oblasti moc pomôcť neviem.

Peace on you! ;)

**Comment by zdila** [comment]
> Spýtam sa čo z toho čo som navrhol vidíte ako realizovateľné a čo vám príde ako zlé riešenie?

vsetko z toho je zrealizovatelne a pride mi to ako dobry napad.

je to nieco ako v starom freemape funkcia "objekty v okoli". zatial by to mohlo byt na klik myskou do mapy.

**Comment by tjamecny** [comment]
Mne sa celkom paci funkcia na map1, kde to automaticky zistuje pre poziciu kurzoru, aka je tam plocha a ake POI: http://beta.map1.eu/#zoom=15&lat=49.19276&lon=18.74902&layers=BT

**Comment by zdila** [comment]
> Mne sa celkom paci funkcia na map1, kde to automaticky zistuje pre poziciu kurzoru, aka je tam plocha a ake POI

len tato implementacia ti nepomoze najst veci ktore v mape nevidno, lebo ti nenapadne cez ne prejst myskou.

**Comment by tjamecny** [comment]
To je pravda. Pozrel som, ako je to riesene a pre kazdy tile sa stahuje separatny JS subor zbaleny GZipom (aj tak maju niektore 150kB!) s OSM informaciami. A navyse to asi nebude fungovat na dotykovych zariadeniach bez nejakeho neintuitivneho hacku (ako je napr. dlhy klik). Takze tadeto cesta nevedie :(

**Comment by petervojtek** [comment]
inak toto je problem ktory povazujem za nevyrieseny (ako interagovat s udajmi ktore su "za mapou") -- a nedokazal to podla mna zatial vyriesit ani google a existujuce riesenia ktore poznam su len evolucia z papierovych map. na revoluciu cakame :)

tu je moja predstava:

zreplikovat funkcionalitu tlacidla `?` z osm.org -- problem je, ze vysledok pripomina surove sql, a kto nepozna ontologiu osm zostane zmateny. preto postupne budeme vyberat niektore udaje ktore zobrazime krajsie. napr na uvod len dve veci:
 * kliknutie na cestu ti ukaze ze "cesta 3. triedy c. 66, povrch asfalt" /toto typicky pouzivam ja ako cyklista ked chcem vediet aky bude mat cesta povrch/
  * kliknutie na budovu zobrazi "adresa: Mlynska 5, Litava 45678"
  * staci tu mat len tych zopar typicky pouzivanych veci

co nebudeme mat osetrene takto pekne sa zobrazi obvyklym surovym osm-sposobom 

technicky to znamena ze az po kliknuti sa deje request na overpass/ine-api.

pripadne (keby tie `?` dopyty mali trvat tak dlho ako tie na osm) , mozeme casom spravit optimalizaciu, ze udaje pre tie krajsie-zobrazovane veci budeme fetchovat nejakym tile-sposobom (cca ako to robi ten map1) -- ale tym ze tam budu len niektore vybrane udaje, tak to nebude az take velke. nevyhoda je ze to kladie naroky na vyvoj na backende (a hlavne naslednu udrzbu :)

**Comment by petervojtek** [comment]
pripadne tie "poludstene zobrazene udaje" mozeme zobrazovat odlisne podla toho aky typ mapy je zobrazeny, napr.:
* ked na cyklomape kliknes na cestu, zobrazi sa povrch a typ (grade2) /na lyziarskej mape je zbytocne to zobrazovat/
* ked na automape kliknes na cestu, zobrazi sa sa info ci je toll-free alebo nie /zbytocne na inej ako automape/

**Comment by petervojtek** [comment]
budeme riesit az po #54

**Comment by MichalPP** [comment]
ako som písal o veľa riadkov vyššie, api je napr na

http://www.oma.sk/api?bbox=17.2,47.8,18,48.3&tabulka=poi

dorobím aby vracalo aj adresné body, ulice, vodné toky atď

**Comment by MichalPP** [comment]
krajšie, ak hovoríme o bodoch v okolí kliku je na

http://www.oma.sk/api?lat=48.14627&lon=17.11128&vzdialenost=25&mapa=T

podľa typu mapy budem filtrovať čo zobrazuje, momentálne iba POI a ulice. dá sa ešte
- adresné body
- cyklotrasy, turistické trasy, mhd, lyžiarske trasy
- potoky, jazerá, ...
- a samozrejme iba niektoré poi (napr nedávať studničky na automapu)

**Comment by zdila** [comment]
duplicated by #159
