### ISSUE TITLE
prehodiť routing na osrm

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/freemap-v3-react#94]
prehodiť routing na osrm, https://github.com/Project-OSRM/osrm-backend

momentálne beží SR na http://freemap.epsilon.sk/#page=navigacia&map=T/16/48.14484/17.11902

turistika, bicycle (a auto)

výhody: funkčné LRM, prepájanie s DB, pracuje na tom veľa ľudí

**Comment by petervojtek** [comment]
hmm, som zmateny -- koreluje to nejako s touto issue?
https://github.com/FreemapSlovakia/FreemapBackend/issues/5

**Comment by MichalPP** [comment]
asi nie, cieľ je vyhodiť gosmore a začať používať niečo určené na routovanie na serveri (osrm)

**Comment by zdila** [comment]
@petervojtek nemyslim si. @MichalPP asi chce povedat aby sme pouzili jeho server ktory pouziva na freemap.epsilon.sk. Ak to tak nie je, tak ten issue patri do backendu.

**Comment by petervojtek** [comment]
rozumiem coraz menej :)
Tibor vyrobil backend edpoint pre route planner (api 0.3), a ja som si vytvoril issue #92 aby som zmenil sucasne api volanie v route planneri (api 0.1) na api 0.3. 
mam teda robit #92, alebo nie? ak ano, nerozumiem co je cielom tejto issue #94 v kontexte freemap-v3-react

**Comment by tjamecny** [comment]
> asi nie, cieľ je vyhodiť gosmore a začať používať niečo určené na routovanie na serveri (osrm)

A kde asi bezi gosmore? Na klientovi urcite nie :)
Poprosim este dodat relevantne porovnanie, preco je prave osrm lepsi ako gosmore, + detailny navod na instalaciu + nastavenie osrm na phenixovi, kedze externe servery neplanujeme pouzivat. V opacnom pripade navrhujem tuto Issue zavriet.

**Comment by MichalPP** [comment]
OSRM vie:

- klasika typu ohodnocanie hrán s inými váhami ako čas, vyhľadávanie naj trás
- matrix output: nájdi časy pre maticu m*n bez nutnosti m*n requestov
- dopytovanie externých zdrojov (napr prepojenie na postgis typu preferuj cesty kde sú blízko vyhliadkové body/studničky)
- ráta cesty veľmi-veľmi rýchlo
- realistické ohodnocanie zátačiek, križovaní, prechodov, ...

na postup inštalácie si stačí prečítať čo som písal minule (je to o 4 komenty vyššie).

**Comment by MichalPP** [comment]
a keď prehodíš na OSRM, nemusíš blbnúť s celou logikou zobrazovania trasy a textových popisov 

https://github.com/perliedman/leaflet-routing-machine

**Comment by MichalPP** [comment]
nech sa páči návody https://github.com/FreemapSlovakia/freemap-routing

**Comment by tjamecny** [comment]
Podľa testov na https://www.routexl.nl/blog/openstreetmap-router-graphhopper-osrm-gosmore/?lang=en to vyzerá, že Graphhopper je ešte lepší ako OSRM. Licencia Apache 2.0, a stále aktívne vyvíjaný: https://github.com/graphhopper/graphhopper

**Comment by MichalPP** [comment]
ok, takže osrm je rýchle. oveľa rýchlejšie ako gosmore. super.

**Comment by petervojtek** [comment]
nepatri do frontendu, riesit dalej na backende

**Comment by MichalPP** [comment]
patrí do frontendu, s backendom to nemá nič spoločné.

**Comment by petervojtek** [comment]
frontendu len treba oznamit na aku URL sa ma dopytovat pri routovani... diskusiu o tom aky engine pouzit by som neriesil vo frontend repozitari.

**Comment by MichalPP** [comment]
url je http://pesi.routing.epsilon.sk/route/v1 a http://mtb-bike.routing.epsilon.sk/route/v1

diskusia o pravidlách je na https://github.com/FreemapSlovakia/freemap-routing/issues
