### ISSUE TITLE
Tooltip prekrýva meranú plochu

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#95]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/osm_sk/ett127QOzdQ/3y-Sffm2CwAJ

Tak jsem jen tak ze zvědavosti vyzkoušel a u měření ploch mi docela vadí, že mi tooltip překryje měřenou plochu.

Marián

**Comment by seg-on** [comment]
Nebolo by možné spraviť:
možnosť uchopiť a presúvať tooltip?
Alebo v prípade malých plôch zobrazovať tooltip prichytený z vonkajšej strany k niektorému vrcholu?

**Comment by zdila** [comment]
zatial som implementoval zoom do 20 takze prekazat by to malo len ak chces merat plochu o velkosti mensej ako ma povedzme tenisovy kurt.

![image](https://cloud.githubusercontent.com/assets/636095/24355659/06e41cc4-12f7-11e7-817d-812c565ae6cb.png)

**Comment by mkyral** [comment]
Anebo to okno umístit někam do rohu.

**Comment by petervojtek** [comment]
no, aktualne je to naozaj nesikovne a pouzivatela to vie znepokojit :)  co keby sme to zobrazovali v toaste ktory bude v lavom dolnom rohu (toast bude permanentne zobrazeny kym bezi meranie plochy). 
taky toast by sme nemohli mat v beznej polohe (pravy horny roh), lebo by (najma na mobile) prekryval pristup k menu.

**Comment by mkyral** [comment]
Musel jsem si najít, co to je toast a nakonec jsem zjistil, že to je přesně to co právě potřebuji na  osmap.cz pro zobrazování zpráv uživateli :-)  👍

Jinak tam taky máme L.control, který zobrazuje gps souřadnice místa, kam se kliklo. Stačí kliknout do mapy a mrknout vlevo vedle měřítka. Je to součástí leaflet kontejneru, takže na mobilu jde menu přes to.

**Comment by zdila** [comment]
osobne mi pride terajsie riesenie vporiadku; par ploch som pomeral a nikdy mi to nezavadzalo. mozno robim nieco zle :-). ale ak verejnost tlaci na prerobenie, tak moze byt ten toast :-)

**Comment by mkyral** [comment]
Možná mám smůlu, že jsem jako první zkusil změřit tak malý rybník :-D
Ale na nic netlačím, to byl jen takový námět na vylepšení. Časem bych totiž chtěl podobný nástroj i na osmap.cz, tak sbírám inspiraci ;-)

**Comment by petervojtek** [comment]
ja spravim ten toast

**Comment by petervojtek** [comment]
no, chvilu som to skumal a kniznica ktoru pouzivame na toasty nie je velmi stavana na to, aby permanentne zobrazovala toast a vedela updatovat jeho obsah (po kazdej zmenej area) /a ine toast kniznice pre react su na tom podobne/. 
viem to v nej spravit, ale radsej pockam kym sa vynori este nejaka ina issue ktorej bude uzitocne mat permanentny toast s dynamickym obsahom, lebo to riesenie nie je extra elegantne.

**Comment by petervojtek** [comment]
spravil som to tak, ze vypocitana merana plocha sa zobrazuje ako popup nad najsevernejsim bodom polygonu, takze ho neprekryva a zaroven je text oznacitelny mysou

<img width="380" alt="screen shot 2017-05-07 at 10 41 55 am" src="https://cloud.githubusercontent.com/assets/225506/25779158/0721635a-3312-11e7-917d-fd0ecd450733.png">
