### ISSUE TITLE
planovac: vyber midpointu robit podobne ako v measure area

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#96]
malo by ist tak, ze najprv trasu rozsekame na segmenty podla midpoints (vyhodou je ze midpoints nemusia lezat priamo na trase):
http://turfjs.org/docs/#lineslice

potom pre kazdy segment vypocitame dlzku L:
http://turfjs.org/docs/#linedistance

a potom pre kazdy segment najdeme bod v vzdialenosti L/2 od zaciatku segmentu:
http://turfjs.org/docs/#along
 a tam umiestnime circle marker ktory bude mozne tahat.

ci je to prilis komplikovane, Martin @zdila ?

**Comment by zdila** [comment]
Ja by som to robil tak ako to je na google maps.

**Comment by MichalPP** [comment]
https://github.com/perliedman/leaflet-routing-machine to rieši.

**Comment by petervojtek** [comment]
> Ja by som to robil tak ako to je na google maps.

z UX hladiska by bolo elegantne, keby sme mali sposob pridavania dalsieho bodu rovnaky v celej apke -- cize aktualne v measure area a planovaci.

google maps to ma velmi pekne na desktope. ale na mobile (v apke google maps) je pridavanie midpointu uplne UX zufalstvo (vobec sa len tak neda tahat tou trasou ako na desktope s mysou).

ale suhlasim, ze ten ich pristup pridavania midpoints sa mi paci a mozem to skusit spravit (aby to fungovalo aj na mobile) -- UX nevyhoda ich pristupu na mobile bude, ze ked nevies ze sa tou trasou da tahat, tak na to nemusis prist (na dekstope sa ti onhover zmeni kurzor, ale na touschcreene nie -- toto je vyhoda nasho sucasneho (umap like) measure area riesenia). 

> leaflet-routing-machine

uz som ho raz [pouzil ked som robil tuto apku](https://greygoo.io/portfolio/go-ground/), a moj dojem je ze je to super nastroj kym ho pouzivas defaultnym sposobom tak, ako to mal na mysli jeho autor, ale ked chces nieco inak, veci sa lahko stanu krkolomnymi. a na mobile sa mi v [deme](http://www.liedman.net/leaflet-routing-machine/) nepodarilo pridat dalsi midpoint (tahanim trasy) /na dektope som to dokazal, ale tiez nic moc, najprv som musel v zozname adries pridat novy riadok a az potom to slo/

**Comment by MichalPP** [comment]
@petervojtek http://freemap.epsilon.sk/#page=navigacia&map=T/14/48.17461/17.11936 chytíš a ťaháš (a do toho trochu dlhší dotyk)

**Comment by petervojtek** [comment]
@MichalPP , skusal som to pouzit (a viem ze si mi to ukazoval nedavno pri pizze), ale ked to skusam teraz, tak:
* neviem prist na to ako zadat start/ciel kliknutim do mapy
* ked start a ciel zadam ako text, tak sa nic nedeje (konzola hodi error Uncaught TypeError: a is not a function)
* na smartfone mam celu obrazovku prekrytu tym sidebarom s vyberom startu a ciela a skusal som kliknut na tie ikony vpravo hore, ale k mape som sa nejako nedostal;

gesto "dlhsi dotyk" sa na inak pouziva velmi zriedka a ludia o nom vobec nevedia, snazil by som sa mu vyhnut lebo intuitivne nan ludia nepridu.

**Comment by zdila** [comment]
> neviem prist na to ako zadat start/ciel kliknutim do mapy

pravym klikom do mapy

**Comment by petervojtek** [comment]
vdaka. ano, to tahanie noveho bodu a pasikave guidelines ktore od neho vedu k starym su fajn, myslim ze k tomu konvergujeme :)

**Comment by MichalPP** [comment]
ako inak emuluješ pravý klik na mobile?

geocoding je hore vypnutý (nechcelo sa mi ho zapínať, ale môžeš si forknúť tie súbory, deployovať u seba a poslať pull request, nič ti nebráni to vylepšiť)

**Comment by petervojtek** [comment]
> ako inak emuluješ pravý klik na mobile?

ja som to teraz pouzil na desktope.

**Comment by MichalPP** [comment]
na desktope pravý klik (ale to je vec úplne blbého a jednoduchého nastavenia)

**Comment by petervojtek** [comment]
no, v kazdom pripade v prehliadaci (na mobile aj na desktope), pravy klik a "dlhy klik" su gesta ktorym sa treba vyhnut, ludia ich tam necakaju.

**Comment by MichalPP** [comment]
to je vec jedného blbého nastavenia UI. kľudne zmeň na čosi iné (normálny klik). vec asi na 4 sekundy nastavovania. pridal si issue na freemap.epsilon.sk?

**Comment by petervojtek** [comment]
ja som to pisal skor v kontexte tohto repozitara (ze ci mame konsenzus v tom, ze tie gesta nie su stastne a chceme sa im podla moznosti vyhnut). co sa tyka toho freemap.epsilon.sk -- mne ta apka pride tak divne spravena (napr. tie tri tlacidla co zapinaju/vypinaju rozne menu), ze nejaky pravy a dlhy klik su oproti tomu drobnosti... takze je zbytocne sa nimi podla mna zaoberat :)

**Comment by petervojtek** [comment]
Martin @zdila, skusal som spravit pridavanie midpointu tak ako to ma google, ale mal som problemy s tym aby to fungovalo na mobile aj na desktope. netvrdim ze sa to neda, ale bolo by to o dost pracnejsie nez som si zelal.

preto som zatial radsej spravil riesenie ako som ho povodne navrhoval (cize vyzera to rovnako ako pridavanie novych bodov v measure area).
este tam planujem fixnut tieto veci:
*  crosshair cursor zobrazovat iba ked sa vybera start/finish
* zobrazovat guidelines zo susednych bodov ked pouzivatel taha ten modry kruzok.

**Comment by MichalPP** [comment]
a LRM nefunguje?

**Comment by petervojtek** [comment]
[tu su nejake pokusy](https://github.com/PaulLeCam/react-leaflet/issues/92) pouzit LRM z react-leafletu, ale neposobi to dojmom produktu ktory staci nainstalovat cez npm.
a [do zoznamu](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/Plugins.md) react-leaflet pluginov sa to zatial nedostalo.

to neznamena ze LRM sa neda pouzit z react.js, len ze by si vyzadovalo nejake usilie to zaintegrovat. ..mne osobne nepride zaujimave sa tym zaoberat, viac ma bavi hrat sa s funkciami ktore poskytuje [turf.js](http://turfjs.org/)

**Comment by petervojtek** [comment]
> crosshair cursor zobrazovat iba ked sa vybera start/finish

toto som spravil v 9ce9e9ea9b2f7b90d5650447faae54c7bda5e91d

> zobrazovat guidelines zo susednych bodov ked pouzivatel taha ten modry kruzok.

s tymto som sa hral cely cen a vela som sa naucil o reacte :), ale neviem to spravit tak, aby to uplne neobchadzalo react. bez ohladu na to ci poziciu mysi nad mapou prenasam cez redux alebo cez eventy, vznikaj tam nejaky sliepka-vajce problem s tym, ze ked zacnem tahat modru bodku, tak mi react updatne komponent, cim sa uz nikdy nedostanem k onDragend callbacku (lebo uz je to ina modra bodka). ked sa snazim nejako zabranovat v update pomocou `shouldComponentUpdate`, tak to zase neprekresluje guidelines. asi by sa to dalo nejako vyladit, ale obavam sa ze to uz kod nebude velmi citatelny. tiez som sa skusal dat `guidelines` a `futureMidpoints` to stavu komponentu, ale nepomohlo mi to..

**Comment by MichalPP** [comment]
a prečo si neurobil pull request aby to išlo do zoznamu pluginov?

**Comment by petervojtek** [comment]
asi sme si neporozumeli (alebo som zle opisal co som robil) -- ja som plugin/medzivrstvu pre LRM do react-leaflet neimplementoval.

**Comment by MichalPP** [comment]
a prečo? načo zbytočné vyrábanie niečoho čo nikto mimo tejto stránky nepoužije?

**Comment by petervojtek** [comment]
asi si nerozumieme.
ja som toto vobec necommitol:

> zobrazovat guidelines zo susednych bodov ked pouzivatel taha ten modry kruzok.

hral som sa s tym, ale nie som spokojny s tym ako by ten kod vyzeral a preto ta feature v kode nie je.
