### ISSUE TITLE
Umiestnenie tlačítka "Kde som?" do lišty

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#97]
Ak by to bolo možné bolo by fajn keby tlačitko "Kde som?" sa pri mobilnom zobrazení nenachádzalo v menu, ale bolo stále na obrazovke.
Užitočnosť možnosti priameho aktivovania bude mať ešte väčší význam ak bude fungovať aj funkcia zrušenia sledovania pri pohybe mapy užívateľom.
Každý klik navyše, môže byť otravný.

Aktuálne zobrazenie [printscreen](http://segi.wz.cz/scrsht_KdeSom.png)

**Comment by zdila** [comment]
Ano, planuje sa.
