### ISSUE TITLE
Vyhľadávanie

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#98]
Dve veci vo vyhľadávaní ktoré som postrehol.
1. Vyhľadávanie presnú frázu takže ak je názov ulice dvojslovný musia sa zadať obe slová podľa druhého to nenájde.
2. Ak sa nachádza ulica vo viacerých mestách tak by bolo fajn keby v zozname bolo názov obce.
Respektíve mohlo by to pre všetky objekty vypisovať názov katastrálneho územia.
3. popis v zátvorkách je dobrý ale možno by nebolo zlé keby aspoň pre najčastejšie používané texty bol slovenský výraz.

**Comment by tjamecny** [comment]
Vyhľadávanie (teda body 1, 2) sa rieši v https://github.com/FreemapSlovakia/FreemapBackend/issues/4
Prvotná verzia bola dosť pomalá, druhá verzia je o dosť rýchlejšia, ale niekedy vracia nepresné výsledky. Až to bude opravené, dám vedieť, a nasadí sa to na frontend.

**Comment by seg-on** [comment]
Aha nevedel som :)

**Comment by zdila** [comment]
Momentalne je vyhlavavanie neskutocne pomale. Take http://www.freemap.sk/api/0.3/searchhint/bratislava&max_count=10 trva od pol minuty az do minut (potom to abortne). @petervojtek neprehodime to zatial na OSMacky nominatim?

**Comment by petervojtek** [comment]
ak sa Tiborov endpoint nema ambiciu vyvijat (za posledne dva mesiace sa tusim nic nezmenilo), tak osm nominativ je zrejme vhodnejsi pre nas ucel.

**Comment by zdila** [comment]
...pripadne nieco od @MichalPP? (mozno casom aj routing?)

**Comment by petervojtek** [comment]
osm nominativ a Tiborove riesenie sme uz vyskusali, som sa vyskusanie aj tretieho riesenia (od Misa :)
pripadne mozeme dat do expertnych nastaveni prepinac kde sa bude dat zvolit endpoint.

**Comment by MichalPP** [comment]
v http://freemap.epsilon.sk/#page=navigacia&map=C/8/47.76702/21.35193 používam nominatim. funguje ok (len mu treba posielať výrez mapy čo momentálne vidí). včera vyšiel nový major release. možno stojí za pozretie, nahodenie u seba (aby mohlo fungovať dopĺňanie).

na oma.sk vlastné riešenie, ale zďaleka nie je dobré.

**Comment by synalik** [comment]
Vyhľadávanie nefunguje - už pri vpisovaní názvu lokality vypisuje "Nastala chyba pri spravovaní výsledkov vyhľadávania: Network Error". (použité prehliadače Vivaldi, Chrome)

**Comment by seg-on** [comment]
U mňa to isté v Opere.

**Comment by tjamecny** [comment]
Predpokladám, že sa jedná o vyhľadávanie na next.freemap.sk a nie na www.freemap.sk . Na next-e je totižto ešte starý odkaz.
@zdila upravíš odkaz na API na old.freemap?

**Comment by seg-on** [comment]
hej potvrzdujem. jedná sa o next,freemap.sk na freemap.sk je vyhľadávanie funkčné.

**Comment by zdila** [comment]
> včera vyšiel nový major release. možno stojí za pozretie, nahodenie u seba (aby mohlo fungovať dopĺňanie)

@MichalPP spolieham sa na teba :-)

**Comment by synalik** [comment]
Pri vyhľadávaní zadám miesto, ktoré chcem vyhľadať. Keď kliknem myšou na vyhľadaný výsledok v tabuľke hľadania sa za menom zobrazí "×". Keď naň kliknem, že zadať nové hľadanie zmizne celé vyhľadávacie dialógové okno nielen text (názov predtým vyhľadaného objektu). Správa sa to rovnako ako keď stlačím tlačidlo "Zavrieť" zobrazeného napravo na paneli. Keďže box na Hľadanie nie je umiestnený priamo na mape, tak sa hľadanie viacerých objektov po sebe mení na veľkú klikačku.

**Comment by synalik** [comment]
- dám vyhľadať jednoslovný názov (napr Tlmače).
- kliknem myšou na prvú nájdenú možnosť. 
- chcem pokračovať vo vyhľadávaní dvojklikom označím Tlmače a začnem písať nový názov. 
Dialógové okno celé zmizne. Platí pre next.freemap.sk ako aj pre freemap.sk (rovnako aj príspevok vyššie)

**Comment by zdila** [comment]
Zatvaram, kedze sa tu nakopilo vela issues. Niektore su uz vyriesene a niektore patria do projektu FreemapSlovakia/FreemapBackend#4.

Pravidlo je robit pre kazdy problem zvlast issue.
