### ISSUE TITLE
"Kde som?" pre zariadenia bez GPS

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-react#99]
Pri desktopoch by mohlo byť fajn aby tlačitkom "Kde som?" určilo polohu podľa IPčky. Aj keď táto možnosť je dosť nepresná, ale lepšie ako nič.

**Comment by zdila** [comment]
Využíva sa HTML5 Geolocation API a využitie IP na zistenie polohy určite používa ako jednu z techník. Alebo ti to na desktope nefunguje?

**Comment by petervojtek** [comment]
drobna poznamka - ja mam na macos taku zvlastnu situaciu, ze sa mi z nejakych pricin ziaden prehliadac nepokusa pytat od operacneho systemu povolenie na pristup ku Location services, v dosledku coho mi geolocation API v ziadnom prihliadaci nefunguje (napriek tomu ze v samotnom prehliadaci je ziskavanie polohy pre danu stranku povolene).

<img width="642" alt="screenshot 2017-04-03 10 09 22" src="https://cloud.githubusercontent.com/assets/225506/24600587/a29a72e0-1855-11e7-87a4-e38a5304460f.png">

ale aspon som vdaka tomu dokazal otestovat tento toast v planovaci /v kde som? by sa tiez taky mohol zobrazit v pripade neuspechu ziskania polohy/

<img width="398" alt="screenshot 2017-04-03 10 10 17" src="https://cloud.githubusercontent.com/assets/225506/24600614/c8a3b104-1855-11e7-8331-b8b56af890b2.png">

**Comment by seg-on** [comment]
Hej, na desktopoch mi to nefunguje. Na iných portáloch to ide. Ono zvädša aj pri prvom použití funcie sa prehliadač opýta či povoliť zisťovanie polohy a tuna nič.
